### ISSUE TITLE
In AppLifetime.ApplicationStarted event, stdout/stderr is not accessable

### ISSUE THREAD

**Issue by shhsu** [aspnet/IISIntegration#1012]
In E2E test, we registered a callback for

https://github.com/aspnet/AspNetCoreModule/blob/dev/test/AspNetCoreModule.TestSites.Standard/Program.cs#L159

This callback is invoked after `app.Run` is completed hence after `~PipeOutputManager()` is called and `Console.Write` would cause a invalid handle exception

**Comment by shhsu** [comment]
@shirhatti This is a minor ci blocking issue. I can workaround it by commenting out this line in our test app

**Comment by jkotalik** [comment]
Once I repro, I'll take a look at why. I think it's a race condition on closing stdout and calling console.WriteLine (though it could just be an invalid handle issue). It will become much easier to see these issues once full IIS tests are done.
