### ISSUE TITLE
Add another way to capture debug logs without the use of setting an environment variable. 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1013]
In full IIS, reading an environment variable in the worker process isn't convenient as:
1. The environment variable must be set on the AppPool, which is part of the apphost.config. Also it is only supported on win10+
2. Must be set system wide and requires was/ computer restart to have the environment variable set.

After working on the full IIS tests, I personally feel that we should move away from setting environment variables and put more things in the web.config (in handler settings, for example).

**Comment by muratg** [comment]
This is a good diagnostics feature!

**Comment by pakrym** [comment]
Done in https://github.com/aspnet/IISIntegration/pull/1033
