### ISSUE TITLE
Change RegKey checks from "IIS AspNetCore Module" to "IIS AspNetCore Module V2"

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1014]
Also we need to check if there are IIS Express RegKeys that should be uniquely checked too.

**Comment by muratg** [comment]
@shirhatti Thoughts on this one?

Please milestone or close it. Thanks.

**Comment by shirhatti** [comment]
Why do we need a unique IIS Express reg key? I'm assuming if there's a vuln, we'd want one global kill switch.
@jkotalik Let's close this
