### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by vend2804** [aspnet/IISIntegration#1016]
We running into this issue in our runtime environment. Aspnetcore 2.1. Website loads fine and works. If you leave it idle ( example iphone safari) when you go back to that page in 30 minutes the error comes up. It doesn’t go away unless you clear cache. Any help is very appreciated. This is first .net core app moving to production

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.

**Comment by dinobu** [comment]
facing same issue

**Comment by JFBChristieTech** [comment]
bump, exact same issue

**Comment by dinobu** [comment]
'**The specified CGI application encountered an error and the server terminated the process**' error message when going to our cloud at www.ourcloudtest.com 
Similarly, swagger api is throwing 500 request time out error "The web server failed to respond within specified time"

**Comment by JFBChristieTech** [comment]
We were able to solve it by destroying the application pool and the site completely and letting our automation re-create from scratch when the target site doesn't exists as usual.

**Comment by muratg** [comment]
@dinobu did you figure it out at your end as well?

**Comment by muratg** [comment]
Note to other folks reading this issue: This error can happen when your app crashes. There's nothing in the error to indicate that this may be a ANCM bug.

**Comment by dinobu** [comment]
> 
> 
> @dinobu did you figure it out at your end as well?

Yes, but unfortunately, I know nothing about the details, I was not involved in it.  It was caused by our code, all I know.

**Comment by arpitce27** [comment]
Same issue has happened to me... did not figured anything at all...
