### ISSUE TITLE
Prevent users breakpoints from being hit twice on debug

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/IISIntegration#102]
Today when a users debugs their application via IISExpress (F5 in VisualStudio) their site gets hit with two requests (breakpoints get hit twice). One debug request to start the application, and then a second from the started web browser. 

I believe VisualStudio currently sends the first request with verb "Debug". "Debug" seems too generic (in my opinion) to be baked directly into IISIntegration. We should consider creating a custom Visual Studio specific debug verb that indicates a request is to boot the application/for debug; that way we can eat it prior to it reaching the users application.

This was initially filed over in tooling [here](https://github.com/aspnet/Tooling/issues/261).

**Comment by Eilon** [comment]
cc @blowdart because presumably we'd need to ensure that this is safe for a deployed site.

Once we're sure we have a solid design for this, we can assign.

**Comment by blowdart** [comment]
Oh is that why this is happening? I noticed that a couple of weeks back. This might be better addressed by getting VS to behave properly. I'm leery of adding new verbs, especially when folks might not be running under IIS Express

**Comment by blowdart** [comment]
Rather than add another verb could we not change the Command header that's sent from IIS so we know we can ignore it if necessary? 

I don't think IISIntegration should support DEBUG by default. It's one of those verbs that should be blocked by default.

**Comment by Tratcher** [comment]
Latest proposal: Have ANCM filter out the DEBUG request if the debugger is attached.

**Comment by Tratcher** [comment]
An auto-start option (https://github.com/aspnet/IISIntegration/issues/161) may also remove the need for the DEBUG request.

**Comment by BillHiebert** [comment]
To make this work we would need to change the way we launch the debugger to attach to IIS Express first (so ANCM filters the debug verb), and then send the debug request and have the debugger attach to the spawned process

**Comment by Tratcher** [comment]
We've opted to have the middleware filter out this request for v1.0. Post 1.0 the plan is to replace the DEBUG request with #161 (auto-start).
