### ISSUE TITLE
WebSocket app crashes

### ISSUE THREAD

**Issue by shhsu** [aspnet/IISIntegration#1036]
The ancm test websocket app is crashing currently for 2 reasons. One is the same reason as #1012. However, there's another more subtle issue. A crash occurs randomly right after a few consecutive messages are sent.

The only errors I am seeing in the event viewer is as followed
```
Application '/LM/W3SVC/2/ROOT' with physical root 'C:\_ANCMTest\DoBasicTest_lsuhp1ag.edi\AspNetCoreApp\' hit unexpected managed background thread exit, ErrorCode = '0x0. Last 4KB characters of captured stdout and stderr logs:
BEGIN Main()
BEGIN Main::Run()
```
Websocket server
https://github.com/aspnet/AspNetCoreModule/tree/dev/test/AspNetCoreModule.TestSites.Standard
Client
https://github.com/aspnet/AspNetCoreModule/blob/dev/test/AspNetCoreModule.TestSites.Standard/wwwroot/chatplus.html

**Comment by pakrym** [comment]
No repro on the latest release/2.2 branch. Is there a live repro? Can we get a crashdump?

**Comment by shhsu** [comment]
not repoing anymore
