### ISSUE TITLE
Resolve win7 test failures with 'api-ms-win-service-core'

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1069]

**Comment by jkotalik** [comment]
Nah some are still failing: http://aspnetci/viewLog.html?buildId=510928&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe
`System.DllNotFoundException : Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

**Comment by jkotalik** [comment]
Will keep open for monitoring purposes.

**Comment by pakrym** [comment]
Fixed in #1197.
