### ISSUE TITLE
Aspnetcore IIS module and process lifetime.

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/IISIntegration#107]
I have deployed the new module.  If I stop the is application pool the dotnet process eg somewebsite.exe stays alive.  I have to kill it to do a publish.  I would expect stoping the application pool to also shutdown or kill the process or am I missing something?

**Comment by pan-wang** [comment]
How did you stop the application pool? The child process should be terminated automatically by the OS unless it was attached by the debugger or hold some resource. I could not repro this issue locally. Could you please share a simple repro for investigation.

**Comment by mikes-gh** [comment]
> How did you stop the application pool?
By using the app pools node in IIS manager .
I will investigate further and come back.

**Comment by mikes-gh** [comment]
Sorry Guys.
Happy to report it was because when I recreated the app it defaulted to "Default app pool" and not the one it was previously using which was the one I was restarting.  No wonder it wasn't affecting the process.
Assigning the app to the correct app pool solved the issue.
Please close.
