### ISSUE TITLE
Move  ANCM build steps into universe Main Build

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1077]
And consume assets produced and signed by universe build. No need to rebuild them again.

**Comment by jkotalik** [comment]
This should be done now. The only thing we may want to do is move building the ANCM installers to SetupSharedFramework. @natemcmaster thoughts?

**Comment by natemcmaster** [comment]
I'm hoping to get SetupSharedFramework open-sourced eventually. It may be okay to leave ANCM installers separate b/c those can't be open-source, IIUC.

**Comment by natemcmaster** [comment]
By the way, do you want the .msi artifacts available in the build drop for ProdCon (this is publicly accessible)? Or are they internal-only artifacts created just to be used by other bundle installers?
