### ISSUE TITLE
Add hosting model Project property to templates

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1079]
Having a project capability isn't sufficient for deciding whether we would like to run in-process or out of process. We need a project property to decide this too. We may have accidentally deleted the property before due to my misunderstanding. #969

**Comment by shirhatti** [comment]
We need to verify that this propagates through Microsoft.AspNetCore.App/All

**Comment by jkotalik** [comment]
This only needs to be done to templates/ new project experiences, per our discussion today.

**Comment by pakrym** [comment]
Done in https://github.com/aspnet/Templating/pull/716
