### ISSUE TITLE
Install aspnetcore IIS module separately

### ISSUE THREAD

**Issue by yashwanthreddyg** [aspnet/IISIntegration#1087]
Currently, installing the module requires one to install the hosting bundle which comes with runtime (please correct me if I'm wrong).
What if the user wants to install only the iis module and not the runtime?
Is there an option to install only the iis module?
This would be particularly useful if the deployment of the app is self-contained or when the user wants to ship a portable runtime.

**Comment by shirhatti** [comment]
We have flags on the Hosting Bundle that allow you to not install the runtimes

```
DotNetCore.1.1.0.Preview1-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0
```

**Comment by yashwanthreddyg** [comment]
That solved it. Thanks. Closing the issue.
