### ISSUE TITLE
why asp.net core deploy in iis every two hours restarted

### ISSUE THREAD

**Issue by netcore-jroger** [aspnet/IISIntegration#1091]
**I use the IIS 10 default setting.**
`aspnetcore.dll` version is : `8.2.1991.0`

![image](https://user-images.githubusercontent.com/3223890/43175448-a7b57788-8ff1-11e8-95bb-2506377dee52.png)
应用程序启动 mean is `Application start`.
应用程序正在停止... mean is `Application starting...`.
应用程序停止 mean is `Application stop`

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.

**Comment by netcore-jroger** [comment]
@pakrym just these logs.
