### ISSUE TITLE
IIS virtual directory browsing

### ISSUE THREAD

**Issue by raymak23** [aspnet/IISIntegration#110]
Hello,

I have an application that is written in ASP.NET 5 and it is configured at site level and it is pointing to wwwroot directory (`c:\inetpub\websites\{app}\wwwroot`). The site name is default web site. In that site, I created new virtual directory called healthcheck and it is pointing to (`d:\healthcheck\`). In that path, I have some static content like html files. When I browse `http://localhost/healthcheck/index.html`, I get 502.3 bad gateway error. 

How do I tell the application that it can ignore healthcheck route and let it pass to healthcheck static content? I think it is the routing in application that is not letting me to get to static contents.

Any health is really appreciated. :)

**Comment by pan-wang** [comment]
under the vdir "healthcheck", you can add a web.config which remove the asp.net core handler defined in the site web.config.

**Comment by dml5** [comment]
Thank you. Thank you. Thank you.  I have been trying for days to figure out how to get my web application subsite working in IIS under a MVC6 application.
