### ISSUE TITLE
Flaky test: AppOfflineAddedAndRemovedStress

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1108]
@pakrym #1107 should resolve this? https://ci.appveyor.com/project/aspnetci/iisintegration/build/1.0.1691

**Comment by pakrym** [comment]
Yes

**Comment by jkotalik** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed also failed. https://dotnet.visualstudio.com/public/_build/results?buildId=9059&view=logs

**Comment by ryanbrandenburg** [comment]
AppOfflineAddedAndRemovedStress [failed again](http://aspnetci/viewLog.html?buildId=519145&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineAddedAndRemovedStress [failed with about the same error](http://aspnetci/viewLog.html?buildId=518725&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineAddedAndRemovedStress [failed with about the same error](http://aspnetci/viewLog.html?buildId=521299&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by mikeharder** [comment]
Another repro in VSTS: https://dotnet.visualstudio.com/public/_build/results?buildId=10523&view=logs

**Comment by mikeharder** [comment]
@pakrym, @jkotalik: Appears test is still flaky after #1107.

**Comment by pakrym** [comment]
> Another repro in VSTS: https://dotnet.visualstudio.com/public/_build/results?buildId=10523&view=logs

Fix for it is in https://github.com/aspnet/IISIntegration/pull/1148

**Comment by mikeharder** [comment]
Another repro: https://ci3.dot.net/job/aspnet_IISIntegration/job/release_2.2/job/windows-Configuration_Release_prtest/363/console
