### ISSUE TITLE
ANCM v1: App fails to start if ASPNETCORE_PORT env var set

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1119]
In ANCM v1, the app fails to start if the `ASPNETCORE_PORT` env var is set.

# Repro steps
1. Set `ASPNETCORE_PORT` in `web.config`, like so:
```
<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true">
  <environmentVariables>
    <!-- Uncomment to run on fixed port instead of random port -->
    <environmentVariable name="ASPNETCORE_PORT" value="10000" />
  </environmentVariables>
</aspNetCore>
```
2. Attempt to run app in ANCM v1
3. App fails with following in stdout log:
```
Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'ASPNETCORE_APPL_PATH'  Key being added: 'ASPNETCORE_APPL_PATH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at System.Environment.GetEnvironmentVariables()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
```
4. If you dump the env vars at app startup (example: https://github.com/mikeharder/ancm-docker/blob/82cf503a9bc7c905df4e9ed0cf7e5caccbf73f1d/app/2.1/Program.cs#L20), you will see that `ASPNETCORE_PORT` is never set, and instead `ASPNETCORE_APPL_PATH` is set twice, which causes the failure:
```
ASPNETCORE_IIS_HTTPAUTH=anonymous;
ASPNETCORE_APPL_PATH=/2.1/OUTPROC
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.Server.IISIntegration
ASPNETCORE_TOKEN=71b6d69c-7786-4c04-b613-5a6a6919d074
ASPNETCORE_APPL_PATH=/2.1/OUTPROC
```
5. The suspected root cause is calling `Dereference()` twice on a hash entry: https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/AspNetCoreModuleV1/AspNetCore/src/serverprocess.cxx#L133
6. ANCM v2 outproc does not have this issue.  It appears the extra call to `Dereference()` was removed in the v2 code.

**Comment by danmosemsft** [comment]
Callstack above (due to IIS corrupting enviroment block) will be fixed by https://github.com/dotnet/corefx/issues/30341

**Comment by vivmishra** [comment]
Approved for 2.1.5
    Hold checkin till the branch opens
