### ISSUE TITLE
Browser hangs indefinitely.

### ISSUE THREAD

**Issue by dallancarr** [aspnet/IISIntegration#112]
Deploying multiple websites accidently hard coded server.urls using localhost:5001 inside both web.config. Second site hangs indefinitely. Is this intended behavior? rc1 update-1 1.2

**Comment by Tratcher** [comment]
How did you define server.urls in web.config?

**Comment by dallancarr** [comment]
Just standard vs template rc1 update1 web command
--server.urls http://localhost:5001

**Comment by Tratcher** [comment]
server.urls should never be defined in the web.config. HttpPlatformHandler/AspNetCoreModule specify the port to listen on via an environment variable.

**Comment by dallancarr** [comment]
Sorry slight confusion I specified inside the project.json file. It is just the behaviour as I wasn't immediately aware that is was issue inside the app.

**Comment by Tratcher** [comment]
Ah. This should not be a problem in RC2 because the urls in the command line and config will be superseded by the the ones in the AspNetCoreModule environment variables.

**Comment by dallancarr** [comment]
Thought as much. So conflicts are mitigated in RC2.

**Comment by Tratcher** [comment]
Right, the two sites should get unique ports.

**Comment by dallancarr** [comment]
Interesting behaviour nonetheless. ☺
