### ISSUE TITLE
Port collisions when multiple apps in separate app pools are started at the same time

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1124]
When multiple apps in separate app pools are started at the same time, it's possible for some apps to fail startup due to port collisions with other apps.  I have confirmed the root cause is:

https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/AspNetCoreModuleV1/AspNetCore/src/serverprocess.cxx#L1915

The resolution of `GetTickCount()` is 10-16ms, so if two apps (in two app pools) are started within this time window, it's possible that `GetTickCount()` returns the same value for both apps, which causes the port collision.

I have verified both v1 and v2 out-of-process are impacted.

# Repro Steps
1. Configure IIS with 10 apps, each in their own app pool.
2. Make requests to all 10 apps in parallel, as quickly as possible.
3. Some apps may fail to start, since they try to start on the same port (as shown in event logs)

# v1 out-of-process
```
Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE/2.1/OUTPROC-MULTI-APPPOOL/4'
started process '2360' successfully and is listening on port '6074'.

Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE/2.1/OUTPROC-MULTI-APPPOOL/2'
with physical root 'C:\apps\2.1\outproc-multi-apppool\2\'
created process with commandline 'dotnet .\app.dll' but failed to listen on the given port '6074'
```

# v2 out-of-process
```
Application '/LM/W3SVC/1/ROOT/2.2/outproc-multi-apppool/10'
started process '376' successfully and process '376' is listening on port '30362'.

Application '/LM/W3SVC/1/ROOT/2.2/outproc-multi-apppool/5'
with physical root 'C:\share\2.2\outproc-multi-apppool\5\' 
created process with commandline 'dotnet .\app.dll' but failed to listen on the given port '30362'

Application '/LM/W3SVC/1/ROOT/2.2/outproc-multi-apppool/5'
with physical root 'C:\share\2.2\outproc-multi-apppool\5\' 
failed to start process with commandline 'dotnet .\app.dll'
at stage 'PostStartCheck', ErrorCode = '0x8007065f', assigned port 30362, retryCounter '0'.

Application '/LM/W3SVC/1/ROOT/2.2/outproc-multi-apppool/5'
with physical root 'C:\share\2.2\outproc-multi-apppool\5\' 
failed to start process with commandline 'dotnet .\app.dll'
with multiple retries. The last try of listening port is '30362'. See pervious warnings for details.
```

**Comment by vivmishra** [comment]
Approved for 2.1.5
    Hold checkin till the branch opens
