### ISSUE TITLE
Debug log should be as similar as possible to stdout log

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1133]
I believe the debug log should be as similar as possible to the stdout log:

* `debugFile` should allow relative paths (currently requires absolute path)
  * debugFile: https://github.com/aspnet/IISIntegration/blob/release/2.2/src/AspNetCoreModuleV2/CommonLib/debugutil.cpp#L138
  * stdout: https://github.com/aspnet/IISIntegration/blob/release/2.2/src/AspNetCoreModuleV2/RequestHandlerLib/FileOutputManager.cpp#L85
* `debugFile` should have a default value like `.\logs\debug` (similar to `.\logs\stdout`)
* `debugFile` should be a prefix, and ANCM should append a timestamp and process ID.

Ideally, the following config would be sufficient to enable both stdout and debug logs:

```
<aspNetCore stdoutLogEnabled="true">
  <handlerSettings>
    <handlerSetting name="debugLevel" value="4" />
  </handlerSettings>
</aspNetCore>
```

Currently, the following is required:

```
<aspNetCore stdoutLogEnabled="true">
  <handlerSettings>
    <handlerSetting name="debugLevel" value="4" />
    <handlerSetting name="debugFile" value="C:\path\to\app\logs\debug.txt" />
  </handlerSettings>
</aspNetCore>
```

**Comment by pakrym** [comment]
Default stdout file is `".\aspnetcore-stdout` according to schema.

Otherwise, I agree, we need to cleanup debug logging a bit.

**Comment by mikeharder** [comment]
I agree that's the default in schema, but WebSDK sets default to `%home%\LogFiles` for App Service and `.\logs\stdout` otherwise.  I would argue the values set by WebSDK are the effective defaults for most customers.

https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/AspNetCoreModuleV1/AspNetCore/aspnetcore_schema.xml#L22
https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/AspNetCoreModuleV2/AspNetCore/aspnetcore_schema_v2.xml#L24
https://github.com/aspnet/websdk/blob/0c47545ea675938160725e30dab7f0efdc58d4cb/src/Publish/Microsoft.NET.Sdk.Publish.Tasks/WebConfigTransform.cs#L118

**Comment by pakrym** [comment]
Most of these things are done except `debugFile should be a prefix, and ANCM should append a timestamp and process ID.`.

Do you feel strongly about it or can I close the issue?

**Comment by mikeharder** [comment]
Is `debugFile` intended for customers to use?  If so, is it something they would only enable temporarily, meaning it's OK to use the file name without appending timestamp/ID?  Or is it something they might want to keep enabled long-term like stdout?

**Comment by pakrym** [comment]
It's something to be enabled temporarily to get more information about ANCM failures.

**Comment by mikeharder** [comment]
Do you think it's better if the filename **does not** have the time/id appended, or do you just not think it's worth the effort?

**Comment by pakrym** [comment]
It's better for what we use it, for example when piping log for tests you don't need to figure out timestamps and generate file name you just get logs written where you expect them.

**Comment by mikeharder** [comment]
OK, the current behavior seems fine then, we can revisit based on customer feedback.
