### ISSUE TITLE
Make ANCM MSI a prodcon artifact

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#1189]
Our ANCM for IIS Express msi aren't prodcon artifacts so they'll get cleaned up every month or so (subject to the CI policy). We need persist these builds if we will be shipping them.

cc @natemcmaster If you want to add anything

**Comment by muratg** [comment]
Need to move the build to Universe.

**Comment by pakrym** [comment]
Things that have to happen:

- [ ] IIS.Setup opensource
- [x] IIS.Common opensource
- [ ] Merge installer source into Universe
- [ ] Figure out signing
