### ISSUE TITLE
aspNetCore processsPath must start with ./

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#119]
`processPath="./IISSample.exe"` works, processPath="IISSample.exe" doesn't. There is probably a path combine happening that does not add the optional slash. stdoutLogFile has a similar limitation, we should be able to set it to empty and have it write to the current directory.

**Comment by Tratcher** [comment]
This appears to be documented behavior: http://www.iis.net/learn/extensions/httpplatformhandler/httpplatformhandler-configuration-reference
"As of v1.2 relative paths are supported, if the path begins with '.' the path is considered to be relative to the site root."
It's still confusing though.

**Comment by pan-wang** [comment]
This looks a little bit annoying for end user. this was limited by CreateProcess but can be workaround. Will fix it.

**Comment by pan-wang** [comment]
this was fixed

**Comment by Tratcher** [comment]
@pan-wang I see that processPath and arguments were fixed, but stdoutLogFile was not.
