### ISSUE TITLE
Test failure: TestInvalidWriteOperations

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1192]
This test [fails](http://aspnetci/viewLog.html?buildId=526800&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\922d7ef3-d9b5-4103-9d4a-7c43f324bcfe as user MyUser with redirection.config password
)) (The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture)
---- System.AggregateException : One or more errors occurred. (Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\922d7ef3-d9b5-4103-9d4a-7c43f324bcfe as user MyUser with redirection.config password
)
-------- System.Runtime.InteropServices.COMException : Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\922d7ef3-d9b5-4103-9d4a-7c43f324bcfe as user MyUser with redirection.config password
---- The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture
----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.IISTestSiteFixture..ctor() in /_/test/Common.FunctionalTests/Utilities/IISTestSiteFixture.cs:line 37
----- Inner Stack Trace -----
   at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)
   at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 173
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 161
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 113
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @muratg

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526615&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526599&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526488&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526477&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526508&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReadAndWriteEchoTwice [failed with about the same error](http://aspnetci/viewLog.html?buildId=526475&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526453&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526280&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReadAndWriteSynchronously [failed with about the same error](http://aspnetci/viewLog.html?buildId=526261&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=526220&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestInvalidWriteOperations [failed with about the same error](http://aspnetci/viewLog.html?buildId=527354&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pakrym** [comment]
Fixed by fixing the agent.
