### ISSUE TITLE
Test failure: AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed - 500.19 0x8007000d - Config Malformed XML

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1194]
```
  Failed   Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed(hostingModel: OutOfProcess, statusCode: 502, content: "502.5")
  Error Message:
   Assert.Equal() Failure
  Expected: 502
  Actual:   500

<title>IIS 10.0 Detailed Error - 500.19 - Internal Server Error</title> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x8007000d</td></tr> 
```

Log: https://ci3.dot.net/job/aspnet_IISIntegration/job/release_2.2/job/windows-Configuration_Release_prtest/363/consoleText
IIS Error Docs: https://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,19,0x8007000d,16299

HResult code | Error message | Cause | Resolution
-- | -- | -- | --
0x8007000d | Server Error in Application "application name"HTTP Error 500.19 – Internal Server ErrorHRESULT: 0x8007000dDescription of HRESULTThe requested page cannot be accessed because the related configuration data for the page is invalid. | This problem occurs because the ApplicationHost.config file or the Web.config file contains a malformed XML element. | Delete the malformed XML element from the ApplicationHost.config file or from the Web.config file.

I think the test should write the contents of apphost.config and web.config to the test log, if the server returns this error.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526999&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526877&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526877&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526798&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526615&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526599&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526488&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526494&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526477&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526508&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526475&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526453&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526280&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526261&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=526220&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=537224&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=537725&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=538895&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=539623&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed [failed with about the same error](http://aspnetci/viewLog.html?buildId=539776&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mikeharder** [comment]
No failures on aspnetci since 8/27/18: http://aspnetci/project.html?tab=testDetails&testNameId=5032441980450767227&projectId=AspNetEf&order=TEST_STATUS_DESC
