### ISSUE TITLE
Switching hostingModel from out-of-process to inprocess does not work

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#1196]
I can switch from in-process to out-of-process with simply changing the hostingModel value while application is running with some stress requests generated by stress test tool.

However I can not switch from out-of-process to inprocess with changing the hostingModel value to inprocess. 
The app is still running in the out-of-process mode even though the configuration is changed.

This is a regression issue.

Workaround is to force to recycle IIS worker process.

BTW, this issue seems to be reproducible without stress test. I found the similar issue without using stress testing. Here is the repro step.

STEPS TO REPRO:

1.	(Optional) Kill w3wp.exe to clean up
2.	Set hostingModel with empty value to set out-of-process
3.	Send a request
4.	Open TaskManager and you will see a new dotnet.exe process is running
5.	Set hostingModel with “inprocess” and save
6.	You will see the dotnet.exe process is gone
7.	Send a request

EXPECTED:

No dotnet.exe is created because hostingModel is now inprocess.

ACTUAL:

New dotnet.exe process starts even though the hostingModel is currently inprocess mode.

**Comment by mikeharder** [comment]
@jhkimnew : Why do you say this is a regression?  Is it a regression from a previous build of ANCM v2?

**Comment by jhkimnew** [comment]
@mikeharder Yes, I think so. I did not see this kind of issue when I used the old version before.
