### ISSUE TITLE
[Suggesstion] Rename IIS -> Iis

### ISSUE THREAD

**Issue by hishamco** [aspnet/IISIntegration#12]
According to the framework guidelines IIS should be rename to Iis. For example ```IISPlatformHandlerMiddleware``` will be renamed to ```IiSPlatformHandlerMiddleware```, in fact this is the case in other aspnet repos such as ```HttpAbstraction``` instead of ```HTTPAbstraction```
/cc @Tratcher

**Comment by Tratcher** [comment]
I agree in principal, but it looks terrible. At this point IIS the common name of the product, it's no longer considered an acronym for Internet Information Services.

**Comment by Eilon** [comment]
I believe we always spell out IIS in caps.

**Comment by davidfowl** [comment]
-1

**Comment by hishamco** [comment]
Yep @Tratcher @Eilon it's always spell out IIS in caps, but that's the same things in ```Http``` and ```Xml```
