### ISSUE TITLE
Verify behaviour in case of invalid message body

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1206]
For example badly formatted chunks.

**Comment by Tratcher** [comment]
On the request? For bad request chunks you shouldn't even receive them, Http.Sys should fail.

**Comment by pakrym** [comment]
Is there any scenario where we get to start reading the body and while the client is sending it realize it's invalid?

**Comment by pakrym** [comment]
> perhaps, but it would be reported as a read error or disconnect.

I want to verify that we get an exception that we expect.
