### ISSUE TITLE
Rename UseIIS() to UseIISIntegration()

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/IISIntegration#121]
It looks strange to have `UseIIS()` and `UseKestrel()` in the same call chain when this is really about integrating with IIS while still using Kestrel. Plus it means the name lines up with the package name, etc.

**Comment by dallancarr** [comment]
It seems that integration is tied to kestrel anyway or will there be future different combinations.

**Comment by Tratcher** [comment]
Kestrel is replaceable. WebListener isn't compatible with AspNetCoreModule right now but we'd like to make it work in the future. You can also plug in 3rd party servers.

**Comment by JunTaoLuo** [comment]
Create an announcement.

**Comment by Tratcher** [comment]
Updated the prior announcement.

**Comment by Tratcher** [comment]
@phenning FYI

**Comment by Eilon** [comment]
@Tratcher close?

**Comment by Tratcher** [comment]
@Eilon There's still a few repos to clean up. Templates, Performance, cli-samples, etc..

**Comment by mikes-gh** [comment]
@Tratcher 

Rename UseIIS() to UseIISIntegration() 

It seems that this change is in rc3 Package is that intentional?

1.0.0-rc2-20383 UseIIS()
1.0.0-rc3-20540 UseIISIntegration()

**Comment by davidfowl** [comment]
It's in both, release is at rc2-20539

**Comment by mikes-gh** [comment]
Ah I see I am only picking up 20383 on cidev
Thanks

**Comment by mikes-gh** [comment]
Looks like I should be moving to the vnext feed for the buildup to rc2 now?

**Comment by mikes-gh** [comment]
As far as I can see vnext is the latest package for rc2 currently 
at 
1.0.0-rc2-20466

**Comment by davidfowl** [comment]
You should use aspnetcirelease if you're tracking the RC2 packages.

**Comment by mikes-gh** [comment]
Got it thanks now at 20539.  There might be other like me who want to track rc2 to release.  If there is no announcement maybe an issue post in Home?

**Comment by Tratcher** [comment]
@mikes-gh I mentioned this on an existing announcement and updated the sample code. https://github.com/aspnet/IISIntegration/issues/105#issuecomment-207051587

**Comment by mikes-gh** [comment]
@Tratcher  thanks
Actually I was referring to an announcement for the change of feeds to continue using updated rc2 packages
There is an article of feeds but I hadn't realised release was now the active branch (and others might not also).
