### ISSUE TITLE
Add EventSource/EventCounter tracing and metrics for IISIntegration

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#1213]
Kestrel emits EventSource events for
- ConnectionStart
- ConnectionStop
- RequestStart
- RequestStop

https://github.com/aspnet/KestrelHttpServer/blob/release/2.2/src/Kestrel.Core/Internal/Infrastructure/KestrelEventSource.cs

We should add event to our server implementation to cover these cases

**Comment by Tratcher** [comment]
You can't do connection start, http.sys doesn't surface that.

**Comment by muratg** [comment]
We'll try to do this in 2.2.0-preview3.

cc @shirhatti

**Comment by pakrym** [comment]
Closing as we decided that having hosting events is enough for now.
