### ISSUE TITLE
Remove old packages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#122]
These packages have been replaced. We left the existing ones until we could get tooling support and covert projects over. Remove these packages before RC2 ships, after https://github.com/aspnet/Coherence-Signed/issues/222.
`Microsoft.AspNetCore.IISPlatformHandler`
`dotnet-publish-iis`
And associated tests.
@Eilon @muratg

**Comment by muratg** [comment]
I guess this consists of removing these from the build script for now? GitHub and CI changes can probably come in later.

Don't forget to update [packages.csv](https://github.com/aspnet/Coherence/blob/dev/packages/packages.csv) :)

**Comment by Tratcher** [comment]
I'd rather remove the sources before RC2 ships to avoid confusion of what shipped. We should be ready this week.

**Comment by mjeson** [comment]
What are values for the LAUNCHER_PATH and LAUNCHER_ARGS [mentioned](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html) in the new web.config ?

Been getting [error](http://stackoverflow.com/questions/37463186/asp-net-core-1-0-rc2-what-are-launcher-path-and-launcher-args-mentioned-in-web) when deploying the published files.

**Comment by mjeson** [comment]
What are values for the LAUNCHER_PATH and LAUNCHER_ARGS [mentioned ](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html) in the new web.config ?

Been getting [error](http://stackoverflow.com/questions/37463186/asp-net-core-1-0-rc2-what-are-launcher-path-and-launcher-args-mentioned-in-web) when deploying the published files to IIS 8.5 (2012 R2). I dont see any executable in the published files.

Apologize for placing this question here. The announcements thread is locked.

**Comment by GuardRex** [comment]
@mjeson To use the `publish-iis` tooling. See the `tools` and `scripts` sections of `project.json` in the samples at: https://github.com/aspnet/cli-samples

To manually setup the `web.config`, see the IISIntegration sample at: https://github.com/aspnet/IISIntegration/tree/dev/samples/IISSample

**Comment by moozzyk** [comment]
%LAUNCHER_PATH% and %LAUNCHER_ARGS% are used by VS. publish-iis tool (if configured) will override them when you publish your application.

**Comment by mjeson** [comment]
Thank you for your help @GuardRex and @moozzyk . I have my deployment working now. Here are my findings (also posted in stackoverflow).

After several hours dealing with them, I found there are **two** web.configs that we need to deal with: `src\ProjectName\wwwroot\web.config` and `src\ProjectName\web.config` . If you dont have the latter, VS2015 publish will generate one for you with %LAUNCHER_PATH% and %LAUNCHER_ARGS% by default.

To have the project run and debuggable locally under VS2015 via IISExpress, both web.config need to have the default value below. Replacing LAUNCHER_PATH and LAUNCHER_ARGS to something else causes VS2015 to hang indefinitely.

`<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>`

However, upon deploying to IIS (I am using 8.5 on WinServer 2012 R2), the value on `src\ProjectName\web.config` must be replaced with the following

`<aspNetCore processPath="dotnet" arguments=".\ProjectName.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>`

If you are migrating from RC1, change the http bound directory as well to Project root folder, not wwwroot. Example: from `C:\inetpub\ProjectName\wwwroot` to `C:\inetpub\ProjectName`.

I am using RC2 Toolkit Preview 1

**Comment by moozzyk** [comment]
I don't think you need the config in the wwwroot - as per https://github.com/aspnet/Announcements/issues/173  the web.config was moved to approot. If you configure publish-iis in your project.json like this: https://github.com/aspnet/cli-samples/blob/master/HelloMvcApi/project.json#L21-L29. You won't have to deal with `%LAUNCHER_*%` values - they will be taken care of for you.

**Comment by mjeson** [comment]
Thank you @moozzyk . You are awesome! I am missing that snippet from project.json. It works as expected now.
