### ISSUE TITLE
Populate IServerAddresses feature for the in process IIS integration

### ISSUE THREAD

**Issue by javiercn** [aspnet/IISIntegration#1223]
@jkotalik

**Comment by Tratcher** [comment]
What do you plan on using it for?

**Comment by muratg** [comment]
@shirhatti please check with @javiercn & @BillHiebert to see what their scenarios are.

**Comment by Tratcher** [comment]
The HttpsRedirect middleware would benifit from it. Not sure if they had other scenarios in mind.

**Comment by pakrym** [comment]
Dup: https://github.com/aspnet/IISIntegration/issues/485
