### ISSUE TITLE
Add ANCM props to VS editor intellisense

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#1224]
I don't get editor intellisense in my csproj file for the `AspNetCoreHostingModel` and `AspNetCoreModuleName`.

**Comment by pakrym** [comment]
@shirhatti any guidance on this?

**Comment by pakrym** [comment]
Copying comment from #891:

Another thing I noticed when looking at VS schema is that hostingmodel values are CamelCased there while the ones I added to templates are all lowercase, we need to decide which one we prefer because schema validation is case sensitive.

**Comment by pakrym** [comment]
@shirhatti  sample PR you gave me is not for csproj intellisense, it's for web.config.

**Comment by jkotalik** [comment]
We still need to update it for the web.config with `handlerSettings`

**Comment by jkotalik** [comment]
@shirhatti Do you prefer CamelCased or all lowercase for inprocess/outofprocess?

**Comment by shirhatti** [comment]
Whatever casing the webSDK uses today to remain consistent. I believe it's all lowercase today, but you should confirm

**Comment by vijayrkn** [comment]
we set it in what ever case the msbuild property is set.

**Comment by jkotalik** [comment]
This was done by CommonStartupTests.StartupStress

**Comment by pakrym** [comment]
Hm?

**Comment by jkotalik** [comment]
Copy paste error.
