### ISSUE TITLE
Make ANCM versions consistent.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1258]
https://github.com/aspnet/IISIntegration/blob/release/2.2/version.props currently has 8.1 as the version number, which isn't higher than the current ANCM installation. This causes the dll not to be replaced.

**Comment by jkotalik** [comment]
### Current public ANCM version:
**ANCMV1**
Dll version: `8.2.1991.0`
Msi version: `2.1.1991`

### Proposed versions:
**ANCMV1 and ANCM V2**
release/2.1
Dll version: `12.1.xxxx`
Msi Version: `2.1.xxxx`
release/2.2
Dll version: `12.2.xxxx`
Msi Version: `2.2.xxxx`
release/3.0
Dll version: `13.0.xxxx`
Msi Version: `3.0.xxxx`

This keeps versions between the dll and msi consistent.

**Comment by pakrym** [comment]
What about WHB?

**Comment by jkotalik** [comment]
@joeloff Can we make build versions of the windows hosting bundle match what we do for the rest of aspnetcore?
https://github.com/aspnet/WindowsHostingBundle/blob/master/tools/Version.props#L50-L63 vs last two digits of the current year + number of days since Jan 1st?

**Comment by joeloff** [comment]
Normally we'd grab the build number from the props file that's passed through during official builds. That section is only used when you build locally to generate a build number
