### ISSUE TITLE
Flaky test: AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1259]
# Failures
AppVeyor 8/17/18: https://ci.appveyor.com/project/aspnetci/iisintegration/build/1.0.2023
aspnetci (last failure 8/27/18): http://aspnetci/project.html?projectId=AspNetEf&buildTypeId=&tab=testDetails&testNameId=-3106583177376966291&order=TEST_STATUS_DESC&branch_AspNetEf=__all_branches__&itemsCount=50

**Comment by aspnet-hello** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=537224&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=537725&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=538895&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=539623&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=539776&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mikeharder** [comment]
Closing until this repros again:
- AppVeyor failed due to timeout, but I believe the publish code has changed since then
- aspnetci failures were caused by a publish error impacting many tests
