### ISSUE TITLE
aspnet-core site unresponsive - "Access is Denied." message in stdout.log

### ISSUE THREAD

**Issue by toastermagic** [aspnet/IISIntegration#126]
I have published a dnx451 application to IIS 8.0 on Windows Server 2012.

IIS is configured to direct requests on port 80 to the wwwroot folder.

When I attempt to browse localhost:80 on the server, there is no response ('waiting for localhost').

In the logs folder is a file (stdout.log_5428_201648135647.log) with the single entry 'Access is Denied.'

Access denied to what? Clearly at least one of the processes involved has write access to the log folder... I tried applying 'Everybody/Full Control' permissions to the parent folder to help diagnose, but it made no difference.

I can find nothing untoward in the eventlog.

dnx --version on the server reports '1.0.0-rc1-16609', the httpPlatformhandler is installed.

dnx --list reports 
```
  Active Version           Runtime Architecture OperatingSystem Alias
  ------ -------           ------- ------------ --------------- -----
         1.0.0-rc1-update1 clr     x64          win
         1.0.0-rc1-update1 clr     x86          win
         1.0.0-rc1-update1 coreclr x64          win
         1.0.0-rc1-update1 coreclr x86          win
    *    1.0.0-rc1-update2 clr     x86          win             default
         1.0.0-rc1-update2 coreclr x64          win
```

**Comment by muratg** [comment]
@toastermagic I assume you meant `dnvm --list` for the last one.

> IIS is configured to direct requests on port 80 to the wwwroot folder.

What do you mean by this?  Did you manually do this?

**Comment by muratg** [comment]
@Tratcher

**Comment by toastermagic** [comment]
It's an edit. I originally set it up on port 8080, but then later changed and tried on 80. Nothing special about the IIS binding.I think the port number is irrelevant here.

**Comment by toastermagic** [comment]
I have worked around this issue by changing the AppPool identity to an account with LocalAdmin. This workaround will not be possible in production.

**Comment by pan-wang** [comment]
if you can workaround the issue by set Apppool identity to LocalAdmin, it usually meant your application tried to access some resources which were not granted to default apppool identity. You can use process monitor to check which resources were accessed by your application.

**Comment by muratg** [comment]
@toastermagic I assume this is some file/folder permission issue. Let us know if you were able to figure it out. If you are able to repro on a "clean" machine, please file another one.

**Comment by toastermagic** [comment]
Hi, I did find out the problem - the AppPool user needed permission to connect to SQL Server. 

It was just difficult to find because the message was so general and I didn't twig that a connection would be attempted during the bootstrap process (i.e. before any connection to the site was made).

My apologies for not updating & closing this issue myself sooner.
