### ISSUE TITLE
Investigate logging framework not found exception on iisexpress

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1262]
#1154 will get this working for full IIS, however it doesn't work for IISExpress.

**Comment by muratg** [comment]
We need to solve logging on IISExpress for Dev16.

We may end up logging to stdout only.

**Comment by jkotalik** [comment]
https://github.com/aspnet/IISIntegration/pull/1421 addressed a majority of the issues (without actually logging to the event log).

**Comment by muratg** [comment]
We think #1421 is good enough. Closing this.
