### ISSUE TITLE
AspNetCoreModule AVs if the processPath contains forward slashes

### ISSUE THREAD

**Issue by moozzyk** [aspnet/IISIntegration#127]
If my web.config file contains backwards slashes like this:

```
<aspNetCore processPath='"%PROGRAMFILES%\dotnet\dotnet.exe"' 
arguments="..\HelloMvc.dll" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" >
```
things work fine. 
As soon as I change slashes in the `processPath` to forward slashes:
```
<aspNetCore processPath='"%PROGRAMFILES%/dotnet/dotnet.exe"' 
arguments="..\HelloMvc.dll" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" >
```

I get this: 

```
Faulting application name: w3wp.exe, version: 10.0.10586.0, time stamp: 0x5632d85f
Faulting module name: aspnetcore.dll, version: 7.1.1962.0, time stamp: 0x56df6972
Exception code: 0xc0000005
Fault offset: 0x00000000000107e5
Faulting process id: 0x6cd0
Faulting application start time: 0x01d191be652f0cb8
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\WINDOWS\system32\inetsrv\aspnetcore.dll
Report Id: cf48a63d-9d69-4010-87d3-d35b4d1845dc
Faulting package full name: 
Faulting package-relative application ID: 
```

I also wonder if this is only forward slashes or some class of characters that is causing the issue. 

/cc @pan-wang

**Comment by pan-wang** [comment]
this is by design. ANCM internally just passes the processPath value as lpCommandLine vale to CreateProcess(). CreateProcess does not accept forwardslash and thus causes failure. ANCM does NOT valid or normalize the processPath value. User should make sure the value is valid.

**Comment by Tratcher** [comment]
Is crashing w3wp from user input really the user experience we want?

**Comment by moozzyk** [comment]
@pan-wang - are you saying this AV is inside the `CreateProcess`? In other words if I call `CreateProcess(L"%TEMP%/myapp.exe", ...)` it will cause an AV? Knowing win32 apis I don't expect them to fail like that. Rather I would expect CreateProcess returns 0 as the result if the path was invalid indicating that the process could not be started...

**Comment by Tratcher** [comment]
By AV he means we are seeing w3wp crashes that show up in the event logs. Bad user input should not cause w3wp crashes, we should get ANCM event logs and an IIS error page instead.

**Comment by moozzyk** [comment]
I guess the behavior should be the same as if the name was just not correct. Hopefully if you just misspelled the name (without using special characters) it does not crash the process with Access Violation...

**Comment by pan-wang** [comment]
Just want to clarify that "by-design" meant we did not support forward slash. AV should not happen and should be a bug in ANCM.

**Comment by moozzyk** [comment]
@pan-wang - Agreed. I already sent a PR to get it fixed: https://github.com/aspnet/IISIntegration/pull/132

**Comment by moozzyk** [comment]
Assigning to myself to try to reproduce it again with the latest version of AspNetCoreModule.

**Comment by moozzyk** [comment]
I can no longer reproduce the crash with forward slashes. I can however create a crash/AV if dotnet returns an error. I will close this and open a new bug for this issue.
