### ISSUE TITLE
Release ANCM in 2.1.5 work

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1271]
- [x] Move current V1 code to 2.1.5 branch
   - [x] https://github.com/aspnet/IISIntegration/pull/1281
   - [x] https://github.com/aspnet/IISIntegration/pull/1276
   - [x] https://github.com/aspnet/IISIntegration/pull/1274
   - [x] https://github.com/aspnet/IISIntegration/pull/1273
- [x] Add build steps to 2.1 build configuration to produce V1 MSI
- [x] Change WebHostingBundle to consume said MSI
- [x] Verify versions of produced MSIs and DLLs are higher than released versions 
- [x] Fix ANCM V1 events

/cc @shirhatti @mikeharder  @jkotalik

**Comment by jkotalik** [comment]
Work items remaining:
- https://github.com/aspnet/IISIntegration/pull/1344
- Verification

I'll start verification once #1344 is in.

**Comment by jkotalik** [comment]
2.1.5 Verification is done and things look good. 

Few things to note:
Only two of the four fixes @mikeharder added were patched to 2.1. We didn't port the event log message and empty port value fix. See: https://github.com/aspnet/IISIntegration/commits/release/2.2/src/AspNetCoreModuleV1/AspNetCore/src

**Comment by pakrym** [comment]
@jkotalik can this be closed?
