### ISSUE TITLE
Inprocess in 2.2-preview1

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/IISIntegration#1314]
**Good news first: It worked without any real issues.**

What I did:
- Update to 2.2-preview1 bits (hosting-bundle, sdk etc.)
- Updated the nuget refs to 2.2-preview1
- Changed the CompatibilityLevel to 2.2
- Changed web.config module name to ``modules="AspNetCoreModuleV2"`` and added ``hostingModel="inprocess"`` to the aspNetCore line
- Changed the Program.cs to following

```cs
return WebHost.CreateDefaultBuilder(args)
.UseKestrel(options =>
 {
     options.AddServerHeader = false;
     options.Limits.MaxRequestBodySize = null;
     options.Limits.MaxResponseBufferSize = null;
 })
 .UseIIS() // needs to be there
 .UseIISIntegration() // needs to be there too 
 .UseStartup<Startup>();
```

dotnet publish did not automatically set ``hostingModel="inprocess"`` even though ``<AspNetCoreModuleHostingModel>inprocess</AspNetCoreModuleHostingModel>`` is in my csproj. Will that work with VS 15.9?

What I noticed: ``UseKestrel`` needs to be before ``UseIIS``, otherwise there is an exception "Application is running inside IIS process but is not configured to use IIS server."

I had to enable the stdlog to find out why it did not start (I don't know if it also shows up in the event log, forgot to check that one).

Both ``UseIIS`` and ``UseIISIntegration`` are necessary otherwise it won't start. Both extension method docs are the same, it might be useful to write in there that both are necessary.
From a user perspective, I don't really see why they should be both necessary as practically both mean the same (to me).

Performance wise (JMeter benchmark):
- 2.2-preview1 *outprocess* is maybe 3-5% slower than 2.1
- 2.2-preview1 *inprocess* is maybe 10% faster than outprocess, main difference is the 99th quantile of the response time, which is quite a bit better (40%), I already noticed that back when in 2.1 inprocess still worked.

**Comment by pakrym** [comment]
>What I noticed: UseKestrel needs to be before UseIIS, otherwise there is an exception "Application is running inside IIS process but is not configured to use IIS server."

This is a known limitation, call to `UseKestrel` replaces active `IServer` implementation.

> dotnet publish did not automatically set hostingModel="inprocess" even though <AspNetCoreModuleHostingModel>inprocess</AspNetCoreModuleHostingModel> is in my csproj. Will that work with VS 15.9?

/cc @shirhatti 

Neither `UseKestrel` nor `UseIISIntegration` should be required to run in-process. How does it fail when you remove these calls?

**Comment by Tornhoof** [comment]
> Neither UseKestrel nor UseIISIntegration should be required to run in-process. How does it fail when you remove these calls?
Sorry my bad, I tried to get both inprocess and outprocess working to switch between it, I just retried it and in-process works without it. I did not try to remove UseKestrel as it works if it's the first one, like in the native sample app. It's actually nice that both hosting models work in parallel. 

Is IIS Express supported for in-process or even a useful scenario, i.e. starting the web project inIIS Express from VS, I did not try it assuming that's where VS 15.9 will be necessary for.

**Comment by shirhatti** [comment]
> What I noticed: UseKestrel needs to be before UseIIS, otherwise there is an exception "Application is running inside IIS process but is not configured to use IIS server."

https://github.com/aspnet/KestrelHttpServer/pull/2761

We're aware. The new guidance is to use `ConfigureKestrel()` instead.

**Comment by pakrym** [comment]
> Is IIS Express supported for in-process or even a useful scenario, i.e. starting the web project in IIS Express from VS, I did not try it assuming that's where VS 15.9 will be necessary for.

It will be supported and will work after VS tooling catches up.

**Comment by shirhatti** [comment]
> dotnet publish did not automatically set hostingModel="inprocess" even though inprocess is in my csproj. Will that work with VS 15.9?

Yes. This already works the 2.2-preview1 SDK. We've had to change the attribute name from preview1 which is probably why it didn't work for you.
The new attributes are

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <!-- <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName> -->
    <AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
  </PropertyGroup>

**Comment by Tornhoof** [comment]
Can you update the NativeIISSample too?
https://github.com/aspnet/IISIntegration/blob/3b3f1283063db02821da4cd76e5c12be7dfc933b/samples/NativeIISSample/NativeIISSample.csproj#L22

**Comment by shirhatti** [comment]
> Can you update the NativeIISSample too?

Thanks for catching that.

**Comment by Tornhoof** [comment]
I think we can close this, the preview2 announcement contained the bits necessary to get it running and it worked just fine for me and I think the preview2 in-process is again a bit faster than preview1.
Thank you for all your work on the in-process mode.

**Comment by pakrym** [comment]
@Tornhoof thank you for trying things out!
