### ISSUE TITLE
dotnet publish-iis: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0

### ISSUE THREAD

**Issue by LeandroPT** [aspnet/IISIntegration#133]
Hey,

Using the "Microsoft.AspNetCore.Server.IISIntegration.Tools" the following error occurs:

`D:\DEV>dotnet publish-iis  -p "D:\Lixo\oo"
Configuring the following project for use with IIS: 'D:\Lixo\oo'
No web.config found. Creating 'D:\Lixo\oo\web.config'
Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.`

The project itself is referencing Newtonsoft.Json 8.0.3

Any ideias why this packages is referencing this specific version?

**Comment by moozzyk** [comment]
This tool is not in a functioning state at the moment. I am working on fixing it but it may take a few days.

**Comment by LeandroPT** [comment]
I want to deploy this to Azure [AppService]... I am totally dying here!!! 

Unsuccessfully tried aspnet/Hosting#672 which miserably fails with HTTPS....
Also believe aspnet/KestrelHttpServer#698 adds to the mix...

Any lights or assistance?

**Comment by natemcmaster** [comment]
cc @davidfowl

**Comment by natemcmaster** [comment]
@LeandroPT can you share your project.json? This may be related to a nuget bug in "imports". cref https://github.com/aspnet/EntityFramework/issues/5022#issuecomment-209704617

**Comment by victorhurdugaci** [comment]
We have a repro project here: https://github.com/aspnet/dotnet-watch/issues/72

**Comment by victorhurdugaci** [comment]
@LeandroPT you can manually generate the web.config file, without publish-iis. Here's a sample file https://github.com/victorhurdugaci/projectk-build-stats/blob/master/src/BuildDashboard.Server/wwwroot/web.config

**Comment by GuardRex** [comment]
@victorhurdugaci nit: The log extension (with timestamp) will be added automatically.

`stdoutLogFile="..\logs\stdout.log"` to `stdoutLogFile="..\logs\stdout"`

... but it won't break the way you have it.

**Comment by LeandroPT** [comment]
A little context:

I already have this running on RC1, what i did was to create a brand new project and use the CIDev bits with RC2.

project.json is attached....[project.json.txt](https://github.com/aspnet/IISIntegration/files/219986/project.json.txt)

Startup

 ```
           var builder = new ConfigurationBuilder()
               .SetBasePath(Directory.GetCurrentDirectory())
               .AddJsonFile("config.json", true)
               .AddEnvironmentVariables()
               .AddCommandLine(args)
               ;
            Configuration = builder.Build();

            IWebHostBuilder hostBuilder = new WebHostBuilder()
                        .CaptureStartupErrors(true)
                        .UseConfiguration(CoreStartup.Configuration)
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseKestrel()
                        .UseIISIntegration()
                        .UseStartup<CoreStartup>()
                        .Build();
            host.Run();
```

**Comment by GuardRex** [comment]
Won't work with HPH on Azure. You need the AspNetCoreModule on Azure Apps ... they're working on it according to @Tratcher with no ETA.

**Comment by LeandroPT** [comment]
HPH?

**Comment by GuardRex** [comment]
HttpPlatformHandler ...sry ... acronyms everywhere :smile:

**Comment by LeandroPT** [comment]
It's like i said: Unsuccessfully tried aspnet/Hosting#672 which miserably fails with HTTPS....

The thing is that i see alot of focus on Linux and other things... but on RC2 the latest bits allows me to use it, some required things got fixed from RC1, however i cannot run it either on Azure.... 

That is the only single little thing right now i urgently need [EF tools i can manage...] and that annoys me like hell, i already hate dnu/x since it's dead on birth.

It is interesting, the priority was not Azure/IIS.. They are having fun with docker/*nix/Mac and whatever... I can see why... but it kills my project... again...

So the bottom line is, either i am a crappy reader, or bits are missing and i rest and nag around about dates :) aspnet/Mvc#4275

**Comment by GuardRex** [comment]
You can run on an Azure VM/IIS with ACM (AspNetCoreModule). At least when the module rolls out on Azure Apps, it would be a simple matter to just deploy it with no or minimal changes.

**Comment by LeandroPT** [comment]
Yeah Rex, i could even build a container... And pay a bunch of money...

**Comment by LeandroPT** [comment]
Found out the problem... Had old Tools and multiple versions installed.

It seems that cli does a First()..

Cleared tools folder, restored and no errors.

**Comment by moozzyk** [comment]
@LeandroPT - [this](https://github.com/dotnet/cli/issues/2540)?

**Comment by LeandroPT** [comment]
@moozzyk Nope. Apparently on "my machine" it uses the 1st version of the tool.

**Comment by moozzyk** [comment]
Did you have `-*` in the version? Did you restore packages in this app (i.e. are you sure the project.lock.json was not stale - if you restore the new version of the tool in a different project then you would end up a new package version in the cache but project with older project.lock.json files would continue to use the old version since lock file contains specific versions).

**Comment by LeandroPT** [comment]
@moozzyk 

Yep :smile: .. It is proved... Very lazy

**Comment by muratg** [comment]
@LeandroPT Looks like this one is resolved. Please file another issue if you still have problems.
