### ISSUE TITLE
Out-Of-Process: Consider increasing default request timeout to infinite

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1356]
Currently, the default request timeout for out-of-process requests is 2 minutes.  If the customer app fails to respond within 2 minutes, ANCM will return a 502.3.  This causes customers to believe the issue is related to ANCM, when the actual problem is likely in their application code.

We should consider changing the default timeout to inifinte (or a very large value like 1 year), so the app behavior is more similar between raw Kestrel, ANCM out-of-process, and ANCM in-process, when customer code blocks indefinitely.

We will need to test the behavior when the customer app stops responding and requests are building up in ANCM.

**Comment by pakrym** [comment]
We can't do it in a non-breaking way, defaults are stored in schema.xml

**Comment by mikeharder** [comment]
@pakrym: Do you think we should plan to make this change in 3.0 then, or just close this issue and never change the default timeout?

**Comment by pakrym** [comment]
We can't do it in 3.0 either. Schema.xml is a global singleton and ideally, we shouldn't change customer app settings when updating ANCM.

**Comment by mikeharder** [comment]
CC: @davidfowl

**Comment by Tratcher** [comment]
ANCM v2 gets a new schema file, correct? Can it be changed there before it ever releases?

**Comment by jkotalik** [comment]
Schema files are loaded in arbitrary orders and whatever one is loaded second will overwrite the first one's options. This means if we change the timeout in the second schema, it can be overwritten by the first schema's value.

This setting is ignored by inproc though.

**Comment by mikeharder** [comment]
Inproc has no timeout, correct?  If so, it seems fine to keep the 2-minute timeout for outproc and no default timeout for inproc.
