### ISSUE TITLE
Verify upgrade scenarios with hosting bundle

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1370]

**Comment by jkotalik** [comment]
Found some issues, waiting on @joeloff assistance.

**Comment by joeloff** [comment]
What are the issues?

**Comment by jkotalik** [comment]
Known issue with ANCM installers for uninstall. TL;DR if you install a 2.2.0 hosting bundle and then a 2.2.1 hosting bundle, you must uninstall the 2.2.0 bundle before uninstalling the 2.2.1 bundle.
