### ISSUE TITLE
Move AspNetCoreModule-Setup in to aspnet/Universe

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/IISIntegration#1376]
We have open sourced the Windows Hosting Bundle installer and the shared framework installers. The ANCM installers are the last bit still in a private repo. After the OOS reviews are done, let's merge those installers here: https://github.com/aspnet/Universe/tree/master/src/Installers/Windows

Once this is done, we should be able to remove this script altogether: https://github.com/aspnet/Universe/blob/1f077cd251884c7fa22191d04f58105d8dc5c0a2/src/Installers/Windows/clone_and_build_ancm.ps1

cc @shirhatti @jkotalik

**Comment by jkotalik** [comment]
Majority of this done by https://github.com/aspnet/Universe/pull/1456. Will iterate a bit to simplify/cleanup.

**Comment by natemcmaster** [comment]
@jkotalik are we tracking that cleanup work somewhere?

**Comment by jkotalik** [comment]
https://github.com/aspnet/Universe/issues/1496
