### ISSUE TITLE
Implement IHttpBufferingFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#1386]
We need to evaluate if DisableRequestBuffering and DisableResponseBuffering are relevant to ANCM in-proc. 

IIS response compression may be one scenario, but that may have been addressed for the signalr scenario by the installer change to remove text/event-stream. @anurse

**Comment by anurse** [comment]
We still use the `Content-Encoding: identity` hack so I don't know for sure that it's working now with that web.config change.
