### ISSUE TITLE
ANCM V2 - net stop was /y Issue

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/IISIntegration#1392]
'net stop was /y' causes 'Failed to gracefully shutdown application' warnings being logged to the Application event log.

Is this a known issue?

**Comment by jkotalik** [comment]
Is this with In-proc or out of proc ANCM? 

This isn't a known issue. Should be an easy repro. Thanks for noticing!

**Comment by rockerinthelocker** [comment]
Sorry for not being specific. Yes, it's in-proc.

**Comment by pakrym** [comment]
Can you share your `Program.Main` method?

**Comment by rockerinthelocker** [comment]
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();
    }



    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore()
                .AddAuthorization()
                .AddRazorViewEngine()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }

```

**Comment by rockerinthelocker** [comment]
IIS application pool settings for the site running on Windows Server 2012 R2 with dotnet-hosting-2.2.0-preview1-35029-win installed:

```
            <add name="MySite" autoStart="true" enable32BitAppOnWin64="false" managedRuntimeVersion="" managedPipelineMode="Integrated" startMode="AlwaysRunning">
                <processModel identityType="SpecificUser" userName="User" password="Pass" idleTimeout="00:00:00" />
            </add>
```

**Comment by rockerinthelocker** [comment]
PS: It's a test server and the test site (just serving static files and 'hello, word!') was idle for hours at the time net stop was executed.

**Comment by rockerinthelocker** [comment]
Just tested with dotnet-hosting-2.2.0-preview2-35157-win and the same warning message got logged. Interestingly, shutting down the worker process takes even longer than with preview 1.

```
C:\Windows\system32>net stop was /y
The following services are dependent on the Windows Process Activation Service service.
Stopping the Windows Process Activation Service service will also stop these services.

   World Wide Web Publishing Service

The World Wide Web Publishing Service service is stopping.
The World Wide Web Publishing Service service was stopped successfully.

The Windows Process Activation Service service is stopping.....................................
The Windows Process Activation Service service was stopped successfully.

```

The dots show that it takes quite some time to shut down the worker process.

**Comment by rockerinthelocker** [comment]
Forgot to mention that the following message gets logged to the System log as well:

`A process serving application pool 'MyPool' exceeded time limits during shut down. The process id was '1234'.`

**Comment by pakrym** [comment]
I was not able to reproduce the error in my environments.

Can you please take a memory dump of w3wp process while it's hanging during stop?

**Comment by rockerinthelocker** [comment]
@pakrym , This issue can also be triggered by recycling the application pool a few times in a row. Additionally, the site is left in a 503er state. If the application pool is stopped via IIS Manager while in this state, one worker process might be left running, and attempts to start the application pool fail with the following message:

```
There was an error while performing this operation.

Details:

The service cannot accept control messages at this time. (Exception from HRESULT: 0x80070425)

```

Also, the error message

`Application pool 'MySite' is being automatically disabled due to a series of failures in the process(es) serving that application pool.`

can be found in the System event log.

**Comment by pakrym** [comment]
@rockerinthelocker can you please verify if you still have this issue with preview3?

**Comment by rockerinthelocker** [comment]
Seems to work now.
