### ISSUE TITLE
IIS web socket broken with asp.net core

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#1408]
_From @jjxtra on September 19, 2018 2:11_

Let me preface by saying that bypassing IIS and connecting directly to Kestrel works fine.

I am using IIS with asp.net core. This is Windows Server 2012 x64 r2 and .NET core 2.1.402 self contained x64 application. I am using Microsoft.AspNetCore.WebSockets (https://github.com/aspnet/WebSockets). I've cloned the source from github and added logging for retrieving the Sec-WebSocket-Key header. I've also set IIS up to log the Sec-WebSocket-Key header as well.

In my IIS logs, I see the correct Sec-WebSocket-Key value for each request, even when using cloud flare or other proxies. In my kestrel logs, the Sec-WebSocket-Key has been changed to a completely different value. Is there a way to prevent IIS from changing this header that it sends to the asp.net core module? I have the IIS web socket module installed in the server roles setup. Or is this a bug in IIS? ws and wss have same behavior.

Here is my logging, changed by modifying https://github.com/aspnet/WebSockets/blob/master/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs.

```
        public static string CreateResponseKey(string requestKey)
        {
            // "The value of this header field is constructed by concatenating /key/, defined above in step 4
            // in Section 4.2.2, with the string "258EAFA5-E914-47DA-95CA-C5AB0DC85B11", taking the SHA-1 hash of
            // this concatenated value to obtain a 20-byte value and base64-encoding"
            // https://tools.ietf.org/html/rfc6455#section-4.2.2

            if (requestKey == null)
            {
                throw new ArgumentNullException(nameof(requestKey));
            }
            requestKey = requestKey.Trim();
            using (var algorithm = SHA1.Create())
            {
                string merged = requestKey + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
                byte[] mergedBytes = Encoding.UTF8.GetBytes(merged);
                byte[] hashedBytes = algorithm.ComputeHash(mergedBytes);
                string hashedKey = Convert.ToBase64String(hashedBytes);

                // This is where the key differs from the correct key logged in the IIS logger settings
                Logger.Write(LogLevel.Warn, "Web socket: {0}, {1}", requestKey, hashedKey);
                return hashedKey;
            }
        }
```

_Copied from original issue: aspnet/Home#3539_

**Comment by jjxtra** [comment]
Adding the webSocket element to web.config with enabled attribute also does not change anything unfortunately.

**Comment by jjxtra** [comment]
I have recently tried on Windows 10 x64 latest version and updates and it is working through IIS there. So it may be specific to server 2012 x64 R2... happy to send you additional config files or whatever if you need them.

**Comment by jkotalik** [comment]
Few areas to check for differences:
What version of ANCM are you using on Windows Server 2012 x64 r2 vs Win10? If there are different versions, try updating the version on the Windows Server 2012 x64 r2. You can check the version by looking in C:\Windows\System32\inetsrv for the aspnetcore.dll version.

**Comment by Tratcher** [comment]
@jkotalik what error would you expect if the WebSocket module wasn't installed / activated?

**Comment by jjxtra** [comment]
On both machines version of aspnetcore.dll is 8.2.1991.0 and file is identical on both.

Upon failed connection I see no new event log entries in Application, System or Security. Is there another category I should check in?

**Comment by jjxtra** [comment]
Screenshot of IIS webSocket settings:
![image](https://user-images.githubusercontent.com/1271832/45783589-6dfd6380-bc23-11e8-984b-bf5d1e128d86.png)

**Comment by jjxtra** [comment]
I have php with fast cgi installed on the server. I wouldn't think this would interfere, but the Windows 10 install did not have php.

**Comment by jjxtra** [comment]
Adding these two lines to applicationHost.config resolved the problem.

```
<add name="WebSocketModule" image="%windir%\System32\inetsrv\iiswsock.dll" />
<add name="WebSocketModule" lockItem="true" />
```

Going forward, it sure would be nice if there was an indicator or log somewhere to denote that the web socket configuration is invalid. I have no idea how those lines were not in there with the web socket module installed...

**Comment by jkotalik** [comment]
Thanks for investigating and figuring out the issue. We can try to add an event log about what features are current enabled/disabled.

**Comment by jjxtra** [comment]
> Thanks for investigating and figuring out the issue. We can try to add an event log about what features are current enabled/disabled.

That would be very helpful, upon IIS start to log this in application or system.

**Comment by jjxtra** [comment]
We can close this issue, do I need to log a new issue about the event viewer log if the configuration is not right?

**Comment by jkotalik** [comment]
https://github.com/aspnet/IISIntegration/issues/1433
