### ISSUE TITLE
Add optional feature to reject requests without IIS token

### ISSUE THREAD

**Issue by blowdart** [aspnet/IISIntegration#141]
This would prevent requests on the same machine bypassing auth/path authorization provided by IIS.

Should default to false though.

**Comment by Tratcher** [comment]
Why default to false? Is there a mainstream scenario where you wouldn't want it on?

**Comment by Tratcher** [comment]
Offline dicussion: On by default, no option to turn it off. The middleware is only added to the pipeline if the AspNetCoreModule environment variables are detected at startup, so enabling this will not affect self-host scenarios.

**Comment by PinpointTownes** [comment]
Why not providing an option to disable this feature? What happens if I want to host my app on various environments? (e.g behind IIS on a Windows machine, behind nginx on a Linux-based machine).
