### ISSUE TITLE
Verify basic auth support for inproc and outofproc

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1429]

**Comment by shorbachuk** [comment]
Why was this removed from 2.2.0-preview3 ?

**Comment by pakrym** [comment]
Verified:

**Out-of-proc** - Not supported
**In-proc** - supported

**Comment by shorbachuk** [comment]
Does this mean I can test with any of the 2.2 previews?

**Comment by pakrym** [comment]
Yes, preview2 should work.
