### ISSUE TITLE
ANCM V2 - Connection Abort Handling Issue

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/IISIntegration#1439]
While ANCM V1 properly handles Http​Context.​Abort() and the likes..., ANCM V2 fails and connections are not aborted.

**Comment by pakrym** [comment]
What's the behaviour you expect vs seeing?

**Comment by rockerinthelocker** [comment]
Expected:
Connection abort (RST/ACK).

Actual:
In-process returns empty body, out-of-process throws.

**Comment by pakrym** [comment]
Can you provide the app func you are using? In my tests I see resets or 502s.

**Comment by rockerinthelocker** [comment]
Just to make sure we're on the same page. This is about the latest bits shipped, which is v2.2.0-preview2 at this time.

Nonetheless, ANCM v2 in-process/out-of-process must reset the connection on abort. ANCM v1 handles it properly for out-of-process and so should ANCM v2 for both, in-process and out-of-process.

```
public class Startup
{
	public Startup(IHostingEnvironment env)
	{
		HostingEnvironment = env;
	}

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddMvcCore()
			.AddAuthorization()
			.AddRazorPages()
			.AddRazorViewEngine()
			.SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
	}
	public void Configure(IApplicationBuilder app)
	{
		app.Use((context, next) =>
		{
			context.Abort();
			return next();
		});
		app.UseMvc();
	}
}
```

**Comment by pakrym** [comment]
I can't repro the issue using the code you provided. Out-of-proc reliably serves `HTTP Error 502.3 - Bad Gateway`. Let's see if issue reproes for you after preview3 update.

**Comment by rockerinthelocker** [comment]
With 2.2.0-preview3-35497, in-process works, out-of-process still fails to reset the connection and returns

```502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.```

instead. Since a connection reset is expected (and works in ANCM v1), what's the point of breaking things and serving a 502 instead?

**Comment by pakrym** [comment]
Serving 502 is not breaking, it's a valid response in the situation when the response wasn't started by IIS yet.

**Comment by rockerinthelocker** [comment]
@coolcsh @DamianEdwards @davidfowl, It's a breaking change because the connection is reset with ANCM v1 while ANCM v2 now returns HTTP 502. https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.abort clearly states 'Aborts the connection underlying this request.'

**Comment by rockerinthelocker** [comment]
How comes it works with ANCM v1 as expected, but no longer with ANCM v2?

**Comment by pakrym** [comment]
ANCM V1 wasn't clever enough to correctly send 502 when the response wasn't started yet.

**Comment by rockerinthelocker** [comment]
If the application aborts the request, the expectation is that the connection is reset and no response is returned -- and, by the way, this is how ASP.NET handles it since day one.

**Comment by pakrym** [comment]
Closing, we are not planning to fix this.
