### ISSUE TITLE
Feature request for publish-iis tool: Ability to override default attributes on the aspNetCore element

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#144]
@moozzyk 

[Opened as an issue instead of rolled into the https://github.com/aspnet/IISIntegration/issues/139 discussion b/c I hope it is important enough to merit its own focus.]

One of the nicest things about the tool is its ability to generate a `web.config` for a project. This means one less trivial file lying around in projects.

I noticed though that it hardcodes values for the attributes that devs may want to set. What would be really nice would be if the tool could set things like `stdoutLogFile`, `startupTimeLimit`, and especially `stdoutLogEnabled` in the script command. Something like this (and showing the most important one to me) ...
```json
"postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% 
    --framework %publish:FullTargetFramework% --stdoutLogEnabled true" 
```
... similar switches for `--stdoutLogFile .\some_funky_log_path\my_funky_log_prefix` and `--startupTimeLimit 20` ... that app better start **quick**! :smile:

The full list would be ...
```
processPath (override whatever the tool would normally provide)
arguments*
startupTimeLimit
startupRetryCount
shutdownTimeLimit
rapidFailsPerMinute
requestTimeout
stdoutLogEnabled
stdoutLogFile
processesPerApplication
forwardWindowsAuthToken
recycleOnFileChange
```
*Ultimate `arguments` control:
- `--arguments-override {string}` for overriding what the tool would normally put there.
- `--arguments-include {string}` for adding arguments to what the tool would normally put there (e.g., adding arguments to the shared framework-style `.\myapp.dll` argument supplied by the tool).

I don't think it could be taken as far as env vars. That's just too crazy. The dev should supply the file if they need that level of customization.

As it stands, I can't really use the tool without this functionality to eliminate `web.config` files from my projects. ~~I don't want to edit files in published output to enable the log every time I publish~~, and having a `web.config` in my project with that attribute set the way I want defeats the value of the tool for me, namely I'd like to get `web.config` totally out of my projects. [EDIT] Looks like you mod a prior-published `web.config`, so I could change once and the tool would update each pass; however, that's still too unreliable for me: I clean my `bin` and `obj` folders every so often.

What da ya tinks?

**Comment by moozzyk** [comment]
The publish-iis tool touches only `processPaths` and `arguments` (for portable apps). Anything else (if exists) is intact. `stdoutLogFile` and `stdoutLogEnabled` are only added (if they don't already exist) to make it easy to turn on logging. `startupTImeLimit` is obsolete in AspNetCoreModule and is going away (I already made change to not add this attribute locally). For any other setting (be it related to AspNetCoreModule or not) - I don't think we want to support them as parameters. Rather you should create your own web.config and allow the publish-iis update only executable path and arguments. The list of the options you provided is big and can become even bigger. It could be hard to maintain the parity between AspNetCoreModule and publish-iis. The way it works today allows for the same flexibility without hardcoding anything in the tool. On top of that - you would already have to do that if you needed to set some additional settings that are not specific to AspNetCoreModule.

**Comment by GuardRex** [comment]
Ok, but it begs the question: "What good is it for anything but the most trivial apps?"

At the minimum, having the ability to enable the log and set the log path would probably be widely used. I can also see the `processPath` override and `arguments` thing being a big hit: There will be a lot of devs who would like to override or add-to any argument the tool supplies for a tool-generated file. Yes, forget about the rest ... I'm thinking perhaps too **big** on the rest of it.

In my case though right now, I can't use it: I need the log enabled. I can't trust that my `bin` won't get cleaned of a manually-modified `web.config` there. There is no point in the tool if I have to keep a `web.config` in my project files. I may as well drop the tool ... save myself a second of downloading, save a second of running it, and keep my `project.json` leaner ... and just have `web.config` setup in the project with hardcoded `processPath` and `arguments`, as I do right now.

I'm just say'in ... if you really wanted to blow the doors off this thing, it needs the ability to customize the completely-tool-generated `web.config` file in the script command IMO. Ok ... I made my case. Thanks for hearing me out.

[... and ... YES! ... It didn't escape my attention that I can still rock on this technology: I just need to clone it, mod it, and use my `guardrex-publish-iis` tool. :wink: ... that was one of the cool things about this being done in the open, and I thank you for that option! :smile: ]

If it's ok with you, I'd like to leave this open for 48 hours to see if any other devs have an opinion to share about it. I hope my fellow community members will give this idea some :heart: love :heart:.

**Comment by Bartmax** [comment]
Does the tool pick a web.config from project folder (not bin) and use that as a base ? Sounds like a more reasonable approach to that situation instead of having params for everything.

**Comment by GuardRex** [comment]
@Bartmax Yes and no. It will mod the `processPath` and `arguments` of your existing file,, and that's fine for those people who want to keep the file in their projects. What I'd like to do is drop the file completely from my projects and have the tool generate it for me, but I need more control over the attributes when it does that.

**Comment by Bartmax** [comment]
@GuardRex what is the reason for you to want to drop the file from your project? If you want to support IIS in a custom (non-default) configuration I think it's valid to assume you can have that file on your project, unless I'm missing something.

**Comment by GuardRex** [comment]
It would result in one fewer trivial files cluttering up my projects that I think a tool like this should be able to generate on-the-fly for published output.

**Comment by GuardRex** [comment]
Amazming how powerful this stuff is. I was able to clone and mod the tool to ...
- default enable the log output to `true`
- set the log filename prefix to the `appName` (sans the extension)

... in **15 minutes** by changing two lines of code in the tool. **Nice!** :+1:
```c#
SetAttributeValueIfEmpty(aspNetCoreElement, "stdoutLogEnabled", "true");
```
```c#
var logPath = Path.Combine(configureForAzure ? @"\\?\%home%\LogFiles" : @".\logs", 
    System.IO.Path.ChangeExtension(appName, null)).Replace("/", "\\");
```
```json
"tools": {
    "GuardRex.AspNetCore.Server.IISIntegration.Tools": {
        "version": "1.0.0",
        "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
}
```
```xml
<aspNetCore 
    processPath=".\teststandalone.exe" 
    stdoutLogEnabled="true" 
    stdoutLogFile=".\logs\teststandalone" />
```

No other comments have come in; and with this being so easy to do and no @moozzyk :heart: for it, I'll close now. Thanks again for considering the proposal.

**Comment by moozzyk** [comment]
I actually was thinking about not blindly overwriting arguments for portable apps for a while. Filed an issue to track this https://github.com/aspnet/IISIntegration/issues/147

**Comment by GuardRex** [comment]
That's cool ... but I want to get rid of `web.config` from my apps on a permanent basis. After looking more careful at how this thing works, I think it would be trivial to mod it for script command line arguments to override the default values for the file. I don't need to take it that far ... what I did above in two lines solves my immediate problems. I'm just shocked at how quick and easy it was to do this ... 15 minutes. Crazy good stuff! :smile:

**Comment by GuardRex** [comment]
Custom `publish-iis` tooling example based on the official tooling: https://github.com/GuardRex/GuardRex.AspNetCore.Server.IISIntegration.Tools

Four differences for this custom version:

1. This project produces a self-contained standalone execuable application.
2. The `stdout` log is enabled by default.
3. The `stdout` log filename is prefixed with the application name.
4. Hidden Segments are generated for three sensitive files in the content root path so that they would never be served by IIS in the event that the `web.config` file were ever accidently renamed or removed from the deployment. The files are: `my_application.xml` [XML Document Comments file (if present in the published output)], `my_application.deps.json`, and `my_application.runtimeconfig.json`.
