### ISSUE TITLE
ProdCon build of Hosting Bundle includes wrong version of .NET Core Runtime

### ISSUE THREAD

**Issue by mikeharder** [aspnet/IISIntegration#1444]
The ProdCon build of the Hosting Bundle includes the wrong version of the .NET Core Runtime.  The suspected root cause is that the ProdCon version of the runtime is not being used by the Hosting Bundle build.

For example, at this page:

https://github.com/dotnet/versions/tree/969b9f06954b24150493fd4245386ca1e2d3701a/build-info/dotnet/product/cli/release/2.2

The SDK `dotnet-sdk-2.2.100-preview3-009417-win-x64.zip` includes the following versions:

```
Microsoft.AspNetCore.All 2.2.0-preview3-35304
Microsoft.AspNetCore.App 2.2.0-preview3-35304
Microsoft.NETCore.App 2.2.0-preview3-26924-02 
```

While the Hosting Bundle `dotnet-hosting-2.2.0-preview3-35304-win.exe` includes the following versions:
```
Microsoft.AspNetCore.All 2.2.0-preview3-35304
Microsoft.AspNetCore.App 2.2.0-preview3-35304
Microsoft.NETCore.App 2.2.0-preview2-26905-02
```

**Comment by pakrym** [comment]
The issue is that WindowsInstallers build configuration doesn't go through https://github.com/aspnet/Universe/blob/master/run.ps1 that downloads prodcon version file https://github.com/aspnet/Universe/blob/62edf4dd38d74bf2ed9446b51b4f14c3daab288f/run.ps1#L216.

**Comment by mikeharder** [comment]
@natemcmaster: I would like to fix this sooner than later to unblock testing of the HostingBundle.  Do you know what needs to be changed?

**Comment by natemcmaster** [comment]
We need to flow ProdCon version variables into the installer's build script: https://github.com/aspnet/Universe/blob/master/src/Installers/Windows/build.ps1. This should be similar to what already exists in https://github.com/aspnet/Universe/blob/62edf4dd38d74bf2ed9446b51b4f14c3daab288f/run.ps1#L212-L218

**Comment by jkotalik** [comment]
@mikeharder the next prodcon build should fix this issue. Please verify this when you get the chance.

**Comment by jkotalik** [comment]
I went ahead and verified this; version is updated. Not sure when the Hosting Bundle will be updated here: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.2

**Comment by mikeharder** [comment]
Verified fixed
