### ISSUE TITLE
ANCM TCP packet loss

### ISSUE THREAD

**Issue by eger-geger** [aspnet/IISIntegration#1459]
I have a setup when multiple sites (asp.net core, asp.net, python) are hosted in IIS together with [Shibboleth Service Provider](https://wiki.shibboleth.net/confluence/display/SP3/Home) which acts before request reaches the actual site code and passes authenticated user information to applications via request headers. It works fine until one of the headers get bigger (over 16 KB of base64 encoded text). Once it happens leading part of the request seem to do be dropped on transport level.

I've setup a wireshark to watch TCP packets going from IIS to Kestrel. When header values are small enough packets represent valid HTTP requests. When header got bigger the request seems to begin with part of long header value. First request line is missing, most of header definitions are missing. The message begins with truncated value of long header (which I've checked is really part of what should be send in that header) and ends with header value tail and possible other smaller header which might go after.

It seems like some buffer or memory overflow issue inside ANCM because it happens for ASP NET Core sites only. Similar setup works perfectly for ASP.NET and python sites for the same users.

Also, the same setup (ASP.NET Core sites) works perfectly on one machine but behaves as described above on another. Both machines are Windows 10 using same versions of IIS and same netcore hosting bundle (2.1.2).

Is there some setting I am missing ? What could go wrong ?

**Comment by Tratcher** [comment]
16kb sounds like you'd be hitting the IIS header size limit ([MaxFieldLength](https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows)), but if that were the case you should see an immidate 400 response without anything being forwarded to Kestrel.

What is MaxFieldLength set to on your system?

Can you test without Shibboleth?

**Comment by muratg** [comment]
@eger-geger Any new/other findings from your side on this issue?

**Comment by muratg** [comment]
@eger-geger can you also share a wireshark trace please?

**Comment by eger-geger** [comment]
Hi! Sorry for late response. I've left VM running for 2 weeks and cannot reproduce it there any longer. It was the only place where I could reproduce it. I'll try to investigate more and post here if I'll have new findings.

**Comment by muratg** [comment]
Closing this issue. @eger-geger if you see issues again, please let us know and file another one with a trace attached. Thanks!
