### ISSUE TITLE
IHostedService won't start automatically on IIS even if preload enabled

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#1465]
_From @Ldoppea on October 3, 2018 15:39_

Hi,

I'm working on a .Net Core Web Api that uses a IHostedService. But I struggle on making it start automatically after a windows reboot.

I implemented the IHostedService as explained here : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1

When debugging then everything works fine.

I deployed it on a Windows Server 2012 R2 running IIS 8.5.

The IIS is configured with : 
- .Net Core 2.1 Runtime installed
- .Net Core 2.1 Runtime & Hosting Bundle installed
- Pool : Start Mode = AlwaysRunning
- Site : Preload Enabled = true

When I restart the server or if I do a `iisreset`, then the application won't start automatically.
The only way to start it is to call one of its controller at least one time. Then the IHostedService will start and work normally.

This behavior seems to be the Start Mode = OnDemand.

Did I miss something in the website configuration?

Thanks

_Copied from original issue: aspnet/Hosting#1557_

**Comment by Ldoppea** [comment]
Sorry for the wrong channel.

**Comment by shirhatti** [comment]
You'll need to use the Application Initialization feature in IIS to achieve what you want. See https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization

**Comment by Ldoppea** [comment]
Are the instructions on this link compatible with a .Net Core web api?

I tried to apply them, but nothing changes.

**Comment by shirhatti** [comment]
@jkotalik Did you recently look into AppInit? If not, I'll take a closer look

**Comment by jkotalik** [comment]
Not yet, issue is on the backlog.

**Comment by pakrym** [comment]
> Did you recently look into AppInit? If not, I'll take a closer look

I did, it worked and I've added some tests: https://github.com/aspnet/IISIntegration/pull/1402
