### ISSUE TITLE
Change the template for 50x error page

### ISSUE THREAD

**Issue by muratg** [aspnet/IISIntegration#1470]
Folks are currently get confused and think the issues are with ANCM instead of the application.

**Comment by pakrym** [comment]
Has to be done before shim ships.

**Comment by muratg** [comment]
@pakrym @jkotalik could one of you pick this?

**Comment by rockerinthelocker** [comment]
@muratg @coolcsh , Is it about design or wording? If the former, please ensure server administrators have a switch to enforce the IIS design to prevent any confusion for support staff. Thank you!

**Comment by davidfowl** [comment]
@rockerinthelocker not sure what you mean. Can you clarify?

**Comment by rockerinthelocker** [comment]
@davidfowl , Same here. Maybe you can be more specific on what you don't understand? Thank you!

**Comment by rockerinthelocker** [comment]
That's fine so long the change is in compliance with IIS ```httpErrors``` => ```errorMode``` settings, especially its default setting ```DetailedLocalOnly```. But I'm sure you guys put security first anyway. Thank you!
