### ISSUE TITLE
question: What will work in/with  `in-process` model

### ISSUE THREAD

**Issue by John0King** [aspnet/IISIntegration#1531]
1. [x] asp.net-core on dotnet core with  framework-dependent-publish
2. [ ] one application pool  multiple application
3. [x] self-dependent-publish app
4. [ ] asp.net core on .net framework

**Comment by Tratcher** [comment]
One core app per app pool.
Standalone core apps will work. 
.net framework apps won't.

**Comment by John0King** [comment]
**I really hope we can use In-Process model without any downside.**
AFAIK, IIS support multiple site running in one pool (including sub-application) and they both running with full framework(except they are not executable),.
Is it possible to find a way to load full framework executable file (Is it just need decode PE file)?

and for multiple app per pool scenario , since there only have a `Main` method as entrypoint ,  give a thread per site as its main thread should work.
