### ISSUE TITLE
[AspNetCoreModule] consider an 'auto-start' option

### ISSUE THREAD

**Issue by tuespetre** [aspnet/IISIntegration#161]
With a 'traditional' ASP.NET application, IIS could be configured to have the app pool "Always Running", which would trigger `Application_Start` or a `Startup` class, giving developers a chance to schedule recurring background tasks and trust that they ran as long as IIS and the app pool were running. This was great for simple, small-scale deployment scenarios.

HttpPlatformHandler was not as friendly and enabling for such scenarios. Now that HttpPlatformHandler has been forked to AspNetCoreModule, could an option be added that causes the module to start the application immediately instead of waiting for a request?

**Comment by mikes-gh** [comment]
Shouldn't the application lifetime be controlled at the IIS app pool level as it is now?

**Comment by GuardRex** [comment]
@mikes-gh It is, @tuespetre is calling attention to the startup nature of the app. Take a Windows Service, for example. When you start that service and set it to automatically start, you know that your service is going to fire right up and always run when the server restarts. We don't have that for IIS apps, and I think this is a great idea.

**Comment by mikes-gh** [comment]
@Guardrex Being devils advocate :smile: I'm not sure web.config could control the app pool process lifetime variables such as "Always Running" ?  The app pool might have more than one app in which case you might have 2 settings fighting each other.  Unless we change the model to one app pol per app.
If @tuespetre is saying lets replace Application Initialization with a new mechanism in AspnetcoreModule I whole heartily agree.  Its a real pain at the mo and pretty much every app I write I want always running and warmed up by default.

**Comment by GuardRex** [comment]
@mikes-gh AFAIK that's a non-starter b/c they issued earlier guidance: one app for one AppPool ... but that may have changed. I don't recall a more recent discussion on it.

I wasn't really too concerned about `web.config` setting it up; although, I believe you can set Idle Time-out with the `<processModel>` and the Always Running with `applicationInitialization` in `web.config`, but I've never done it. If I could just set things up manually, I'd be happy.

> I want always running and warmed up by default.

:+1:

**Comment by Tratcher** [comment]
We plan to use this feature to replace the DEBUG request (#102) VS currently sends to start the process. When that happens remove the DEBUG filter from IISMiddleware.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#29
