### ISSUE TITLE
Head-check on moving `web.config` back to `wwwroot`

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#164]
@JunTaoLuo @Tracher @moozzyk

[Opened outside of the discussion on the announcement so that I can link/find it easier.]

Coming off of [Publish for IIS changes to web.config location (Announcements/#173)](https://github.com/aspnet/Announcements/issues/173) and [concern over accidental renaming or moving of `web.config` that would leak sensitive files](https://github.com/aspnet/IISIntegration/issues/158#issuecomment-215468241), may I get a head-check for those wishing to put `web.config` back into `wwwroot`?
- ~~Use `.UseContentRoot("../")` on `WebHostBuilder`~~
- Use `.UseContentRoot(Directory.GetParent(Directory.GetCurrentDirectory()).FullName)`
- Set `processPath="..\my_app.exe"` (self-contained) or `arguments="..\my_app.dll"` (portable)
- Set `stdoutLogFile="..\logs\stdout"` (presuming `logs` is in the content root)
- Move `web.config` to `wwwroot`
- Point the IIS website physical path to `wwwroot`

Seems ok in testing. Is that correct or would that break something?

**Comment by Aequoris** [comment]
I second this. I too will be moving it back to be similar to RC1.

**Comment by GuardRex** [comment]
Just to clarify one more point. I recall the conversations with @moozzyk on paths. I'm not asking about dev/test, where debugging might not like that `.UseContentRoot("../")` ... One could easily program around that. I'm asking about on the IIS server in production.

**Comment by muratg** [comment]
@GuardRex did you get a chance to test it on Azure Websites?

**Comment by GuardRex** [comment]
@muratg No. I only ran an IIS Local test. It would be good to know if this will break in Azure Apps.

**Comment by davidfowl** [comment]
`Use .UseContentRoot("../")` Seems non portable. It'll only ever work if always hosting on IIS, self host will fail.

**Comment by GuardRex** [comment]
Very interesting ... It works self-host if you double-click the `.exe`, but it fails if you run the `.exe` through the command line???? What's up with that?

**Comment by GuardRex** [comment]
Spoke too soon. I was in the wrong dir. I wasn't in the `publish` directory. Kestrel runs it from the command line or double-clicking the `.exe` ...

![capture](https://cloud.githubusercontent.com/assets/1622880/15064247/d9d65c68-1317-11e6-990a-d29a07fd1cc4.PNG)

**Comment by GuardRex** [comment]
It fails in VS Code debug ...
```
App Started: 5/6/2016 4:20:39 AM
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
Hosting starting
Exception thrown: 'System.AggregateException' in Microsoft.AspNetCore.Server.Kestrel.dll
```
... but if you simply change the `../` to `Directory.GetCurrentDirectory()`, of course, it runs in debug.

@Bartmax might be testing this config in Azure Apps soon.

**Comment by moozzyk** [comment]
@GuardRex - I actually think it could be possible to contain all the changes to `web.config`. Instead of changing the content root in the application you could try setting it as an environment variable (`ASPNETCORE_CONTENTROOTKEY`) in web.config. You would need to ensure that configuration is reading environment variables.

**Comment by GuardRex** [comment]
@moozzyk There would be no effect on the app for debugging that way :+1:, so that sounds very good. That would also be easy to roll into my `GuardRex.AspNetCore.Server.IISIntegration.Tools` <--- **malware** :smile:. I'll test this approach on Saturday. Thx. /cc @Aequoris

**Comment by GuardRex** [comment]
@moozzyk @Aequoris

#### Env Var Approach
I didn't fully implement it b/c I could see along the way that it was something I wasn't interested in using, but it was shaping up along the lines of the following. Please correct the pseudo-code for others. I actually stopped cold with what you see here ...
```json
"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*"
```
```c#
using Microsoft.Extensions.Configuration;

var config = new ConfigurationBuilder()
    .AddEnvironmentVariables(prefix: "ASPNETCORE_")
    .Build();
var contentRootPath = Environment.GetEnvironmentVariable("ASPNETCORE_CONTENTROOT") ?? 
        Directory.GetCurrentDirectory();
var host = new WebHostBuilder()
    .UseContentRoot(contentRootPath) ...;
```
`web.config` to be placed in `wwwroot` ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add 
          name="aspNetCore" 
          path="*" 
          verb="*" 
          modules="AspNetCoreModule" 
          resourceType="Unspecified" />
    </handlers>
    <aspNetCore 
          processPath="..\teststandalone.exe" 
          stdoutLogEnabled="true" 
          stdoutLogFile="..\logs\teststandalone">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_CONTENTROOT" value="../" />
      </environmentVariables> 
    </aspNetCore>
  </system.webServer>
</configuration>
```

Nah ..... It's not called the "CRAPJOB" pattern ... it's the "NUTJOB" pattern. :smile: This approach seems to do **a lot** of engineering for something that should be a simple workaround. That's too much crap floating around in my startup pattern, and I had no other interest in env vars, so it ends up bringing that into the app just for this one purpose.

#### Another option ... `Hidden Segments`
Going back to my earlier idea (and the one spelled out in the IIS doc): Leave `web.config` in the content root but leverage `Request Filtering` to protect known sensitive files. You know, a big aspect of "NUTJOB" is to keep server config at the absolute bare minimum, so I would want to implement this in `web.config`.

`web.config` in its normal spot in the content root ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add 
      <add 
          name="aspNetCore" 
          path="*" 
          verb="*" 
          modules="AspNetCoreModule" 
          resourceType="Unspecified" />
    </handlers>
    <aspNetCore 
          processPath=".\teststandalone.exe" 
          stdoutLogEnabled="true" 
          stdoutLogFile=".\logs\teststandalone">
    <security>
      <requestFiltering>
        <hiddenSegments>
          <add segment="teststandalone.xml" />
          <add segment="teststandalone.deps.json" />
          <add segment="teststandalone.runtimeconfig.json" />
        </hiddenSegments>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```
I confirmed that this works. The `Hidden Segments` entries shown below were loaded from the `web.config` when IIS hit the file ...

![capture](https://cloud.githubusercontent.com/assets/1622880/15093057/5378245a-1441-11e6-8e02-87f03b3abc03.PNG)

Note: `teststandalone.xml` is not a normal (cli-generated) file. This file is here because I set `"xmlDoc": true,` on `buildOptions` in `project.json` to get an XML Documentation comments file out that I would leave in the content root.

This is lean, clean, and cool :sunglasses: as far as the app is concerned. It would very easy to roll the logic for this into `GuardRex.AspNetCore.Server.IISIntegration.Tools`. I'll do that because I want the tool to entirely create the file (with logging enabled and with a custom log filename) when I publish and not need to have a `web.config` file in my projects ... one less trivial file lying around the office! :+1:

**Comment by GuardRex** [comment]
@Bartmax @Aequoris Were either/both going to test for `web.config` in `wwwroot` for Azure Apps? I'm getting ready to close this, because I'm going to go with the `Hidden Segments` approach and just leave `web.config` in my content root (full explanation is below).

#### Modding `dotnet-publish-iis` tooling to include `Hidden Segments`

I have a tooling version that will do this now :sparkles: auto-magically :sparkles:. Now if @moozzyk thought `GuardRex.AspNetCore.Server.IISIntegration.Tools` was "**malware**" before, he'll think this is the **largest abomination on Earth** now. I'll be looking over my shoulder for the next few weeks! :smile:

- Enables application logging by default
- Changes the name of the log file to be the application name (sans the file extension)
- Adds the bits for `Hidden Segments` to `web.config`, including XML Doc comments file

I'm using the tool as a self-contained `.exe` program in my projects, but there shouldn't be any problem leaving it as a tooling dependency and portable app and running it in the usual way. I trigger it ...
```
"scripts": {
    "postpublish": "<PATH_TO_MY_EXE>\\dotnet-publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
},
```
... and there is no `tools` section in my `project.json`; however, you can clone and mod the tooling and use it in the ordinary way ...
```json
"scripts": {
  "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
},
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
    "version": "1.0.0-*",
    "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
  }
}
```

I'm going to show the full `WebConfigTransform.cs`, which contains all of the changes that I made to pull this off.

```c#
using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;

namespace GuardRex.AspNetCore.Server.IISIntegration.Tools
{
    public static class WebConfigTransform
    {
        public static XDocument Transform(XDocument webConfig, string appName, bool configureForAzure, bool isPortable)
        {
            const string HandlersElementName = "handlers";
            const string aspNetCoreElementName = "aspNetCore";
            const string SecurityElementName = "security";
            const string RequestFilteringElementName = "requestFiltering";
            const string HiddenSegmentsElementName = "hiddenSegments";
            
            webConfig = webConfig == null || webConfig.Root.Name.LocalName != "configuration"
                ? XDocument.Parse("<configuration />")
                : webConfig;

            var webServerSection = GetOrCreateChild(webConfig.Root, "system.webServer");

            TransformHandlers(GetOrCreateChild(webServerSection, HandlersElementName));
            TransformAspNetCore(GetOrCreateChild(webServerSection, aspNetCoreElementName), appName, configureForAzure, isPortable);

            // Add the Hidden Segments to secure sensitive files
            var securitySection = GetOrCreateChild(webServerSection, SecurityElementName);
            var requestFilteringSection = GetOrCreateChild(securitySection, RequestFilteringElementName);
            var hiddenSegmentsSection = GetOrCreateChild(requestFilteringSection, HiddenSegmentsElementName);
            var appNameWithoutExtension = System.IO.Path.ChangeExtension(appName, null);
            TransformHiddenSegments(hiddenSegmentsSection, appNameWithoutExtension, ".xml");
            TransformHiddenSegments(hiddenSegmentsSection, appNameWithoutExtension, ".deps.json");
            TransformHiddenSegments(hiddenSegmentsSection, appNameWithoutExtension, ".runtimeconfig.json");

            return webConfig;
        }
        
        private static void TransformHiddenSegments(XElement hiddenSegmentsElement, string appName, string fileNamePart)
        {
            var addSegmentElement =
                hiddenSegmentsElement.Elements("add")
                    .FirstOrDefault(e => string.Equals((string)e.Attribute("segment"), appName + fileNamePart, StringComparison.OrdinalIgnoreCase));

            if (addSegmentElement == null)
            {
                addSegmentElement = new XElement("add");
                hiddenSegmentsElement.Add(addSegmentElement);
            }

            addSegmentElement.SetAttributeValue("segment", appName + fileNamePart);
        }

        private static void TransformHandlers(XElement handlersElement)
        {
            var aspNetCoreElement =
                handlersElement.Elements("add")
                    .FirstOrDefault(e => string.Equals((string)e.Attribute("name"), "aspnetcore", StringComparison.OrdinalIgnoreCase));

            if (aspNetCoreElement == null)
            {
                aspNetCoreElement = new XElement("add");
                handlersElement.Add(aspNetCoreElement);
            }

            aspNetCoreElement.SetAttributeValue("name", "aspNetCore");
            SetAttributeValueIfEmpty(aspNetCoreElement, "path", "*");
            SetAttributeValueIfEmpty(aspNetCoreElement, "verb", "*");
            SetAttributeValueIfEmpty(aspNetCoreElement, "modules", "AspNetCoreModule");
            SetAttributeValueIfEmpty(aspNetCoreElement, "resourceType", "Unspecified");
        }

        private static void TransformAspNetCore(XElement aspNetCoreElement, string appName, bool configureForAzure, bool isPortable)
        {
            // Forward slashes currently work neither in AspNetCoreModule nor in dotnet so they need to be
            // replaced with backwards slashes when the application is published on a non-Windows machine
            var appPath = Path.Combine(configureForAzure ? @"%home%\site" : ".", appName).Replace("/", "\\");
            var logPath = Path.Combine(configureForAzure ? @"\\?\%home%\LogFiles" : @".\logs", System.IO.Path.ChangeExtension(appName, null)).Replace("/", "\\");

            if (!isPortable)
            {
                aspNetCoreElement.SetAttributeValue("processPath", appPath);
            }
            else
            {
                aspNetCoreElement.SetAttributeValue("processPath", "dotnet");

                // In Xml the order of attributes does not matter but it is nice to have
                // the `arguments` attribute next to the `processPath` attribute
                aspNetCoreElement.Attribute("arguments")?.Remove();
                var attributes = aspNetCoreElement.Attributes().ToList();
                var processPathIndex = attributes.FindIndex(a => a.Name.LocalName == "processPath");
                attributes.Insert(processPathIndex + 1, new XAttribute("arguments", appPath));

                aspNetCoreElement.Attributes().Remove();
                aspNetCoreElement.Add(attributes);
            }

            SetAttributeValueIfEmpty(aspNetCoreElement, "stdoutLogEnabled", "true");
            SetAttributeValueIfEmpty(aspNetCoreElement, "stdoutLogFile", logPath);
        }

        private static XElement GetOrCreateChild(XElement parent, string childName)
        {
            var childElement = parent.Element(childName);
            if (childElement == null)
            {
                childElement = new XElement(childName);
                parent.Add(childElement);
            }
            return childElement;
        }

        private static void SetAttributeValueIfEmpty(XElement element, string attributeName, string value)
        {
            element.SetAttributeValue(attributeName, (string)element.Attribute(attributeName) ?? value);
        }
    }
}
```

**Comment by dazinator** [comment]
This issue is probably related, I perhaps should have created it here: https://github.com/aspnet/Home/issues/1645#issuecomment-230870188
