### ISSUE TITLE
Hosting the Mvc.Server project on IIS with net451 not working

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/IISIntegration#169]
## project
https://github.com/openiddict/openiddict-core
This project has sample MVC.Server which i am trying to host on IIS

## Actual Behaviour
when i publish with netcoreapp1.0 as a target framework and host on IIS it works fine.
But when i publish with net451 as a target framework and  host on IIS it doesn't.

For More info about this
https://github.com/openiddict/openiddict-core/issues/105

**Comment by Tratcher** [comment]
Please do not open the same bug in multiple repos.
https://github.com/aspnet/Hosting/issues/744
