### ISSUE TITLE
Not using IISPlatformHandler in Azure AppService causes 301 loop

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/IISIntegration#170]
It looks like IISPlatformHandler went away in RC2, but just in case...any idea why removing IISPlatformHandler would cause a site in Azure AppService to just loop 301 (redirect)? The only redirect I'm using is to go to https but no code changed except removing the IISPlatformHandler (which I thought was only to support Windows Auth).

**Comment by Tratcher** [comment]
Because it was applying the x-forwarded-proto header to your Scheme so you knew the request was HTTPS. Otherwise the request appears to be HTTP because that's what's used between the module and back-end process.

**Comment by shawnwildermuth** [comment]
Again, not sure what happens in RC2, but in this case we need IISPlatformHandler whenever we're IIS hosted, not just in Windows Auth scenarios (since redirect to https is such a common case). Right?

**Comment by Tratcher** [comment]
Right. In RC2 this has moved to Main where you call UseIISIntegration and it hooks up the dynamic port and middleware. https://github.com/aspnet/IISIntegration/blob/dev/samples/IISSample/Startup.cs#L79

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
