### ISSUE TITLE
Disable shutdownTimeLimit when the debugger is attached

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#171]
Similar to how startupTimeLimit is ignored while the debugger is attached to enable debugging startup, shutdownTimeLimit should also be ignored to help debug shutdown.

**Comment by muratg** [comment]
@Tratcher What's the impact with the debugging experience?

cc @shirhatti

**Comment by Tratcher** [comment]
It's difficult to debug your shutdown code because the process gets terminated.

**Comment by shirhatti** [comment]
Same as #173
