### ISSUE TITLE
Disable requestTimeout when the debugger is attached

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#173]
Similar to how startupTimeLimit is ignored while the debugger is attached to enable debugging startup, requestTimeout should also be ignored to help debug requests.

**Comment by pan-wang** [comment]
this is a per request issue. If we check whether debugger is attached for each request, there will be significant performance cost. There is a simple workaround that user can change the request time out value at the web.config.

**Comment by Tratcher** [comment]
What's the % overhead per request for checking if the debugger is attached?

**Comment by shirhatti** [comment]
We don't have concrete % overhead since we haven't protoyped it. However, we are confident there will be a perf impact looking at the code path.
Since there are multiple config changes required (see also #171), we think it's best to document it in a debugging document.
