### ISSUE TITLE
app_offline does not work if app_offline.htm is empty

### ISSUE THREAD

**Issue by moozzyk** [aspnet/IISIntegration#174]
If you drop/create an empty app_offline.htm the application is not getting stopped and the app_offline.htm is not served.

**Comment by pan-wang** [comment]
current code loads the file content into a buffer. if the file size is 0, the load is marked as failed and therefore no process shutdown will be triggered. Will fix it in next release.

**Comment by pan-wang** [comment]
This was fixed
