### ISSUE TITLE
IISIntegration (dotnet/iis) Gitter Room?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#175]
@Tratcher @JunTaoLuo @moozzyk @pranavkm

I asked at http://forums.dotnetfoundation.org/t/i-could-really-use-an-iisintegration-gitter-room/1632 ... but prob better to ask over here. Can we have an IISIntegration Gitter room?

It would provide a quiet place to chat with devs on IIS issues and troubleshoot issues. JabbR is almost :skull: dead :skull:, and Slack has a sign-up barrier to meet with devs who don't have an aspnetcore Slack Team account. It's best if there is just a link that I can provide that provides more of a "guest chat" experience, and a GH account gets one right into Gitter.

If you'd be up for creating this room, would you link the room in the README of this repo? I'd like to sit over there for a few weeks/months and see if it gets any traffic on IIS issues. Also, consider naming the  room just "iis" (as in "dotnet/iis"), instead of "dotnet/iisintegration."

**Comment by Tratcher** [comment]
@DamianEdwards, @Eilon?

**Comment by Eilon** [comment]
BTW there is already a Gitter room listed at https://github.com/aspnet/Home

* https://gitter.im/aspnet/Home?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by GuardRex** [comment]
@Eilon I know. I'm asking about a Gitter for IISIntegration where I can have IIS-related chats with cats. Home is ok ... but it can get busy with general chats. No prob if this doesn't work out. I made a #iis channel at Slack. The only prob with Slack is that it has this barrier to entry: They have to get a Slack account, so it's not quite as user-friendly getting into it; whereas, the GH sign-in to Gitter is a snap.

**Comment by GuardRex** [comment]
@Eilon btw -- I was planning to "hang out" in there and just see how it goes. I'm not "royalty" of course, but it's not like anyone would go there and it would be completely dead. If nobody ever shows up in such a Gitter room, it could always be shutdown later. I just wanted to see if you'd be up for an experiment with it.

**Comment by GuardRex** [comment]
Nevermind. I think we're good without this.

**Comment by Eilon** [comment]
@GuardRex ah ok, I was just mentioning it in case you hadn't seen it. We're having some discussions on how to optimize some of the communications. We have GitHub, Gitter, JabbR, Slack, various semi-private mailing lists, and I'm sure all kinds of other things. Clearly we need a new chat/message system that will unify all those other systems 😄
