### ISSUE TITLE
Creating .NET Core web app that includes 'web' or 'app' in the name silently fails to launch in VS (it just hangs on launch)

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#176]
_From @BillHiebert on May 10, 2016 23:51_

Create a new Empty .NET Core Web app in VS
Call it "web"

Hit F5 (to launch under IIS Express)

Actual:
It fails to launch (spinning Edge icon waiting for it to load) - there are not even an IIS Express logs to debug the issue

What's happening is kestrel is throwing the following exception. It only repros with projects named "web" and when hosted in iisexpress.
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -4092 EACCES permission denied) ---> Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4092 EACCES permission denied

at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListenerPrimary.CreateListenSocket()
at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerPrimary.<StartAsync>d__9.MoveNext()
--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
at web.Program.Main(String[] args)

```
_Copied from original issue: aspnet/KestrelHttpServer#824_

**Comment by Tratcher** [comment]
_From @benaadams on May 10, 2016 23:54_

The error means the port Kestrel is trying to listen on already has something listening on it

**Comment by Tratcher** [comment]
_From @halter73 on May 11, 2016 0:3_

@benaadams Agreed that that is the most likely explanation. @cesarbs Said he was able to repro and that he would debug it.

**Comment by Tratcher** [comment]
_From @cesarbs on May 11, 2016 0:47_

@benaadams I'm not sure. When you try to listen on a port that's already in use you normally get an `EADDRINUSE`.

**Comment by Tratcher** [comment]
_From @cesarbs on May 16, 2016 19:1_

Interesting find here. Look what happens to the address Kestrel tries to bind to when the project is named "web":

![image](https://cloud.githubusercontent.com/assets/924164/15300460/ad5fdd82-1b5d-11e6-8eea-a70e95dd7b02.png)

Compare to any other project:

![image](https://cloud.githubusercontent.com/assets/924164/15300511/efa9d738-1b5d-11e6-9545-2e7468084762.png)

Looks like the issue is coming from ANCM. cc @pan-wang

**Comment by Tratcher** [comment]
_From @cesarbs on May 16, 2016 19:1_

cc @Tratcher

**Comment by Tratcher** [comment]
Specifically, the ASPNETCORE_APPL_PATH is set to `ROOT/WEBHOST/WEB` for some reason. Is `WEB` a reserved site name in IIS/Express?

**Comment by muratg** [comment]
@pan-wang Is `web` a reserved name in IIS/ANCM?

**Comment by sovaska** [comment]
Facing same problem when project name includes "Web", in my case project name is Transfer.Web

**Comment by Morcatko** [comment]
I have a Project.WebSite and it works fine. Can be repro only when it ends with Web?

**Comment by kspearrin** [comment]
Renamed my project to `Web2` and it works fine now.

**Comment by BillHiebert** [comment]
It does seem to be related to ANCM or Kestrel. I can create and run an MVC5\Webform application with the name web.

**Comment by pan-wang** [comment]
I don't think Web is a reserved keyword in either IIS and IISExpress. Will look at it.

**Comment by lruckman** [comment]
Can confirm creating a new project in RC2 (net461) and naming it Web causes this in VS. Was not the case in RC1. This happen in both brand new projects and those converted from RC1.

**Comment by pan-wang** [comment]
this is bug in ANCM. When resolving the site path, it simply takes the sub string from the app path using the site name and did not consider the app path may already contains string as 'WebRoot' and "AppHost". Will fix it.

**Comment by Tratcher** [comment]
Root cause: ANCM had a bad IndexOf on the string `Machine\WebRoot\AppHost\<sitename>\<appname>\...`. Any project who's name is a subset of those values will get the wrong PathBase and crash Kestrel on launch. E.g. Web, App, Host, Machine, Root, etc..

**Comment by DreamingDevs** [comment]
My project was named ```CarSolution.Identity.Web``` and I am also facing the same problem. So having ```web``` might be the problem?

**Comment by road42** [comment]
As you see in #193 it also fails when the url is something like "http://app.whatever.tld/SaveProjectNameHere"

**Comment by Tratcher** [comment]
@road42 That was because you set your root site name to `APP`. The url didn't matter.

**Comment by road42** [comment]
@Tratcher Ah sorry this wasn't clear enough. Thank you.

**Comment by martincostello** [comment]
I've just come across this issue when deploying an update to a site running RC2 (which was already RC2) when accessing it at ```http://{name}.azurewebsites.net/```. Is this falling foul of the same issue because of the ```web``` in ```azurewebsites```?

**Comment by Tratcher** [comment]
@martincostello I don't think so, it has worked for others on azurewebsites.net.

**Comment by martincostello** [comment]
@Tratcher I've been playing around with this, and I _think_ I've actually narrowed it down to there being RC1 and RC2 bits in the same wwwroot folder after the "delete existing files" option wasn't used when publishing the site. However, I've no idea what change triggered it suddenly making a difference. Deleting every file in wwwroot in Azure, re-publishing and restarting the site fixed the problem with the site not starting.

**Comment by cherici-simone** [comment]
I migrate a solution from RC1 to RC2 and one of the projects was named "Web". I rename it (both name and folder) but I'm still get the same error. Are there "strange" steps to rename a projects?

**Comment by muratg** [comment]
@cherici-simone what was the new name?

**Comment by cherici-simone** [comment]
I try "Site" but nothing...then I try..."aaa" but the error persist. I try
with a new project and perform the same rename without success. I also
change folders, namespace, launchSettings.json and also rename the solution

On Wed, Jun 15, 2016 at 5:50 PM, Murat Girgin <notifications@github.com>
wrote:

> @cherici-simone <https://github.com/cherici-simone> what was the new name?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aspnet/IISIntegration/issues/176#issuecomment-226231094>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG9pOmtsW7QJqzZTPYjA8mk-Iz08SF47ks5qMB9AgaJpZM4Ifmw9>
> .
>



-- 
Simone Cherici

**Comment by martincostello** [comment]
@cherici-simone Is this in Azure? I had issues with a RC1 -> RC2 migration in Azure because there were things left in the site folder for RC1 that created strange conflicting behaviour. Deleting the RC1 remnants via FTP fixed it.

**Comment by Gabee01** [comment]
In my case, changing the port I was using fixed it.. maybe that port was already busy

**Comment by M-Yankov** [comment]
Thanks for the comments.
For anyone who has the same issue, check whether you are hosting an application on the same port in IIS.
That solved my problem.
