### ISSUE TITLE
Latest AspNetCoreModule installer is now part of Server installer

### ISSUE THREAD

**Issue by muratg** [aspnet/IISIntegration#177]
Latest AspNetCoreModule is now part of Server installers. You can download the server MSI from: https://www.microsoft.com/net/download.  Search for "**Windows (Server Hosting)**". This includes .NET shared runtime as well as latest ANCM.

**Comment by nil4** [comment]
@muratg are there any plans to publish a separate installer for AspNetCoreModule only? The use case here is a server hosting multiple apps, where only stand-alone (self-contained) apps should be deployed. To avoid apps accidentally relying on the share runtime being available, no .NET Core bits will be deployed to the server. ANCM, however, needs to be installed in IIS.

**Comment by muratg** [comment]
@nil4 We're considering different options. I think the current investigation is having check boxes on the installer to selectively install components, but no decision has been made yet.

cc @joeloff

**Comment by joeloff** [comment]
That would require a custom bootstrapper application that can interface with the Burn engine. It will be more than one week's worth of work.

**Comment by dotcom9** [comment]
@nil4 I believe there already is a standalone installer. Links [here](https://github.com/aspnet/Announcements/issues/164).

**Comment by nil4** [comment]
@dotcom9 those links point to version 0.8 of ANCM, which is already out-of-date (version 0.9.1965 is currently bundled with the Server Hosting RC2 installer). The version bundled with the RTM release is likely to be revved up again, so at this point I think the links in the announcement are more confusing than helpful.

**Comment by GuardRex** [comment]
@joeloff Would it be a lot easier to zip the module and schema file and shoot them into blob storage for our access, similar to the way the .NET Core Binaries are provided? For the handful of people (relatively speaking) who will be interested in deploying them themselves, that should be fine.

**Comment by Tratcher** [comment]
@GuardRex The installer does more than drop files:
- The module needs to be added to the applicationhost.config
- The handlers section in the applicationhost.config needs to be unlocked
- x86 vs x64
- Enables servicing / windows update

**Comment by GuardRex** [comment]
I know that. I can do that myself (except the last one). It's not a different process than what we do now with Nano TP5.

**Comment by nil4** [comment]
There is in fact an installer for *just ANCM* that, insofar as I tested, does most (all?) the things that @Tratcher listed above. 

On my machine, I found it under *C:\Documents and Settings\All Users\Package Cache\{A0845055-ED2B-41CF-B799-A5765C485F29}v0.9.1965\packages\aspnetcoremodule_x64_en_rc2_14.msi* after installing the Preview1 tooling.

The issue is really that there is no "official" download link to enable installing it separately from the .NET Core runtime.

**Comment by GuardRex** [comment]
The thing I like about zipped content is that I can't run an MSI on Nano, so it would be more convenient to just be able to have the files (`aspnetcore_schema.xml` and `aspnetcore.dll`) available. No biggie ... I can just go on pulling them locally.

I have a suspicion, too, that if a package is made available for Nano that it will be the full bundle, which I don't want. I have a feeling that my fastest way to get the latest ANCM in a standalone scenario will be compiling the OSS ANCM (when it goes OSS).

**Comment by nil4** [comment]
Update for RTM. The ASP.NET Core Module MSI can be found at *C:\Documents and Settings\All Users\Package Cache\\{4ADC4F4A-2D55-442A-8655-FBF619F94A69}v1.0.1967\packages\aspnetcoremodule_x64_en_rc2_39.msi*

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by bgever** [comment]
@muratg So no standalone installer is in the works? We need to have the standalone installer (MSI from the cache as mentioned above) for an important customer (big bank) as well. We can't suggest them to use that hacky way. ;-)

**Comment by GuardRex** [comment]
@bgever You can get it (standalone) from the hosting bundle installer. See the Note in https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#install-the-net-core-windows-server-hosting-bundle

**Comment by bgever** [comment]
@GuardRex Awesome, thanks!

For completeness, here's the note from that page:

> Note - If you only plan to host self-contained deployments and thus don't require the .NET Core runtime on the system, you have the option of only installing the ASP.NET Core Module by running the installer from an Administrator command prompt: DotNetCore.1.0.3_1.1.0-WindowsHosting.exe  OPT_INSTALL_LTS_REDIST=0  OPT_INSTALL_FTS_REDIST=0
