### ISSUE TITLE
AspNetCoreModule should set content type when serving app_offline.htm

### ISSUE THREAD

**Issue by moozzyk** [aspnet/IISIntegration#178]
Currently when AspNetCoreModule does not set content type at all when serving app_offline.htm which  can result in this: https://cloud.githubusercontent.com/assets/1438884/15302651/ec3c58d6-1b68-11e6-9f26-a28fee642c7e.png

**Comment by muratg** [comment]
@pan-wang Could you have a look? 

Also, maybe someone from WebDeploy team should look into default app_offline.html file... I'm not convinced it should have an xml tag.

**Comment by moozzyk** [comment]
There is already an item for this: https://github.com/aspnet/Tooling-Internal/issues/576

**Comment by pan-wang** [comment]
this will be fixed in next release

**Comment by Tratcher** [comment]
@pan-wang please add the `Done` label to issues when you've checked in the fix. We'll plan to verify and close them.

**Comment by pan-wang** [comment]
this has been fixed and will be included in next release
