### ISSUE TITLE
ASP.NET Core RC2 support for Windows Server 2008 RC2?

### ISSUE THREAD

**Issue by PeterJakubik** [aspnet/IISIntegration#179]
Hi
I created an empty RC2 WebApp and it runs ok on windows 7.

In project.json I have
`"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",`

in Main.cs
`var host = new WebHostBuilder().UseKestrel().UseContentRoot(Directory.GetCurrentDirectory()).UseIISIntegration().UseStartup<Startup>().Build();
            host.Run();
`

I want to deploy the app to Windows 2008 R2 server. 
The installation of new aspNetCore IIS Modul (DotNetCore.1.0.0.RC2-WindowsHosting.exe) failed (Error 0x80070002: Failed to find payload: DotNetRedist_x64 in path....,  Error 0x80070002: Failed to cache payload: DotNetRedist_x64). The .NET 4.5.1 is already installed on server.

Is the Windows Server 2008 R2 supported by RC2? 
Is there any way it can be supported?

Thanks
Peter

**Comment by GuardRex** [comment]
@PeterJakubik Yes, your server is supported. I'm going to attempt to repro your issue now.

**Comment by muratg** [comment]
cc @joeloff @pan-wang

**Comment by joeloff** [comment]
Wonder if this is related to the rename we did for the files.

**Comment by joeloff** [comment]
@PeterJakubik can you share the installation logs?

**Comment by GuardRex** [comment]
I'm unable to repro "Error 0x80070002" here with a fresh Azure 2008R2 VM.

**Comment by joeloff** [comment]
As for the Windows version, ANCM requires VersionNT to be >= 6.1. Windows Server 2008 is 6.0. We do support Server 2K8 R2 (you can find a list of version numbers [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx))

We only do the version check for ANCM.

**Comment by PeterJakubik** [comment]
If you still need the installation log, let me know your e-mail address, and l will mail it to you

**Comment by joeloff** [comment]
@PeterJakubik  You can just drag/drop the log into the comment

**Comment by PeterJakubik** [comment]
[dotnet-core-100rc2-windowshosting.txt](https://github.com/aspnet/IISIntegration/files/271350/dotnet-core-100rc2-windowshosting.txt)

**Comment by joeloff** [comment]
@PeterJakubik looks like the error is originating from running the .NET Core runtime installer.

Could you look at your %temp% folder and see if there's a log file starting with Microsoft.NET_CORE or something along those lines.

The .NET Core runtime does bring in the C++ redist as well. I don't see any obvious blocks in the .NET Core runtime, but it carries three separate installers itself so it's likely one of those are the cause of failure.

**Comment by PeterJakubik** [comment]
I looked at the server and it has only VS C++ 2005 redist package installed. 
Which C++ redist version requires the handler?

[Microsoft_.NET_Core_1.0.0_RC2_-_Runtime_(x64)_20160518224752.txt](https://github.com/aspnet/IISIntegration/files/271389/Microsoft_.NET_Core_1.0.0_RC2_-_Runtime_.x64._20160518224752.txt)

**Comment by joeloff** [comment]
It's accessing http://download.microsoft.com/download/8/c/b/8cb4af84-165e-4b36-978d-e867e07fc707/vc_redist.x64.exe (I believe the VS2015 redist)

According to the runtime installer, it fails to download the redist

[23C8:20D0][2016-05-18T22:48:14]e000: Error 0x80072efd: Failed to send request to URL: http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409, trying to process HTTP status code anyway.
[23C8:20D0][2016-05-18T22:48:14]e000: Error 0x80072efd: Unknown HTTP status code 0, returned from URL: http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409
[23C8:20D0][2016-05-18T22:48:14]e000: Error 0x80072efd: Failed attempt to download URL: 'http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409' to: 'C:\Users\USR_AB~1\AppData\Local\Temp\4\{74CD9518-B600-41ED-BC4E-31AA4EA5BCDB}\VC_redist.x64.exe'

**Comment by PeterJakubik** [comment]
I installed the VS 2015 redist x64 from first link and I can install the dotnet core windows hosting successfully. 
The RC2 works on 2K8 R2 Server

Thank you @joeloff

**Comment by GuardRex** [comment]
@Rick-Anderson @shirhatti Do we need to explicitly call out the need for VC++ 2015 x64 for 2008R2 when that is (AFAIK) on 2008R2 by default? Even if not, do we want to add this to the Troubleshooting section? My plan would be to go and repro the way I did before with the other exceptions to get the correct entries for the section (i.e., I'd like to adhere to the same layout we have there now for 'browser response,' 'module log,' and 'Application log').

**Comment by GuardRex** [comment]
@Rick-Anderson @shirhatti @danroth27 I'm going to investigate this further later today and open a discussion item in Docs with my findings.

**Comment by PeterJakubik** [comment]
I believe my issue was that the admin that tried to install the asp handler has limited internet connectivity for security reasons. The installer failed to download  required redist  package  from internet

**Comment by joeloff** [comment]
I see. We have several nested levels of installers. The ServerHosting EXE contains the embedded .NET Core Runtime EXE and ANCM. However, the .NET Core runtime EXE doesn't embed the VC redists and will always go on line for that.

**Comment by csmith93** [comment]
@joeloff: Does that mean there's no way to install it without having an internet connection? If so, are there any plans to provide windows hosting without this requirement?

I'm trying to evaluate it in a environment that's intranet only.

**Comment by joeloff** [comment]
@csmith93 Let me follow up on this. The only real solution for this would be for the outer bundle (Server Hosting) to carry the VC redist, that way when the .NET Core portion runs it will find that it's already installed.

**Comment by csmith93** [comment]
@joeloff, thanks!

**Comment by Andriy-Kulak** [comment]
I am getting the same error and I already have VS2015 redis installed. This is frustrating because I can't get my app into production as a result which I am trying to do by the end of this week. When I try to "repair" redis, I am unable to finish the process and get the log attached. I also attached the Server Hosting install log for reference. Does anyone have any suggestions on how to rsolve this?
Thanks!

[dd_DotNetCoreWinSvrHosting__20160627172552.txt](https://github.com/aspnet/IISIntegration/files/335871/dd_DotNetCoreWinSvrHosting__20160627172552.txt)
[dd_vcredist_amd64_20160627171605.txt](https://github.com/aspnet/IISIntegration/files/335864/dd_vcredist_amd64_20160627171605.txt)

**Comment by joeloff** [comment]
@Andriy-Kulak Have you tried repairing the VC redists (both x86 and x64)? What's the version for these that show in Add/Remove Programs?

**Comment by Andriy-Kulak** [comment]
@joeloff When I try to repair the redis, the loading stops and I get the log attached in my first post (second one from the top). I have multiple versions of redis (2015, 2013 and 2012). Should I delete all of them and install the latest stable version or can that cause trouble with two other apps that are currently running on this server?

**Comment by joeloff** [comment]
@Andriy-Kulak Just try repairing the 2015 ones first. There's a quirk in the 2015 redists that shipped with Update 3 where they remove a registry key that .NET CLI relies on to detect them. The result is that it thinks it's not installed and then tries to install an older version.

**Comment by Andriy-Kulak** [comment]
@joeloff The repair doesn't work because when I try to install either the redis or the DotNet Core Windows hosting, I am getting the same error (below). I didn't see many ways to fix this issue except to reinstall the entire OS, which I am not going to do. In My Services, Windows Installer is set to "Manual" which is the appropriate type according to this article: [here](http://www.techpayee.com/failed-to-install-msi-package/)

any ideas would be greatly appreciated!

[F5C0:E38C][2016-06-27T17:17:40]e000: Error 0x80070642: Failed to install MSI package.
[F5C0:E38C][2016-06-27T17:17:40]e000: Error 0x80070642: Failed to execute MSI package.
[6678:8DE0][2016-06-27T17:17:40]e000: Error 0x80070642: Failed to configure per-machine MSI package.

**Comment by PeterJakubik** [comment]
Could you look at your %temp% folder and see if there's a log file starting with Microsoft.NET_CORE ?

**Comment by Andriy-Kulak** [comment]
@PeterJakubik I don't see any log files in my published directory nor my C:/Temp folder. Anywhere else I can look?

**Comment by joeloff** [comment]
%temp% should map to AppData\Local\Temp in your user folder.

**Comment by Andriy-Kulak** [comment]
@joeloff @PeterJakubik I don't see any Microsoft.NET_CORE file there.

**Comment by PeterJakubik** [comment]
In C:\Users\<LOGGEDON_USER_NAME>\AppData\Local\Temp should be a file beginning with Microsoft_.NET_Core_1.0.0_RC2_-_Runtime_(x64)....

**Comment by AndrewPlusTen** [comment]
I have the same problem installing the DotNetCore.1.0.0-WindowsHosting.exe as my AWS server does not have internet access and I am told by my server admins that it won't be able to get internet access.

[Microsoft_.NET_Core_1.0.0_-_Runtime_(x64)_20160729105956.log.txt](https://github.com/aspnet/IISIntegration/files/390959/Microsoft_.NET_Core_1.0.0_-_Runtime_.x64._20160729105956.log.txt)

Looking at the error file I see this line:
[0964:0750][2016-07-29T10:59:56]i052: Condition '(VCRedist_KeyExists AND VCRedist_KeyValue >= "v14.0.23506.00")' evaluates to false.

The installer file from the link in the documentation is an older version than it is looking for:
Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026

Where can we download the newer version of this redistributable? Google points me to the same file as the documentation.

**Comment by GuardRex** [comment]
This one? https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by petersonfs** [comment]
I installed the VS 2015 redist x64 from link (http://download.microsoft.com/download/8/c/b/8cb4af84-165e-4b36-978d-e867e07fc707/vc_redist.x64.exe) and I can install the dotnet core windows hosting successfully. 

The correct version is: 14.0.23918

The RC2 works on 2K12 R2 Server

Thank you @joeloff

**Comment by joeloff** [comment]
@petersonfs Glad to hear it worked!

**Comment by Inrego** [comment]
Just chiming in to say that I had installation problems too. After looking at this issue, I manually installed the VS 2015 redist linked here, and then the installation worked.

**Comment by moander** [comment]
Installing redist for Visual Studio 2015 solved the problem for me on Windows Server 2012 R2

http://download.microsoft.com/download/8/c/b/8cb4af84-165e-4b36-978d-e867e07fc707/vc_redist.x64.exe
