### ISSUE TITLE
HttpPlatformHandler/Kestrel: Losing the response when creating an SslStream

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#18]
Following: https://github.com/aspnet/IISIntegration/issues/16

I'm using my [custom mail server code](https://github.com/dotnet/corefx/issues/1006#issuecomment-96300051) (reason: `System.Net.Mail` isn't done yet for .NET Core) with my Contact Us form of this app.

If I run this controller/view, it runs and returns the view up to ...
```
using (var client = new TcpClient(server, port)) { ... }
```
... but if I take that one more step to the `SslStream`, it chokes and actually throws a 404 ... and this is all inside a `try-catch` that should show an exception in the view. Nope ... 404 as soon as it hits that `SslStream` line ... bizarre.
```
using (var client = new TcpClient(server, port))
{
    using (var stream = new SslStream(client.GetStream(), false)) { ... }
}
```

**Comment by Tratcher** [comment]
Your startup referenced over at https://github.com/aspnet/IISIntegration/issues/17#issuecomment-148849686 shows you using `app.UseExceptionHandler("/error");`. If there is an exception then this will try to re-execute with a path /error, but if nothing handles requests on that path you will get a 404. Make sure you have an MVC route for /error.

**Comment by GuardRex** [comment]
Old app: I revamped all of that error handling in later apps. I fixed it ... it was a simple route problem. Thanks for spotting that.

If I just go with the developer exception page on the server, it comes back ...
```
FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
The package is ...
```
"System.Net.Security": "4.0.0-beta-*"
```
... which turns out to be `4.0.0-beta-23409` when loaded. This worked in beta7 (dnxcore50). Should I close and re-open in CoreFx?

**Comment by Tratcher** [comment]
double check your published output to make sure all the packages are there.

**Comment by GuardRex** [comment]
It's there ...

![capture](https://cloud.githubusercontent.com/assets/1622880/10555431/dc436bda-7434-11e5-9228-ba60497b022b.PNG)

**Comment by GuardRex** [comment]
looks right ...

![capture](https://cloud.githubusercontent.com/assets/1622880/10555444/257cc3d2-7435-11e5-91d3-a8519d63a712.PNG)

**Comment by GuardRex** [comment]
Since `System.Net.Security` is a CoreFx package, I'll move this over there.
