### ISSUE TITLE
Invalid Child Element aspnetcore in web.config in RC2 final

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/IISIntegration#181]
I know this is cosmetic ....

![schema issue](https://cloud.githubusercontent.com/assets/16208742/15386796/97d54c18-1da1-11e6-8756-ae70ea2acb17.png)

**Comment by davidfowl** [comment]
This is pretty annoying. It's a tooling issue though.
/cc @BillHiebert @sayedihashimi

**Comment by mikes-gh** [comment]
I did think about posting it there but that repo doesnt get much :heart: .  Do you want me to move it?

**Comment by davidfowl** [comment]
Yap

**Comment by mikes-gh** [comment]
This issue was moved to aspnet/Tooling#501
