### ISSUE TITLE
publish-iis fails on x86 - Could not load type 'System.ConsoleColor'

### ISSUE THREAD

**Issue by Morcatko** [aspnet/IISIntegration#183]
`dotnet publish-iis` fails on x86 with
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.Cli.Utils.Reporter' threw an exception. ---> System.TypeLoadException: Could not load type 'System.ConsoleColor' from assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Extensions.Cli.Utils.Reporter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Cli.Utils.Reporter.get_Error()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
```

I reproduced it on two machines with Windows X x86 (x64 works fine)

STR:
- dotnet new
- edit project.json. Add
```
"tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-*",
      "imports": "net46"
    }
  }
```
- dotnet restore
- dotnet publish-iis

I am using default nuget, so the versions of everything are RC2/Preview1
x64 works fine

**Comment by moozzyk** [comment]
Does it work if you use correct imports as shown [here](https://github.com/aspnet/Announcements/issues/169)? After changing the imports please clear your caches before restoring with `nuget.exe locals -clear all`

**Comment by GuardRex** [comment]
I thought it was `nuget locals all -clear`

**Comment by GuardRex** [comment]
I can see it's going to be one of those days! :smile:

@moozzyk Did you join Slack? I don't see you over there. The reason I mention it on this issue is that I'm working on additional docs for IIS, including info about the `publish-iis` tooling. If you have a few minutes, I hope to get your feedback at some point. It's in the #iis channel.

**Comment by muratg** [comment]
Let us know if you still have issues after fixing the imports!

**Comment by Morcatko** [comment]
Thanks, It works now.
