### ISSUE TITLE
Combination wwwroot/Views and IIS Express doesn't work in RC2 

### ISSUE THREAD

**Issue by Weboholics** [aspnet/IISIntegration#184]
We have a folder in wwwroot named Views, containing static css files and images. The css files are not longer accessible under the folder Views, but other css/javascript under wwwroot are accessible. The problem seems to be related to the fact that this folder is named Views.  
It did work in RC1, but stopped working in RC2.  It works when not using IIS Express.

**Comment by moozzyk** [comment]
Can you post a small repro?

**Comment by muratg** [comment]
@moozzyk Assigning to you for further investigation.

**Comment by moozzyk** [comment]
I created a new web app with VS created a Views folder and put an image there. I referenced the image from the Index.cshtml like this: `    <img src="~/Views/Untitled.png" alt="ASP.NET" class="img-responsive" />` and it worked. 
@Weboholics - you need to provide more details about your scenario, ideally a repro.

**Comment by Weboholics** [comment]
We finally found the cause of the problem. Our Razor "Views" folder had a web.config file containing a BlockViewHandler, removing it solved the issue. The current project has been migrated from a RC1 version.The web.config file was an artifact from an earlier version.
```
<system.webServer>
    <handlers>
      <remove name="BlockViewHandler"/>
      <add name="BlockViewHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.HttpNotFoundHandler" />
    </handlers>
  </system.webServer>
```

**Comment by moozzyk** [comment]
Glad you were able to figure this out!
