### ISSUE TITLE
Sub-App cannot add duplicate collection entry with name 'aspNetCore'(500.19)

### ISSUE THREAD

**Issue by YaoaY** [aspnet/IISIntegration#190]
Windows Server 2012 R2 
IIS 8.5

Website - Default WebApplication Project (ASP.NET Core 1.0 RC2)
      |
      |-  subapp1 - Default WebApplication Project (ASP.NET Core 1.0 RC2)

Website is ok,but the subapp1 get a 500.19 error:

> HTTP Error 500.19 - Internal Server Error

> The requested page cannot be accessed because the related configuration data for the page is invalid.

> Config Error: Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'aspNetCore'

![issue002](https://cloud.githubusercontent.com/assets/8706312/15491054/7f1a2cc8-219f-11e6-88db-6e42315b5522.png)

![issue003](https://cloud.githubusercontent.com/assets/8706312/15491027/437b22f8-219f-11e6-9d38-55244ecb19d9.png)

because of the name 'aspNetCore' is already in use:

![issue001 1](https://cloud.githubusercontent.com/assets/8706312/15491031/504c31ca-219f-11e6-8c31-78b3feff2b26.png)

rename 'aspNetCore':

![issue004](https://cloud.githubusercontent.com/assets/8706312/15491042/62a1b00c-219f-11e6-8399-860357c50e94.png)

**Comment by Tratcher** [comment]
This is normal behavior for IIS modules. There are two parts to the web.config data. The handlers section only needs to be added for the root site. The `aspNetCore` options should be specified per site.
