### ISSUE TITLE
Logs are not created if the log folder does not exist

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#196]
The templates set `stdoutLogFile=".\logs\stdout"` by default, but do not include a logs directory in the project. ANCM will not create log files unless the logs directory already exists. ANCM should create the directory.

**Comment by GuardRex** [comment]
Great idea in the specified case, but it's also related to a side-issue with `dotnet cli` in that if we create a `Logs` folder in the app and include it for publishing in `publishOptions > include`, it will not appear in published output without a dummy file in it. https://github.com/dotnet/cli/issues/1396 cc/ @piotrpMSFT @blackdwarf

The possible problem here is that devs may want to put the logs anywhere [possibly putting logs from all apps in one folder and naming the log files to match their app (e.g., `stdoutLogFile="c:\logs\this_app_name"`)]; so, are you saying that ANCM could create the path anywhere? ... not just to `.\logs` ... but the full path of `.\funky_folder\nutty_folder\goofy_folder` or `f:\put_the_log_here` or `\\server\share\path` or whatever path the dev sticks in there?

Notwithstanding https://github.com/dotnet/cli/issues/1396, this doesn't feel like a "bug" as much as it is an "ID-10T Error." :smile:

**Comment by Tratcher** [comment]
Also fix the path logic so the `.\` isn't required, and so that even any empty path works.
https://github.com/aspnet/IISIntegration/issues/119#issuecomment-226005524

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#30
