### ISSUE TITLE
Appends random bytes to the HTML document

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#199]
_From @koistya on May 31, 2016 13:46_

![image](https://cloud.githubusercontent.com/assets/197134/15686347/83f2d1d0-2778-11e6-9e14-18e1b4dd4f8f.png)

![image](https://cloud.githubusercontent.com/assets/197134/15676398/b18e97f2-274e-11e6-910f-dd37c3ca6659.png)

##### `Startup.cs`

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace server
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app, ILoggerFactory factory)
        {
            factory.AddConsole(LogLevel.Trace);
            app.UseStaticFiles();
            app.UseWelcomePage();
        }

        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
            host.Run();
        }
    }
}
```

##### `web.config`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*"
        modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="dotnet"
      arguments=".\server.dll" stdoutLogEnabled="false"
      stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

##### `project.json`

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002702", "type": "platform" }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "tooling": {
    "defaultNamespace": "server"
  },
  "publishOptions": {
    "include": [
      "web.config"
    ]
  }
}
```

(testing in Azure Web Apps, hitting F5 - sometimes it appends these bytes, sometimes it's not)

_Copied from original issue: aspnet/KestrelHttpServer#895_

**Comment by Tratcher** [comment]
This is caused by BrowserLink. You can comment it out in your Startup.
https://github.com/aspnet/Mvc/issues/4671

**Comment by Tratcher** [comment]
_From @koistya on May 31, 2016 17:3_

Hm, but I don't have BrowserLink anywhere in my code.

**Comment by Tratcher** [comment]
Good point... is there a utf-8 BOM in the static file?

**Comment by Tratcher** [comment]
Or is it the welcome page?

**Comment by Tratcher** [comment]
_From @koistya on May 31, 2016 17:17_

@Tratcher take a look here https://tarkus2.azurewebsites.net (it's a welcome page generated by `app.UseWelcomePage()`). You need to refresh the page several times because it doesn't reproduce in a consitent manner.

**Comment by Tratcher** [comment]
Interesting. That's exactly the same symptom we got from the BrowserLink bug, but you don't have that enabled.

**Comment by Tratcher** [comment]
Do you see this with any other pages, or just with the WelcomePage?

**Comment by Tratcher** [comment]
_From @koistya on May 31, 2016 17:55_

I haven't seen this issue with `app.Run(async (context) => { await context.Response.WriteAsync(...); })`. Haven't tried ASP.NET Web Pages or MVC yet.

**Comment by Tratcher** [comment]
This appears to be caused by the dynamic compression module in IIS Express. Commenting out the `httpCompression` section in the `.vs\config\applicationhost.config` file gets rid of the BOM chars.

@pan-wang can you investigate why this is happening?

**Comment by Tratcher** [comment]
Note this reproduces with the WelcomePageSample: https://github.com/aspnet/Diagnostics/blob/dev/samples/WelcomePageSample/Startup.cs

**Comment by muratg** [comment]
:eyes:

**Comment by shirhatti** [comment]
@jhkimnew Can you look into this?

**Comment by Tratcher** [comment]
At least part of this is caused by the renderer in WelcomePage. https://github.com/aspnet/Common/pull/152. I'll get that fixed and re-test. wac-a-mole...

**Comment by Tratcher** [comment]
I can no longer reproduce this after fixing the issue in the Welcome page. @koistya let us know if you're able to reproduce this with pages other than hose from the Diagnostics components.
