### ISSUE TITLE
Application Shutdown via IApplicationLifetime should be graceful when behind HttpPlatformHandler

### ISSUE THREAD

**Issue by davidfowl** [aspnet/IISIntegration#20]
More details to come...

**Comment by MaximRouiller** [comment]
Any workaround on this? Can we catch and event when a process is being closed?

**Comment by muratg** [comment]
@davidfowl For RC2 ask mode?  Or postpone?

cc @DamianEdwards

**Comment by Tratcher** [comment]
Design: HttpPlatformHandler will define a new opt-in web.config setting "signalShutdown=true" (verify name). When set, it will send a Ctl+C & Ctl+Break to the back-end process and wait for a given timeout for the process to shut itself down. If the timeout expires then the process will be forcefully terminated.

This feature is being developed as part of the app offline deployment scenario.

**Comment by Tratcher** [comment]
Implemented via https://github.com/aspnet/IISIntegration/issues/81, no setting required.

**Comment by moozzyk** [comment]
:clap: for "no setting required"

**Comment by muratg** [comment]
Nice!

@Tratcher I assume you forgot to close. :)

**Comment by muratg** [comment]
Oh perhaps you're waiting for the full verification before closing. :)

**Comment by Tratcher** [comment]
This as been fixed in AspNetCoreModule v0.8: https://github.com/aspnet/IISIntegration/issues/105.
