### ISSUE TITLE
RC2 - 502.3 On IIS Request Log for requests that end with 200 on kestrel log

### ISSUE THREAD

**Issue by itayit** [aspnet/IISIntegration#201]
We have two servers in production environment hosting a website in kestrel behind IIS. 
the sites are running on ASP Core RC2 and see about 100K-200K requests per day.
around 3-5% of the hrrp requests fail according to iis log with 502.3 error.
I enabled kestrel logging (by adding stdoutLogEnabled="true" in web.config for aspnetcore module)
and see that the same requests complete with OK(200) on kestrel.
some of the failing requests fails relatively shortly after ~400ms while some fail after a long period of ~20000ms, on the kestrel logging I see that all the requests are completed within a short time.

I enabled also failed request tracing in IIS and found the following:

<failedRequest url="http:/.../s/Globe Sabre"
               siteId="1"
               appPoolId="..."
               processId="48620"
               verb="GET"
               remoteUserName=""
               userName=""
               tokenUserName="NT AUTHORITY\IUSR"
               authenticationType="anonymous"
               activityId="{8000037B-0003-F600-B63F-84710C7967BB}"
               failureReason="STATUS_CODE"
               statusCode="502.3"
               triggerStatusCode="502.3"
               timeTaken="641"
               xmlns:freb="http://schemas.microsoft.com/win/2006/06/iis/freb"
               >

113. GENERAL_RESPONSE_HEADERS Headers="Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Kestrel
X-Powered-By: ASP.NET
" 05:51:36.163 
114. GENERAL_RESPONSE_ENTITY_BUFFER Buffer="1ba
" 05:51:36.163 
115. GENERAL_RESPONSE_ENTITY_BUFFER Buffer="%1F%8B%08" 05:51:36.163 
116. GENERAL_RESPONSE_ENTITY_BUFFER Buffer="
" 05:51:36.163 
117. GENERAL_FLUSH_RESPONSE_END BytesSent="0", ErrorCode="The parameter is incorrect.
 (0x80070057)" 05:51:36.163 
118. MODULE_SET_RESPONSE_ERROR_STATUS

Warning
 ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="The parameter is incorrect.
 (0x80070057)", ConfigExceptionInfo="" 05:51:36.163 
119. SET_RESPONSE_ERROR_DESCRIPTION

Warning
 ErrorDescription="There was a connection error while trying to route the request." 05:51:36.163 
120. NOTIFY_MODULE_END ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", NotificationStatus="1" 05:51:36.163

**Comment by Tratcher** [comment]
@pan-wang can you investigate?

**Comment by pan-wang** [comment]
My guess is that when ANCM parsing the response from Kestrel, it always assume the first line is the status line and start with empty space. This assumption may not always hold. Could you please share a repro so that I can test it with instrumented assembly?

**Comment by itayit** [comment]
we dont manage to repro on staging env only in production. also  this error is not repeated for a specific set of requests but happen sparsely

**Comment by pan-wang** [comment]
let me add more logs to windows event log for this "The parameter is incorrect. (0x80070057)" error as warning so that we can figure out what happened with the response received from backend.

**Comment by Tratcher** [comment]
1.0 has now been released, please try it and let us know if you are still having issues and if you get additional log data.

**Comment by itayit** [comment]
Thanks Chris.

Guys please put the rc2->rtm upgrade on our dev roadmap for stuc. Once done
lets switch back from nginx to iis as our reverse proxy and see if problem
repeats

On Jun 28, 2016 15:43, "Chris R" <notifications@github.com> wrote:
>
> 1.0 has now been released, please try it and let us know if you are still
having issues and if you get additional log data.

**Comment by shirhatti** [comment]
@itayit Were you able to repro this in 1.0.0?

**Comment by shirhatti** [comment]
Closing. Feel free to re-open if you are able to repro this issue

**Comment by RLaptev** [comment]
I’m experiencing the same issue on ASP.NET Core 1.1 RTM 
This is a production site running on Windows 2008R2 with all the latest patches. There are no failed request in  AspNetCoreModule stdout log. 
For example, I see the following successful entry in the stdout:
`Request finished in 347.108ms 200 text/html; charset=utf-8 `
And a corresponding 502 error response in IIS log:
`2016-12-10 03:47:14 76.12.55.140 GET /xyz - 80 - 73.188.236.249 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/51.0.2704.79+Safari/537.36+Edge/14.14393 502 3 64 343 `

This is a completely random 502.3 response for MVC view, or even static JS/CSS file. Server load is not a factor, this happens even over night when there are almost no users on the site.

IIS failed request tracing showed the following two types of consistent errors:
1. `ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="The parameter is incorrect. (0x80070057)", ConfigExceptionInfo=""`
2. `ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="An operation was attempted on a nonexistent network connection.
 (0x800704cd)", ConfigExceptionInfo=""`

Here is a snippet of the failed request tracing for error 1:

84. GENERAL_RESPONSE_HEADERS: 
Headers="Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Server: Kestrel
X-Powered-By: ASP.NET
85. GENERAL_RESPONSE_ENTITY_BUFFER:
Buffer="1ee5"
86. GENERAL_RESPONSE_ENTITY_BUFFER
	Buffer="<!doctype html>…………………………..html/js content……………
87. GENERAL_RESPONSE_ENTITY_BUFFER
Buffer=""
88. GENERAL_FLUSH_RESPONSE_END
 	BytesSent="0", ErrorCode="The parameter is incorrect.  (0x80070057)"
89. MODULE_SET_RESPONSE_ERROR_STATUS
ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="The parameter is incorrect. (0x80070057)", ConfigExceptionInfo=""
90. SET_RESPONSE_ERROR_DESCRIPTION
	ErrorDescription="There was a connection error while trying to route the request."

Please help!!!!!! This is a productions sever, and user experience is going downhill with this 502.3 random error!

Thank you.

**Comment by pan-wang** [comment]
Could you please take a look at windows event log to see if there's any ANCM event error or process restart?
If possible, could you please provide a simple repro so that we can investigate it in-house?

Thanks

Pan

Sent from my Windows 10 phone

**Comment by RLaptev** [comment]
In windows log I only see info messages like the one below:
`Process '7188' started successfully and is listening on port '13240'.`
It appears every hour as I have IIS recylce memory pool every hour due to the following [issue](http://stackoverflow.com/questions/40791138/aspx-net-core-random-502-error-on-iis-server).

I'm not sure how to setup a simple repro for you. This is in production site. Is there a set of instructions on how this can be achieved without revealing the source code for the site?

**Comment by RLaptev** [comment]
Here is an example of a random 502.3 produced by a static PDF file.
See lines 1463, 1464
[fr000001.pdf](https://github.com/aspnet/IISIntegration/files/644222/fr000001.pdf)

**Comment by pan-wang** [comment]
Is your application hosted on Azure Antares or a server ? Which version (file version) of ANCM was used?

The error started at 1462

    1462. GENERAL_FLUSH_RESPONSE_END
    BytesSent="0", ErrorCode="An operation was attempted on a nonexistent network connection.  (0x800704cd)"
I am not sure why the flush failed. if you fully control the server, is it possible for you to apply private, set a break line at 502 error setting code  and capture a dump?

________________________________

**Comment by RLaptev** [comment]
The site is hosted on our own dedicated server. 
The current version of aspnetcore.dll is 7.1.1967.0, but apparently the latest release is 7.1.1969.0 
Were there any fixes between version 1967 and 1969 that could help us? I will schedule and upgrade overnight.  
If the upgrade doesn't help, can you please steer me in the right direction on how I can produce a dump when 502 is returned? Is there online help for this?

Thank you.

**Comment by RLaptev** [comment]
Upgrade to 7.1.1970.0 didn't help. Still seeing multiple 502.3 errors
Attached is the latest example of the random 502.3 error for a static image.
[fr000011.pdf](https://github.com/aspnet/IISIntegration/files/646615/fr000011.pdf)

**Comment by toblea** [comment]
@RLaptev What do the _request_ headers look like?
I get the same error when the request headers contain a X-Forwareded-For with **a comma**:
`X-Forwarded-For: <proxy_ip>,<local_ip>`

**Comment by antonGritsenko** [comment]
Just small addition, we have application installed on many customers envs (more than 50 I think), but only one of them have a 502.3 issue with same symptoms as above: just error, nothing in event log. So looks like so env-related issue.
