### ISSUE TITLE
IIS custom error pages do not work with ANCM

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#203]
The IIS custom error page feature allows IIS to provide/replace the response body for specific status codes. By default it will do this for 401,403,404,405,406,412,500,501,502.  However, this does not work with ANCM/Kestrel, all configured error pages are bypassed and the original body from the application is returned to the client.

Questions:
- Do we want to support IIS custom error pages with Asp.Net Core? We have a replacement feature in Diagnostics called StatusCodePages. We also have multiple 500 pages.
- If yes, should it be opt-in or opt-out? If it were opt out you would be unable to see any of the Asp.Net diagnostics pages by default.

@DamianEdwards @shirhatti @pan-wang @davidfowl

**Comment by Tratcher** [comment]
Note we see the same behavior in Azure.

**Comment by Tratcher** [comment]
@blowdart

**Comment by GuardRex** [comment]
I vote for making this an opt-in feature. I enjoy keeping as much server-ish work within Kestrel as possible ... even secretly hoping that Kestrel could get the needed features to make it a full-fledged, standalone server for WS one day.

If you made this an opt-out feature, it feels like that would be leaning in the opposite direction. I hope every decision that comes down to choosing default behavior between IIS and Kestrel leans in the Kestrel direction.

**Comment by shirhatti** [comment]
@muratg This was by design. We don't see enough people asking for this to be done.
I'm leaving this issue open to gather feedback, but right we don't plan on changing behavior

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#31
