### ISSUE TITLE
AspNetCoreModule status code when serving app_offline.htm

### ISSUE THREAD

**Issue by dolly22** [aspnet/IISIntegration#204]
Is it possible to configure status code returned by AspNetCoreModule? It returns **200 OK** which has it's issues.

For example when serving static assets through CDN configured with origin pull, app_offline.htm page content may be cached when 200 OK is returned. 

Classic ASP.NET returns **503 Service Unavailable** when serving app_offline.htm requests.

**Comment by Tratcher** [comment]
@pan-wang, this should be changed.

**Comment by naveedahmed1** [comment]
@Tratcher is it possible to add Retry-After header as well when serving app_offline.htm since search engines suggest adding it https://webmasters.googleblog.com/2011/01/how-to-deal-with-planned-site-downtime.html

**Comment by Tratcher** [comment]
@naveedahmed1 that's an interesting idea. Please open a new issue in https://github.com/aspnet/AspNetCoreModule/issues

**Comment by pan-wang** [comment]
where does the value of 'Retry-After" come from?  Host has no clue about it.
