### ISSUE TITLE
Serving App_Offline.htm returns HTTP Status Code 200

### ISSUE THREAD

**Issue by bruno-garcia** [aspnet/IISIntegration#206]
Support to App_Offline.html was added via aspnet/IISIntegration#81
I'm using it with RC2 and it works fine. Files are unlocked and I'm able to redeploy the app.

On .NET 2.0, dropping App_Offline.htm would be served with a status code 404.
That was changed (Fixed?) to 503 on .NET 4.0, but now (on my unmanaged app pool) running AspNetCoreModule, the file is served with a status code 200.

I've tried, without success, defining it on Web.config:

```
<httpErrors errorMode="Custom" existingResponse="Replace">
    <clear />
    <error statusCode="503" path="App_Offline.htm" responseMode="File" />
</httpErrors>

```

Is there a work around? Or perhaps I'm missing something?

**Comment by Tratcher** [comment]
This has already been changed to 503. https://github.com/aspnet/IISIntegration/issues/204. There isn't a workaround available, you'll have to wait for the RTM release.
