### ISSUE TITLE
500 Internal Server Error - Unable to locate a project.json at 'E:\WebASP.NET.Core\'.

### ISSUE THREAD

**Issue by nasheayahu** [aspnet/IISIntegration#208]
Hi,
I already posted a issue on "[Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html)" about getting a "502.3 Bad Gateway" and was instructed to publish my project here.  I had to create another solution because the project was within another solution with multiple projects.

In doing so after publishing it to IIS on a Windows Server R2 2012 to test it again I get this error:

500 Internal Server Error
<a href='https://postimg.org/image/deyea20bn/' target='_blank'><img src='https://s5.postimg.org/deyea20bn/Screenshot_2.png' border='0' alt='postimage'/></a>

[My test project via OneDrive](https://1drv.ms/u/s!AmKVgWrndmwbk_YBOWUWLGpEEKlNLg)

**Comment by Tratcher** [comment]
See https://github.com/aspnet/UserSecrets/issues/62. You can't use UserSecrets in IIS. Your project is set up to only include UserSecrets in Development so you just need to set your environment to Production after publishing (which should be the default). See ASPNETCORE_ENVIRONMENT.

**Comment by nasheayahu** [comment]
Hi, thanks for the reply, this is my development server, one mention putting the in the "content section" which folder is he referring too, the Views?
