### ISSUE TITLE
AspNetCoreModule hangs under heavy load

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/IISIntegration#210]
### Title

AspNetCoreModule hangs under heavy load when I am trying to crawl my website with around 1 000 000 urls.
### Functional impact

Server starts normally, talks to first 6000 or so requests, and then returns 502 on all subsequent requests (even when I stop crawler). DebugDiag doesn't show anything suspicious. There is plenty of available memory (server has 32 Gb, application uses < 2 Gb).

Module: AspNetCoreModule, 
Message: The specified CGI application encountered an error and the server terminated process
Error code:   0x80072efd (ERROR_WINHTTP_OPERATION_CANCELLED I guess?)

IIS says that he got 502, application log is silent (there are no new entries after IIS starts serving 502's). Is it known issue? How can I debug such issue? I can't say if it's my application or AspNetCoreModule as there is no meaningful error message.

**Comment by pan-wang** [comment]
could you please provide a repro so that I can take a look at it?

**Comment by Tratcher** [comment]
This sounds a lot like port exhaustion. A server is only configured for 5000 ports by default, and once they are gone it can take up to two minutes to recycle them. This can be raised to 65534. See https://support.microsoft.com/en-us/kb/196271

**Comment by GuardRex** [comment]
@Tratcher @pan-wang This seems like it would be uncommon ... uncommon enough not to sweat it for the `Publishing to IIS` doc. Is that correct?

If this issue came up several more times though, then perhaps it would be worthy of listing in the Troubleshooting section there.

**Comment by ShadowDancer** [comment]
@GuardRex I think that increasing port number is fairly easy to find. It's mentioned when you google error code (in decimal, there are no docs for hex error code as returned by IIS).

I'm not sure if that was the cause though. Running netstat -a show far less than 5000 ports open. Also when TIME_WAIT connections end I should be able to make new request (in other words, after some time pool should recover) - that was not the case even after few hours.

Don't you think that such failures should be detected either by Kestrel or by AspNetCoreModule and recycle app pool?

**Comment by Tratcher** [comment]
@GuardRex @ShadowDancer This looks like a stress issue and we've got someone looking into it. We'll let you know what we find. No point in adding it to the doc until we understand it.

**Comment by ShadowDancer** [comment]
I may share memory dumps of w3wp and eventually my application.

**Comment by pan-wang** [comment]
@ShadowDancer   please do let me know once you have a dump or a repro step.
You do raise a good question about detecting the health of Kestrel process and under which condition IIS/Asp.NetCore Module should recycle the Kestrel process. Today, IIS does allow user to set apppool  recycle policy based on memory usage or time.

**Comment by ShadowDancer** [comment]
@pan-wang How can I share it with you? There is no private messaging so far. There is sensitive data in that dump.

**Comment by Tratcher** [comment]
@ShadowDancer upload it somewhere non-public (e.g. OneDrive) and e-mail me the link. See https://github.com/tratcher

**Comment by ShadowDancer** [comment]
@Tratcher 
Done. By the way - I made more tests on my side and after removing some HttpClient and task related code application do not hang anymore.

**Comment by Tratcher** [comment]
Interesting, so it may have been a hang in the application, not ANCM.

**Comment by ShadowDancer** [comment]
Or update to RTM...

**Comment by gencebay** [comment]
I have a example repo for similar issue we encountered
[Net Core Small Load](https://github.com/gencebay/NetCoreSmallLoadRepro)
Thanks!

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
