### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway (Error Code   0x80072ee2)

### ISSUE THREAD

**Issue by himadrinath** [aspnet/IISIntegration#211]
In my solution i have 2 projects. one of them is netstandard1.5  class library containing Db Models and DbContext Classes and i named it [project].Core

![project core](https://cloud.githubusercontent.com/assets/12247490/16382340/0bf53778-3c9e-11e6-8c51-4d4caea11a19.png)

in my other Core Web Application i named it [project].Web and added my [Project].Core Reference.

![project web](https://cloud.githubusercontent.com/assets/12247490/16382589/1639cc66-3c9f-11e6-82e6-a82b8fa542ae.png)

I added Db Migration update the databse. Everything works great.

if i don't use this dbcontext the web app works fine. 
But when i tried to get data from my Dbcontext I getting an error

![error](https://cloud.githubusercontent.com/assets/12247490/16382734/b2409e5a-3c9f-11e6-8fd3-ebab9af90fd0.png)

 i visited many github repos try to find any solution but i couldn't. i also renamed my web project to [project].Site but it did't help.

**and the thing is after i getting this error in my browser then if  i refresh the browser few mins later the error this gone and my app works perfectly** . i still don't understand why it happening...

**Comment by moozzyk** [comment]
0x80072EE2 is ERROR_WINHTTP_TIMEOUT. Looks to me that for whatever reason the application take a long time to start and the AspNetCoreModule is timing out trying to start the application. To confirm you can check event log - AspNetCoreModule writes startup errors there. You can also turn on stdOutLogging in your web.config to see what is happening. You may want to take a look at [my post](https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/) where I describe steps to troubleshoot 502.3 errors.

**Comment by himadrinath** [comment]
@moozzyk  thanks you. right now i am going to investigate using your post and i will get back to u with result. thanks again......

and another thing i have to say that when i cutting down my table number in my database its working fine. but when i using all my table in my database only then the problem arriving.

**Comment by moozzyk** [comment]
@himadrinath - once you get more details and you confirm your issue is related to database you may want to file a new issue in the EntityFramework repo.

**Comment by himadrinath** [comment]
@moozzyk i will do that. once i get the reason...

**Comment by himadrinath** [comment]
@moozzyk after installing 1.0.0 (Tools Preview 2) the problem automatically solved. i think may be the problem is EntityFramework related not IISIntegration. before Db migration takes couple of mins and now its take couple of sec. Thanks for u replies. i read your post and its help me to understand asp core startup and how iis and Kestrel working together and process the request. thanks again
