### ISSUE TITLE
RTM Windows Server Hosting bundle?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#212]
Is there a new link that I can embed in the [Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html#install-the-net-core-windows-server-hosting-bundle) doc?

cc/ @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@shirhatti ?

**Comment by GuardRex** [comment]
Is this it?

 https://go.microsoft.com/fwlink/?LinkId=817246

From Q&A @danroth27 at https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/

**Comment by GuardRex** [comment]
That looks correct. I'm putting in the PR now for the link update and the `publish-iis` tool code block update.
