### ISSUE TITLE
publish-iis code block change for RTM?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#213]
@moozzyk 

Do I need to make an RTM update for the `publish-iis` code block in [Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html#application-configuration)? It currently appears as ...
```
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
    "version": "1.0.0-preview1-final",
    "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
  }
},
"scripts": {
  "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
}
```

cc/ @Rick-Anderson

**Comment by moozzyk** [comment]
Yes. The version should be `1.0.0-preview2-final` and the imports should no longer be needed.

**Comment by GuardRex** [comment]
Thanks! I'll get that change in with the update for the hosting bundle link (if there is one).
