### ISSUE TITLE
Problems with 32 bit AppPool on 64 bit HostSystem

### ISSUE THREAD

**Issue by FlorianRainer** [aspnet/IISIntegration#214]
I have installed the DotNetCore.1.0.0-WindowsHosting.exe on my Windows 10 (x64) Workstation.
I have compiled the WebApplication Example (Visual Studio 2015 Update 3) its a "netcoreapp1.0" deployed as release build for Target Runtime "Any".

If i configure a IIS (not iisexpress) ApplicationPool to use x64 it runs without Problems.
if i try to run the AppPool as x86 the page ends up with a 503 error and the AppPool stops.

I think the DotNetCore.1.0.0-WindowsHosting.exe installs only the x64 version of AspNetCoreModule?

Is there any way to run both versions of AspNetCoreModule (x86 and x64) on the same server, and if yes how ?

may only approach is to install both but register 2 IIS Modules one AspNetCoreModuleX86 and one AspNetCoreModuleX64

**Comment by Tratcher** [comment]
What did the event logs say?

**Comment by FlorianRainer** [comment]
The Eventlog has 5 Warnings from "WAS" EventID 5139 then it stopps with an Error EventID 5002.

But i was able to reproduce it with HttpPlatformHandler on a other machine with RC1 there i get a error from httpPlatformHandler.dll

Error on Loading from Modul-DLL  C:\WINDOWS\system32\inetsrv\httpPlatformHandler.dll.
The Data have not correct Information. 7E000000.

Maybe a similar problem already on HttpPlatformHandler?

**Comment by FlorianRainer** [comment]
Maybe related to this issue?
https://github.com/dotnet/cli/issues/3684

**Comment by muratg** [comment]
@pan-wang Does our installer install both 32-bit and 64-bit versions of ANCM? How can @FlorianRainer verify that he has 32-bit version on the disk?

**Comment by FlorianRainer** [comment]
I have tested a bit and i may have a interesting hint for you.
i have added `net46` to `frameworks` and have builded the application, same story, it runs with x64 and app pool stops with x86, then i compiled with `platform` `x86` and same result here, cant start the app pool.

but net46 produces a .exe file and i have started it by doubleclicking it, normaly Kestrel starts on port 5000. but with the x86 exe it shows an exception, maybe this is the reason for the malfunction.

(german locale) 
```
Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.BadImageFormatException: Es wurde versucht, eine Datei mit einem falschen Format zu laden. (Ausnahme von HRESULT: 0x8007000B)
   bei Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   bei Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_size()
   bei Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   bei Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
   bei Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   bei Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   bei Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   bei Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   bei WebAppRtm.Program.Main(String[] args) in C:\Users\florian\Documents\Visual Studio 2015\Projects\WebAppRtm\src\WebAppRtm\Program.cs:Zeile 14.
```

**Comment by moozzyk** [comment]
Looks like it is trying to load 64-bit libuv into 32-bit process.

**Comment by FlorianRainer** [comment]
i checked the project.lock.json `targets` > `.NETFramework,Version=v4.6` > `Libuv/1.9.0` 
shows me 
```
          "runtimes/win7-x86/native/libuv.dll": {
            "assetType": "native",
            "rid": "win7-x86"
          }
```
in `runtimeTargets`

the problem is the `libuv.dll` in my deploy output folder (deploy with vs2015 file system) is not the x32 dll (size 228kb) its the x64 dll 271kb

if i copy the x86 dll from .nuget to my output its working.

but none then less im not able tu run the same publishing output on x86 and x64 because i cant have both `libuv.dll` files in my deploy

**Comment by FlorianRainer** [comment]
Update:
I have tested some combinations of compiled applications and following result:

The `AspNetCoreModule` is not the causing the problem, it works on x86 and x64 BUT it has one feature missing, if the app pool is configured as 32bit it dont cares, it starts the application if compliled for `AnyCpu` on x64 if OS is 64 bit and x86 on 32 bit.

**Results for 64 Bit Windows:**
Compile x64 + AppPool x64 = x64 (ok)
Compile x86 + AppPool x64 = x32 (works, maybe should a error?)
Compile x64 + AppPool x86 = x64 (works, maybe should a error?)
Compile x86 + AppPool x86 = x32 (ok)
Compile AnyCpu + AppPool x64 = x64 (ok)
Compile AnyCpu + AppPool x86 = x64 (works, but should be x86)
Compile AnyCpu 32 Bit pref. + AppPool x64 = x32 (works, but should be x64)
Compile AnyCpu 32 Bit pref. + AppPool x86 = x32 (ok)

i know its maybe a feature, and not related to the problem here, i wrote this for documentation only.

i think this issue can be closed, cause it is not `AspNetCoreModule` related, but the wrong version of `libuv.dll` or the missing possability to have x86 and x64 `libuv.dll` side by side still exists.
i dont know if this is a issue related to `Kestrel` or if this is a problem with how nuget manages native dll. I don't know where i should create this issue, maybe someone who knows better can do this?

**Comment by Tratcher** [comment]
A lot of this comes from kestrel running out of process. The AppPool bitness setting applies to the worker process and AspNetCoreModule, but the sub process AspNetCoreModule launches to run Kestrel can have any bitness it wants.

**Comment by aplocher** [comment]
Having same issue here.  I've loaded VS "15" Preview 3, along with Visual Studio 2015.  My "Enable 32 bit" app pools with .NET 4.6 aren't working and I get the 403 error and it auto-stops my app pool.  Is there a workaround for this?  I haven't used .NET Core yet, but can I uninstall it without affecting the rest of VS "15" and 2015?  My priority is getting up and running with .NET 4.6/32bit app pools - .NET Core is just something to play with when I have time :).

**Comment by aplocher** [comment]
Ok, immediately after my last comment I tried disabling the "Enable 32 bit" option, and it seems to be working fine.  Not sure why I was under the impression we had to run with that turned on.  Maybe something has changed in our app (or IIS/ASP.NET) since I last attempted that...  Crisis averted

**Comment by pan-wang** [comment]
On 64bit Windows OS, you have both 32-bit and 64-bit ANCM binaries installed. Running 32-bit apppool should not be a problem. Some people did see 32bit apppool failure after OS upgrade. This is due to a bug inside IIS/OS upgrade.That is 32-bit ANCM as well as other IIS OOB binaries got removed from wow64 follder after OS upgrade.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by FlorianRainer** [comment]
I have tested some cases, but not all today on Win 10 (IIS 10) with Asp.Net Core 1.1 (Default Web Application Template from VS 2017)

If i Compile it for AnyCpu and set the ApplicationPool to 64 bit it works, if i change the pool to 32 bit the app will not start. i have done some testing back in time https://github.com/aspnet/IISIntegration/issues/214#issuecomment-229756588 for full framework (4.6)

and i think the problem is that ANCM does not load the core application for a specific bit version, the app pool it self (w3wp.exe) is started in the correct bit mode it starts ANCM correct as well, but the `dotnet run` (dotnet.exe) seems to be the 64bit version (OS bit version maybe) of the dotnet exe, even if both are installed.

for me ANCM should be able to sellect the right dotnet.exe for 32bit and 64bit mode, if this feature from iis should work correctly for ANCM / asp.net core
