### ISSUE TITLE
Microsoft.AspNetCore.Server.IISIntegration.Tools does not support .NET 4.6.1

### ISSUE THREAD

**Issue by hikalkan** [aspnet/IISIntegration#216]
I got this error. And as I check, nuget package only supports .NETCoreApp 1.0 https://www.nuget.org/packages/Microsoft.AspNetCore.Server.IISIntegration.Tools

Is that normal?

**Comment by moozzyk** [comment]
You probably reference the tool from the "dependencies" section. This tool should only be referenced from the tools section. Remove the reference to Microsoft.AspNetCore.Server.IISIntegration.Tools from the dependencies section and make sure your tools section looks like this: 

```
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
    "version": "1.0.0-preview2-final"
  }
}
```

**Comment by hikalkan** [comment]
Thank you very much. It fixed the problem.
