### ISSUE TITLE
Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-preview2-final fails on Win10 x64

### ISSUE THREAD

**Issue by azhoshkin** [aspnet/IISIntegration#217]
Steps to reproduce:
 * Open VS
 * Create default Core ASP.Net project
 * When deps was restored run dotnet publish-iis.
Error:
````
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.Cli.Utils.Reporter' threw an exception. ---> System.TypeLoadException: Could not load type 'System.ConsoleColor' from assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Extensions.Cli.Utils.Reporter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Cli.Utils.Reporter.get_Error()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
````

Works with 
````
"tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview3-*"
  },
````
and works with WinServer2008 x64

project.json+project.lock.json https://gist.github.com/azhoshkin/d7e3f3a0cb1b3b9a09f7d8806cc969c4

Any workarounds for preview2?

**Comment by moozzyk** [comment]
Your project.json and project.lock.json seems correct. However when tools are restored they create their own project.lock.json. For preview2 this file should be here: %USERPROFILE%\.nuget\packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-preview2-final\netcoreapp1.0, Can you add it to the gist?
I am a bit surprised that 1.0.0-preview3-* worked - what feeds do you use? Can you clear your nuget cache (`nuget.exe locals -Clear cache`) and restore the project without using any special feeds. I wonder whether they can get in the way.

**Comment by moozzyk** [comment]
Also, do you have global.json? If so, how it looks like?

**Comment by azhoshkin** [comment]
Hi @moozzyk!

project.lock.json for tools added to the gist as tools.project.lock.json

My Nuget.config in AppData:
````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Local DEV source" value="*******" />
  </packageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>
````
Yeah, that's one thing I forgot to touch... Helped removing Nuget.config above, but looks really strange, does not see any wrong sources here (local source is empty folder).

I've closed the issue as it solved, but keep the gist for a couple of days. @moozzyk thank you!

**Comment by azhoshkin** [comment]
In addition to post above. Looks like package was cached from another source and another project that I tested first:
````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2/" />
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources />
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2/" />
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
  </activePackageSource>
</configuration>
````

**Comment by moozzyk** [comment]
That's probably it...
