### ISSUE TITLE
Performance issue when running IIS+Kestrel

### ISSUE THREAD

**Issue by hallatore** [aspnet/IISIntegration#220]
Running ASP.NET Core under IIS results in less than halved performance, and w3wp uses more CPU than the dotnet process by just proxying requests.

Repro: https://github.com/hallatore/aspnetintegration_performance
Tested on Windows 10 IIS and .NET Core 1.0.

1 worker with 1 connection:
Kestrel: 9806 req/s
IIS+Kestrel: 3865 req/s

1 worker with 10 connections:
Kestrel: 38828 req/s
IIS+Kestrel: 17408 req/s

```
// Kestrel
wrk -t1 -c1 http://localhost:5000
Running 10s test @ http://localhost:5000
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   463.31us  623.16us   6.47ms   79.63%
    Req/Sec     9.85k   307.45    10.23k    73.00%
  98072 requests in 10.00s, 36.29MB read
Requests/sec:   9806.82
Transfer/sec:      3.63MB

// IIS+Kestrel
wrk -t1 -c1 http://localhost:5001
Running 10s test @ http://localhost:5001
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   551.70us  670.83us   6.00ms   76.87%
    Req/Sec     3.89k   119.71     4.11k    58.42%
  39045 requests in 10.10s, 15.32MB read
Requests/sec:   3865.94
Transfer/sec:      1.52MB

// Kestrel 10 connections
wrk -t1 -c10 http://localhost:5000
Running 10s test @ http://localhost:5000
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   307.83us    1.03ms  25.00ms   98.62%
    Req/Sec    38.92k     4.13k   42.00k    91.00%
  388325 requests in 10.00s, 143.69MB read
Requests/sec:  38828.61
Transfer/sec:     14.37MB

// IIS+Kestrel 10 connections
wrk -t1 -c10 http://localhost:5001
Running 10s test @ http://localhost:5001
  1 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   549.28us  232.34us   6.00ms   83.99%
    Req/Sec    17.44k     0.96k   18.41k    95.00%
  174089 requests in 10.00s, 68.33MB read
Requests/sec:  17408.03
Transfer/sec:      6.83MB
```

**Comment by Tratcher** [comment]
@SajayAntony

**Comment by Tratcher** [comment]
@DamianEdwards

**Comment by SajayAntony** [comment]
ANCM does add a well known overhead and the plain text or echo scenarios amplifies the affect similar to NGNIX. Do you need IIS in your scenario?

**Comment by DamianEdwards** [comment]
We are aware of the overhead added by the ASP.NET Core Module (ANCM) and have plans to improve this moving forward. As @SajayAntony points out, any type of reverse-proxying will have an overhead. However, as of 1.0 we still recommend that kestrel **not** be directly exposed to the internet due to it not containing mitigations for common types of DOS and other attacks.

**Comment by hallatore** [comment]
It's more of a feature request than a bug @SajayAntony and @DamianEdwards.

I'm testing around with Azure app service and found the overhead for IIS to be rather large. Note that the repro-app is mvc with razor views, a plaintext echo would be cheating.

What are the future plans for IIS+Kestrel performance? Especially if ANCM is going to be the asp.net core driver for Azure app services.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
