### ISSUE TITLE
ASP.NET Core 1.0  on IIS - HTTP Error 502.3 - Bad Gateway 

### ISSUE THREAD

**Issue by radenkozec** [aspnet/IISIntegration#223]
I am running my .NET Core 1.0 app on IIS successfully. When I redirect to some controller I am getting error:
```
HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.
```

No way to get any info.
I have tried to enable logging stdoutLogFile (no error logged).
In Event log nothing useful.

Cannot get any error info and I know it is something long running causing timeout.

**Comment by Tratcher** [comment]
How are you doing the redirect?

**Comment by radenkozec** [comment]
When I click standard login button or register from using standard Identity provider I am getting this error. I suspect it is related to communication with database.

**Comment by radenkozec** [comment]
@Tratcher Managed to resolve issue.
Seen in Eventlog that IIS user don't have permissions to write in logs folder. After assigned permissions seen that database connection string was wrong.

Problem was that I had assign database logger as well that writes error to database.
Somehow it tried to log this error to database and stack in infinitive loop -> stackoverflow exception.
This caused 502.3 Bad Gateway to appear.

After I corrected connection string everything works.
Also one not related question. When I change connection string in appsettings.json do I need manually recycle app pool or not?
Not sure when Kestrel hosted app is recycled?

**Comment by Tratcher** [comment]
Config files are not watched by default, you need to recycle to pick up changes.

**Comment by radenkozec** [comment]
@Tratcher I have noticed that. That is different when you compare it with previous versions of ASP.NET MVC hosted on IIS. Hope you will improve this in some upcoming versions.

**Comment by Tratcher** [comment]
There are ways to do it, it's just not automatic because you now get to choose what kind of config sources to use and where they are. 1. you can have the config file itself reload if changed, but you'd still have to re-read the values from IConfiguration. 2. AspNetCoreModule has a recycleOnFileChange section where you can ask it to watch specific files. See https://docs.asp.net/en/latest/hosting/aspnet-core-module.html#child-elements

**Comment by paulirwin** [comment]
I am getting this with ASP.NET Core 1.1, .NET Framework 4.6.2, and IIS Express. After seeing the tip from @radenkozec about checking the event logs, it had this message: 

```FailedRequestTracing module failed to create directory '\\?\C:\Users\Paul\Documents\IISExpress\TraceLogFiles\Docio\'. No logs will be generated until this condition is corrected. The problem happened at least 18 times in the last 5 minutes. The data is the error.```

The last two subfolders in the path did not exist. Once I created them and granted write permission to Everyone, it immediately resolved itself. This solution is not obvious and should be addressed.

**Comment by Allann** [comment]
Thanks @paulirwin that helped me too.  And totally agree that this should be addressed.

**Comment by Tratcher** [comment]
@shirhatti where should this IIS Express issue be filed? https://github.com/aspnet/IISIntegration/issues/223#issuecomment-324339617
