### ISSUE TITLE
What is the switch for the ANCM-only install

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#224]
@Tratcher 

@shanselman and @DamianEdwards just said on the Standup (7/5) that there is a switch that can be provided when invoking the hosting bundle installer from the command line that will only install the ANCM. Do you know/can you say what the switch is?

**Comment by Tratcher** [comment]
@joeloff @pan-wang ?

**Comment by GuardRex** [comment]
Ah! He just provided the answer in https://github.com/aspnet/Home/issues/1454#issuecomment-230818177 .... `OPT_INSTALL_REDIST=0`

**Comment by joeloff** [comment]
Run the server installer and pass OPT_INSTALL_REDIST=0 to disable installing the .NET redist.
