### ISSUE TITLE
IISExpress: .NET 4.5 and .net core incompatibility

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/IISIntegration#225]
I've found a very strange bug.
I have couple old projects that using .NET 4.5 and IISExpress for debugging. Also I have .net core 1.0 installed on same machine.
The .net core projects works fine.
But when I try to start debugging for old .NET 4.5 using IISExpress the issexpress process crashed, and I got this in event log:

> The Module DLL C:\Program Files (x86)\Microsoft Web Tools\AspNetCoreModule\aspnetcore.dll failed to load.  The data is the error.

I found this conversation on stackoverflow, looks like similar issue.
http://stackoverflow.com/questions/37495024/net-core-rc2-applicationhost-config-incompatible-with-asp-net-net-4-6

Any plans to fix this?

**Comment by Tratcher** [comment]
@BillHiebert @pan-wang ?

**Comment by Tratcher** [comment]
Recommendation: Update the tooling: http://stackoverflow.com/a/38251109/2588374

**Comment by muratg** [comment]
@antonGritsenko Did using the final tooling work?

**Comment by antonGritsenko** [comment]
@muratg yes, latest available. BTW, forgot to mention, The issue occurs only if two projects (4.5 and core) are in same solution.
And I have found the workaround (really crazy): delete $(SolutionDir)\.vs\config\applicationhost.config before switch to debug an another project. In this case VS re-creates it with default for current project settings.

**Comment by Tratcher** [comment]
@BillHiebert sounds like a tooling bug.

**Comment by BillHiebert** [comment]
this should just work with final tooling.

**Comment by antonGritsenko** [comment]
@BillHiebert by "final" you mean future RTM or "latest available" (Preview2)?

**Comment by BillHiebert** [comment]
Preview2

**Comment by antonGritsenko** [comment]
Will play around again, thanks

**Comment by muratg** [comment]
@antonGritsenko If you still have this issue, please file a bug in aspnet/tooling.
