### ISSUE TITLE
Head-check on one app per AppPool

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#232]
Raised on Slack by @wpostma.

This was discussed ages ago, but I can't find the original issue. What is the current guidance on assigning multiple apps to a single AppPool?

I'm asking from the technical perspective ... not best practices. I think everyone is well aware of the best practices implications (e.g., app isolation, security, settings isolation, etc.). Is there any technical reason with ASP.NET Core/ANCM apps that would prevent it from working? Note that @tuespetre has been doing well with it in staging.

**Comment by wpostma** [comment]
A side question on the one app per app pool thing is, if you did have two apps per pool, how could you tell which dotnet process whas for which app?  The "title" in project.json does not end up as the "Description" in the task manager, and dotnet has no equivalent to the java "jps" that can list process IDs with their actual assembly names or assembly descriptions.

It seems it is also almost essential to keep to a single pool for multiple apps if you want to use IIS url rewriting.  Knowing what the limitations are on multiple apps in the same pool, would be useful in the documentation.

**Comment by GuardRex** [comment]
> which dotnet process whas for which app

If there is one AppPool and multiple apps, they would share the same process. You could determine the process id for each AppPool by using `appcmd`. http://www.iis.net/learn/get-started/getting-started-with-iis/getting-started-with-appcmdexe
```
%systemroot%\system32\inetsrv\appcmd list wps
```
Example output:
```
WP "2900" (applicationPool:MyAppPool1)
WP "1361" (applicationPool:MyAppPool2)
WP "2360" (applicationPool:MyAppPool3)
WP "1872" (applicationPool:MyAppPool4)
```

**Comment by GuardRex** [comment]
You could also get it programatically ...
```c#
System.Diagnostics.Process.GetCurrentProcess().Id
```
