### ISSUE TITLE
Move PathBase from Kestrel to Middleware

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#236]
Right now UseIISIntegration takes the ASPNETCORE_APPL_PATH and adds it to the prefix registered with Kestrel so that Kestrel will split the path and path base. @davidfowl doesn't like the path base feature in Kestrel because it does not reject request from other paths.  Assuming the feature gets removed, UseIISIntegration should handle the path logic via middleware instead.

Create a new middleware that's a combination of MapPath and UseWhen that splits path into path and path base like map, but continues the pipeline like UseWhen. It should also undo at the end like MapPath.  This should be an independent middleware (UsePathBase("/base")) because Nginx has the same problem.

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/Hosting/issues/815

**Comment by muratg** [comment]
@davidfowl How much do you care about this?

cc @JunTaoLuo heads-up :)

**Comment by muratg** [comment]
Let's copy the feature to the middleware and keep the one in Kestrel, because removal would be a breaking change in 1.1.  

Let's remove the one in Kestrel in 2.0. @JunTaoLuo, could you file a bug in 2.0.0 milestone in Kestrel?

**Comment by JunTaoLuo** [comment]
Removal of Kestrel feature tracked in https://github.com/aspnet/KestrelHttpServer/issues/1050
