### ISSUE TITLE
RTM iis publish fails

### ISSUE THREAD

**Issue by riegelj** [aspnet/IISIntegration#237]
If I use preview2-final for Microsoft.AspNetCore.Server.IISIntegration.Tools I receive an error on publish
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5)" Error Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0 ...

If I try to load it using Nuget I get an error that it does not support the 4.5.1 framework.

If I drop back to preview1-final I am able to publish code.

**Comment by muratg** [comment]
@JunTaoLuo Could you investigate?

**Comment by muratg** [comment]
@riegelj What's the exact version of .NET Framework and .NET CLI you are using?

(For CLI, you can do `dotnet --version`)

**Comment by riegelj** [comment]
1.0.0-preview2-003121

 

Framework  4.5.1

 

Also note we are using x86  not 64 bit

**Comment by JunTaoLuo** [comment]
@riegelj I am not able to reproduce this locally using our released tooling on a `net451` project. Can you provide a link to your project or a minimum repro? Also, I would try clearing your package and HTTP caches and see if the problem persists.

**Comment by riegelj** [comment]
I have Microsoft .Net Core Tools (Preview 2) 14.1.20624.0 is that the latest?

**Comment by JunTaoLuo** [comment]
Yes

**Comment by riegelj** [comment]
I removed the lock files. NOTE: It says the publish succedes, but if I look in the build output I see the error below and I get a http Error 502.5 - Process error.
 
json file tools section:
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8"
    }
  },

Changing back Microsoft.AspNetCore.Server.IISIntegration.Tools to preview1 works with no errors.

Nuget Package source is set to: https://api.nuget.org/v3/index.json

I created a vanilla solution using the templates and tried to publish it to my server and received the same error. 

Error below:

Configuring the following project for use with IIS: 'C:\Users\JRIEGEL\AppData\Local\Temp\PublishTemp\ScCustSvcOCC.Service72'
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)

**Comment by GuardRex** [comment]
@riegelj See advice at https://github.com/aspnet/IISIntegration/issues/215#issuecomment-231460410

... also, you can drop the `imports` in your tools section. If there is anything else amiss, put up your project as a GH repo for us to see.

**Comment by riegelj** [comment]
A vanilla solution which fails the same way and does not have imports in the tools section was already uploaded. Please se the zip in my previous post.

**Comment by GuardRex** [comment]
I think if you clear your caches out, you might be able to get past that exception: Try a `nuget locals all -clear`.

I can't open the ZIP here due to security restrictions.

**Comment by riegelj** [comment]
How do I run that? From command line nuget says unknown command: 'locals' from package manager console it doesn't work either

**Comment by GuardRex** [comment]
oh, yeah ... you need it. You can get an installer at Nuget.org: https://www.nuget.org/

**Comment by GuardRex** [comment]
If you click just the link for `latest nuget.exe` ... it will give you the latest one directly (the .exe).

**Comment by riegelj** [comment]
Thanks that did the trick works now :)

**Comment by JunTaoLuo** [comment]
Thanks @GuardRex! Just a note that although nuget.exe is convenient, you don't need it to clear your cache. You can just manually delete your package cache, `~\.nuget\packages`, and http-cache, `%LocalAppData%\Nuget\v3-cache`.

**Comment by MarkOsborneMS** [comment]
I hit this problem after upgrading from 1.0.0-rc1-update2 to 1.0.0-preview1-002702. Running `nuget locals all -clear` fixed the problem for me too.
