### ISSUE TITLE
The IIS config may be locked if ASP.NET 4 is not installed

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#24]
The Asp.Net 4.5 installer unlocks IIS’s system.webServer/handlers section. However if you don’t install that component then the section remains locked and you can’t enable HttpPlatformHandler. Should the HttPlatformHandler msi unlock that section?
https://github.com/aspnet/Docs/pull/551/files#diff-62465270a6cd44f684f23a2a1ca872c9R64

**Comment by davidfowl** [comment]
Yes it should

**Comment by rramachand21** [comment]
handlers section is never locked - whats the machine configuration?

**Comment by Tratcher** [comment]
As far as I know it's locked for any default windows install if you do not also install ASP.NET 4. Several people have reported this recently: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by Tratcher** [comment]
Actual error message: "This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false"."

**Comment by Tratcher** [comment]
This as been fixed in AspNetCoreModule v0.8: https://github.com/aspnet/IISIntegration/issues/105.
