### ISSUE TITLE
Use ConditionalFacts to skip tests at runtime

### ISSUE THREAD

**Issue by pranavkm** [aspnet/IISIntegration#241]
Our CI build configurations skip IISIntegration tests for xplat test pass today. This results in the tool (which can run xplat) not getting any test coverage. We should instead use ConditionalFact to skip WIndows only tests.

**Comment by muratg** [comment]
Agreed, the publish tool tests should run across the board while the middleware tests should run only on Windows SKUs.

**Comment by Tratcher** [comment]
Note a few of the negative tests should run x-plat.

**Comment by Tratcher** [comment]
Why was this closed?

**Comment by pranavkm** [comment]
@pakrym said this works xplat today without having to do any work.
