### ISSUE TITLE
UseIISIntegration should delay setting urls

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#242]
Today it's a common mistake for callers to reverse UseIISIntegration and UseUrls, breaking their app in IIS/Express and Azure.

Proposal, rather than having UseIISIntegration set the url [immediately](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L39), set it later when Build is called (e.g. inside the [ConfigureServices ](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L42) callback) or in the [IStartupFilter ](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs#L21) via IServerAddressesFeature.

**Comment by halter73** [comment]
Seems like a good idea. Today, you can check whether UseIISIntegration is activated in Program.Main() by checking whether whether the urls setting was changed after calling it. Technically, changing when we change the urls settings is breaking, but it probably won't affect too many apps.

It would be nice if there was still an easy workaround to figure out if the app is running behind IIS in Program.Main() after this change.

**Comment by Tratcher** [comment]
What would you do in Main if you did detect IIS?

Checking for the environment variables directly may be better. Or we could provide an IsRunningInIIS API.

**Comment by halter73** [comment]
To disable Kestrel connection filters that are replaced by IIS modules perhaps. Admittedly it's probably not common to use a single code base to deploy with and without IIS, so I don't think this would break (m)any people.
