### ISSUE TITLE
Error Publishing to IIS

### ISSUE THREAD

**Issue by d13cd2** [aspnet/IISIntegration#243]
We're having a problem publishing our web app to IIS.
We've even tried just creating a blank NETcore web app and we're still getting the same issue.

When performing a web deployment we are getting the following error:

> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error : An error occurred during publish.
Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined."

Any ideas?

**Comment by muratg** [comment]
What version of ASP.NET Core, VS/WebDeploy, etc?  Are you able to deploy an ASP.NET4 apps without issues?

**Comment by d13cd2** [comment]
ASP.NET core 1.0.0
Web Deploy 3.6
VS 2015

Here's our project.json:
{
  "dependencies": {
    "AspNet.Security.OpenIdConnect.Server": "1.0.0-beta6-final",
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0",
    "Microsoft.AspNetCore.SpaServices": "1.0.0-beta-000007",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.NETCore.Platforms": "1.0.1",
    "PHMG.ProspX.BusinessLogic": "1.0.0-*",
    "PHMG.ProspX.Data": "1.0.0-*",
    "PHMG.ProspX.Security": "1.0.0-*",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls=http://*:5000/"
  },

  "tools": {
     "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

    "scripts": {
        "prepublish": [ "cmd /c SET NODE_ENV=development&& webpack -d --color" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}

Haven't tried and ASP.NET 4 app.  I'll give that a go and report back.

**Comment by GuardRex** [comment]
btw - You can drop the `"commands"` section ... that's gone now.

Your publishing target is a well-formed Uri, correct? I'm thinking along the lines of ...
```
<UseMSDeployServiceURLAsIs>true</UseMSDeployServiceURLAsIs>
```
as seen in https://github.com/aspnet/vsweb-publish/issues/45. Apparently, it chokes on Uri's it can't parse (e.g., perhaps when there is no protocol on the Uri).

**Comment by d13cd2** [comment]
That was it exactly.  Thanks!
