### ISSUE TITLE
Site published to IIS returning 404 for API urls

### ISSUE THREAD

**Issue by twilliamsgsnetx** [aspnet/IISIntegration#244]
My site is serving static content just fine, but when I try to access the API urls, it returns 404 errors. Not sure where to begin looking for this. Having trouble finding the process id so I can do remote debugging and finding the cause. Any thoughts?

**Comment by twilliamsgsnetx** [comment]
So I figured out the issue. My production setup was from RC1, and my site was pointing to wwwroot instead of the root like it required back then(at least for my site).

I pointed it to the root, and now things work. Hope my suffering helps another at some point.

**Comment by GuardRex** [comment]
Cross reference: https://docs.asp.net/en/latest/migration/rc1-to-rtm.html
