### ISSUE TITLE
Can we get documentation on sub-application support in .net core?

### ISSUE THREAD

**Issue by wpostma** [aspnet/IISIntegration#248]
It seems that deploying  sub-applications in IIS, with .net core 1.0 are not documented.

Sub-apps are referenced elsewhere in other issues:
https://github.com/aspnet/IISIntegration/issues/190

There's no full working example and no IIS configuration and example code or docs for it yet.  Or if there is, my google-fu is failing me.

**Comment by wpostma** [comment]
Here's where I think that docs might have existed:
https://docs.asp.net/en/latest/publishing/iis.html

**Comment by GuardRex** [comment]
Good idea for the sample, and I'll put this on my list for the next Publishing to IIS doc update, which is coming soon.

**Comment by muratg** [comment]
This issue was moved to aspnet/Docs#1764
