### ISSUE TITLE
NTLM / Negotiate show up as authentication providers

### ISSUE THREAD

**Issue by Schlurcher** [aspnet/IISIntegration#25]
Don't know if this belongs here or in Templates. 
With the latest rc1 bits NTLM and Negotiate show up as external auth schemes.

![unbenannt](https://cloud.githubusercontent.com/assets/973681/10806492/0e67437a-7dd6-11e5-91c3-aca0b413b1c1.PNG)

I had a look at the source of Templates, but from what I could see nothing related has changed.

In the end I removed them like this:
```
app.UseIISPlatformHandler(options =>
{
    options.AuthenticationDescriptions.Clear();
});
```

Is this the right way to do it?

**Comment by Tratcher** [comment]
That works. There's a separate work item to make it easier to completely disable the windows auth support https://github.com/aspnet/IISIntegration/issues/15
