### ISSUE TITLE
802 Bad Gateway when request takes > 2 minutes

### ISSUE THREAD

**Issue by jugglingthebits** [aspnet/IISIntegration#253]
I am runnning an aspnet core 1.0 app (on .net framework, not dotnet core) behind an IIS 8.5 on Windows Server 2012 R2.

Now, while web app and services work, I have one service that often takes 3-4 minutes until it returns with an 200 OK. I have logging enabled and the framework reports that a 200 OK is sent. However, IIS returns 802 Bad Gateway around 2 minutes after the request was sent.

I assume this is due to a timeout in IIS. How do I change the timeout setting? In IIS, there is an entry "Advanced Settings" -> "Limits" -> "Connection time-out", but changing it doesn't help.

**Comment by Tratcher** [comment]
Set See requestTimeout in the web.config. See:
https://docs.asp.net/en/latest/hosting/aspnet-core-module.html#configuring-the-asp-net-core-module

**Comment by jugglingthebits** [comment]
Thanks for the link! Works perfectly.

Closing this issue.
