### ISSUE TITLE
Enable Windows authentication

### ISSUE THREAD

**Issue by MortenChristiansen** [aspnet/IISIntegration#254]
I have enabled Windows authentication in my website and it works when running in IIS Express. In IIS, however, the `ControllerBase.User` is a `ClaimsPrincipal` instead of a `WindowsPrincipal` which it is in Express.

I have set `"windowsAuthentication": true` and `"anonymousAuthentication": false` in `launchSettings.json` and `forwardWindowsAuthToken="true"` in `web.config`.

This whole issue might reveal a lack of understanding of how IIS handles Windows authentication but I have been unable to find any real documentation on the subject, only various people trying to make it work in different ways.

Is there some configuration I am missing in IIS?

**Comment by Tratcher** [comment]
Launchsettings only apply in visual studio, they are not published as part of your app. For IIS, auth should be configured in the management UI or web.config.

**Comment by MortenChristiansen** [comment]
Ah, the missing part was that I needed to add the Windows Authentication feature to Windows and enable it in IIS.
