### ISSUE TITLE
Msbuildify tools

### ISSUE THREAD

**Issue by muratg** [aspnet/IISIntegration#258]
### Microsoft.AspNetCore.Server.IISIntegration.Tools
  - Expect to run via MSBuild

### TODO
  - Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
  - Use desktop msbuild to start our work until the new msbuild is ready for   consumption

### Notes
  - [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
  - [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by natemcmaster** [comment]
This work is mostly done. @vijayrkn touched up the code from #260. Additional work tracked on aspnet/aspnetpublishtargets.
