### ISSUE TITLE
ASP.NET Core 1.0 app_offline.htm IIS 8.5 hosting with AspNetCoreModule

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#261]
_From @gencebay on September 4, 2016 20:34_

ASP.NET Core 1.0 App on hosting IIS 8.5 with AspNetCoreModule but during **msdeploy** that puts **app_offline.htm** (as I want) to the root path of application then each request getting only plain-text content of the **app_offline.htm** file. It doesn't seem to send Content-Type header to the browser. Its working on the IE but not the others! (webkit based)

_Copied from original issue: aspnet/Hosting#848_

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/IISIntegration/issues/178, which should have been fixed for 1.0

**Comment by Tratcher** [comment]
_From @muratg on September 7, 2016 21:24_

@gencebay Are you using the latest AspNetCoreModule?

**Comment by Tratcher** [comment]
_From @gencebay on September 8, 2016 9:24_

.NET Core and AspNetCoreModule versions:

![netcorestackdetails](https://cloud.githubusercontent.com/assets/879469/18344077/8d5c663e-75be-11e6-93f5-5906dab0c542.PNG)

**Comment by Tratcher** [comment]
_From @gencebay on September 8, 2016 10:0_

When I uninstall .NET Core SDK Preview 2 and just remain .NET Core 1.0.0 Runtime then worked. Its getting right page for http://localhost:8080 but its getting **The service is unavailable** (as plain text) for http://hostname:8080 when app_offline.htm in root path!

**Comment by Tratcher** [comment]
http://localhost:8080 and http://hostname:8080 are different from IIS's perspective. What's your actual binding in IIS? Does http://hostname:8080 work without the app_offline.htm?

**Comment by Tratcher** [comment]
_From @gencebay on September 8, 2016 16:9_

IIS binding is type:http port:8080 yes it is working without the app_offline.htm on http://hostname:8080

**Comment by Tratcher** [comment]
I cannot repro this with IIS 10.

**Comment by Tratcher** [comment]
_From @gencebay on September 8, 2016 21:19_

For your information, my release management steps are:

$(Build.DefinitionName) = Api
`dotnet publish -c Release -f net46 -o %cd%\bin\$(Build.DefinitionName)`

`msdeploy -verb:sync -source:contentPath=%cd%\bin\$(Build.DefinitionName)\ -dest:package=$(buildFullPath)\$(Build.DefinitionName).zip -declareParam:name="IIS WebApplication Name",defaultValue="$(Build.DefinitionName)"`

Package ready to deploy for production environment on UNC path then powershell executes on target machine with WinRM like:

--pseudo code: add the app_offline.htm to the $(Build.DefinitionName) IIS site root path

`msdeploy -verb:sync -source:package=\\servername\repo\releases\$(Build.DefinitionName)\$(Build.DefinitionName).zip -dest:contentPath=$(Build.DefinitionName) -enableRule:AppOffline`

--pseudo code: remove the app_offline.htm to bring back the application online

**Comment by pan-wang** [comment]
Was the app_offline.htm file really uploaded to application targeted folder? What kind of file system was used by the UNC file server?

**Comment by gencebay** [comment]
Yes the app_offline.htm file exactly uploaded to the application folder. Interesting part is that http://localhost:8080 is working with the app_offline.htm (html and page rendering are ok) but http://<dns-or-hostname>:8080 does not work that only getting "service unavailable" as plain text. UNC file server is Windows Server 2012 and default file system used we don't have any customization for it.

**Comment by pan-wang** [comment]
So app_offline feature does work. For http://:8080, I think this is because you did not give the hostname. The webclient/browser may use other default hostname (or empty) than localhost. You can use netmon to capture the network traffic to see which host name  was really used.

**Comment by pan-wang** [comment]
I assume you call http://dns-or-hostname:8080  remotely. Be default, IIS disable error details for remote request. if you want detailed error message flew to remote client, you need to config iis custom error setting.  see this blog https://blogs.msdn.microsoft.com/rakkimk/2007/05/25/iis7-how-to-enable-the-detailed-error-messages-for-the-website-while-browsed-from-for-the-client-browsers/

**Comment by gencebay** [comment]
Thanks! That takes care of that.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
