### ISSUE TITLE
500 error when trying to access sub-application

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/IISIntegration#263]
Hi, I wrote up  a ticket on IIS.Net but after looking there a bit I think this is the more appropriate place.
Would you guys  mind taking a look?  I'm probably missing some config item - a push in the  right direction will be much appreciated.

http://forums.iis.net/t/1233590.aspx?500+error+when+trying+to+access+sub+application

**Comment by Tratcher** [comment]
If you set your ASPNETCORE_ENVIRONMENT to Development you will get a more detailed error page.

**Comment by sam-wheat** [comment]
Thank you Tratcher!!!
