### ISSUE TITLE
.NET Core 1.0.1 Windows Server Hosting Bundle Installation failed -0x80070490 

### ISSUE THREAD

**Issue by NormanMann** [aspnet/IISIntegration#267]
I just tried installing the Microsoft .NET Core 1.0.1 Windows Server Hosting Bundle on two different Windows 2012 Servers. Both attempts failed with Error "Element not found"

[log.txt](https://github.com/aspnet/IISIntegration/files/480669/log.txt)

I downloaded from here: https://go.microsoft.com/fwlink/?LinkID=827547

**Comment by Tratcher** [comment]
@mikeharder does this look like the same corfx installer issue you were seeing?

**Comment by mikeharder** [comment]
@Tratcher, @NormanMann: Yes.  Here's the main issue which includes a workaround:

https://github.com/dotnet/cli/issues/4190
