### ISSUE TITLE
Using Kestrel with IISIntegration in IIS Express buffers, preventing SSE from working

### ISSUE THREAD

**Issue by mythz** [aspnet/IISIntegration#268]
I'm seeing different behavior when running [Kestrel self-hosting](https://github.com/ServiceStackApps/NetCoreApps/blob/master/src/ChatSelfHost/Program.cs) (which doesn't buffer) vs running [Kestrel with IIS Integration](https://github.com/ServiceStackApps/NetCoreApps/blob/master/src/Chat/Program.cs) which seems to buffer 1 write.

When running with `IISIntegration()`, in order to flush what was previously written to the Response OutputStream I have to [write something else to the buffer](https://github.com/ServiceStackApps/NetCoreApps/blob/785badd8857adfa6c307c23739333cb606ce584f/src/Chat/Startup.cs#L70), e.g:

```csharp
httpRes.Body.Write(frame);
httpRes.Body.Flush();
httpRes.Body.Write("\\n"); // Required to flush what was previously written to the OutputStream
```

This isn't required when [self-hosting the same App in Kestrel SelfHost](https://github.com/ServiceStackApps/NetCoreApps/tree/master/src/ChatSelfHost) where `Write()` and `Flush()` behave as expected.

No combination (or multiple calls) of `Flush()`, `FlushAsync()`, `FlushAsync().Wait()` seem to have any effect on flushing what's currently in the buffer - the only thing that seems to flush the existing buffer is to write something else to it.

Is there anyway to disable buffering when using IIS Express? e.g. in order to disable buffering in ASP.NET 4 we have to [disable dynamic compression](https://github.com/ServiceStack/ServiceStack/wiki/Server-Events#response-buffering-delaying-events), is there any config switch to do the same in Kestrel/IISIntegration?

**Comment by Tratcher** [comment]
Disabling dynamic compression via web.config is also relevant to ASP.NET Core, have you tried it?

**Comment by mythz** [comment]
Beautiful, works a treat! 

Had no idea we could still use Web.config in .NET Core, thx 👍

**Comment by Tratcher** [comment]
All the stuff in system.webServer is for IIS, not ASP.NET, so it applies regardless. Only the system.web section was ASP.NET 4 specific.
