### ISSUE TITLE
ASP.Net 1.0 Core app - HTTP Error 502.3 - Bad Gateway in AspNetCoreModule ErrorCode: 0x80072efe

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#269]
_From @gradom on September 21, 2016 17:59_

I'm working on a .Net Core project for 4 months already. If I work in the "Debug" mode the application runs successfully  and publishing functions correctly. I published my project like the guidline on the asp.net core documentary: [https://docs.asp.net/en/latest/publishing/iis.html](url)

After starting the IIS, the application runs approximatily 5 sec. then I get the following error message: 
![image](https://cloud.githubusercontent.com/assets/22346527/18720817/ede33ab8-802d-11e6-99d5-4cf8561a4286.png)

In the event viewer I get a message which says that an error occurred in the KERNELBASE.dll (ErrorCode: 0xe0434352), the corrupt application is the dotnet.exe.
A subsequently event viewer entry says that the proccess started successfully and is listening on a port (Source: IIS AspNetCore Module).

Another problem is, when I'm enabeling the logging (the stdoutLogEnabled="true") in the web.config I get the following warning message: 

> Warning: Could not create stdoutLogFile \?\C:\appname\logs\stdout_3052_2016921155154.log, ErrorCode = -2147024893.

The problem-solving approach I already tried is to set the user permissions from "IIS_IUSRS" to full control.

If you have an idea to solve the problems I would be pleased to hear it!
And please don't condemn my english - it's my first entry. Thx. ;)

_Copied from original issue: aspnet/Hosting#855_

**Comment by pan-wang** [comment]
It seems your app crashed and thus IIS logged 502 to windows event log. After crash, IIS will try to start your app process again for new request. This is why you saw some process start success. 
For Stdout log warning, please make sure the folder 'logs' does exist. IIS won't create the folder for you.  If the folder does not exist, you will see that warning.

**Comment by gradom** [comment]
Thank's for your assisting response. The solution regarding the logging issue helped me a lot. I was able to log the error in the app and so I managed to sort out the problem.

**Comment by GuardRex** [comment]
@gradom I'm reviewing issues for a Publish to IIS doc update, and I'm curious about what the underlying issue was with the app. Did you find out the exact cause of the crash?

**Comment by gradom** [comment]
@GuardRex Yes, I found out the issue. In the Startup.cs I tried to create a default user subsequently, the application tried to build a connection to the database but the connection string was incorrect. Secondly,  I only got a KERNELBASE error in the event log because of the missing stdout-logfile. I fixed the error through to recreating the stdout-file.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by johnstaveley** [comment]
How did you find out the issue? I have the same problem but with nothing useful in either stdout or the event log I have no idea how to debug this?

**Comment by vend2804** [comment]
I am having the same error. the error is not appearing all the time is random but happens when the site loads. it checks for cookies and if no cookie found trying to redirect to another site and it fails 

thanks

**Comment by muratg** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**
 
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

**Comment by pan-wang** [comment]
the error code is WININET_E_CONNECTION_ABORTED. WinHttp (used by ANCM to forward the request) decided to abort the connection or the backend closed the connection.
