### ISSUE TITLE
Forward client certificates

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#27]
If IIS accepts a TLS client certificate then HttpPlatformHandler should forward it on to us. This could be done as a base64 encoded header that is then unpacked by the middleware upon request from the ITlsConnectionFeature.

**Comment by davidfowl** [comment]
For Azure websites - https://azure.microsoft.com/en-us/documentation/articles/app-service-web-configure-tls-mutual-auth/#special-considerations-for-certificate-validation

**Comment by Tratcher** [comment]
Requires a new release of HttpPlatformHandler (v1.3?)

**Comment by Tratcher** [comment]
This as been fixed in AspNetCoreModule v0.8: https://github.com/aspnet/IISIntegration/issues/105.
