### ISSUE TITLE
JQuery in a View page stops working after ASP.NET MVC Core is puplished to IIS

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/IISIntegration#271]
In my ASP.NET MVC Core project, the JQuery in the following view works fine on VS2015 (that uses IIS Express). But when the same app is published to IIS on the **same** developer machine (Windows 10) , it's not working. The JQuery code in the view below removes the $ and comma symbols from the input in `<td>@Html.EditorFor(r => r[i].SaleAmount, new { htmlAttributes = new { @class = "saleAmt" } })</td>` control in the view before the form is submitted to the controller that saves the data to a SQL Server Db. But this functionality is not working  after app is published to IIS. As a result, user input in that control is not saved to the database. I can see the exact same view is there in the published folder (that I'm using as a physical path to application directory in IIS). Accept this issue, the entire app in IIS is working fine:

**UPDATE**: Updated the Jquery in View below. But the issue remains the same.

**Model**:

    public class SaleViewModel
    {
        [DisplayFormat(DataFormatString = "{0:C0}", ApplyFormatInEditMode = true)]
        public float? SaleAmount { get; set; }
        ....
    }

**Controller**:

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateSales(List<SaleViewModel> model, string returnUrl = null)
    {
        ....
    }

**View**:

    @model IList<MyProj.Models.SaleViewModel>
    ....
    <form id="target" asp-controller="DbRelated" asp-action="UpdateSales" asp-route-returnurl="@ViewData[" ReturnUrl"]" method="post"">
        <table class="table">
            <thead>
                ....
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td>@Html.EditorFor(r => r[i].SaleAmount, new { htmlAttributes = new { @class = "saleAmt" } })</td>
                        ....
                    </tr>
                }
            </tbody>
        </table>
        <button type="submit" class="btn btn-default">Save</button>
    </form>

    @section scripts
    {
        <script>
           $("#target").submit(function () {
             var textboxes = $('.saleAmt');
             $.each(textboxes, function(index, item) {
             var text = $(this).val().replace(/[$,]/g, '');
             $(this).val(text);
           });
        });
        </script>
    }

**Comment by Tratcher** [comment]
@NTaylorMullen @rynowak? Maybe he's missing a publish setting in project.json?

**Comment by NTaylorMullen** [comment]
@saf-itpro could you provide a simple repro project?

**Comment by saf-itpro** [comment]
@NTaylorMullen I've added an UPDATE section in my post above. I'm working on creating a simple repo project for you, as well.

**Comment by saf-itpro** [comment]
@Tratcher  I followed [this article](https://weblog.west-wind.com/posts/2016/Jun/06/Publishing-and-Running-ASPNET-Core-Applications-with-IIS) to publish the app to IIS.
**Could you please point out** where and what publish settings in project.json I need to change?

**Comment by saf-itpro** [comment]
@NTaylorMullen Per your request, I've added a simple repo project [here](https://github.com/saf-itpro/DeploymentIssue). You'll need to change connection string in `StartUp.cs` and `appsettings.json` files. The View that has `Jquery` code in question is: `Views\DbRelated\SalesAmount.cshtml`

**Comment by NTaylorMullen** [comment]
@saf-itpro I gave your repro a shot. I was able to publish and run via Kestrel directly (`dotnet DeploymentIssue.dll`) but ran into unrelated issues when trying to boot the application with IIS. I didn't want to setup a DB so tried to use LocalDB with IIS. Wholllle host of other problems to tackle there.

I'd be willing to invest more time if you were to modify your reproduction steps to not include the DB.

**Comment by saf-itpro** [comment]
@NTaylorMullen Thank you for trying. But the issue is related to Db (Jquery removes formatting from user input before input is submitted to Db). How you think I should try without using Db? Or, maybe, you mean create a repo with LocalDb instead, correct?

**Comment by Tratcher** [comment]
Jquery doesn't directly interact with the database, it goes through an MVC controller. It would help if you could stub out the controllers with static data so we don't need the database piece.

**Comment by saf-itpro** [comment]
@Tratcher  and @NTaylorMullen It seems the issue is related to two submit buttons (for different purposes) for the same POST action in my app. When I hit one submit button I'm posting back all of the data in the form and the model expressions are actually bound to the model state with that posted data. In my repo app with one submit button the Jquery issue is working fine. So, I may have to either use two submit actions for two submit buttons or do something else. If problem persists I will create a new issue in a different context. Thank you for your team for trying to help.
