### ISSUE TITLE
IIS 502.5 Error

### ISSUE THREAD

**Issue by rockdalegreen** [aspnet/IISIntegration#273]
I tried to publish my dotnetcore web api appliction to IIS and got IIS502.5 error.

I create my REST api following this doc
https://docs.asp.net/en/latest/tutorials/first-web-api.html

I can run it within Visual Studio then call the REST service successfully. 

I can also run it in command line
dotnet todoapi.dll and call the REST service successfully. 

But when I publish and deploy to the IIS server runs on the same machine (win 7 IIS 7.5)  
followed this doc 
https://docs.asp.net/en/latest/publishing/iis.html

this is the detailed error message I got when I tried to call the REST service
```
Status: 502: Bad Gateway

Response Headers:
Content-Type: text/html
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Wed, 28 Sep 2016 19:23:17 GMT
Content-Length: 1465
```
```
<pre>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">         <html xmlns="http://www.w3.org/1999/xhtml">         <head>         <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />         <title> IIS 502.5 Error </title><style type="text/css"></style></head>         <body> <div id = "content">           <div class = "content-container"><h3> HTTP Error 502.5 - Process Failure </h3></div>            <div class = "content-container">            <fieldset> <h4> Common causes of this issue: </h4>             <ul><li> The application process failed to start </li>              <li> The application process started but then stopped </li>              <li> The application process started but failed to listen on the configured port </li></ul></fieldset>           </div>           <div class = "content-container">             <fieldset><h4> Troubleshooting steps: </h4>              <ul><li> Check the system event log for error messages </li>              <li> Enable logging the application process� stdout messages </li>              <li> Attach a debugger to the application process and inspect </li></ul></fieldset>              <fieldset><h4> For more information visit:              <a href="http://go.microsoft.com/fwlink/?linkid=808681" <cite> http://go.microsoft.com/fwlink/?LinkID=808681 </cite></a></h4>              </fieldset>           </div>        </div></body></html>
</pre>
```
This is the error msg in event log
Failed to start process with commandline '"dotnet" .\TodoApi.dll', ErrorCode = '0x80070002'

I also set outputlog to true the log file is created but there is no content in the log file. the size of the log file is 0K. 

Here is my web.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\TodoApi.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

Here is project.json
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```
this is the program.cs 

I am using VS2015 update 3. I have search on the web and tried different fixes but none of them solved my issue. Am I missing something? Hope somebody can direct me to the right direction. Let me know if you need more info about my settings/configurations. Thanks in advance

**Comment by moozzyk** [comment]
Probably dotnet is not on the %PATH% or you did not restart your server after adding dotnet folder to the system wide %PATH%

**Comment by rockdalegreen** [comment]
Hmm, I checked my system path, dotnet is there. 
![image](https://cloud.githubusercontent.com/assets/22506599/18953454/86b9f40e-861c-11e6-9400-c175123b9260.png)

also I can run dotnet.exe in command line
![image](https://cloud.githubusercontent.com/assets/22506599/18953496/c3fec33a-861c-11e6-87a1-00bcada7b72d.png)

and successfully access the REST API from REST Client 
![image](https://cloud.githubusercontent.com/assets/22506599/18953567/1b4df638-861d-11e6-8b5d-5ae73a3e9432.png)

I will restart my machine and try again.

**Comment by moozzyk** [comment]
I actually think this is this: https://github.com/aspnet/IISIntegration/issues/256 (which is IIS cannot find dotnet.exe and hence 0x8007002 which is FILE_NOT_FOUND)

**Comment by GuardRex** [comment]
@moozzyk It's a similar result if the AppPool user identity can't access it, right? I think that was one of the failure scenarios that had a similar behavior to what @rockdalegreen reports.

**Comment by rockdalegreen** [comment]
I am sorry I could not get back to you guys earlier. After I restart my machine. Everything works fine now.  Thank you for your help.

**Comment by moozzyk** [comment]
@GuardRex - I don't think so. @danroth27 hit permissions issues yesterday and AFAIR the HRESULT was different.

**Comment by GuardRex** [comment]
@moozzyk I'll prob need to revise the troubleshooting advice on that one on my next doc review. My plan is to break it on every common error and confirm the exception messages and the advice.

I was planning to wait a bit more for 1.1 to land so that I can deal with the  MSBuild/csproj changes at the same time that I address the common errors section, unless I hear this is important to do now from @danroth27, @Rick-Anderson, or @spboyer. In that case, I'll block out a day next week to run through the common errors and start breaking stuff. :smile:

Let me know when we need start rucking. :runner: :runner: 🏉 🏃 🏃

**Comment by Rick-Anderson** [comment]
No hurry

**Comment by moozzyk** [comment]
I think common errors are related to runtime while MSBuild is design time + publishing. As a result I don't think the common errors section will be much different from what it looks like now. I also think that it may be easier to review if the two are done separately.

**Comment by GuardRex** [comment]
The advice on some of them involves checking things in the project that might change ... e.g., `buildOptions` and `publish-iis` tooling. There are only a few of them. It will be a little easier on my scheduling if I block out two days and just concentrate on the doc exclusively. I'm a little buried in :heart: Xamarin :heart: code at the moment.
