### ISSUE TITLE
Publish fail with "Could not load file or assembly 'Microsoft.DotNet.ProjectModel"

### ISSUE THREAD

**Issue by rave1502** [aspnet/IISIntegration#277]
In Visual Studio 2015 Update 3, create any "Net Core Web Application (.Net Framework)" project. While publishing it on azure we get the following error:
**_Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified._**

project.lock.json has following entry
```
".NETCoreApp,Version=v1.0": {
      "Microsoft.AspNetCore.Server.IISIntegration.Tools/1.0.0-preview2-final": {
        "type": "package",
        "dependencies": {
          "Microsoft.DotNet.ProjectModel": "1.0.0-rc3-003121",
          "Microsoft.Extensions.CommandLineUtils": "1.0.0",
          "Microsoft.NETCore.App": "1.0.0",
          "System.Diagnostics.Process": "4.1.0"
        },
        "compile": {
          "lib/netcoreapp1.0/dotnet-publish-iis.dll": {}
        },
        "runtime": {
          "lib/netcoreapp1.0/dotnet-publish-iis.dll": {}
        }
      }
    }
```
 Fresh boilerplate project can also display the same behavior.

**Comment by natemcmaster** [comment]
@rave1502 this likely means there was an error restoring your project.json file. What is in your project.json file? Are you using NuGet.config to point to custom sources? Which version of dotnet-cli are you using? (run `dotnet.exe --info`)

Also, try deleting `%USERPROFILE%/.nuget/packages/.tools/Microsoft.AspNetCore.Server.IISIntegration.Tools` and restoring again.

**Comment by rave1502** [comment]
@natemcmaster following dotnet-cli is in use on my system:

```
.NET Command Line Tools (1.0.0-preview2-003121)
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5
```
On my machine there was one old project created with dotnet 2015 update 1 or 2 was working fine, so did a quick file diff, the following line has done the trick:
```
"tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": "portable-net45+win8+dnxcore50"
        }
    },
```
The original project.json has only this entry:

```
"tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
```

I guess `"imports": "portable-net45+win8+dnxcore50"` was missing.

**Comment by natemcmaster** [comment]
You should not need "imports" for preview2. The original project.json entry is the correct syntax for the latest version of the tool. See https://docs.asp.net/en/latest/publishing/iis.html#publish-iis-tool.

**Comment by rave1502** [comment]
@natemcmaster Ok. deleting and restoring package `%USERPROFILE%/.nuget/packages/.tools/Microsoft.AspNetCore.Server.IISIntegration.Tools` helped. I am able to publish profile now.

Thanks for your help.
