### ISSUE TITLE
AppPool recycling or stopping does not perform graceful shutdown

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/IISIntegration#279]
Whenever application pool is stopped or recycled - process is terminated without graceful shutdown. 

I have noticed that graceful shutdown has been introduced for scenarios including app_offline ( #20, #81  ) . However not for simple app pool recycle. This is a problem because scheduled server restart or even simple recycling are preventing graceful shutdown logic.

I am fully aware that web applications should be resilient enough to survive ungraceful shutdown, however I am still conviced that standard app pool lifetime events should be handled gracefully.

**Comment by pan-wang** [comment]
changed the process shutdown logic. It will try the best effort to send ctr-c signal to the backend process before recycling.

**Comment by mkosieradzki** [comment]
WOW, thanks @pan-wang, that's really big for me! I was sure it's more by-design issue! When can we expect the new module version to be available in official channel?
