### ISSUE TITLE
IIS integration issue - 500 error

### ISSUE THREAD

**Issue by tom-cognify** [aspnet/IISIntegration#280]
I have an ASP.NET Core MVC app that works fine on several win 2012 R2 servers. I just added a 3rd server to our farm and it only shows blank screen, returning 500 internal server error.  There are no errors in the windows event log and the stdout logging shows the process starting normally

Hosting environment: Production
Content root path: C:\inetpub\wwwroot\myapp
Now listening on: http://localhost:26258
Application started. Press Ctrl+C to shut down.

I also see the app.exe running in task manager after trying to hit the site

If I start the app directly from the command line, it starts up and runs fine using kestrel on port 5000. So it seems to be just an issue with the IIS integration. I've tried reinstalling the server hosting package several times.

I've reviewed the docs: https://docs.asp.net/en/latest/publishing/iis.html but none of the common errors seam to apply. Not sure where to go from here.

**Comment by Tratcher** [comment]
Have you tried turning on application/disk logging (`stdoutLogEnabled=”true”`, log folder) or the DeveloperExceptionPage (see Diagnostics)?

**Comment by tom-cognify** [comment]
I do have stdoutLogEnabled, it just shows the app starting up normally, I included the log entry above...
I'll have to redeployed a Debug build to use the DeveloperExceptionPage...Is there some specific way to use that? or just deploy and see if I get different behavior with that enabled?

**Comment by Tratcher** [comment]
DeveloperExceptionPage should render a detailed error rather than a blank 500 page

**Comment by tom-cognify** [comment]
I redeployed a debug build, but I'm still seeing in my log that it thinks the Hosting environment is Production, how do I set this?

**Comment by Tratcher** [comment]
DeveloperExceptionPage doesn't directly depend on the environment, are you checking the environment in the Startup (like the template app)?
You have to an environment variable `ASPNETCORE_ENVIRONMENT=Development`. One of the easier places to do this is in the web.config http://stackoverflow.com/a/39903673/2588374

**Comment by tom-cognify** [comment]
yes, I did have it conditionally adding it for development...I just pulled it out so it always adds it in startup. I also set the environment variable to development, but still same behavior. Looking at the response headers on the 500, it does say it is coming from Kestrel...

**Comment by Tratcher** [comment]
Hmm, let's try something different. Is the ConsoleLogger enabled in your app?
https://github.com/aspnet/BasicMiddleware/blob/dev/samples/ResponseCompressionSample/Startup.cs#L71-L74
Then check the log file.

**Comment by tom-cognify** [comment]
I found it...I was calling app.UseSession() before app.UseDeveloperExceptionPage(), I switched the order and then starting getting errors. Data Protection Keys are configured on a file share and the new server did not have access to the share.

its always the little things that get you :)

Thanks so much for your help.
