### ISSUE TITLE
IIS 7.5 + App_Offline.htm rapid rename - app not always reloading

### ISSUE THREAD

**Issue by andersnm** [aspnet/IISIntegration#281]
I have twice seen our app won't come back properly after quickly moving App_Offline.htm in and out of the app root, f.ex when updating a single dll or aborting a deployment. The workaround is simple, but still an annoyance.

This is an ASP.NET Core 1.0 RTM app targeting net451 hosted on Windows 2008 R2/IIS 7.5/ANCM. ANCM was installed with "DotNetCore.1.0.1-WindowsHosting.exe OPT_INSTALL_REDIST=0". Normally the app serves around a request per second with response times in the range of 10-20 sec, mostly waiting for IO.

Steps to reproduce:

1. Have App_Offline-.htm in the IIS application root (with a dash, ie ignored by ANCM)
2. Rename App_Offline-.htm to App_Offline.htm (remove the dash)
3. Suddenly realize you weren't ready to deploy afterall
4. Rename App_Offline.htm to App_Offline-.htm (put the dash back)

Actual result: Server permanently returns 502 error (the type with red title and border around)

Expected result: App

Workaround: Repeat steps 1-4, ie put App_offline.htm back in and rename again, and it runs fine. 

Speculation: Could there be some kind of race condition unloading/reloading the app if the time spent in step 3 is brief, possibly while there is some load on the app?

Apologies for the lack of the full error message returned by IIS - I had to get the app back online asap and forgot to take note in the heat. The Event Viewer shows a few of these around the time it happened, although they seem to appear always, even when our app reloads successfully:

	Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7a5f8
	Faulting module name: ntdll.dll, version: 6.1.7601.23392, time stamp: 0x56eb302d
	Exception code: 0xc000070a
	Fault offset: 0x0009c049
	Faulting process id: 0x1224
	Faulting application start time: 0x01d217c697dbaa52
	Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
	Faulting module path: C:\Windows\SysWOW64\ntdll.dll
	Report Id: c5eb01d8-8f84-11e6-a9a1-0050568563a5

I tried but failed to repro the issue in our mostly identical staging environment on Windows2012/IIS 8, although under practically zero load.

**Comment by Tratcher** [comment]
@pan-wang this may be related to the issue with loading the config for the wrong site.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#33
