### ISSUE TITLE
Installing .NET Core 1.0.1 Windows (Server Hosting) fails with error 0x80070643

### ISSUE THREAD

**Issue by alex-gausman** [aspnet/IISIntegration#287]
Hello,

I'm trying to install .NET Core 1.0.1 Windows Server Hosting on Windows Server 2012 R2, but keeps failing with error code 0x80070643. Tried many things: checked SYSTEM permissions on C:\ProgramData, ran the .NET Repair Tool, installed VC++ Redist. Nothing seems to have worked. Has anyone else encountered this error?

Attaching the log: [log.txt](https://github.com/aspnet/IISIntegration/files/534416/log.txt)

**Comment by alex-gausman** [comment]
Realized the issue was caused because of our shared IIS config.

**Comment by GuardRex** [comment]
@alex-gausman Thanks for reporting this. I made a note of it for possible inclusion in the next update to the Common Errors section of the Publishing to IIS doc.
