### ISSUE TITLE
Question: Passing through caller windows credential?

### ISSUE THREAD

**Issue by rockdalegreen** [aspnet/IISIntegration#288]
Hi, All:
We are creating a dotnetcore REST web api that hosted in IIS. A wpf client will be calling this REST Web API. Also, this REST web API needs to call a couple "traditional" WCF services and ASMX services.  this REST web api needs to know caller's credential and pass that information to the WCF/ASMX services.  But I somehow could not get this working.  Here is a similar question asked https://github.com/aspnet/IISIntegration/issues/75. But it is not clear to me what the solution is? I have made a sample application and here are the settings

On IIS. 
Authentication setting:

![image](https://cloud.githubusercontent.com/assets/22506599/19478554/020ac3f6-9511-11e6-8db9-ea2d3d03c375.png)

Application Pool setting:
![image](https://cloud.githubusercontent.com/assets/22506599/19478677/7d440d0c-9511-11e6-9024-23333b5e0600.png)

Web.config file

![image](https://cloud.githubusercontent.com/assets/22506599/19478802/f0fb201e-9511-11e6-9e11-069001bd5803.png)

and these are the different methods I tried in my controller to get caller's windows credential
1. returns null
      [HttpGet]
       [Route("WhoAmI")]
       public IActionResult GetWhoAmI()
       {
           ClaimsPrincipal currentUser = this.User;
           string userName = currentUser.Identity.Name;
           return Json(userName);
       }
2. Returns IIS App Pool Identity - WhoAmI
       [HttpGet]
       [Route("WhoAmI1")]
       public IActionResult GetWhoAmI1()
       {
           string userName = System.Environment.UserName;
           return Json(userName);
       }
3. Returns null
       [HttpGet]
       [Route("WhoAmI2")]
       public IActionResult GetWhoAmI2()
       {
           string userName = HttpContext.User.Identity.Name;
           return Json(userName);
       }
4. Returns IIS App Pool Identity - IIS APPPOOL\WhoAmI
       [HttpGet]
       [Route("WhoAmI3")]
       public IActionResult GetWhoAmI3()
       {
           var identity = WindowsIdentity.GetCurrent();
           string userName = identity.Name;
           return Json(userName);
       }

to my big surprise, number 1 and 3 returns null - I expected them to return the caller windows credential. Did I miss something here. And this is just the first step - my next step is after I got the windows credential I will try to call the other services with the credential using httpclient (read about that there are some hops need  to jump too). But even the first step I failed miserably. Can you shed some light on this, If needed I can upload my sample project to github. Thanks in advance.  

-Rockdale

**Comment by davidfowl** [comment]
Settings in the system.Web section don't apply to ASP.NET Core. @Tratcher wrote up a summary here:

https://github.com/aspnet/IISIntegration/issues/75#issuecomment-230927600

You also need to set `forwardWindowsAuthToken=true` in web.config.

**Comment by rockdalegreen** [comment]
Ok, It took me sometime but I finally figured out. 
First issue, this.User.Identity and HttpContext.User.Identoty returns null. 
When I switch AspNetCore.Mvc, AspNetCore.Routing from 1.0.1 back to 1.0.0. It is working. Not sure what changes in the new version causes the problem. Here is the dependencies part of the project.json file.

Not working one: 

  "dependencies": {
    **"Microsoft.AspNetCore.Mvc": "1.0.1"**,
**"Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.1"**,
**"Microsoft.AspNetCore.Routing": "1.0.1"**,
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
**"Microsoft.AspNetCore.Server.Kestrel": "1.0.1"**,
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
  },

The working one:

  "dependencies": {
  **"Microsoft.AspNetCore.Mvc.Abstractions": "1.0.0"**,
**"Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0"**,
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
**"Microsoft.AspNetCore.Hosting": "1.0.0"**,
**"Microsoft.AspNetCore.Server.Kestrel": "1.0.0"**,
**"Microsoft.AspNetCore.Mvc": "1.0.0"**,
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
  },


To pass the caller credential to another service. Just like in post https://github.com/aspnet/IISIntegration/issues/75. Using Impersonate in the code. You do not need to enable Asp.Net impersonation on IIS. (It changes the the <Identity impersonate="true"/> setting in the web.config file.)

Help this helps somebody who has the similar issue.  

Thanks

**Comment by davidfowl** [comment]
I'm like 98.6% sure that changing the dependencies from 1.0.1 to 1.0.0 had nothing to do with it.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
