### ISSUE TITLE
Confirm HttpPlatformHandler uses Fast TCP Loopback

### ISSUE THREAD

**Issue by benaadams** [aspnet/IISIntegration#29]
[Fast TCP Loopback](
http://blogs.technet.com/b/wincat/archive/2012/12/05/fast-tcp-loopback-performance-and-low-latency-with-windows-server-2012-tcp-loopback-fast-path.aspx) hopefully will be coming to libuv https://github.com/libuv/libuv/issues/489

**Comment by shirhatti** [comment]
Win HTTP doesn't support fast loopback.

**Comment by benaadams** [comment]
:crying_cat_face:
