### ISSUE TITLE
I can't get the recycleOnFileChange element in web.config to work

### ISSUE THREAD

**Issue by BillDines** [aspnet/IISIntegration#291]
I want IIS to restart my asp.net core app if my appsettings.myEnvironment.json file changes.  I think this should be possible using the recycleOnFileChange element in my web.config file as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
     <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false">
        <recycleOnFileChange>
           <file path="d:\myWebApplicationPath\appsettings.myEnvironment.json"/>
        </recycleOnFileChange>
     </aspNetCore>
  </system.webServer>
</configuration>
```

Unfortunately this doesn't seem to have any effect.  I can't find much in the way of documentation or samples for using recycleOnFileChange.  Should it be working?  If so, what am I doing wrong?

Many thanks

Bill

**Comment by GuardRex** [comment]
@shirhatti has implied that `recycleOnFileChange` is nop in https://github.com/aspnet/Docs/issues/1965

**Comment by shirhatti** [comment]
Yeah. `recycleOnFileChange` currently just no-ops. The element remains a part of the schema to prevent us from breaking existing applications.

**Comment by GuardRex** [comment]
@BillDines `reloadOnChange` won't help?
```
.AddJsonFile("appsettings.json", reloadOnChange: true)
```

**Comment by BillDines** [comment]
Oh well, that explains it!  @GuardRex - I could probably implement what I need with reloadOnChange, its just much harder work.  I am using the Options pattern and I think I'd have to do quite a lot of work to refresh my options objects after reload - something I'd hoped to avoid!

**Comment by BillDines** [comment]
Thanks @GuardRex - I had seen you can use a callback.  I'll see if I can do something in the callback that works nicely with DI and IOptions<T>...

**Comment by muratg** [comment]
It would be nice to update the docs @danroth27

**Comment by danroth27** [comment]
@muratg Could you please open an issue in the aspnet/Docs repo with the details of what you want added to the docs?

**Comment by GuardRex** [comment]
It's in the section at https://github.com/Microsoft/Docs-1/blob/master/aspnet/aspnetcore/fundamentals/configuration.md#using-the-built-in-sources

It only says that ...

> When specifying files as configuration sources, you can optionally specify whether changes to the file should result in the settings being reloaded. This is configured by passing in a true value for the reloadOnChange parameter when calling AddJsonFile or similar file-based extension methods.

**Comment by muratg** [comment]
https://github.com/aspnet/Docs/issues/1990 tracking doc work

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
