### ISSUE TITLE
[Test] Modify tests to consume the newest build of ANCM

### ISSUE THREAD

**Issue by pranavkm** [aspnet/IISIntegration#292]
Related to https://github.com/aspnet/ServerTests/issues/46

Once aspnet/AspNetCoreModule#20 is done, we'll need to modify IISExpress tests to run using the most recent build of ANCM package from the feed.

**Comment by muratg** [comment]
Let's give it a shot in 1.1.0.  If we can't plan and finish the work, we can move it out to 1.2.0.

**Comment by Tratcher** [comment]
Complication: The ANCM repo / nupkg does not support Win7. The real MSIs are built from a private repo with Win7 support.

**Comment by Tratcher** [comment]
Hosting workaround for the Win7 issue: https://github.com/aspnet/Hosting/commit/4064b42a19d1f19f887a3f9b0688e8616889b93a
Prototype: https://github.com/aspnet/IISIntegration/commit/907301bd4a26c306c1b3ac6b68370e129ce0bb02
Waiting for the new package structure: https://github.com/aspnet/AspNetCoreModule/issues/37
