### ISSUE TITLE
1.0.0-preview3-final release notes?

### ISSUE THREAD

**Issue by davenewza** [aspnet/IISIntegration#293]
`1.0.0-preview3-final` of `Microsoft.AspNetCore.Server.IISIntegration.Tools` was pushed to [NuGet ](https://www.nuget.org/packages/Microsoft.AspNetCore.Server.IISIntegration.Tools/)earlier this week. I am unable to find release notes on this. 

Should we be updating our tooling?

**Comment by Tratcher** [comment]
This was part of the 1.1.0-preview1 release: https://github.com/aspnet/IISIntegration/releases/tag/rel/1.1.0-preview1

You only need to update your tools if you are updating your runtime to 1.1.0-preview1.
https://blogs.msdn.microsoft.com/webdev/2016/10/25/announcing-asp-net-core-1-1-preview-1/

**Comment by moozzyk** [comment]
Here are the release notes: https://github.com/aspnet/IISIntegration/releases/tag/rel/1.1.0-preview1. If your target 1.1.0-* I would recommend using preview3 version. Technically, even if your application targets 1.1.0 runtime and you have 1.0.0 runtime installed preview2 version will continue to work using 1.0.0 runtime (while the application will use 1.1.0 runtime) but I think it's best to keep both in sync.

**Comment by GuardRex** [comment]
@moozzyk @Rick-Anderson Currently, we have ...
```
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
},
```
... in the Publish to IIS doc.

Update it there (aspnet/Docs) to `1.0.0-preview3-final`?

Is there any point to updating Microsoft/Docs-1, since that section will either change dramatically or be removed completely for the 1.1 release?

**Comment by Tratcher** [comment]
Is there a branch of the docs for 1.1-pre?

**Comment by GuardRex** [comment]
Not that I'm aware of ... they told me to commit to master of `Microsoft/Docs-1`.

**Comment by GuardRex** [comment]
![capture](https://cloud.githubusercontent.com/assets/1622880/19772399/b87e0e42-9c2b-11e6-9e99-663eb63d5bb1.PNG)

**Comment by moozzyk** [comment]
@GuardRex - I guess it would be nice to be more general and say that it is good practice to make sure that tools target the same runtime as the application. In case of 1.1 runtime preview3 is the version.

**Comment by GuardRex** [comment]
@moozzyk ok ... gotcha.

Do the old docs (aspnet/docs) need the update tho?

My instruction from @Rick-Anderson was to only submit PR's to Microsoft/Docs-1. Since that might not land for customers until 1.1 and that whole section will possibly get major changes later, I'm wondering if this should be held off for now?

**Comment by Tratcher** [comment]
Please wait. We don't want to confuse customers with preview bits in the 1.0 docs.

**Comment by GuardRex** [comment]
I just asked b/c we already have ...
```
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
},
```
... in the current doc. If that's ok, we're all good.

**Comment by Tratcher** [comment]
That's correct for 1.0.0 runtime packages.

**Comment by Rick-Anderson** [comment]
@GuardRex  I hope we have this repo converted to .MD in the next couple of days.
