### ISSUE TITLE
IIS: Wildcard + URL in route results in configuration error

### ISSUE THREAD

**Issue by ala53** [aspnet/IISIntegration#30]
```
[Route("/Important/{*routeInfo}")
public IActionResult DoSomethingImportant(string routeInfo) {
  //...
}
```

If that route is called with `/Important/http://github.com`, it works on Kestrel but errors on IIS (at least through auto-deploy azure).
The error is:
Config Error: Cannot read configuration file
Config File: \\?\D:\home\site\wwwroot\Important\http:\web.config
...claiming the physical path is
Physical Path: D:\home\site\wwwroot\Login\http:\github.com

In short form, ASP.net doesn't hook the URL...and IIS can't find any to match.

**Comment by davidfowl** [comment]
Check your web.config and see if forwardWindowsAuthToken=false is set, if it is, remove it and try deploying again.

**Comment by ala53** [comment]
It is not. The contents of web.config are:
```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

**Comment by davidfowl** [comment]
set stdoutLogEnabled=true and take a look at the logs. Also take a look at the event log.xml and see if there's anything interesting in there.

**Comment by muratg** [comment]
@ala53 Could you provide us a simplified repro code?

**Comment by ala53** [comment]
Hello
As requested: https://github.com/ala53/iis-error-sample
It is hosted here: http://zsb-test-123.azurewebsites.net/

Unfortunately, the initial post is wrong. It isn't a problem with IIS on all systems. It only occurs when using the Visual Studio auto deploy to azure. 

See here: http://zsb-test-123.azurewebsites.net/this-will-work-fine.com and http://zsb-test-123.azurewebsites.net/http://this-will-crash-the-server.com
When hosted locally, it works fine.

**Comment by muratg** [comment]
@Tratcher

**Comment by ala53** [comment]
The entire issue can be reproduced via this:
```
        [HttpGet, Route("/{*routeData}")]
        public string HttpGetRoutedData(string routeData)
        {
            return "Your route data was: " + routeData;
        }
```

**Comment by muratg** [comment]
@BrennanConroy Can you investigate?

**Comment by BrennanConroy** [comment]
This is an Antares issue, I have contacted them to see if they can resolve it.

**Comment by Tratcher** [comment]
Note this also repros with Asp.Net 4 on azure web sites.

**Comment by gemehendrix** [comment]
I'm also getting issue. The character causing the problem appears to be the colon.
