### ISSUE TITLE
Show how to use Azure Web App Log Streaming with ASP.NET Core.

### ISSUE THREAD

**Issue by olegburov** [aspnet/IISIntegration#300]
Hi Guys,

I'm straggling to make the Azure Web App Log Streaming works with ASP.NET Core application. I tried it based on both .NET Framework and .NET Core, with ASP.NET Core 1.0 and 1.1 Preview-1, using `System.Diagnostics.Trace` and `ILogger/ILoggerFactory`. It just doesn't work for me.

At the same time, it works perfectly with old-fashioned ASP.NET 4 using the example @shanselman showed in the Azure Fridays video: https://channel9.msdn.com/Shows/Azure-Friday/Azure-Web-App-Log-Streaming-with-Scott-Hanselman

Could you please show what needs to be done with a clean ASP.NET Core Web Application (.NET Framework / .NET Core) to make it work?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Docs#2146
