### ISSUE TITLE
Issues shutting down site in IIS. An attempt was made to access an exiting process

### ISSUE THREAD

**Issue by mythjuha** [aspnet/IISIntegration#301]
Taking the site down to do a publish causes the site's .exe process to stay hanging in a blocked state. Trying to kill the process with processhacker shows the error 'An attempt was made to access an exiting process'.

This error is discussed in the trouble shooting section of the asp.net core website, how to publish to IIS. But none of 2 reasons shown there are valid for my project

``` 
var host = new WebHostBuilder()
.UseKestrel()
.UseContentRoot(Directory.GetCurrentDirectory())
.UseIISIntegration()
.UseStartup<Startup>()
.Build();
host.Run();
```

**Comment by Tratcher** [comment]
Is this with 1.0 or 1.1 (just released this week)?

**Comment by mythjuha** [comment]
1..0.1. Prepped the update to 1.1 today, will push it to the server tomorow. Really hopes this fixes the issue because it results in long downtimes of the site, often needing a full reboot of the server (and thus affecting other sites as well}.

**Comment by muratg** [comment]
Assigning to @JunTaoLuo for investigation.

**Comment by JunTaoLuo** [comment]
@mythjuha have you tried the latest releases of 1.1 and ANCM? Also, can you elaborate on how your application is hosted and how you are shutting down the app to publish an update?

**Comment by mythjuha** [comment]
@JunTaoLuo I'll get back on the issue on thursday due to lack of time. I've already updated to 1.1, but havent tried any update since. What's ANCM?

The site is hosted on IIS in its own application pool, and targets the full .net framework.

I usually try to publish through visual studio, with the following publish settings:
`    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>False</EnableMSDeployBackup>
    <EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>
    <UsePowerShell>True</UsePowerShell>`

When publishing, the app_offline.htm gets created but then an error is thrown (will get back on the details thursday). Afterwards, trying to copy the files over manually fails because the .exe is in use. Trying to kill the process with task manager just says 'access denied', using process hacker the exception says (trying to access an exiting process'.

I've also tried to take the site and app pool offline through IIS manager but this results in the same issues.

Non 'standard' things about the site:

- It uses Telerik DataAccess instead of Entityframework because the database model library is shared with a WPF client for administration that used Telerik data access.
- NLog with the NLog asp.net core wrapper

These problems didn't exist early on. Not sure but they might have started since the 1.0.1 update. Development was minimal when i upgrade so thats why i might not have noticed the issue immediatly.

**Comment by Tratcher** [comment]
ANCM: AspNetCoreModule

**Comment by mythjuha** [comment]
Ok, the issues still persist with 1.1.

I took a few screenshots the publish error in visual studio, and the task manager and event viewer on the server.

![screenshot_1](https://cloud.githubusercontent.com/assets/3154195/20592327/1f14b4fa-b22d-11e6-98bc-700bd7f3159c.png)
Publish fails after creating the App_Offline.html

![screenshot_2](https://cloud.githubusercontent.com/assets/3154195/20592341/33bdc6d0-b22d-11e6-9d0f-30c1757e19a9.png)
Site should be offline, but processes still there in taskmanager. Impossible to kill.

![screenshot_3](https://cloud.githubusercontent.com/assets/3154195/20592362/48ee57c2-b22d-11e6-9d79-2cb52a264e3f.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/3154195/20592367/4ba56e60-b22d-11e6-9a08-f5898e48c107.png)
Restarting the site fails because the file is locked.

**Comment by mythjuha** [comment]
Not sure if it's related, but:

 In the above screenshots you'll see multiple instances of the file Paulo.Web.exe. But in the description of the process, one still has the .exe while the other hasn't. It's always the process without the .exe in the description that keeps handing.

**Comment by shirhatti** [comment]
@mythjuha What version of ANCM are you using?

**Comment by mythjuha** [comment]
@shirhatti Each time i've upgraded the project to the latest asp.net core, we've also updates the server with the latest available host bundle. So this should be 1.1 as well.

**Comment by shirhatti** [comment]
Try this
`[System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\WINDOWS\System32\inetsrv\aspnetcore.dll").FileVersion`

**Comment by satauros** [comment]
FileVersion = 7.1.1970.0 (same as Product version)

**Comment by pan-wang** [comment]
ANCM sends a ctr-break signal to gracefully shutdown user's process. in this case, the process is in exiting state but never fully terminated per the error message "'An attempt was made to access an exiting process'". This looks wired. Could you please share a repro so that we can debug it in-house?

**Comment by mythjuha** [comment]
@pan-wang : Any way to contact you / send the repo without posting it here?

On a sidenote: publishing from visual studio failed even before attempting to write the files due to an account issue of the wep deploy user. Having fixed this we now get the more logical 'publish failed do to file in use error'. In the event viewer of the server, i also found the following log:

A process serving application pool 'MyAppPool' terminated unexpectedly. The process id was '3628'. The process exit code was '0x0'.

**Comment by shirhatti** [comment]
@mythjuha Can you upload your repo to some file sharing site (Dropbox, OneDrive) and email me the link? I'll share it with the team. My email address is on my GitHub profile.

**Comment by mythjuha** [comment]
Very carefully i'll say the issue 'might' be resolved. Last few updates been without issues. I modified access to the application folder to allow 'everyone' read access (didn't look into detail yet which user might have needed read access that was blocked previously). If i find the time i'll try to get more details.

**Comment by JunTaoLuo** [comment]
@mythjuha @pan-wang are there still issues that need investigation here?

**Comment by mythjuha** [comment]
@JunTaoLuo Depends on how you look at it. My issues were resolved by giving 'everyone' read access to the folder. I still didn't look into which user was trying to read the folder but wasn't allowed.

However, as a developer it might be worth investigating to prevent this issue, as to me it seems pretty severe. There are no errors, no messages, nothing pointing towards the reason why shutting down the application fails, and the only solution is a reboot of the server.

**Comment by JunTaoLuo** [comment]
Without a repro, we are not able to investigate further into this issue so I'll close this issue for now. @mythjuha please reopen this issue if there is a repro you can provide.
