### ISSUE TITLE
Microsoft.AspNetCore.Server.IISIntegration.Tools 1.1.0-preview4-final is not compatible with net462

### ISSUE THREAD

**Issue by skorunka** [aspnet/IISIntegration#302]
Microsoft.AspNetCore.Server.IISIntegration.Tools 1.1.0-preview4-final is not compatible with net462 (.NETFramework,Version=v4.6.2). Package Microsoft.AspNetCore.Server.IISIntegration.Tools 1.1.0-preview4-final supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)

What should version should I include when working with Asp.NET Core 1.1.0 ?

**Comment by Tratcher** [comment]
@natemcmaster ?

**Comment by natemcmaster** [comment]
Can you share a repro? I'm guessing you've listed the package in the wrong section. Tools packages should be installed into the "tools" section of 'project.json', not 'dependencies'. See https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#publish-iis-tool

**Comment by luisgoncalves** [comment]
I had the same problem when running on .NET 4.6.2 after updating all the packages to version 1.1.0 (and the corresponding previews for tools). After removing the `project.lock.json` files and running `dotnet restore` again, I was able to `dotnet publish`. Not sure what cause the incoherence... Hope this helps.

**Comment by skorunka** [comment]
@luisgoncalves : yes, it actually resolved my issue as well
