### ISSUE TITLE
Add environment variables for external information

### ISSUE THREAD

**Issue by Drawaes** [aspnet/IISIntegration#306]
Is it possible to add environment variables to allow the hosted application to understand the external address that IIS is exposing for the hosted application. This information is available from the HttpContext.Request but only once you have a request. An example of how you can do this in a "traditional asp.net" application

```C#
ServerManager serverMgr = new ServerManager();
Site site = serverMgr.Sites["YourSiteName"];
List<string[]> urls = new List<string[]>();
foreach (Binding binding in site.Bindings)
{
    string bindingInfo = binding.BindingInformation;
    string subString = bindingInfo.Substring(2, bindingInfo.Length - 2);
    string[] adrs = subString.Split(':');
    adrs[0] = "localhost:" + adrs[0];
    urls.Add(adrs);
}
```

**Comment by Tratcher** [comment]
This belongs in the new AspNetCoreModule repo.

**Comment by Drawaes** [comment]
Noted
https://github.com/aspnet/AspNetCoreModule/issues/46
