### ISSUE TITLE
IIS url rewrite with custom provider routing to Asp.Net core applications hosted by AspNetCoreModule

### ISSUE THREAD

**Issue by Matasx** [aspnet/IISIntegration#309]
Hi,

I am facing following scenario:
- Business case: routing customer aliases specified in URL to correct application version, e.g.:
   - /customer1/request -> /1.0.0/request
   - /customer2/request -> /1.0.5/request
   - /customer3/request -> /1.0.0/request
- I am hosting multiple **Asp.Net Core** applications **side by side** via AspNetCoreModule on IIS (it uses pool 'No Managed Code')
   - Each application represents the same product on different version
- I need to be able to route requests to specific application based on entry url
- I **cannot expose rewrited url** back to the client (otherwise I could use redirect instead of rewrite, but it is not my case)
- Routing is done via **custom** url rewrite **provider**, because it resolves rules based on settings in database

I cannot make it work, because:
- IIS URL rewrite must run in the same App Pool as the target application
   - That means 'No Managed Code'
- I need to use custom url rewrite provider, but it can only run on pool with managed code

How am I supposed to route requests to multiple Asp.Net Core applications on IIS? 
Is there any way to achieve this?

**Comment by GuardRex** [comment]
I'm not sure about exposing the re-written URL to the client, as I haven't had a chance to play with this yet, but check on URL Rewriting Middleware and see if that would help ...

https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.Rewrite
https://github.com/aspnet/BasicMiddleware/tree/dev/samples/RewriteSample

**Comment by Matasx** [comment]
@GuardRex I thought this was intended for url manipulation inside Asp.Net Core application. 
What I need is ability to route url to different application (other than the one doing url rewriting). Is that really possible just with rewrite middleware?

**Comment by GuardRex** [comment]
Perhaps so in your case. I haven't had a chance to play with it yet. I'm interested in how this prob will be solved. One of the MS devs will come in to help; but I'll be back at my desk within three hours, and I'd like to repro your problem here.

**Comment by GuardRex** [comment]
Thinking along the lines of a sub app approach, where maybe the middleware is receiving the requests at the root app and farming them out to the appropriate sub app. .... just spitball'in   on it.

**Comment by GuardRex** [comment]
Testing shows that the middleware is capable of redirecting to subapps ...

![capture](https://cloud.githubusercontent.com/assets/1622880/20905552/f2fed70c-bb09-11e6-80e4-2e75abdc1240.PNG)

```
var options = new RewriteOptions()
    .AddRedirect(@"customer1/$", @"version1/$1")
    .AddRedirect(@"customer2/$", @"version2/$1")
    .AddRedirect(@"customer3/$", @"version1/$1");

app.UseRewriter(options);
```

... but, of course, that doesn't preserve the Url. The middleware is not capable of rewriting to subapps AFAICT.

**Comment by Tratcher** [comment]
@pan-wang @shirhatti ?

**Comment by shirhatti** [comment]
@Matasx Does editing your ApplicationPool from 'No Managed Code' to load a version of the CLR solve your problem?

**Comment by GuardRex** [comment]
Might be possible to do something like this with the proxy middleware (https://github.com/aspnet/Proxy by @mikaelm12). Could possibly set the host on the fly from the incoming request (i.e., the "customer" in the Url).

**Comment by Matasx** [comment]
@shirhatti no it is not possible (when talking about IIS rewrite) since it specifically requires to any url rewrites (and I am talking about rewrites, no redirects) to happen withing the same application pool (which needs to be 'no managed code' since I am hosting Asp.Net core applications).

@GuardRex thanks for all the suggestions, I am going to review now.

**Comment by Matasx** [comment]
@GuardRex Hi, finally I was able to create working solution using the proxy middleware, although I had to change its implementation a bit for ability to change path as well (not only host part). Nevertheless I am a bit **concerned about performance**. At this point any request must go down folllowing path:
1) Initial request hits IIS
2) AspNetCoreModule translates the request and calls kestrel process (my Asp.Net Core Proxy implementation)
3) The URL is translated to desired application version specific endpoint, request is once again translated and sent to IIS again
4) Again AspNetCoreModule translates the request and calls kestrel process (this time the final specific application)

- then the response is propagated back the same way.

I am wondering whether this is a good thing to do at all, as to process single request there will be 6 switches from/to managed/no managed code, not talking about all the content transfer, headers copy etc.

What is your opinion?

**Comment by pan-wang** [comment]
Is it possible for you to use iis url rewrite module directly https://www.iis.net/downloads/microsoft/url-rewrite?

Sent from my Windows 10 phone

**Comment by GuardRex** [comment]
@pan-wang ... at the same host address? I don't think that's possible is it?

@Matasx The only other thing that jumps to mind would be one of the Layer 7 switches out there, but I'm sure you know, those appliances get really pricey really fast. eBay might be a good source tho.

**Comment by Matasx** [comment]
@GuardRex It would be cheaper for us to create custom IIS module that would handle routing to multiple Asp.Net Core self-hosted apps.

**Comment by GuardRex** [comment]
@Matasx Yeah ... I hear you on that.

I still have these apps setup from that testing I did before. I'll try to use the IIS module and see if it can rewrite to the subapps. I'll ping back the result in a bit.

**Comment by Matasx** [comment]
@GuardRex IIS rewrite module can be used to rewrite tu .Net Core subapps, just make sure you use some custom plugin to do the rewrite (because I need to reach DB for the rules) - and that is the issue as it needs to be "no managed code pool" and therefore you cannot use .Net IIS rewrite custom plugin ... I do not mind much if it could be done in native code instead of .Net IIS Rewrite custom plugin - I just culdn't find any note anywhere stating it is possible and how to do that.

**Comment by GuardRex** [comment]
@Matasx I don't have a custom plugin, but since the ordinary module works ... and if you can't use the [DbProvider built-in](https://www.iis.net/learn/extensions/url-rewrite-module/using-custom-rewrite-providers-with-url-rewrite-module), then I guess you could write a custom module to do it.

Anyway ... the test here was successful. The IIS module can rewrite to a subapp and mask the Url. [Ignore the cheesiness of my rule ... I didn't put much thought into it, as this was just a quick test.] The rule was applied to the `rewrite_root` app, which is a Core app.
 
![capture1](https://cloud.githubusercontent.com/assets/1622880/21459123/4ed34a90-c901-11e6-9c21-daf9e7ed52e1.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/21459125/51ab8bce-c901-11e6-831e-485155f29b54.PNG)

![capture3](https://cloud.githubusercontent.com/assets/1622880/21459248/4959cffc-c902-11e6-89d9-b5d346baa997.PNG)

**Comment by GuardRex** [comment]
I guess my question is ... Why can't the DbProvider work in your setup?

**Comment by Matasx** [comment]
@GuardRex Because DbProvider (or any other, even custom plugin for IIS Rewrite) is **managed code**. If you use IIS rewrite to Core app, you must use "**No** managed code" pool and managed plugin stops working.

**Comment by GuardRex** [comment]
> If you use IIS rewrite to Core app, you must use "No managed code" pool and managed plugin stops working.

Not according to my test ... but it might be simpler than what you need to do. I set the `rewrite_root` app (thus AppPool for all three apps) to managed code. It works either way.

![capture4](https://cloud.githubusercontent.com/assets/1622880/21459580/f791e210-c904-11e6-8a53-98f582679928.PNG)

**Comment by pan-wang** [comment]
It is NOT mandatory to switch IIS application pool to “no managed code”. You can host classic Asp.Net application with the core app inside the same apppool.


Sent from my Windows 10 phone

**Comment by GuardRex** [comment]
Goes back to original ? then: DbProvider. It should :sparkles: just work:tm: :sparkles:

**Comment by Matasx** [comment]
Wow that is strange, I tried to use managed pool for Core app but IIS just ignored the AspNetCore handler then ... I will retry once I get back to the office on Tuesday. Thanks for now. I will let you know.

**Comment by Matasx** [comment]
Ok I have tested it now and it works. Meaning that I have just spent whole week on an issue that does not exists. Yay me. 

**Thanks a lot guys for your time and effort, appreciated!**

**Comment by Matasx** [comment]
I would like to add one final note and that is this does not work with .Net Core Windows hosting 1.0.1, but it works with version 1.1.0 (it will be probably filed somewhere, but I wasn't searching ...)
