### ISSUE TITLE
Need a tip on location for httpTracing traces

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#314]
Researching for https://github.com/aspnet/Docs/issues/2367

Activating `httpTracing` with ...
```xml
<httpTracing>
    <traceUrls>
      <add value="/favicon.ico" />
    </traceUrls>
</httpTracing>
```
I wish they would state the location of the traces explicitly in https://www.iis.net/configreference/system.webserver/httptracing, but the doc doesn't say.

I'm expecting them to be elsewhere than the failed request tracing traces ... I know where those are. I don't see what I'm looking for in the vicinity of `C:\inetpub\logs`.

Anyone know where they go?

**Comment by Tratcher** [comment]
@pan-wang @shirhatti ?

**Comment by muratg** [comment]
@shirhatti could you follow-up?

**Comment by muratg** [comment]
This issue was moved to aspnet/AspNetCoreModule#65
