### ISSUE TITLE
Graceful shutdown does not work on Win7

### ISSUE THREAD

**Issue by pan-wang** [aspnet/IISIntegration#316]
For graceful shutdown, ANCM sends ctrl-C signal to backend Kestrel process. The later should do cleanup  and terminate after receiving the signal. When debugging other issues, I found this graceful shutdown failed on Win7 but worked on Win10, while ANCM did send the ctrl-C  signal successfully.

**Comment by JunTaoLuo** [comment]
Issue has been resolved, an Windows API behaves slightly differently on Win7. Fix will be in ANCM. Thanks @pan-wang for investigating!
