### ISSUE TITLE
Webdeploy parameter file support/tool

### ISSUE THREAD

**Issue by aL3891** [aspnet/IISIntegration#317]
Hello,
I've been working on deploying a asp.net core app to azure via webdeploy (in vsts) recently and I think the tooling could be improved here, in particular with respects to webdeploy and its parameter file syntax.

The [current docs](https://docs.microsoft.com/en-us/aspnet/core/publishing/vsts-continuous-deployment) recommends simply zipping up the publish contents and this works fine if you don't want to use the parameters file support provided by web deploy and the vsts website tasks. however a very nice feature webdeloy is to be able to specify a Setparameters.xml file at release time for different environments. When building with msbuild this file is generated by the publish target, but to my knowledge this is not supported with the dotnet cli.

## Proposal: Add a new tool to Microsoft.AspNetCore.Server.IISIntegration.Tools that generates a SetParameter.xml file

In addition to doing this I think it would be nice to have tools for actually managing web deploy parameters, but that is kind of an aside.

I went looking for the code for publish-iis and I did found it in the master branch in this repo, but not in the dev branch, has it moved somewhere else? (also, do you think this is a worth while idea at all?)

I know webdeploy isn't very cutting edge but it is a very useful tool especially combined with the vsts tooling.

**Comment by moozzyk** [comment]
/cc @vijayrkn 
I think a better repo to report this is https://github.com/aspnet/websdk. This is also a new home for the publish-iis tool which was converted to an MSBuild task (https://github.com/aspnet/websdk/tree/dev/src/Publish/Microsoft.NETCore.Sdk.Publish.Tasks)

**Comment by vijayrkn** [comment]
We have added support for adding parameters file for web deploy publish. https://github.com/aspnet/websdk/blob/dev/src/Publish/Microsoft.NET.Sdk.Publish.Targets/netstandard1.0/PublishTargets/Microsoft.NET.Sdk.Publish.MSDeploy.targets#L237 

The next VS 2017 release should have this.

**Comment by aL3891** [comment]
aha nice to see it coming! also I didn't know they opened up the websdk repo, that's great!
