### ISSUE TITLE
Can web.config be simpler for docs samples?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/IISIntegration#318]
I was thinking about using the IISIntegration repo sample `web.config` for docs samples. Since docs samples will set the project SDK to `Sdk.Web` and `Sdk.Web` can add `processPath` and `arguments` with appropriate values, it would simplify `web.config` quite a bit to go with ...

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <!-- Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380 -->

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore stdoutLogEnabled="false" stdoutLogFile=".\logs\aspnetcore-stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```
Would that be acceptable for docs samples with `Sdk.Web`?

**Comment by Tratcher** [comment]
The samples should use what's generated by the default templates where appropriate. Note there's a tooling work item to not require a web.config by default, it would only be added as part of publish.
