### ISSUE TITLE
Unable to load DLL 'sni.dll' fix means you cannot start remote debugger

### ISSUE THREAD

**Issue by ImageQC** [aspnet/IISIntegration#319]
[#264](https://github.com/aspnet/IISIntegration/issues/264) proposes a solution to the problem of IIS not loading sni.dll by adding type: platform to the Microsoft.NETCore.App dependency in project.json. 

    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },

I understand this enforces resolution of the dependency on the deployed platform rather than just during build-time so ensuring sni.dll is deployed to IIS. Unfortunately on Azure this has the side-effect of stopping remote debugging as it seems a 32-bit sni.dll is deployed rather than 64-bit. When starting remote debugging from Visual Studio I get the message "64 bit version  of Visual Studio Remote Debugger (MSVSMON.EXE) cannot be used to debug 32-bit processes".

How can this problem be resolved?

Will

**Comment by moozzyk** [comment]
Adding `"type": "platform"` means that you no longer publish the runtime with your application but use the runtime installed on the target machine. Windows Azure App Service is running 32-bit machines so it could not load 64-bit sni.dll to the process. When you started publishing without the runtime it started using the 32-bit runtime installed on the target machine. I guess you need to start 32-bit debugger on your local machine to be able to remotely debug an Asp.NET Core app on Azure.

**Comment by ImageQC** [comment]
Thanks for the clarification about type:platform - I'm a bit new to all this. I've done some further investigation using the Kudu debugger (activate by clicking my website URL from Azure Portal and then altering the URL in the browser by adding .SCM before azurewebsites.net). The application settings for my WebApp on Azure include platform 64 bit.

- When I deploy with Microsoft.NetCore.App type : platform the debugger's process explorer lists dotnet.exe and examination of its environment vars shows PROCESSOR_IDENTIFIER=Intel64 and PROCESSOR_ARCHITECTURE=x86. This is why I can't attach the 64 bit remote debugger.
- When I deploy without type: platform the debugger's process explorer lists myWebsite.exe (as built and deployed by me) and its environment vars shows PROCESSOR_IDENTIFIER=Intel64 and PROCESSOR_ARCHITECTURE=AMD64. 

Therefore adding type : platform means I'm using the runtime installed on the target machine which is 32-bit (x86) rather than the 64-bit suggested by the Azure setting. I presume this is because sni.dll is a 32 bit DLL which can't run on a 64-bit processor so Azure switches to a 32 bit environment. 

**QUESTION: When will Microsoft release a 64bit version of sni.dll so that people can deploy websites using SQL Server that can run in a 64 bit environment?**

(Agreed, most WebApp run better in 32 bit, but that not the point)

**Comment by ImageQC** [comment]
**ANSWER to my original post:**

In order to run the remote debugger you just need to **change the Azure architecture platform setting to 32 bit** (find in Azure Portal, WebApp, Application Settings). I'm not sure why this should matter, but it does.

Other settings in the Azure Portal are remote debugging on and (in my case) Visual Studio 2015. I built and deployed with Debug - Any CPU configuration. I hope this helps others.
