### ISSUE TITLE
Install  .NET Core Windows Server Hosting bundle on Windows Server Core

### ISSUE THREAD

**Issue by techgeek03** [aspnet/IISIntegration#327]
Hello, 
I'm trying to install .NET Core Windows Server Hosting bundle on docker using the official microsoft/iis:windowsservercore. Here is my docker file 

`FROM microsoft/iis:windowsservercore

RUN mkdir C:\build
COPY DotNetCore.1.1.0-WindowsHosting.exe /build

RUN dism /online /enable-feature /all /featurename:IIS-WindowsAuthentication /featurename:IIS-HttpCompressionDynamic

RUN msiexec /package C:\build\DotNetCore.1.1.0-WindowsHosting.exe /quiet

RUN setx /M PATH "%PATH%;%ProgramFiles%\dotnet"

RUN net stop was /y
RUN net start w3svc`

Running RUN msiexec /package C:\build\DotNetCore.1.1.0-WindowsHosting.exe /quiet fails with "T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     C o n t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   th i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g e ." 

Is hosting bundle supported on windows Server Core?

**Comment by Tratcher** [comment]
@shirhatti

**Comment by shirhatti** [comment]
I'm trying to repro this now.

**Comment by milenvk** [comment]
It works if instead of RUN msiexec /package... you directly execute as in:
**RUN C:\build\DotNetCore.1.1.0-WindowsHosting.exe /quiet /install**

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
