### ISSUE TITLE
Invalid runtimeconfig.json error and error 502.5

### ISSUE THREAD

**Issue by zemien** [aspnet/IISIntegration#332]
This is on my development environment:
Server: Windows Server 2016 Standard
dotnet --version is 1.0.0-preview2-1-003177
ANCM installed

I first got this error with my projects (one API and one webapp) that are on Microsoft.NETCore.App 1.1.0. I then reproduced this error easily with the default VS2015 webapp template, which uses Microsoft.NETCore.App 1.0.1.

I've confirmed running Kestrel manually with the dotnet command spins it up on port 5000 just fine.

After setting everything up on IIS according to the current docs, I get a 502.5 Process Failure. I enabled stdoutLogEnabled and this is the error:

> Invalid runtimeconfig.json [C:\Users\AdminSL\Desktop\TestSite\WebApplication1.runtimeconfig.json] [C:\Users\AdminSL\Desktop\TestSite\WebApplication1.runtimeconfig.dev.json]

This is the guilty runtimeconfig.json:
```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.1"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

What is causing the error? Thank you.

**Comment by muratg** [comment]
@zemien 1.0.1 NetCore.App is no longer supported. Could you try 1.0.5 or 1.1.2 instead?   Also, it would be useful to try this with VS2017 templates instead.

**Comment by tkalayci** [comment]
I am having a similar issue. I have published a NetCore console app to an Ubuntu host. However I am getting an "invalid runtimeconfig.json" error when I try to run the application

runtimeconfig.json file content is:

{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2"
    }
  }
}

and dotnet --info  is:

NET Command Line Tools (1.0.4)
Product Information:
Version:            1.0.4
Commit SHA-1 hash:  af1e6684fd
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

Any ideas how to fix this?

**Comment by abhisheksaxena741** [comment]
Same issue is occuring in .net core 2.1.0 version as well.

**Comment by muratg** [comment]
@abhisheksaxena741 Are you able to create a simple app that reproduces the issue and share it on GitHub? That would help us investigate the issue further. Thanks.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
