### ISSUE TITLE
[HttpPlatformHandler] termination of child process causes termination of parent process

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#34]
_From @tuespetre on November 12, 2015 0:43_

Specific example: running the dnx-watch command. When you save changes to a file, dnx-watch terminates its child dnx process and starts a new one, but by the time dnx-watch has recorded that to stdout (which does show in the logs) the HttpPlatformHandler terminates the dnx-watch process and starts a new one.

_Copied from original issue: aspnet/Hosting#477_

**Comment by Tratcher** [comment]
_From @muratg on November 12, 2015 0:55_

@Tratcher Where's the best place to log this?

**Comment by Tratcher** [comment]
@davidfowl What did we settle on for the file monitoring story for HttpPlatformHandler?

**Comment by davidfowl** [comment]
This sound unrelated. What os was this? Does tweaking the timeouts on the platform handler work?

**Comment by tuespetre** [comment]
This is in Windows 10, IIS 10. The startup timeout is something ridiculous like an hour (I think that was set in the web.config by tooling) and the request time limit is the default of two minutes, but I have found that this happens even within two minutes.

I wrote a hokey C++ thing that spins off a process (`CMD /C ECHO something`) and then waits for 30 seconds before writing a message and exiting. The main process did not get terminated when the child process exited, so I'm guessing it has something to do with HttpPlatformHandler detecting that a process stopped listening on the port?

**Comment by tuespetre** [comment]
Here is an example of one of the logs:

```
[DnxWatcher] info: Running dnx with the following arguments: --project ..\project.json web
[DnxWatcher] info: dnx process id: 15884
info    : [Microsoft.Framework.DependencyInjection.DataProtectionServices] User profile is available. Using 'C:\Users\TEMP.IIS APPPOOL\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Now listening on: http://localhost:31713
Application started. Press Ctrl+C to shut down.
[DnxWatcher] info: File changed: C:\path\to\my\project\Startup.cs
[DnxWatcher] info: Running dnx with the following arguments: --project ..\project.json web
[DnxWatcher] info: dnx process id: 5540
```

**Comment by tuespetre** [comment]
For what it's worth, rc1 makes it all the way to the second `Application started` before being terminated:

```
[DnxWatcher] info: Running dnx with the following arguments: --project ..\project.json web
[DnxWatcher] info: dnx process id: 11668
Hosting environment: Production
Now listening on: http://localhost:14242
Application started. Press Ctrl+C to shut down.
[DnxWatcher] info: File changed: C:\Users\grayd\Documents\TFS\CommunityDetail\src\CommunityDetail\Authentication.cs
[DnxWatcher] info: Running dnx with the following arguments: --project ..\project.json web
[DnxWatcher] info: dnx process id: 4528
Hosting environment: Production
Now listening on: http://localhost:14242
Application started. Press Ctrl+C to shut down.
```

I'm chalking that up to the great work of the ASP.NET team on the performance side of things ;)

**Comment by Tratcher** [comment]
https://github.com/tuespetre/dnx-watch-iis/blob/master/README.md

**Comment by pakrym** [comment]
This is expected behavior, development scenario will be fixed by https://github.com/aspnet/dnx-watch/issues/47
