### ISSUE TITLE
PUT and DELETE issue on IIS

### ISSUE THREAD

**Issue by HarelM** [aspnet/IISIntegration#346]
I have the following issue which I don't know how to solve (might be stupid but still...).
I want to publish to a server.
When using .Net Core publish to file system a web.config file is generated (I don't have it before publishing as far as I can tell).
But now I need to be able to add the following lines to it otherwise DELETE and PUT won't work.
```xml
<modules>
  <remove name="WebDAVModule" />
 </modules>
```
But I'm not sure how to achieve this. I don't want to do it manually obviously...

**Comment by JunTaoLuo** [comment]
The `web.config` file is added (or modified if you already have one) to your publish output. You can add the required configuration in your own `web.config` in your project directory. See https://github.com/aspnet/IISIntegration/tree/4334fe19f29827d2a12830e0332164e991328076/samples/IISSample for a sample with a `web.config`

**Comment by HarelM** [comment]
Is there a way to do it in the code? I have moved all the configuration out of web.config to the startup class.
Is this the only way? is it possible to do it with msbuild task? I kinda like how empty and simple the web.config file is. also I have a appsetting.json file as well, keeping two files is confusing...

**Comment by Tratcher** [comment]
No, IIS configuration must remain in web.config.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
