### ISSUE TITLE
Implement an IHostingStartup

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#348]
Implement IHostingStartup and add the HostingStartupAttribute so we can remove UseIISIntegration from default templates. ANCM will set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.Server.IISIntegration and Hosting will load and add IIS.

**Comment by shirhatti** [comment]
Sanity check question. Append to `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` instead of set it?

**Comment by Tratcher** [comment]
Yes, ANCM should append to it.
