### ISSUE TITLE
ASP.NET Core Web API + Kestrel + IIS response time is slow

### ISSUE THREAD

**Issue by qazq** [aspnet/IISIntegration#351]
I publish my Web API application to IIS server 8.5 (running on Windows Server 2012), but the performance is not good. If I run Web API by `dotnet myapi.dll` (pure Kestrel Http Server), the performance is good.

**Client to IIS**
![client-to-iis](https://cloud.githubusercontent.com/assets/997727/24737819/3bb2ab3a-1ac4-11e7-993f-b1e29e8a9a12.PNG)

**Client to Kestrel**
![client-to-kestrel](https://cloud.githubusercontent.com/assets/997727/24738014/57862322-1ac5-11e7-9bbe-b77f875112fc.PNG)

**localhost to IIS**
![localhost-to-iis](https://cloud.githubusercontent.com/assets/997727/24738034/7ddc9c36-1ac5-11e7-97cd-dded5df43e50.PNG)

**localhost to Kestrel**
![localhost-to-kestrel](https://cloud.githubusercontent.com/assets/997727/24738039/88be7da4-1ac5-11e7-9202-4847163fb650.PNG)

Content download time is slow if the web API run on the IIS. If connect from the localhost looks like work normal.

Is it possible to tune the performance? Or this is IIS limitation?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#87
