### ISSUE TITLE
UseIISIntegration should set IServerAddresses.PreferHostingUrls

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#352]
When running behind IIS ANCM should override any Kestrel endpoint configuration by setting PreferHostingUrls
https://github.com/aspnet/IISIntegration/blob/c420addfca0b3ea421cfb2131cae28c4ac556a80/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L54

This can clean up some ugliness from Program.Main:
https://github.com/aspnet/Security/blob/2d7cd6038fea34b84084685648ac9d0c97be610b/samples/SocialSample/Program.cs#L19

See https://github.com/aspnet/Hosting/pull/992
@JunTaoLuo

**Comment by shirhatti** [comment]
Especially given the fact we are injecting UseIISIntegration, this makes me a little uncomfortable. Anything we can do to improve discoverability around this behavior?

**Comment by JunTaoLuo** [comment]
@shirhatti The servers will log if server addresses are used to override the endpoint configurations. We can have UseIISIntegration log that it's setting the PreferHostingUrls flag. Other than that, I can only think of updating docs to make this behaviour more clear.
