### ISSUE TITLE
Anonymous user identity

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/IISIntegration#358]
With IIS we can set identity for application pool account and **for anonymous user**, so access we can use low privilege account for anonymous access. This really helpful to protect apps with anonymous access allowed in local networks (based on Active Directory permissions). But this doesn't work in case of Kestrel and integration with IIS. Any plan to implement this and any way to workaround this right now?

**Comment by Tratcher** [comment]
It's worth noting that IISIntegration does not do any impersonation for you, even for authenticated users. All actions are performed with the app pool identity unless you do explicit impersonation.

How do your permissions to differ between the app pool and your anonymous identities? Does anonymous get more, or less?

**Comment by antonGritsenko** [comment]
> It's worth noting that IISIntegration does not do any impersonation for you
I know. But I can use impersonation manually in ASP.NET Core. So it will be great to transfer anonymous identity to Kestrel somehow.
>do your permissions to differ between the app pool and your anonymous identities
Of course. Anonymous user usually very stricted account, but pool account had access to network, local files etc.

**Comment by Tratcher** [comment]
Is there anything stopping you from doing the impersonation directly in the app?

@blowdart

**Comment by Tratcher** [comment]
@shirhatti

**Comment by antonGritsenko** [comment]
OK, may be I have to explain a scenario. For instance, we have app that had access to some data. All data are stored in database\remote location etc that can be accessed only with valid active directory account. No problem here, we just setup application pool account with required AD permissions and it works fine. 
But now we have to protect all other thing from being executed from this account, so we setup Anonymous User Identity with very low privileged account (IUSR by default), and only execute code which needs to communicate with remote machine under application pool account.
In case of Kestrel all code needs to be executed under application pool account.

An another example (an more important): we are using ASP.NET Core web site (WS) to access remote system (RS) to get\update some data. RS requires different access level to do different things. For instance, to check users permission inside RS we have to use admin account inside RS. And again, in "pure" IIS this is not a problem: we setup application pool account with admin account, but Anonymous User Identity (AUI) is low privilege account. Regular communication made using AUI, but when we need to do some "admin" thing we just switch context to application pool and everything work well.

This is very similar with Windows Authentication: we have two Windows contexts: context of application pool and context of the logged in user. Will be great to have the same for anonymous access.

**Comment by Tratcher** [comment]
This would require a change to our overall impersonation story (or lack there of).

**Comment by antonGritsenko** [comment]
So it's hard from your side to "emulate" this by just pass-through the anonymous context like you did for Windows Authentication? I thought it's almost the same :(

**Comment by Tratcher** [comment]
The WindowsAuth user is passed through and assigned to HttpContext.User, but it's not impersonated. Do you do the impersonation yourself?

It may be possible to flow the anonymous user config from IIS to HttpContext.User, but impersonating that user would still be a separate concern.

**Comment by antonGritsenko** [comment]
>Do you do the impersonation yourself?

Yes, we did it manually. I do not expect automatic impersonation.

>It may be possible to flow the anonymous user config from IIS to HttpContext.User

This's exactly what I'm talking about. But that must be WindowsIdentity object to able to impersonate.

**Comment by Tratcher** [comment]
@pan-wang @shirhatti I think this is actually an ANCM request. I don't think anything would have to change in IISIntegration.

**Comment by shirhatti** [comment]
The IUSR account has a well-known SID that is consistent across all OSes. Forgive my naivety, but can you not just use this identity when doing the impersonation manually? Why do you need ANCM to flow this identity?,

**Comment by antonGritsenko** [comment]
Because IUSR rarely used in case of AD world. We almost always change it to some domain account (see case 2 from [comment above](https://github.com/aspnet/IISIntegration/issues/358#issuecomment-295790327))

**Comment by shirhatti** [comment]
This issue was moved to aspnet/AspNetCoreModule#92
