### ISSUE TITLE
Response Header(Server)

### ISSUE THREAD

**Issue by JonghoL** [aspnet/IISIntegration#36]
ASP.NET Beta8

Windows Server 2012 R2 Datacenter
IIS 8.5
Application Pool(.NET CLR version - No Managed Code)
Install HttpPlatformHandler

Http Response OK
Headers
 [expected] Server : Microsoft-IIS/8.5
 [actual] Server : Kestrel

Is it correct?

**Comment by muratg** [comment]
It looks correct to me... what do you think, @Tratcher?

**Comment by Tratcher** [comment]
That's expected now. IIS is acting as a reverse proxy to Kestrel. If you don't want it to say Kestrel then your app can do `httpContext.Response.Headers.Remove("Server");`.

**Comment by GuardRex** [comment]
@JonghoL Just as an add-on to that. This was recommended to me earlier and works quite well. I place it immediately before the `app.UseMvcWithDefaultRoute();` ...
```
app.Use(next => 
{
    return ctx => 
    {
        ctx.Response.Headers.Remove("Server");
        return next(ctx);
    };
});
```

**Comment by Tratcher** [comment]
```
app.Use((context, next) => 
{
    context.Response.Headers.Remove("Server");
    return next();
});
```

**Comment by GuardRex** [comment]
Oh, even better. Thanks.
