### ISSUE TITLE
Windows Authentication with Anonymous Authentication

### ISSUE THREAD

**Issue by NLI-KelbyHunt** [aspnet/IISIntegration#364]
Basically I am trying to have both options enabled for these cases:

1. Allow anonymous user to make a POST with login information to an API login controller than writes a JWT token back to the body after manual authentication.
2. Allow windows users to browse to the MVC application through a browser, using their windows identity to authenticate. (They don't see this happen, a.k.a pass-through authentication against our user database which is partially linked to AD)

Problem:

After enabling Anonymous Authentication in my IIS, the user will no longer automatically authenticate. My guess is anonymous authentication took precedence over windows authentication NTLM? 

I used IClaimsTransformer to get a ClaimsTransformationContext to query the Principal.Identity to get the windows authenticated user and query that against our database and retrieve our custom claims.

Question:

Can I use both authentication types the way I have explained?

**Comment by jruckert** [comment]
Yes, we are currently running this same setup (Anonymous, Windows Auth with Kerberos). The key is that you need to separate out the authentication from the authorisation

**Comment by NLI-KelbyHunt** [comment]
@jruckert Do you know of any examples that are publicly available that you speak of? I'm not quite understanding what you mean by separating the authentication from authorization.

**Comment by jruckert** [comment]
Try something like:

- Create/Inject your own authorisation logic - ours is contained within our own IAuthoriseResourceService (e.g. performs the .IsInRole checkes etc)

then decorate your MVC Controllers with the 
`
[TypeFilter(typeof(AuthoriseResourceProvider), Order = -1)]
public class BaseController : Controller
{
}
`

`using Microsoft.AspNetCore.Mvc;
 using Microsoft.AspNetCore.Mvc.Filters;

    public class AuthoriseResourceProvider : IActionFilter
    {
        private readonly IAuthoriseResourceService authoriseService;

        public AuthoriseResourceProvider(IAuthoriseResourceService authoriseResourceService)
        {
            authoriseService = authoriseResourceService;
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            if (!this.authoriseService.Authorise(context))
            {
                Fail(context);
            }
        }

        protected virtual void Fail(ActionExecutingContext context)
        {
            if (authoriseService.AuthenticateOnFail)
            {
                context.Result = new UnauthorizedResult();
            }
            else
            {
                context.Result = new NotFoundResult();
            }
        }

        public void OnActionExecuted(ActionExecutedContext context)
        {
        }
    }
`

**Comment by NLI-KelbyHunt** [comment]
@jruckert Is that the only route I can take? 

I am confused why I have an attribute available `[AllowAnonymous]` and it doesn't work out of the "box". I posted here because I felt this was an IIS issue not allowing me to use both Windows Authentication and Anonymous Authentication. The behavior acts like Anonymous authentication overwrites Windows Authentication. Is that intended? Why can I not find documentation on that?

**Comment by Tratcher** [comment]
@HaoK an AuthZ question for you.

**Comment by Tratcher** [comment]
This may help: https://github.com/aspnet/Security/issues/1062

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
