### ISSUE TITLE
iis 10 on win server 2016

### ISSUE THREAD

**Issue by guymalka** [aspnet/IISIntegration#374]
im setting new empty ( just the site visual studio create for me ) web site on the iis 
and receive error 500.19 
any help

**Comment by muratg** [comment]
Could be any of the reasons. Did you install AspNetCoreModule on IIS for example? (It comes with Windows Server Hosting Bundle which you can find at https://www.microsoft.com/net/download/core#/runtime)

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
