### ISSUE TITLE
Web.config Problem

### ISSUE THREAD

**Issue by cihadsevim** [aspnet/IISIntegration#381]
Hello everyone,
I've got a web.config file which contains only rewrite rule for http to https. I use web.config file for HTTPs redirection  because Google and Facebook can not fetch data from site when I use a middleware for it.

My problem is, when I publish the application to my host. Visual Studio overwrites on web.config file so, I lose these rules. 

How can I keep my web.config file?

**Comment by Tratcher** [comment]
> Google and Facebook can not fetch data from site

That's worth investigating...

@BillHiebert @moozzyk Isn't the web.config publish supposed to be additive?

Does publish work if you include the aspnetcore section in your web.config?
```
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Comment by moozzyk** [comment]
AFAIR adding aspnetCore related things was additive. I am not sure if it has changed or something else is happening now. I think @vijayrkn would now.

**Comment by vijayrkn** [comment]
The behavior should be same as before. There has been some reports on the values getting overwritten. 

Here is the bug tracking the issue.
https://github.com/aspnet/websdk/issues/115

As a work-around, IsTransformWebConfigDisabled property can be set to true and web.config transform wont get called.

**Comment by moozzyk** [comment]
The handler [will always be added](https://github.com/aspnet/websdk/blob/dev/src/Publish/Microsoft.NET.Sdk.Publish.Tasks/WebConfigTransform.cs#L44-L48) if it is missing. The problem @cihadsevim reports is that his rewrite rules are removed from web.config which should not happen.

**Comment by vijayrkn** [comment]
Could it be possible that the local web.config is not getting copied and because of this a new web.config is always created. 

@cihadsevim  can you try setting this property (IsTransformWebConfigDisabled  to true ) in the pubxml and see if the source web.config is getting published?

**Comment by cihadsevim** [comment]
Let me explain it fully. 

Using middleware for non-www or http-to-https redirect are no good for Google and Facebook scaping. I've tested Facebook with URL Linter tool, Google's Structured Data Testing Tool. Both can not crawl the page. I am not sure but the main problem seems first response needs to stop processing.

So, I tought using a web.config can be a solution. Defining "*" term for match url is causing an error on Visual Studio when developer tries to debug or hit f5. Using (.*?) regex pattern is solved this debugging problem. That way overrwite problem also solved.

Adding below web.config solved problem.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="HTTPS" enabled="true" patternSyntax="Wildcard" stopProcessing="true">
           <match url="(.*?)" />
          <conditions>
            <add input="{HTTPS}" pattern="off" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>`

**Comment by vijayrkn** [comment]
@cihadsevim Can you confirm if you have this in the web.config locally, is the rewrite rule getting overwritten during publish?

```
<?xml version="1.0" encoding="utf-8"?> <configuration> <system.webServer> <rewrite> <rules> <rule name="HTTPS" enabled="true" patternSyntax="Wildcard" stopProcessing="true"> <match url="(.*?)" /> <conditions> <add input="{HTTPS}" pattern="off" /> </conditions> <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" /> </rule> </rules> </rewrite> </system.webServer> </configuration>
```

**Comment by cihadsevim** [comment]
@vijayrkn No it does not. The .exe or dll directive is writing to appendlin eby VS2017 which is awsome.

**Comment by vijayrkn** [comment]
Can we close this issue then?

**Comment by cihadsevim** [comment]
Using <match url="(.*?)" /> with web.config does not work for redirect. Seems there is a bug or something else.

**Comment by cihadsevim** [comment]
That problem is still going on with Visual Studio 2017 and ASPNET Core 1.1

**Comment by cihadsevim** [comment]
Any update on issiue?

**Comment by Tratcher** [comment]
@cihadsevim One likely issue with your redirects is that IIS Express uses non-default ports for https (e.g. 44300-44399). Your redirect appears to send the client to http://localhost/, which uses the default 443 port.  When you start your app under the debugger it sends a request to test if your site is up, but it gets redirected to http://localhost:443/ which IIS Express isn't listening on so it fails.  This is going to be hard to get right with web.config based rewrite. However the new rewrite middleware directly supports this: https://github.com/aspnet/BasicMiddleware/blob/13e01db0d2096e2eb8c73501bfdb3ed5c1a15be9/samples/RewriteSample/Startup.cs#L29

MVC's RequireHttpsAttribute also now has support for specifying the port:
https://github.com/aspnet/Mvc/blob/3fc3d8d060e1ab7edffdb43c90258331f2d0162a/src/Microsoft.AspNetCore.Mvc.Core/RequireHttpsAttribute.cs#L80

**Comment by cihadsevim** [comment]
I'll try and feedback it.
