### ISSUE TITLE
DotNetCore.1.0.3_1.1.0-WindowsHosting.exe is not recognized as an internal or external command

### ISSUE THREAD

**Issue by cvetyab** [aspnet/IISIntegration#384]
Hi guys I am trying to deploy a new self hosted .net core app to windows server 2012 R2 where we have multiple other .net 4 applications and following the instructions on Microsoft docs site: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#install-the-net-core-windows-server-hosting-bundle  but when I ran the following
 DotNetCore.1.0.3_1.1.0-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0
I get 'DotNetCore.1.0.3_1.1.0-WindowsHosting.exe is not recognized as an internal or external command'
What am I doing wrong?

**Comment by GuardRex** [comment]
You're **not** doing anything wrong ... *I AM!* lol .... There was an update, so the command now is ...
```
DotNetCore.1.0.4_1.1.1-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0
```
I'll get a PR in to update those docs quickly! Thanks for pointing this out.

**Comment by cvetyab** [comment]
@GuardRex thank you, however I am still getting the same error running the updated version you posted

**Comment by GuardRex** [comment]
Is the downloaded executable named `DotNetCore.1.0.4_1.1.1-WindowsHosting.exe`?

**Comment by GuardRex** [comment]
I used the link that we have there that leads to `https://go.microsoft.com/fwlink/?linkid=844461`

**Comment by cvetyab** [comment]
Sorry for the stupid question but do I need to put that executable in some specific folder or run it first?

**Comment by GuardRex** [comment]
No specific folder AFAIK. You probably need to run it as an administrator, but one of the dev team members would know for sure if that could be a blocker. I always do the install as an admin, so I'm not sure if it will :boom: if you're logged in as an ordinary user.

**Comment by cvetyab** [comment]
@GuardRex never mind I figure it out the exe was in a different folder. Thank you!

**Comment by GuardRex** [comment]
AH ... very good. Thanks again for point this problem out with the doc!! :smile: :+1:

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
