### ISSUE TITLE
Azure Web App: Environment variables provided in the arguments attribute aren't interpreted anymore

### ISSUE THREAD

**Issue by toburger** [aspnet/IISIntegration#389]
I use the following library to host my web application: https://github.com/SuaveIO/Suave.IIS

The hosting port gets provided via:
`arguments="%ASPNETCORE_PORT%"`

Since yesterday everything worked normally. The port was parsed and the app worked flawlessly.
But suddenly I've got the dreaded 502 gateway error.

After some debugging I found the reason of the error:
The environment variable doesn't get interpreted anymore. My program receives the plain "%ASPNETCORE_PORT%" string and not the value of the environment variable.

My workaround is to read the environment variable in the application itselft, but I wonder why the behavior has changed and why this is happening exclusively on Azure. I think the aspNetCore module was updated, but I can't find any information about this breaking change.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#117
