### ISSUE TITLE
AspNetCoreModule needs to abort failed responses

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#39]
https://github.com/aspnet/KestrelHttpServer/issues/341#issuecomment-155245802

If the back-end server fails while writing out the response body (after the first 8kb) and closes/resets the connection, platform handler does not correctly fail the response to the client.

For a chunked request that fails sometime before the final chunked terminator the handler mistakenly adds the missing terminator. This is problematic because it tells the client the response completed successfully. It should have just closed/reset the connection.

Content-Length responses that fail after sending 8kb just hang.

**Comment by muratg** [comment]
@Tratcher is this still pending?

**Comment by Tratcher** [comment]
I tested with private builds and the behavior has improved, but it is still intermittently incorrect, especially if only a small amount of data has been sent before the back-end connection closes.

**Comment by Tratcher** [comment]
@rynowak, @glennc said you keep running into this as a response truncation issue?

**Comment by glennc** [comment]
@rynowak When using IIS the problem of JSON.NET throwing on circular models is exacerbated by the ANCM not severing the connection appropriately.

I can use HTTPClient to grab data from a web api in my controller and send that to a view, and not know that anything is broken if I don't have much data. In my case it was happily showing a single result on my page, and leaving out the rest. I didn't even realize until I moved it to Linux and then I would get exceptions and the app would fail.

**Comment by muratg** [comment]
@shirhatti Is the change not in ANCM? Why assign it back to @Tratcher

**Comment by shirhatti** [comment]
Repro app https://github.com/shirhatti/ConnectionCloseRepro

**Comment by shirhatti** [comment]
@muratg I'll assign it to @jhkimnew to further investigate

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#26
