### ISSUE TITLE
Add an option allowing to configure the scheme/display name associated with the Windows scheme

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/IISIntegration#391]
`IISMiddleware` registers the `Windows` scheme using the hardcoded `null` display name. Yet, there are cases where you want to specify a display name so the scheme appears in the external schemes list.

Please add an option to make the display name configurable (and maybe the scheme name too).

https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L60

**Note: this also applies to WebListener.**

/cc @Tratcher @HaoK

**Comment by PinpointTownes** [comment]
@Tratcher not having this option will be blocking for me for at least 3 projects. Is it too late to send a PR adding a `DisplayName` property to `IISOptions`? (and optionally, an `AuthenticationScheme` property)

**Comment by Tratcher** [comment]
If you're blocked go ahead and send the PR. We'll see if we can get it approved.

**Comment by Tratcher** [comment]
rel/2.0.0 branch

**Comment by PinpointTownes** [comment]
Okay, will do that tonight.

**Comment by Tratcher** [comment]
Tentatively approved, I'll do the PR today.

**Comment by Tratcher** [comment]
Let me know if you have a compelling reason to set the auth scheme, but not for 2.0.

**Comment by PinpointTownes** [comment]
@Tratcher haha no, I can live with the scheme not being configurable :trollface: 

Do you plan to port the fix to WebListener?

**Comment by Tratcher** [comment]
Not sure. It wasn't configurable before, and we still have an open item (that I can't find at the moment) about making WebListener work with individual schemes like it used to. Any plans to use WebListener?
