### ISSUE TITLE
ANCM sends 502.3 StatusCodes

### ISSUE THREAD

**Issue by MarcusKohnert** [aspnet/IISIntegration#398]
__Problem:__
ASP.NET Core Module sends 502.3 Status Codes. The behaviour is not constantly reproducible. The same request sometimes works, sometimes fails with 502.3.
This behaviour is observable on different machines in the same network.

ModuleName: AspNetCoreModule 
Notification: EXECUTE_REQUEST_HANDLER 
HttpStatus: 502 
HttpReason: Bad Gateway 
HttpSubStatus: 3 
ErrorCode: Access is denied. (0x80070005) 

__Dependencies:__
AspNetCore 1.1.2 (API only components)
AspNetCore.Server.IISIntegration 1.1.2
.NET Core 1.1

__Environment:__
IIS 8.5
Windows Server 2012 R2
hosted on premise

Only Windows Authentication is enabled and request is invoked with impersonation.
```
public class WindowsIdentityImpersonation
    {
        private readonly RequestDelegate next;
        
        public WindowsIdentityImpersonation(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            var windowsIdentity = context.User.Identity as WindowsIdentity;
            await WindowsIdentity.RunImpersonated(
                    windowsIdentity.AccessToken, 
                    async () => { await next.Invoke(context); }
            );
        }
    }
```

Could you please provide any guidance on how to solve this problem or gather more information?
Windows EventLogs give me no clues.

Thanks!

**Comment by Tratcher** [comment]
That impersonation approach doesn't work. See https://github.com/dotnet/corefx/issues/9996#issuecomment-307870746. There is no support for async impersonation.

**Comment by MarcusKohnert** [comment]
So this will work then?

WindowsIdentity.RunImpersonated(
    windowsIdentity.AccessToken, 
    () => { next.Invoke(context); }
);

**Comment by Tratcher** [comment]
That's worse, you're invoking next without waiting for the result. You'd have to do `next.Invoke(context).Wait();`, but that would cause other terrible things to happen to your app. Consider moving the impersonation to where you need it rather than trying to impersonate for the entire pipeline.

**Comment by MarcusKohnert** [comment]
Ok, thanks for your help!

So if I rethink the issue...
* The executing Thread is required to call the database on behalf of the authenticated windows user (integrated security)
* Async impersonation is not yet working
* --> So all my database calls (EF core) must be sync
* --> All my database calls must be wrapped in WindowsIdentity.RunImpersonated()

Is that the correct conclusion?

**Comment by Tratcher** [comment]
Yes, that covers it.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
