### ISSUE TITLE
Cannot connect to Db after publishing ASP.NET Core to IIS

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/IISIntegration#401]
1. **Application**: From this [Official ASP.NET tutorial][1]
 2. **Published** to IIS 7.5 on Windows 7 (64bit): Using this [Official ASP.NET doc][2]
 3. **Db used**: `SQL Server EXPRESS 2012` (instead of LocalDb)
 4. App works fine inside `VAS2017`
 5. Both `VS2017`, Db, and published app are on the same machine
 6. Db Connection string is using **windows Authentication** and works fine when running app inside `VS2017`
 7. I've verified that the `appsettings.json` file in the published folder has correct connection string

1.  Added `IUSR` with `db_owner` role with access to the Db.

**Issue**:
App works fine after publishing to IIS as long as you browse the pages that do not connect to Db. E.g., `http://localhost:2590` displays the home page correctly. But the URL `http://localhost:2590/Blogs` - that connects to the Blogs table in Db - throws the following error:

**Error**. `An error occurred while processing your request.`

**NOTE**: The issue is related to ONLY **windows Authentication**  and works fine with SQL Server Authentication.

  [1]: https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db
  [2]: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by Tratcher** [comment]
Logs? https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
