### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error The request page cannot be acessed because the related configuration data for the page is invalid

### ISSUE THREAD

**Issue by PraisyA** [aspnet/IISIntegration#405]
Hello there ,
 I face a problem when publish the project into local IIS 10.0 . 
Issue : 
   I have develop a sample **Angular 4 and Webapi** project in VS2017 , when i run the project from Visual studio its working fine even Azure also working . I publishing this app and try to run this from localhost with different port number and i set the **DefaultAppPool is Non manage code**  . Then i run the application from the browser i am getting error and unable to duplicate the issue 

![iiserror](https://user-images.githubusercontent.com/30825040/29062326-ded3fdce-7c3e-11e7-940d-14ab2f9c7d02.png)

and my web.config file is :
```
 <?xml version="1.0" encoding="utf-8"?>
            <configuration>
                  <system.webServer>
                               <modules runAllManagedModulesForAllRequests="true" />
                 <handlers>
                             <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
               </handlers>
                  <aspNetCore processPath="dotnet" arguments=".\Sample.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
                  </system.webServer>
               `</configuration>`
               <!--ProjectGuid: 095643ab-525a-44d1-96c9-03f972327fd2-->
```

Please help me out .

Thanks.`

**Comment by Tratcher** [comment]
You don't need runAllManagedModulesForAllRequests. I assume those backticks around configuration aren't in the original?
You'll get this error of the module isn't installed, like if you installed your tooling before installing iis. Try a repair on the tooling.

**Comment by PraisyA** [comment]
Hello Tracher , thank you for your reply .
i have manually added that   **runAllManagedModulesForAllRequests="true"**  i removed this and tried but same issue came.  

What tooling i have to repair? can you please tell me that .


Thanks.

**Comment by Tratcher** [comment]
A full repair of VS 2017 would be the simplest.

**Comment by PraisyA** [comment]
Hello Tratcher ,
 It is working in developer machine , but when publish this project to another machine ( which is does not have visual studio  just like client machine ) for testing , there it is not working .  have to install any components in client machine ? 


Thanks.

**Comment by Tratcher** [comment]
Yes, you need the Windows Server Hosting installer from https://www.microsoft.com/net/download/core#/runtime

**Comment by PraisyA** [comment]
Hi,
After install Windows Server Hosting installer i am getting different Error . See below pic.
![erroriis](https://user-images.githubusercontent.com/30825040/29077121-f275c4d0-7c74-11e7-856c-eec5eb885e95.png)

Thanks.

**Comment by Tratcher** [comment]
What do the event logs say?

**Comment by PraisyA** [comment]
That error is 👍 

**Application 'MACHINE/WEBROOT/APPHOST/BIZSIGHTN' with physical root 'C:\inetpub\TestSite\' failed to start process with commandline '"dotnet" .\sample.dll', ErrorCode = '0x80070002 : 0.**


Thanks

**Comment by PraisyA** [comment]
Hello Tratcher ,
Application is running fine now , i just restart the client machine after installing the Windows Server Hosting installer . Thank you for your Wonder full support ...


Thanks
Victor.A
