### ISSUE TITLE
IIS Development Time Support not working for .NET Core 2

### ISSUE THREAD

**Issue by danjohnso** [aspnet/IISIntegration#407]
Did you read the documentation? **Yes**
Did you include the snippet of broken code in the issue? **N/A**
What package versions are you using (you can see these in the project.json file)? **microsoft.aspnetcore.server.iisintegration 2.0.0**
What operating system are you using? **Windows 10 x64 (Version 1703, OS Build 15063.483)**
What version of IIS are you using? **10.0.15063.0**

I am running VS 2017 (15.3.1) and I have the .NET Core 2 web hosting bundle installed.  I have a series of applications that interconnect so I run them on IIS locally under the domain *.portalapps.com which I have host entries for pointing to 127.0.0.1 and a trusted certificate in the Cert store.  When I go to run my project using the IIS Development Time support, the debugger will not launch.  The only error I get is written to the temp directory:

![2017-08-22_10-37-19](https://user-images.githubusercontent.com/852995/29574101-36a7d916-8726-11e7-922d-597580452d27.png)

The error written to that file is: **DEBUG request is not valid.**

The project builds and runs fine, and I can manually attach the debugger to the process to start debugging, but this is a huge inconvenience when the tooling is advertised to work like normal .NET Framework debugging on IIS.  Since the debugger fails to attach, the process keeps running and I can't build again without using task manager to kill the core .exe which slows down development even more.  

Only thought I have is that this is related to using a domain name pointed at localhost instead of actually using localhost, but this worked fine in MVC5 on Full .NET Framework an IIS so it should for Core too.

**Comment by shirhatti** [comment]
cc @BillHiebert

**Comment by BillHiebert** [comment]
VS sends a request with the Debug verb to have IIS start your process (via ANCM). It sounds like there isn't a handler for this verb. @shirhatti  - does IIS log any information which could be used to track this down?

**Comment by danjohnso** [comment]
Tried that, nothing is generated by failed request tracing.  Tried for All Content, status codes 400-520.  Any other ideas?

**Comment by shirhatti** [comment]
Try all status codes (100-999)

**Comment by danjohnso** [comment]
Now I get a trace.  I do see the DEBUG verb right away, but the ANCM is getting a 302 back from Kesterel so I can authenticate (OIDC).  Is DEBUG command getting lost because of that?  I can't upload the trace here, but I can send it to you if you want to see the whole thing.

**Comment by danjohnso** [comment]
@BillHiebert @shirhatti any other ideas?  Would the trace be helpful?  Its odd the VS error box says it receives a 500 error back, but the trace is capturing a 302, seems like the error is happening somewhere else than in IIS or maybe the tool is mis-reporting

**Comment by danjohnso** [comment]
Wow so it magically started working after I was messing around with publish settings for deploying to our staging environment.  Not sure what triggered it, but the web.config was updated to to use this path and arguments in the module:
processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt"

Before it was getting set to the .exe in the bin folder directory with no arguments.

**Comment by BillHiebert** [comment]
VS writes those values when you press F5 as this is the linkage between the ANCM module in IIS and your .net core application (via an intermediate process which VS owns). Odd that they weren't there before

**Comment by danjohnso** [comment]
I think something is still broken in the tooling here.  I can't get the web.config to get the correct values written if I change the launch option between IISExpress and IIS.  It updates for changing to IIS Express, but not when going back to IIS.  I also have some projects which will not launch with this error:

![image](https://user-images.githubusercontent.com/852995/30177032-10fcac18-93ca-11e7-871e-5a167a6f5934.png)

The error appears to be happening when trying the tooling tries to create the IISExeLauncherArgs.txt or pidfile.txt files since they never get created in the IISSupport folder of bin.  I copied web.config and project settings over from the other project I got to start working unexpectedly, but this error persists when trying to connect to a different local IIS site.  Only difference between the two is the broken one is using localhost:8080 as the site address and the working on is a host file created domain (but also local).

**Comment by BillHiebert** [comment]
How have you configured your application pool? There is a bug (since fixed) in handling the authentication of the application pool. If it is configured to run a specific user, network service, or local service it exposes a bug in VS and you get that (unhelpful) error message

**Comment by danjohnso** [comment]
Yes I do have it running as a specific user, is there another issue tracking that or a fix available?

**Comment by BillHiebert** [comment]
The issue tracking it is here: https://developercommunity.visualstudio.com/content/problem/94448/error-when-using-development-type-iis-support.html

This fix is slated for the upcoming 15.4 release, I am not sure which preview build has it.

**Comment by muratg** [comment]
Done
