### ISSUE TITLE
Is SignInManager.GetUser() called cross process?

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/IISIntegration#411]
The call below parses a value to obtain the handle to an NT resource. Can this be called cross process or cross machine?

https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs#L36

**Comment by davidfowl** [comment]
The IIS module duplicates then handle into the child process it launches and passed the value via a header. There's no cross process call here if that's what you're asking...

**Comment by brentschmaltz** [comment]
@davidfowl thanks, that's what I was looking for. Handles are unique within a process.
