### ISSUE TITLE
Running ASP.net Core 2.0 in a server cluster with IIS and Shared Configuration

### ISSUE THREAD

**Issue by scionwest** [aspnet/IISIntegration#412]
We are working towards deploying an ASP.Net Core 2.0 project onto our existing server cluster in AWS. The cluster uses IIS Shared Configuration and has _n_-App Pools. While reading [the documentation](https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module#aspnet-core-module-with-an-iis-shared-configuration), we found this little nugget of information that is a little vague.

> The ASP.NET Core Module installer runs with the privileges of the SYSTEM account. Because the local system account does not have modify permission for the share path which is used by the IIS Shared Configuration, the installer will hit an access denied error when attempting to configure the module settings in applicationHost.config on the share.
> The unsupported workaround is to disable the IIS Shared Configuration, run the installer, export the updated applicationHost.config file to the share, and re-enable the IIS Shared Configuration.

Does this mean the work-around is not supported, but running ASP.Net Core with Shared Configuration on (regardless of how that's achieved) _is_ supported? Or is this meant to be read as ASP.Net Core not being supported at all by Microsoft with Shared Configuration?

If it is not supported at all, what is Microsofts recommendation for shops that have an existing infrastructure running on a server cluster? We would prefer not to have to manage the deployment across multiple virtual machines manually and using Shared Configuration gives us a simple means to deploy once and let the new version scale out across _n_-server instances.

**Comment by guardrex** [comment]
@Tratcher I'll open a doc issue if we need a topic revision when this is resolved.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#145
