### ISSUE TITLE
CORS preflight for Authorization Header failed with IIS

### ISSUE THREAD

**Issue by subprime** [aspnet/IISIntegration#413]
# Current situation
I'm running an ASP.NET Core 1.1 application as an API Backend and React application as an client frontend. For authentication and authorization i use OpenIdDict and jwt. The Bearer token is send in the Authorization Header. 

Locally it works, but when i try to use the backend behind IIS the preflight request is made but the GET request failed with 500 response.

I The following tests running:
- Run pure XMLHttpRequest without Authorization / api locally (200 response code)
- Run pure XMLHttpRequest with Authorization / api locally (200 response code)
- Run pure XMLHttpRequest without Authorization / api behind iis (200 response code)
- Run pure XMLHttpRequest with Authorization / api behind iis (500 response code)
- Run react without Authorization / api locally (200 response code)
- Run react with Authorization / api locally (200 response code)
- Run react without Authorization / api behind iis (200 response code)
- Run react with Authorization / api behind iis (500 response code)

**UPDATE** 
Here is an Example between client (locally) / api (remote) without Authorization Header which means no preflight request
![grafik](https://user-images.githubusercontent.com/17912160/30213257-91aab40c-94a8-11e7-9083-068628c3b074.png)

Here is an Example between client (locally) / api (remote) with Authorization Header which means a preflight request
![grafik](https://user-images.githubusercontent.com/17912160/30213382-11f05b80-94a9-11e7-9fe6-c33d03588630.png)
![grafik](https://user-images.githubusercontent.com/17912160/30213399-2775ae42-94a9-11e7-8aa5-dae6f20fd991.png)

So for my understanding there is something in IIS which is wrong. 
Can someone help me please. I try to fix this more than a week.... :(

**Comment by Tratcher** [comment]
What's in the application logs for your 500 responses?

**Comment by subprime** [comment]
@Tratcher Nothing. It seems that behind IIS the Kestrel is never reaced with Authorization Header

**Comment by shirhatti** [comment]
@subprime Could you share FREB logs in IIS for the 500?

**Comment by subprime** [comment]
@shirhatti Sure but. what do you mean with FREB Logs? I get no errors for the 500 response from IIS. Thats my big problem. I dont know what happens inside..

**Comment by subprime** [comment]
Can you help me to provide the logs?

**Comment by shirhatti** [comment]
https://docs.microsoft.com/en-us/iis/troubleshoot/using-failed-request-tracing/troubleshooting-failed-requests-using-tracing-in-iis

**Comment by subprime** [comment]
@shirhatti Thanks for the link! After a while of trying to install the TRACE-Addon it works now 👍 

I tried to study the logs ([IIS_Trace_500_Logs.zip](https://github.com/aspnet/IISIntegration/files/1299385/IIS_Trace_500_Logs.zip)) but i doesnt know why...

**Comment by subprime** [comment]
@Tratcher / @shirhatti Any idea why this error is thrown?

**Comment by shirhatti** [comment]
Looking at your FREB logs.
Pre-flights request succeeds and responds with a 204.
The actual GET request is forwarded to your backend that responds with a 500 after ~2 seconds.

There isn't enough information in the FREB logs to ascertain why it's failing. App logs are your best bet

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
