### ISSUE TITLE
How to host an ASP.NET Core app as sub-application of ASP.NET app in IIS

### ISSUE THREAD

**Issue by elevate-andrewlock** [aspnet/IISIntegration#415]
I've been trying to host an ASP.NET Core 2.0 app as a sub application of an ASP.NET app but I'm getting the following error when I try and browse the .net core site:

```
502.3 - Bad Gateway 
There was a connection error while trying to route the request
```

I can reproduce this with the "empty" .NET Core web app template.

I have installed installed the [.NET Core 2.0 Hosting bundle](https://aka.ms/dotnetcore.2.0.0-windowshosting), I have the .NET Core 2.0 SDK installed, and I'm just deploying to IIS locally at the moment. I've checked app pool configurations are correct.

I don't get an error if:
- I publish the .NET Core app to the local filesystem (e.g. _C:\Repos\testapp_)
- Create a new web site in IIS
- Set the physical path to the published app folder  (_C:\Repos\testapp_)

However, I _do_ get an error if: 
- I create a new web site in IIS  (e.g. _C:\Repos\testapp_)
- Set the physical path to  _%SystemDrive%\inetpub\wwwroot_
- Add a sub-application to the new web site
- Set the physical path to the published app folder  (_C:\Repos\testapp_)

Do I need to change anything in the _web.config_ file? [The documentation](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications) describes hosting ASP.NET and ASP.NET Core apps as sub-apps of ASP.NET Core apps, but not the reverse configuration I'm attempting.

 I've tried adding `<clear />` to the `<system.webServer><handlers>` section before adding the `AspNetCoreModule`, but that resulted in other errors attempting to directly return a file etc).

I originally found this issue when trying to use [development time support](https://blogs.msdn.microsoft.com/webdev/2017/07/13/development-time-iis-support-for-asp-net-core-applications/), but that appears to have the same problem.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#150
