### ISSUE TITLE
VSIISExeLauncher hangs

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/IISIntegration#416]
I have a project on asp.net core 2 target netcore2. 
I configured the project to run under IIS, create an application for it in IIS.

web.config:
```
  <system.webServer>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
```

Inside my project folder `bin\IISSupport\VSIISExeLauncher.exe` was depliyed (by VS I guess).
I open the app in the browser and see that lots of instances of VSIISExeLauncher.exe spaw. It looks like that for every request a new instance of VSIISExeLauncher.exe is started. Is it by design?
But my app in dev mode loads more 500 files (unbundled js/css modules) so it fails due to timeout.
I refresh the page but then I see that one instance of VSIISExeLauncher.exe is running. It eats 10-15% CPU and nothing happens. It hangs.
If I kill it via ProcessExplorer, a new instances continue to spawing and die. But when I refresh the browser again some of instances hangs.

If I run the app via `dotnet run` or "f5" from VS it woks fine.

How is it suppose to work?

**Comment by Tratcher** [comment]
@BillHiebert

**Comment by BillHiebert** [comment]
@evil-shrike 
There should only be one instance of VSIISExcLauncher spawned and its lifetime is governed by the lifetime of the dotnet.exe process that is hosting your application. Is there anything interesting in the ASP.NET Web Server output window (VS collects console output from asp.net core and dumps it into this window)

**Comment by evil-shrike** [comment]
@BillHiebert 
I run it via full IIS (not from IISExpress and not from VS), just target an IIS app to my folder and open in the browser.

**Comment by BillHiebert** [comment]
@evil-shrike 
If you open your browser and make a request, is dotnet.exe still running (or if you are running full framework your projectname.exe)? It should be. It sounds to me like the app is starting and then immediately failing. If this is the case, every request will cause ANCM to restart the application. 

What happens if your Ctrl-F5 from Visual Studio? Do you get the same failures?

**Comment by evil-shrike** [comment]
I open a page in the browser, get main page (it's SPA app), it loads tons of scripts, most of them load with 200 (successfully). At this time I can see how new processes start and die. 
![image](https://user-images.githubusercontent.com/1203230/30660892-058afe76-9e4b-11e7-8613-730a0b304eae.png)
Then at some script (always different) server stops responding - at that time a single VSIISExcLauncher process is running and eating CPU (10-20%), client waits, then client fails due to timeout. 
Sometimes that hanging process exits, sometimes doesn't. 

I tried run via pressing Ctrl-F5. Nothing visible happened (as I configured running under full IIS). When I accessed the app from client I got the same results as before. But when I repeated (opened a new page again) - it started to work as expected - only one single process is running and everything is fast. So sometimes "running" via Ctrl-F5 works fine, sometimes not. But if I kill w3wp and open the page again without touching VS I'll have that spawning processes again.

Is VSIISExcLauncher.exe suppose to work with VS?

**Comment by BillHiebert** [comment]
This should just work. Which version of VS do you have installed. We made a lot of fixes to this area in 15.3

**Comment by evil-shrike** [comment]
15.3.5

**Comment by enterpub** [comment]
Hi, I have same issue. This happens when I merge some branch into my branch => this causes change of files => by some reason visual studio can not process them correctly and then I see VSIISExeLauncher process uses about 15-20% CPU.
The only workaround I found is restart the VS (unload and reload the solution does not help). I have VS 15.3.5

**Comment by joshkrak** [comment]
Has anyone found a workaround to this? My VSIISExeLaunch eats up an entire core (25%). Even after reboot, no VS open, as soon as I make the first request to the site, VSIISExeLaunch starts up and takes up 25% CPU.

**Comment by BillHiebert** [comment]
@joshkrak, @enterpub - can one of you capture a dump of VSIISExeLaunch process while it is in this state, or an ETL trace? I've never been able to reproduce it.  Thanks.

**Comment by enterpub** [comment]
I'm now on VS 15.5.2 and have not experienced this issue yet, fortunately. If it comes up again, I'll try to have a dump

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
