### ISSUE TITLE
ASP.NET Core 2.0 IApplicationLifetime not working on IIS

### ISSUE THREAD

**Issue by thshr** [aspnet/IISIntegration#421]
When registering IApplicationLifetime callbacks in ASP.NET Core 2.0 hosted in IIS, they are not triggered i.e. Stopped and Stopping registered delegates are not being fired when the app pool is recycled on IIS.

They are triggered only when ASP.NET Core app is launched as an executable and stopped with CTRL-C

sample app: [https://github.com/thshr/AspNetCoreIAppLifetimeIIS](url)
output from logger with custom warnings:
**EXECUTABLE**
AspNetCoreIAppLifetimeIIS.Controllers.ValuesController:Warning: *** STARTED! ***
AspNetCoreIAppLifetimeIIS.Controllers.ValuesController:Warning: *** STOPPING.... ***
AspNetCoreIAppLifetimeIIS.Controllers.ValuesController:Warning: *** STOPPED!!! ***
**IIS**
AspNetCoreIAppLifetimeIIS.Controllers.ValuesController:Warning: *** STARTED! ***

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#166
