### ISSUE TITLE
Consume ANCM as a nuget package rather than requiring installation for In-Process

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#424]
As the mirror isn't up, we can't use the ANCM pulled from the nuget package for in-process testing.

**Comment by Tratcher** [comment]
So the tests are currently disabled...

**Comment by natemcmaster** [comment]
The mirror is up now. You can get a new version of ANCM by updating this:     <ExternalDependency Include="Microsoft.AspNetCore.AspNetCoreModule" Version="1.0.0-pre-10134" Source="$(AspNetCoreModuleFeed)" Private="true" Mirror="true" />

**Comment by muratg** [comment]
@jkotalik Any update on the agents required?  I assume each Windows agent with IIS should have the schema change, right?

**Comment by jkotalik** [comment]
I have updated all agents that run ANCM and IISIntegration. I'll need to confirm that other repos (ServerTests and I guess Music store) have updated schema files. 
I have also provided a fix that will remove the AV if ANCM doesn't have the schema change.
