### ISSUE TITLE
Consider merging UseNativeIIS() and UseIISIntegration()

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#429]
Currently, we specify that we are in-process by calling:
```csharp
var host = new WebHostBuilder()
         .UseNativeIIS();
```
We should consider merging this call with UseIISIntegration(), where we can somehow specify we want to run in-process:
```csharp
var host = new WebHostBuilder()
         .UseIISIntegartion(hostingModel: "inprocess"); // or an enum
```
or 
```csharp
var host = new WebHostBuilder()
         .UseIISIntegartion(); // Picked up by an environment variable or setting.
```

**Comment by Tratcher** [comment]
`.UseIISIntegartion(hostingModel: "inprocess");` doesn't work, that can only be set in the web.config.

**Comment by jkotalik** [comment]
After further investigation, I definitely think we need to do this. The single switch for turning on inprocess vs out of process should be in web.config's hostingModel. IISIntegration will need to pick up that we are running in "inprocess". 
By having the "UseNativeIIS()" call, if people call this and say they are using hostingModel="outofprocess", their app will fail to load because IISIntegration expects to be running in process while ANCM is configured to run out of process. 

Do we just want to try to see if ANCM is loaded and if it fails, assume we are out of process? Specifically: https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IIS/IISHttpServer.cs#L130-L142
