### ISSUE TITLE
Mock ANCM for testing purposes

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#431]
In Kestrel, we currently [mock libuv](https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Kestrel.Transport.Libuv.Tests/TestHelpers/MockLibuv.cs) for testing purposes. We should consider doing this for ANCM, as it would ease identifying if there were bugs in IISIntegration or ANCM. This could also be shared to Kestrel/ANCM to verify behavior behind it.

**Comment by muratg** [comment]
Won't be doing this.
