### ISSUE TITLE
Make IISHttpRequestBody and IISHttpResponseBody consistent in reading and writing

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#435]
Currently, ReadAsync on IISHttpRequestBody does contains the read logic in its class, but WriteAsync in IISHttpResponseBody contains the write logic in HttpProtocol. These should be consistent in code flow.

**Comment by davidfowl** [comment]
Is this actually fixing anything or is it just code cleanup?

**Comment by jkotalik** [comment]
I believe this is just clean up.

**Comment by jkotalik** [comment]
Will be part of #447
