### ISSUE TITLE
Add logging to file for in process

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#439]
Add logging to the file specified in web.config for the managed application. In the out of process scenario, we currently clone the logging file handle for both ANCM and the managed application. I believe we technically don't need to clone the file handle across native and managed, but it may cause difficulties for closing the handle and guaranteeing no extra writes occur.

**Comment by jkotalik** [comment]
@pan-wang for etw and event logs, we will just expose pInvokes which call etw and event logs, correct? For aspnetcore logs, it will be a bit more interesting (log to a file or something else).

**Comment by pan-wang** [comment]
.net core has windows event log implementation, https://www.nuget.org/packages/Microsoft.Extensions.Logging.EventLog/ 
I don't think we need pinvoke.  For file logging, I. E.,  user enabled stout in configuration,  ANCM can pass a file handle,  manage layer needs to use that handle.

**Comment by jkotalik** [comment]
Ongoing work with https://github.com/aspnet/AspNetCoreModule/pull/232. Will react once requirements are determined.
