### ISSUE TITLE
Sub-applications within IIS don't work anymore

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#44]
_From @Fosol on December 4, 2015 17:3_

I used to be able to publish an aspnet 5 beta 7 web application as a sub-application.  Since I'm upgrading to rc1-final I am no longer able to do it.

Here is the error I get when I attempt to call the sub-application within IIS.
> Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'httpplatformhandler' 

I can of course publish to a separate root IIS application and it will work, but of course that breaks the whole architecture of the application.

It's the result of the web.config changes that occurred.  
```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```

So how do I publish in the new world?

_Copied from original issue: aspnet/KestrelHttpServer#449_

**Comment by Tratcher** [comment]
@ajaybhargavb You got this working right? Can you share your findings?

**Comment by Tratcher** [comment]
I think the trick was to only include
```
<handlers>
  <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
</handlers>
```
in the base application's web.config. IIS Web.Configs are hierarchical, so your sub apps are inheriting the handlers section. Hence the error about duplicates.

**Comment by Fosol** [comment]
We did this.  The subapplication will only throw 404s from that point on.

This is a bug or a change that requires information to implement.

**Comment by Tratcher** [comment]
See the temporary Map workaround https://github.com/aspnet/IISIntegration/issues/14#issuecomment-150716529
