### ISSUE TITLE
Large ResponseBodies are cut short if using Static and Dynamic compression

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#442]
Repro example: 
Run the template MVC application. When navigating to the homepage, the Jquery.js file will sometimes lose a chunk of data, causing the file to be unusable. We should investigate why this is happening, which could either be in native or managed.

**Comment by jkotalik** [comment]
Seems to be possibly be caused by the Dynamic and Static compression modules in IIS. When running an MVC application with a applicationhost.configfile, all file responses came back as chunked and encoded. Disabling these fixed the issue from what I can tell. We should eventually verify that the Static and Dynamic compression modules work with in-process.

**Comment by Tratcher** [comment]
Those modules should be transparent to you, and they're on by default. Disabling them is not a sufficient workaround. Keep working on this.

**Comment by davidfowl** [comment]
I think that’s why the issue *isn’t* closed 😁

**Comment by Tratcher** [comment]
He said 'eventually'. There is no 'eventually' about data corruption. There should be no more feature work until we get this figured out.

**Comment by davidfowl** [comment]
I don’t want to not pick on those details. It’s a known issue and @jkotalik made some progress. The issue will be resolved just like all of the other ones.

**Comment by jkotalik** [comment]
Sorry poor word choice. I'm still working on this right now.

**Comment by jkotalik** [comment]
Alright after further investigation, it seems that the call to IIS WriteEntityChunks works normally if no compression module is enabled. However, when enabled, if the response body grows above ~65KB, it will only write up to that much to that call, even if more than 65Kb of data is provided. Without the module enabled, it works in both the chunked and content-length scenarios. 
@pan-wang is currently investigating why that call doesn't return the full response length. If it is a bug, we may need to change the way we write the response.

**Comment by pan-wang** [comment]
This is seems to be by design.  In duplex mode, the callback is registered on io completion, it this returns the number of bytes sent of first chunk. I think we can ignore the number as long as it is not zero.  Once the callback is called,  we can assume the chunk is handled by IIS correctly.   In case of failure,  nothing we can do here as some byte already sent to the client.

**Comment by jkotalik** [comment]
Seems we can't use WriteEntityChunks for any use because the dynamic and static compression modes have a configurable chunk size. Because of this, we cannot reliably limit the size from managed to chunking below the buffer limit.  Per discussion with @pan-wang, we should probably avoid using IHttpResponse2::WriteEntityChunks. Moving this to ANCM.
