### ISSUE TITLE
MS-ASPNETCORE-TOKEN error hosting an ASP.NET Core 2.0 Web API on IIS 8

### ISSUE THREAD

**Issue by AdrienTorris** [aspnet/IISIntegration#448]
I have some trouble hosting an ASP.NET Core 2.0 Web API on IIS 8.

I have this error : fail: Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware[0]
      'MS-ASPNETCORE-TOKEN' does not match the expected pairing token 'SOME_GUID_HERE', request rejected.

**Comment by Tratcher** [comment]
That's a first. This check is to prevent the application from accepting requests from anywhere but the IIS reverse proxy. It sounds like something is trying to access the app directly via localhost. Is this error for requests you are making or are you only seeing these in your logs?

**Comment by AdrienTorris** [comment]
Ok I fixed it.
I had a problem with my configuration file, the one who defined the server.urls value. It takes me 4 or 5 hours I think but it's working now, sorry to disturbed you.

**Comment by geirsagberg** [comment]
@AdrienTorris Having a similar problem, only with IIS Express; what was your solution?

**Comment by HB-2012** [comment]
@geirsagberg I just ran into this issue because I disabled the option "Launch browser". This results in an address being printed in the output window, but that address is actually incorrect. You have to use the address that is configured in the "App URL".

You can get to these settings through Project Properties > Debug

**Comment by HristoHentov** [comment]
This is quite an old issue, however I wonder if anyone here know if I this "validation" can be disabled. 
The reason I would want to disable it, is since I have a health-check endpoint that is called from a service discovery app, and it only knows the actual port, where the kestrel-hosted app is.

**Comment by Tratcher** [comment]
No it can't.
