### ISSUE TITLE
HTTP 502.3 Bad Gateway running on the IIS with HttpPlatformHandler(1.2)

### ISSUE THREAD

**Issue by zhengchun** [aspnet/IISIntegration#45]
I'm sorry,i known this issue already discussing at [ASPNET-Home#1000](https://github.com/aspnet/Home/issues/1000) or at [ASPNET-Hosting#364](https://github.com/aspnet/Hosting/issues/364),but it still can't help me how to running correct.

I'm testing run a `HelloWeb` project that in the `v1.0.0-rc1-update1` version and it can running correct on `dnu web` command,when publish(dnu publish command) and run on IIS integration with HttpPlatformHandler1.2,get `HTTP 502.3 Bad Gateway` error,i'm read this article [Publishing to IIS](http://docs.asp.net/en/latest/publishing/iis.html).

the following is my environment:

Win10 64-bits
HttpPlatformHandler 1.2
.net 4.6
dnvm on `1.0.0-rc1-update1 clr     x64`

web.config on wwwroot folder:
```c#
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```
project.json
```c#
{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "exclude": [
        "wwwroot"
    ],
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
        "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final"
    },
    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://*:5004"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    }
}
```

**Comment by davidfowl** [comment]
Anything interesting in `..\logs\stdout.log`?

**Comment by zhengchun** [comment]
NO,there are no any log to output,it's  a empty folder.

**Comment by zhengchun** [comment]
hi,@david,i found a error message in windows event viewer:

```
无法找到来自源 HttpPlatformHandler 的事件 ID 1004 的描述。本地计算机上未安装引发此事件的组件，或者安装已损坏。可以安装或修复本地计算机上的组件。

如果该事件产生于另一台计算机，则必须在该事件中保存显示信息。

以下是包含在事件中的信息: 

Warning: Could not create stdoutLogFile \\?\C:\Users\Jacky\home\samples\1.0.0-rc1-update1\HelloWeb\bin\output\logs\stdout.log_1568_201512764716.log, ErrorCode = -2147024891.

无法找到来自源 HttpPlatformHandler 的事件 ID 1000 的描述。本地计算机上未安装引发此事件的组件，或者安装已损坏。可以安装或修复本地计算机上的组件。
```

```

如果该事件产生于另一台计算机，则必须在该事件中保存显示信息。

以下是包含在事件中的信息: 

Process '0' failed to start. Port = 25289, Error Code = '-2147024891'.
```

it's looks missing some components?

**Comment by zhengchun** [comment]
i setted a permission for the logs folder and get a `Maximum rapid fail count per minute of '10' exceeded` error in the event viewer window.

**Comment by davidfowl** [comment]
Whats in the log file now?

**Comment by zhengchun** [comment]
` "dnx.exe"' is not recognized as an internal or external command, operable program or batch file`

**Comment by davidfowl** [comment]
@zhengchun Try publishing from visual studio instead of from the command line. It looks like you are running into several problems:

- Permissions aren't setup properly
- You didn't publish the runtime
 - As a result of not publishing the runtime the dnx.exe can't be found (because it's normally in the user profile and the identity your app pool is running under can't find it)

**Comment by zhengchun** [comment]
Hi,@david,it can working using visual studio instead of the command line,thanks.

`HTTP 502.3 Bad Gateway` that  not just don't have install a HttpPlatformHandler,and also missing permission will also cause this error.Thanks.

**Comment by jijiechen** [comment]
@zhengchun  I hope my comment [ASPNET-Hosting#466](https://github.com/aspnet/Hosting/issues/466#issuecomment-168372853) could help, you may have a try.
