### ISSUE TITLE
.NET 4.7x Framework pages are started with Workstation GC

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/IISIntegration#452]
In the old DNX the pages were started with Server.GC, due to an issue with https://github.com/dotnet/project-system/issues/2896 the appropriate project setting is ignored for netfx.
It might be more useful to have the default GC set to server as it was in the old DNX.

# Steps to reproduce:
1. Create Webpage for ASP.NET Core 2.0 and target Framework 4.7.x
2. Run in IIS
3. Log the GC type
# Expected Result
Server GC
# Actual Result
Workstation GC

This bug is kinda annoying because the performance characteristics of Server GC vs. Workstation GC are quite different on server systems.

Repro:
[WrongDefault.zip](https://github.com/aspnet/IISIntegration/files/1394003/WrongDefault.zip)

**Comment by Tratcher** [comment]
GC is an app configuration, it's unrelated to IIS / the launcher. The default is controlled by the runtime, though perhaps it could be influenced by the SDK.

Adding an app.config file to your project with the following should help.
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element

This should be included in the template.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/templating#73
