### ISSUE TITLE
Switching between inprocess and outofprocess still needs to call UseKestrel() 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#456]
As part of merging [UseIISIntegration() ](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L29) to support in-process and out-of-process, I didn't recognize that UseIISIntegration() does not call UseKestrel() in the out of process scenario. Therefore, if we switch the web.config from "inprocess" to "outofprocess", we get an exception in Startup that there was no IServer implementation provided. This mostly will be a design question for the future, but it would be nice to have a one place switch where UseIISIntegration will call UseKestrel() for out of process.
Related to #455 and https://github.com/aspnet/AspNetCoreModule/issues/204.

**Comment by Tratcher** [comment]
WebHost.CreateDefaultBuilder already takes care of that:
https://github.com/aspnet/MetaPackages/blob/fcdd25635c8174a0c8a7a0853a6f3d8620448839/src/Microsoft.AspNetCore/WebHost.cs#L151
Thus far we've voided adding a direct call from UseIISIntegration to UseKestrel as the server is theoretically replaceable.

**Comment by jkotalik** [comment]
Yeah definitely replacing Kestrel in the future :trollface: . Is it required that UseIISIntegration is called after UseKestrel? If so, then for anyone that is calling CreateDefaultBuilder or UseKestrel before IISIntegration and wants to run in-process, Kestrel will be replaced by the IIS Server.

**Comment by Tratcher** [comment]
We were discussing the ordering issue on a different thread that I can't find at the moment. CreateDefaultBuilder currently calls UseKestrel and UseIISIntegration in the correct order, allowing iis to replace kestrel if in-process. If someone reversed those manually then their in-process apps would break. Out-of-proc does not have a problem because IIS lightup is dynamic.

**Comment by jkotalik** [comment]
My main issue with the current switch in web.config for the in process mode is discoverability. If someone calls UseKestrel(), it would be confusing if the server ended up not being Kestrel without an explicit . 
If a user wanted to explicitly use the in process mode, it should be a replacement for UseKestrel(). We may be overloading UseIISIntegration() as that is currently a switch between running kestrel standalone versus running behind IIS. 
cc/ @shirhatti . Ping me if you want more information on this issue.

**Comment by Tratcher** [comment]
The web.config setting is a deployment setting, it shouldn't require an app code change / recompile. This is similar to our IIS integration lightup today, you can run the same app in IIS or self-host without recompiling. There has been a little confusion around if Kestrel is still in use in the IIS out-of-proc scenario, especially around url config, but it hasn't been a major blocker for people.

**Comment by shirhatti** [comment]
I'm with Chris on this. Ability to switch modes without recompiling takes higher precedence than being more explicit.

Here's what I assumed setting up WebHostBuilder would look like, essentially unchanged.
```
 var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
```
@jkotalik I'm assuming your concern here is that Kestrel won't be used despite an explicit call to `UseKestrel()`?

**Comment by jkotalik** [comment]
Yeah that sums up the issue. The main issue is before the in-process mode, UseIISIntegration didn't add its own server implementation. Now that it does, it could be considered a breaking change to change all server defaults from out of process to in process. 
To be very clear about the options for handling this:

**Option A: (what is currently implemented)**
```csharp
 var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
// web.config has hostingModel="inprocess" or "outofprocess"
```
This will remove Kestrel when inprocess is true, otherwise use kestrel behind ANCM.

**Options B:**
```csharp
 var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseNativeIISIntegration() // or some call like that
                .UseStartup<Startup>()
                .Build();
// web.config has hostingModel="inprocess" or OutOfProcess
```
In UseNativeIISIntegration, If we are inprocess, we will add the IISHttpServer, else Kestrel and UseIISIntegration. This forces consumers to call UseNativeIISIntegration rather than leaving it in UseIISIntegration, and allows for switching between inprocess and out of process with just a webconfig change.

**Comment by shirhatti** [comment]
To further distill down the crux of your argument, we're introducing a behavior change in what `.UseIISIntegration()` does in a minor release, but semver doesn't allow us to do that. So we should create a new extension method (name is up for discussion) that hangs of WebHostBuilder that does what UseIISIntegration does in option A, but has a different name.

@muratg @DamianEdwards  Any thoughts on this?

**Comment by Tratcher** [comment]
The behavior is opt-in based on a user provided web.config flag. That's not a breaking change.

**Comment by muratg** [comment]
@shirhatti What's some of the important scenarios that may be breaking if we keep the name of the extension?

**Comment by jkotalik** [comment]
I think we intend on keeping the behavior the same. If a user wants to swap between in process and out of process, the will have to call UseKestrel and UseIISIntegration, and UseIISIntegration will replace Kestrel for in process.
