### ISSUE TITLE
.net core 2.0 hosting iis is very very slow on high traffic

### ISSUE THREAD

**Issue by taoli0124** [aspnet/IISIntegration#459]
I use jmeter as a test tool，if my site hosting iis ,200 concurrent，per second 20+，but not use iis per second 300+.

Who can tell me why? 

Many thanks

**Comment by Tratcher** [comment]
@sebastienros

**Comment by sebastienros** [comment]
Just to be sure I understand the problem, you are hosting your website on Windows, and you tried with IIS and without IIS (Kestrel only). And you see a worse performance with IIS?

Can you be more specific about the numbers you get, what is the unit of "20+" and "200+"

**Comment by taoli0124** [comment]
Forgive me please,my english is so bad.
I create a default project with visual studio 2017.Write some code

![qq 20171025094243](https://user-images.githubusercontent.com/18223429/31976258-ff8838ca-b968-11e7-9eea-af5ef557151a.png)

I use ab test.It's my result.

with IIS
![qq 20171025094728](https://user-images.githubusercontent.com/18223429/31976388-daae7144-b969-11e7-9eb3-31f3dec6a442.png)

without IIS (Kestrel only)
![qq 20171025095203](https://user-images.githubusercontent.com/18223429/31976658-4d19f234-b96b-11e7-9a0c-cb3ff351d6bb.png)

**Comment by dallancarr** [comment]
Is this production code? Check your use of httpclient maybe.

**Comment by taoli0124** [comment]
@dallancarr 
I also found httpclient has problem,but i can't solve.

**Comment by sebastienros** [comment]
Do you have the same issue is you remove the call to HttpClient and just use a constant text value instead?

**Comment by taoli0124** [comment]
If i  remove the call to HttpClient and the performance is ok.

**Comment by dallancarr** [comment]
That should work. Just don't new it up in the controller or lazy load it. There are certain patterns of use around this object which have come to love recently.

**Comment by taoli0124** [comment]
The issue is that asp.net core module in IIS doesn't forward calls faster to the application. Any idea?

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
