### ISSUE TITLE
[Dotnet CLI]: IIS Hosting big rocks

### ISSUE THREAD

**Issue by davidfowl** [aspnet/IISIntegration#46]
With the upcoming CLI changes, we need to change how IIS launches the application. Since commands are going away, the application will be the main entry point. Here's the example `web.config`:

In dev

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

After publish

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```

### During development

We could look at keeping the pattern and changing the names of the env variables to be more generic:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%HTTPPLATFORM_PROCESS_PATH%" arguments="%HTTPPLATFORM_PROCESS_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

Another option would be to put the relative path to the executable:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="..\bin\Debug\dnxcore50\WebApplication1.exe" arguments="" stdoutLogEnabled="false" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

### After publish

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="..\bin\Release\dnxcore50\WebApplication1.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```

This approach is basically telling VS to write the current launch settings into the processPath, arguments and environment variables sections of the web.config to make the HttpPlatformHandler work in IIS Express. The benefits to this approach are:

1. It keeps publish and development in sync
2. No post processing needs to happen to the web.config
3. Full IIS doesn't require any changes (other than the usual permission goop)

**Comment by Tratcher** [comment]
Isn't this a Tooling task?

**Comment by GuardRex** [comment]
Nit (unless this is changing, too): The file extension for the log file is added automatically.

**Comment by muratg** [comment]
@Tratcher At least the environment var names would need to be updated with this approach on the runtime.  Also I'm not sure if we modify web.config after publish for HttpPlatformHandler sections but this change seems to require that as well. Tooling will be impacted too.

**Comment by davidfowl** [comment]
It's mostly a templates work item actually and tooling. We should just decide where what we want to try.

/cc @BillHiebert

**Comment by muratg** [comment]
@davidfowl Is it OK to close on IISIntegration and file in Tooling repo instead?

**Comment by davidfowl** [comment]
No leave it for now. When we get something working end to end then we can close it.

**Comment by muratg** [comment]
Is there a tooling WI tracking the work on their side?  

@BillHiebert?
