### ISSUE TITLE
In-process mode may not work with current lightup method.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#460]
For the out of process scenario, we created a [backdoor](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/IISHostingStartup.cs) to allow us to inject the startup assembly for lightup. In the in process scenario though, we will not have control of the process lifetime, therefore we can't inject the Microsoft.AspNetCore.Server.IISIntegration.IISHostingStartup assembly. We may need to create our own backdoor to handle this too.
cc/ @shirhatti @Tratcher

**Comment by Tratcher** [comment]
Why not? We just need an environment variable set and ANCM in proc can still do that.

**Comment by muratg** [comment]
This should work, but we'll need to test this.  

Related #306

**Comment by shirhatti** [comment]
@jhkimnew Can you test this? This should be complete right now

**Comment by Tratcher** [comment]
@jkotalik why wouldn't it work? You only need to ensure the env var is added like out-of-proc does.

**Comment by jkotalik** [comment]
You are correct. I am not sure why I thought this originally. We just need to verify it.

**Comment by shirhatti** [comment]
I'll help @jhkimnew verify this

**Comment by jhkimnew** [comment]
@shirhatti  @jkotalik  a sample aspnetcore app of the lightup method is verified in inprocess mode.
