### ISSUE TITLE
Implement IHttpLifetimeFeature

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#461]
Currently the abort logic only works for managed to native. When native sends a signal for ClientDisconnected, we need to stop reading and writing and cleanup the connection once fired.

**Comment by Eilon** [comment]
@muratg / @jkotalik - anything to do here for preview1?

**Comment by jkotalik** [comment]
Push this to preview2. I have a WIP branch to implement this but I need to do a bit of redesign.

**Comment by Eilon** [comment]
I'll let @muratg do the honors.

**Comment by muratg** [comment]
@jkotalik could you file one more bug to fix crashes? We can keep this one for the feature for managed events etc.

**Comment by pakrym** [comment]
https://github.com/aspnet/IISIntegration/issues/1020
