### ISSUE TITLE
Add a target file to the IISIntegration package so VS can detect support for the new InProc mode

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#466]
InProc support is new in 2.1 and requires changes in ANCM, IISIntegration, and VS. VS is going to add a checkbox for in-proc that maps to the web.config setting, but it only wants to show the checkbox for projects with the right dependency versions. It could try to inspect package versions, but it would be cleaner to add a targets file to the package to advertise the support.

@BillHiebert will supply the targets file.

If this works then we may do something similar for Kestrel's new default https support.

**Comment by jkotalik** [comment]
Could this checkbox in VS set an environment variable which is then mapped to the web.config setting?
cc/ @DamianEdwards @glennc as we were discussing this.

**Comment by jkotalik** [comment]
@BillHiebert @shirhatti is this complete through the project capability?

**Comment by shirhatti** [comment]
This has already been checked into dev
