### ISSUE TITLE
HTTP Error 502.5 - Process Failure 

### ISSUE THREAD

**Issue by apis3445** [aspnet/IISIntegration#467]
Hi! I have a .net core 2.0 app I try to publish to IIS 10
 I have my webconfig like this
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments=".\Core.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

I review and I have the dotnet.exe in this path, if I try in console dotnet Core.dll runs correctly in localhost:5000 but in IIS I geth this error

HTTP Error 502.5 - Process Failure
and in the event viewer I get this error 

Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root  'C:\inetpub\wwwroot\' failed to start process with commandline ' ', ErrorCode =  '0x80070057 : 0.
--

why doesn't set anything in the comandline?

**Comment by jkotalik** [comment]
How are you publishing the application to IIS? Through Visual studio, commandline, etc? Based on that scenario, check [our sample web.config](https://github.com/aspnet/IISIntegration/blob/dev/samples/IISSample/web.config) as an example.

**Comment by apis3445** [comment]
with visual studio with the folder path option I Have the webconfig like the sample and withd comand line runs correctly the user of the application pool and iste in iis has privileges

**Comment by ndreisg** [comment]
I had the same issue today. I found out, that my Azure Web App automatically updated the .net Core runtime to 2.0.3 so my 2.0.0 deployment didn't work anymore.
I had to update my local installed .net Core SDK to 2.0.3 too (https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3.md)

I also updated the NuGet Package "Microsoft.AspNetCore.All" to 2.0.3

Hope this helps :)

**Question to ASP.net Core Team**: Will future updates be backwards compatible?

**Comment by apis3445** [comment]
hi thank you I reinstall iis and works but today I have the same issue I update the project last week and yesterday the deploy has an error with the .net core version maybe in the future the team can works and don't mark a 503 error by the exact version of the .net core

**Comment by Tratcher** [comment]
@davidfowl

**Comment by alrz** [comment]
For my case the issue was rather silly but I had the same error. Make sure that the application is under "Default Web Site" in IIS console.

**Comment by nokturnal** [comment]
@ndreisg totally solved my issue...

**Comment by mdevreeze** [comment]
We've run into this issue too, several times. 
I do think the errors thrown are not really helpful in explaining what is going on. A simply SDK check should take place which reports when there is a mismatch.

**Comment by PRElias** [comment]
Having same issue. Already tried to update .Net Core to 2.0.3

**Comment by ryanbeaz** [comment]
Same here...any ideas?

**Comment by jkotalik** [comment]
@mdevreeze interesting idea. I wonder if we can call "dotnet.exe --info" to check that.

@PRElias @ryanbeaz what is the error you are seeing from the windows event log? I believe the latest dotnet version is 2.0.5.

**Comment by ryanbeaz** [comment]
Hey @jkotalik! I'm seeing:

failed to start process with commandline 'dotnet .\NameofDLL.dll', ErrorCode = '0x800004005 : 8000808c.

**Comment by PRElias** [comment]
In my case it was the Identity used in the pool. The Default does not work

**Comment by agnimitra** [comment]
I ran through the same issue today and have fixed by changing web.config file.
[https://stackoverflow.com/questions/38624453/asp-net-core-1-0-on-iis-error-502-5/48761913#48761913](https://stackoverflow.com/questions/38624453/asp-net-core-1-0-on-iis-error-502-5/48761913#48761913)

**Comment by nxplus** [comment]
I have the same issue when trying to deploy to a windows server 2008 machine, I have another cause of the error:
![dotnet_cmd](https://user-images.githubusercontent.com/17198037/36477503-b0263100-1701-11e8-8e54-f2c06615bceb.jpg)

This will only be apparent when you manually try to run "dotnet" on the server machine.
(and maybe with the hint in the event log: "failed to start process with commandline 'dotnet'...")

After reading, it seems that something called Universal C Runtime needs to be installed on the machine.

**Comment by TomCJones** [comment]
I never was able to solve it on a move from 2.0.2 to 2.0.5 The only way I got out was to delete the account on azure and reinstall. And that took most of a day for one reason or another

**Comment by kamruldotnet** [comment]
Download .net core latest version and install this. Hope solving your problem.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
