### ISSUE TITLE
ASP.NET Core module runs app twice

### ISSUE THREAD

**Issue by ysmoradi** [aspnet/IISIntegration#475]
I've multiple **ASP.NET Core 1.1** apps with **.NET 4.6.1 as a sdk target** and **.NET 4.7 as a runtime** on **Windows server 2012 R2 (6.3.9600)**. 

I've also installed **ASP.NET Core 1.1 hosting module** for an **unmanaged/integrated application pool**.

**Max worker process = 1**

IIS structure:
     App pools >> MainAppPool, AppPool1, AppPool2, AppPool3, AppPool4, AppPool5
     Web Site >> Main web site with MainAppPool
     Web Apps under main web site >> WebApp1 with AppPool1 to WebApp5 with AppPool5

MainWebSite has no process other than w3wp.exe process. (It's a simple folder)
WebApp1,3,5 have only one process for each of them + 3 processes for w3wp.exe
**WebApp2,4 have two processes for each of them** + 2 processes for w3wp.exe
So I've 13 processes instead of 11 processes.

I tried to stop/start IIS and it creates those extra processes every time.

What can cause such a problem like this?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#247

**Comment by ysmoradi** [comment]
@Tratcher Thanks. Sorry for my bad.
