### ISSUE TITLE
HTTP Error 502.5 on Azure Web App, even with PublishWithAspNetCoreTargetManifest set to false

### ISSUE THREAD

**Issue by sebastianbk** [aspnet/IISIntegration#479]
I am running my ASP.NET Core app in Azure Web Apps and recently upgraded to version 2.0.3 due to some bugs in v2.0.0. However, now when I deploy to Azure, I get an error (HTTP 502.5), which other users have also encountered (e.g., #476).

I have tried setting the `PublishWithAspNetCoreTargetManifest` property to `false`, cleaned up the `wwwroot` folder in my Azure Web App and then redeployed. Though, I am still getting the error. I tried creating an entirely new Web App too but I still get the same issue.

Here is a copy of my `csproj` file: https://pastebin.com/1CfNKcRb

After upgrading to 2.0.3 I also had to add these lines:

```xml
<PropertyGroup>
  <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
</PropertyGroup>
  
<PropertyGroup>
  <NoWarn>$(NoWarn);NU1605</NoWarn>
</PropertyGroup>
```

I do not know if adding these lines is affecting whatever `PublishWithAspNetCoreTargetManifest=false` is doing.

I really hope that somebody has a fix for this, as it is extremely critical to our app and we currently feel pretty stuck. Downgrading to 2.0.0 is not an option for us, as we rely on some of the bug fixes in 2.0.3 (related to security and two-factor auth).

**Comment by acquire16** [comment]
Getting exact same issue here.  Just updated from 2.0.0 to 2.0.3 and after publishing getting a 502.5.

**Comment by MikahB** [comment]
Same issue here, much the same troubleshooting as well.  I'm going to revert back to "last known good" and see if I can get it going again, but all day today so far been dead in the water.

**Comment by shirhatti** [comment]
This was a temporal issue when Azure App Service had not updated to 2.0.3. This should no longer be an issue

**Comment by Leon99** [comment]
This happened again with 2.0.8. Is there a schedule of Azure App Service rollouts that we can follow to know when it's OK to upgrade Microsoft.AspNetCore.All?

**Comment by FrancescoBonizzi** [comment]
Same here!

**Comment by shirhatti** [comment]
Unfortunately, there's not much I can offer in terms of guidance here to mitigate these temporal issues.
Azure App Service posts announcements when they start new deployments and it doesn't hurt to keep a finger on the place- https://github.com/Azure/app-service-announcements/issues/107
