### ISSUE TITLE
Font-Awesome woff files css url rewriting missing.

### ISSUE THREAD

**Issue by neojg** [aspnet/IISIntegration#481]
# Scenario

1. Generate the Angular SPA template based application.
2. Add Font-Awesome package
3.  Add some arbitrary fa into home.component.html like: `<i class="fa fa-spinner fa-spin"></>`
4. Limit the webpack url-loader to some small number e.g. 1000
5. build the project
6. Create the Debug profile to run on local IIS (Windows 10) with app URL: http://localhost/WebApplication1
7. Run the project.

# Error

The displayed misses the fonts:
![image](https://user-images.githubusercontent.com/7301205/33293918-bd73b722-d3ce-11e7-92aa-51a01978f301.png)

# Error Observation

Look into the files downloaded with Chrome:

![image](https://user-images.githubusercontent.com/7301205/33293991-fa5cda38-d3ce-11e7-931d-241f6bb37188.png)

The missing fonts are all directed incorrectly to `http://localhost/dist/....` missing the application root folder `Webapplication1`
Looking into the css files the url of the fonts was not rewritten by the reverse proxy of the IIS!
The same happens on the Windows Server IIS and in case IIS Reverse proxy!

![image](https://user-images.githubusercontent.com/7301205/33294169-a4c3d9f4-d3cf-11e7-9846-2d1a7dd17c8a.png)

**Comment by shirhatti** [comment]
@Tratcher This sounds like pathBase issue. Does this ring a bell?

**Comment by Tratcher** [comment]
I expect it would work if you left off the leading slash. E.g. if `/dist/f4...` was `dist/f4...`. The leading slash tells the browser it's an absolute path, not relative to the current path.

**Comment by shirhatti** [comment]
@neojg Did this fix the problem for you?

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
