### ISSUE TITLE
HTTP Error 502.5 - Process Failure - 2.0.0 Deployment in Azure Web App with 2.0.3 Runtime

### ISSUE THREAD

**Issue by ndreisg** [aspnet/IISIntegration#482]
As @davidebbo stated in #406 I create a new Issue here for my Problem with 2.0.0 deployment on 2.0.3 Azure Web App.

My 2.0.0 deployment broke when the .net Core Runtime of my Azure Web App was updated to 2.0.3.
A HTTP Error 502.5 - Process Failure was displayed.

**The app that was running suddenly broke with no deployments.**
I then tried to redeploy my 2.0.0 App but the error stayed.
After I updated my locally installed .net Core SDK to 2.0.3 and redeployed, it was working again.

I still have a 2.0.0 Deployment on another instance (http://sto-update-test.azurewebsites.net/), there you can still see the error.

Message from Application Events:
`Application 'MACHINE/WEBROOT/APPHOST/STO-UPDATE-TEST__A4C5' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\MyApp.dll', ErrorCode = '0x80004005 : 8000808c.`

Message from KUDU Debug Console:
```
D:\home\site\wwwroot>dotnet .\MyApp.dll
Error:
  An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.0-beta6'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'

  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-preview2-25794-linux-x64.xml;aspnetcore-store-2.0.0-preview2-25794-osx-x64.xml;aspnetcore-store-2.0.0-preview2-25794-win7-x64.xml;aspnetcore-store-2.0.0-preview2-25794-win7-x86.xml;aspnetcore-store-2.0.0-preview2-final-linux-x64.xml;aspnetcore-store-2.0.0-preview2-final-osx-x64.xml;aspnetcore-store-2.0.0-preview2-final-win7-x64.xml;aspnetcore-store-2.0.0-preview2-final-win7-x86.xml
```

PS: The real Application Name above was replaced with "MyApp"

**Comment by Tratcher** [comment]
Was this targeting 2.0.0 or 2.0.0-preview2 as implied by the manifest errors?
Can you share your deps.json?

**Comment by davidebbo** [comment]
It looks like it's targeting 2.0.0, but has references to pre-release assemblies which only existed in the pre-release runtime store. So it got broken when 2,0 prerelease was removed from [App Service](https://github.com/Azure/app-service-announcements/issues/35), and not because 2.0.3 was deployed.

So I think this is by design.

**Comment by ndreisg** [comment]
I think this explains it.
Thank you. Can be closed.
