### ISSUE TITLE
ASP Net Core vs WCF performance

### ISSUE THREAD

**Issue by ravikumarsureshbabu** [aspnet/IISIntegration#489]
Hello, 

I upgraded a WPF application to be a ASP NET CORE 2 application. I am running  ASP NET CORE 2 application using IIS + Kestrel.   ASP NET CORE 2 application has application insights and authentication middleware with empty handler, while WPF dont. 
Excluding all the time it takes to process the business logic in the application, ASP application takes approximatly 150ms more than WPF application. That is, time taken at IIS + kestrel + middlewares. 
The processing time I calculated is a average of over 1000 calls. 

Does this delay sounds right ? Or am I missing any configuration in IIS or Kestrel to get it better ?

**Comment by Tratcher** [comment]
The IIS + Kestrel scenario does have some known latency overhead. In the short term the best alternatives are to use Kestrel or HttpSys directly. In the future we're working on a direct IIS option that will address this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
