### ISSUE TITLE
ASP.NET Core Module 1.1 not installed in IIS on Windows 2016

### ISSUE THREAD

**Issue by tkallsen** [aspnet/IISIntegration#493]
I'm not able to get the ASP.NET Core Module 1.1 installed in IIS on Windows 2016. I have tried three different 2016 servers, but it's the same problem with all of them.

Installation goes ok as far as I can see after scanning the logs, but the aspnetcore.dll is not installed under C:\Windows\system32\inetsrv, and there is no entry in the IIS Module list.

I'm using the Server Hosting Bundle (https://www.microsoft.com/net/download/thank-you/dotnet-runtime-1.1.5-windows-windows-server-hosting-installer).

I have tried uninstalling and installing a few times, with reboots in between but nothing seems to help. This page (https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore1x#iis-configuration) says under Troubleshooting -> "Incorrect role, module not installed, or incorrect permissions" that the ASP.NET Core Module is supposed to have an entry under installed programs, which is not true in my case. However, when I check a working Window Server 2012 installation, I don't have that there either.

Another symptom is that IIS fails to read a web.config in IIS Manager if it contains the `<aspNetCore>`-element, but I guess that is just because the ASP.NET Core Module is missing.

Install logs attached.
[logs.zip](https://github.com/aspnet/IISIntegration/files/1578537/logs.zip)

**Comment by Tratcher** [comment]
@pan-wang @joeloff

**Comment by pan-wang** [comment]
This is a known issue due to a bug in bundle. We are rebuilding the bundle and will release it soon.  As workaround, you can uninstall the problematic bundle and install an older one.

**Comment by tkallsen** [comment]
Ok, the 1.1.4 bundle (https://download.microsoft.com/download/6/F/B/6FB4F9D2-699B-4A40-A674-B7FF41E0E4D2/DotNetCore.1.0.7_1.1.4-WindowsHosting.exe) worked, as you said. Do you have an ETA for "soon"? ;)

**Comment by jkotalik** [comment]
See https://github.com/aspnet/AspNetCoreModule/issues/275 for more information. We are working on repackaging it as soon as possible.

**Comment by muratg** [comment]
@tkallsen If you're still seeing issues, please let me know.

**Comment by RodrigoFCampos** [comment]
I'm trying to download the "Hosting Bundle Installer" from here:

https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7

But when I click on the link:

https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/DotNetCore.2.0.7-1-WindowsHosting.exe

I got the following response:

This site can’t be reached

:)

**Comment by joeloff** [comment]
I'm following up with a few folks. The reported download size on that link also seems incorrect. It shows as 1.2KB - it should be ~99MB

**Comment by muratg** [comment]
cc @leecow

**Comment by joeloff** [comment]
Please try https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/DotNetCore.2.0.7-WindowsHosting.exe

**Comment by robertmuehsig** [comment]
Is the above link "stable"? I try to use the link in a install script for our software and want to make sure that this link is not a temporary one. @muratg

**Comment by joeloff** [comment]
@robertmuehsig yes, that link should be stable.
