### ISSUE TITLE
IISIntegration and static files in asp.net core 1.x

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/IISIntegration#494]
Hello all

I have IIS integration enabled as usual:
```
services.Configure<IISOptions>(options =>
{
     options.AutomaticAuthentication = true;
     options.ForwardWindowsAuthentication = true;
});
```
and static files in default configuration:
`app.UseStaticFiles();` 

Everything located in wwwroot (defaults folder for static files) with such config will require authentication.
Not sure if it's a bug or just misunderstanding, but from my point this is at least weird behavior, because the doc of static file clearly mentioned (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files): 

> The static file module provides no authorization checks. Any files served by it, including those under wwwroot are publicly available.

So my question is: if this is a feature and not a bug, then what options do we have to make static file available without authentication?
With IIS itself this is possible, I can just set Anonymous access to any folder.

**Comment by Tratcher** [comment]
Do you mean that you've configured IIS to require windows auth for all requests? And now you want to exclude your static files from that?

See Allow anonymous in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?tabs=aspnetcore2x
In short, you need to enable anonymous and windows in IIS and then configure Authorization on your various restricted resources.

**Comment by antonGritsenko** [comment]
@Tratcher thanks for quick response. 
And I'm using Kestrel, not a WebListner. But in any case, I think I have found my problem. Anonymous access must be enabled on site's root, not on subfolder as it was before (with regular ASP.NET and IIS).
I will re-open this item in case if it's not a case.
