### ISSUE TITLE
IIS Functional tests should try multiple ports if one is already being used.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#495]
Currently many ports are hard coded to a certain value, like https://github.com/aspnet/IISIntegration/blob/dev/test/IISIntegration.FunctionalTests/NtlmAuthentationTest.cs#L31. I had an application on the same port, which caused the test to always fail. We should have a port count that we will continue to increment and allow tests to try multiple ports, like in HttpSys: https://github.com/aspnet/HttpSysServer/blob/dev/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Utilities.cs#L70

**Comment by Tratcher** [comment]
This applies to ServerTests and MusicStore as well.
