### ISSUE TITLE
Increment aspnecore.dll and aspnetcorerh.dll file versions based on build version.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#506]
We need to modify the version.h file and the ANCM file version to reflect the build version number.  See: https://github.com/aspnet/IISIntegration/blob/dev/src/RequestHandler/version.h and https://github.com/aspnet/IISIntegration/blob/bcc10d3012f6e48a5ed4e5d639331bf874ba5fb5/version.props

**Comment by shirhatti** [comment]
Done
