### ISSUE TITLE
Enable In Process tests once latest ANCM schema is added to Visual Studio

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#515]
ANCM in process tests have to be disabled until we add the updated ANCM schema to Visual studio. The 1985 build of ANCM was supposed to have the schema change (current build on VS), however it was actually in the 1986 build of ANCM. We need this schema change to run in process tests because adding the new hostingModel="inprocess" to your web.config will fail at schema validation. As we rely on IISExpress to run tests, we can't run any in proc tests until this change is in. We could write a script to manually add the schema to all known locations, but we wouldn't be able to update AppVeyor and it could be overwritten every time we want to update Visual Studio. 
cc/ @shirhatti

**Comment by shirhatti** [comment]
😭
