### ISSUE TITLE
ANCM: Inprocess: 500 error when 32 bit dotnet installation path is set before 64 bit's installation path for the PATH environment variable

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#519]
1. Configure PATH environment variable to put the path of 32 bit dotnet.exe before 64 bit path.
Ex.) %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\dotnet;C:\Program Files\dotnet;
2. Restart IIS services to apply the change
3. Configure inprocess mode and set relative path for dotnet.exe, not full path
4. Send a request

EXPECTED:

No error

ACTUAL:

500 error

**Comment by muratg** [comment]
@jkotalik close?
