### ISSUE TITLE
ANCM: Inprocess: 500 error after switching to inprocess from outofprocess mode

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#522]
REPRO STEPS:
1. Set hostingMode with outofprocess or empty value (default value is outofprocess)
2. Send a request and you can see w3wp.exe is started
3. Set hostingMode with inprocess
4. Send a request

EXPECTED:

No error 

ACTUAL:

500 error

NOTE:

1. In the aspnetcorerh!IN_PROCESS_APPLICATION::ExecuteApplication function, LoadLibraryW(m_pCOnfig->QueryHostFxrFullPath()) returns false and that's why the 500 error happens.

At the moment, the m_struHostFxrLocation was empty value, which means that the value was used here without waiting it is initialized. 

2. Attached the stack information.

0:018> kn
 # Child-SP          RetAddr           Call Site
00 00000096`d0e0f850 00007ffa`21653e7a aspnetcorerh!IN_PROCESS_APPLICATION::ExecuteApplication+0x71 [d:\gitroot\iisintegration\src\requesthandler\inprocess\inprocessapplication.cpp @ 525] 
*** ERROR: Module load completed but symbols could not be loaded for C:\Windows\SYSTEM32\vfbasics.dll
01 00000096`d0e0f900 00007ffa`21731d54 aspnetcorerh!IN_PROCESS_APPLICATION::ExecuteAspNetCoreProcess+0x3a [d:\gitroot\iisintegration\src\requesthandler\inprocess\inprocessapplication.cpp @ 501] 
02 00000096`d0e0f940 00007ffa`3ba413d2 vfbasics+0x11d54
03 00000096`d0e0f980 00007ffa`3de75444 KERNEL32!BaseThreadInitThunk+0x22
04 00000096`d0e0f9b0 00000000`00000000 ntdll!RtlUserThreadStart+0x34

**Comment by muratg** [comment]
Workaround is manually recycling the process after changing the config.
