### ISSUE TITLE
ANCM: Inprocess: stdoutLogEnabled: w3wp.exe crashed when it is being recycled if stdoutLogEnabled is set to true

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#534]
The repro step of the crash issue.
1. Set inprocess for hostingModel
2. Set true for stdoutLogEnabled.
3. Send a request 
4. Recycle the IIS AppPool that is used by the application

Expected:

W3wp.exe is recycled with no error.

Actual:

W3wp.exe gets crashed.

**Comment by jkotalik** [comment]
#535
