### ISSUE TITLE
ANCM: Inprocess: environmentVariables does not work 

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#536]
1. Configure environmentVariables  for inprocess mode as the following example web.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="c:\program files\dotnet\dotnet.exe" arguments=".\Test123.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess">
            <environmentVariables>
                <environmentVariable name="MyEnv" value="foo" />
            </environmentVariables>
        </aspNetCore>
  </system.webServer>
</configuration>
```

2. Send a request to the aspnetcore app

EXPECTED:

The configured environment variables are available in the application process

ACTUAL:

The configured environment variables are not available in the application process

**Comment by jkotalik** [comment]
This should be a quick fix, @pan-wang we decided on appending environment variables rather than overwriting them, correct?

**Comment by Tratcher** [comment]
Yes please

**Comment by jkotalik** [comment]
@muratg let's put this in preview 2. There are work arounds by setting the environment variables directly on the w3wp process. The question is if we are okay with the web.config environment variable settings affecting the rest of the IIS pipeline's environment variables.

**Comment by Tratcher** [comment]
Vs. having consistent behavior for in and out of proc.

**Comment by muratg** [comment]
@shirhatti FYI

**Comment by jhkimnew** [comment]
BTW, the work-around is only available recent OS build. For example, on Windows 2012 R2, users can add additional environment variable to IIS worker process.

**Comment by shirhatti** [comment]
@jkotalik / @pan-wang Has it been verified that appending the environment variables will work? @BillHiebert is relying on this feature to work for tooling

**Comment by muratg** [comment]
@BillHiebert @jkotalik will be working on this soon.

**Comment by jkotalik** [comment]
@pan-wang @Tratcher we need to confirm if any environment variables need to be modified from their original values. The out of process code does manipulation on the auth environment variables, but features like hostingstartup may need to be modified.

**Comment by Tratcher** [comment]
List the variables and values you're concerned about.

**Comment by jkotalik** [comment]
Here are the ones I can find.
```
ASPNETCORE_IIS_AUTH_ENV_STR
ASPNETCORE_IIS_AUTH_WINDOWS
ASPNETCORE_IIS_AUTH_BASIC
ASPNETCORE_IIS_AUTH_ANONYMOUS
ASPNETCORE_IIS_AUTH_NONE
HOSTING_STARTUP_ASSEMBLIES_ENV_STR
```

**Comment by Tratcher** [comment]
The IIS_AUTH variables are not interesting, we can handle those in directly.

For HOSTING_STARTUP_ASSEMBLIES we could keep adding IISIntegration if we wanted. Low priority.

**Comment by pan-wang** [comment]
For out of process,  as we don't allow user to set those values, we have to check and replace the value. For in process, the authentication value is not read from environment variable, you can just filer them out.
