### ISSUE TITLE
ANCM: Inprocess: No event information for startup and graceful shutdown

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#542]
1. Send a request to an aspnetcore app in inprocess
2. Recycle IIS worker process where the application was running
3. Look at Windows Events

EXPECTED:

There must be events of starting/stopping applications

ACTUAL:

No event.

**Comment by muratg** [comment]
@jhkimnew will verify again, because @pan-wang thinks this is fixed.
