### ISSUE TITLE
ANCM: Inprocess: We don't show any additional information in Freb log unlike outofprocess mode

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#553]
We don't show any additional information in Freb log unlike outofprocess mode. 
We have to show some useful information for inprocess mode as well so that users can utilize FREB log for troubleshooting.

**Comment by muratg** [comment]
@shirhatti to look into this a bit more.

**Comment by shirhatti** [comment]
We need to agree upon the scope of this feature

**Comment by pakrym** [comment]
Fixed in https://github.com/aspnet/IISIntegration/pull/1461
