### ISSUE TITLE
Grant requestTimeout for InProcess scenario

### ISSUE THREAD

**Issue by pan-wang** [aspnet/IISIntegration#555]
For OutOfProcess case, ANCM grants the requestTimeout in configuration by setting WinHttp connection timeouts. For InProcess, we grant this timeout setting by flowing it to the managed layer.

**Comment by muratg** [comment]
@jkotalik will sync up with @Tratcher on this regarding http.sys features around this. That may mitigate the need for this one.  Tentatively putting this in preview2, but we may move it out.

**Comment by Tratcher** [comment]
Http.Sys has no matching feature. It has request header parsing timeouts and rate limiting, but there's no timeout on application request processing like ANCM had.

**Comment by muratg** [comment]
@Tratcher I think this was about header parsing timeout.

**Comment by Tratcher** [comment]
No, https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module.
> Specifies the duration for which the ASP.NET Core Module will wait for a response from the process listening on %ASPNETCORE_PORT%.

The in-proc corollary is waiting for the application to process the request.

**Comment by muratg** [comment]
Per triage, we won't be doing this.
