### ISSUE TITLE
New error page for inprocess application start failure

### ISSUE THREAD

**Issue by pan-wang** [aspnet/IISIntegration#556]
For OutOfProcess scenario, if ANCM failed to start the backend process, it will sent a special 502.5 page to the client with some diagnose hints,  if disableStartUpErrorPage is configured as FALSE (default). We should consider a similar page for inprocess scenario to help user debug the failure.

**Comment by muratg** [comment]
@shirhatti Could you check with @blowdart?

**Comment by blowdart** [comment]
I'm going to need to know what is in the page, what circumstances send it, and if it's available to anyone on a crash, or just, say, to people accessing localhost

**Comment by Tratcher** [comment]
![image](https://user-images.githubusercontent.com/1821173/35832181-1f274bda-0a81-11e8-9734-fffaf83fe392.png)

**Comment by blowdart** [comment]
Oh just static? With nothing else? That's fine then.

**Comment by muratg** [comment]
This is for cases where the app failed to load. Otherwise, if the app is working, Developer Exception Page could be used instead.

**Comment by blowdart** [comment]
Oh, I missed "today".

OK, so what information, and under what circumstances? Would the environment affect the information displayed?

**Comment by shirhatti** [comment]
We're still designing this. Thinking out loud we want to control it via [web.config](https://github.com/aspnet/IISIntegration/blob/dev/src/AspNetCore/aspnetcore_schema.xml#L27) or an env variable.

**Comment by Tratcher** [comment]
What's changed from when we designed this a few years ago and decided a static page was the only possible safe content?

**Comment by shirhatti** [comment]
Think developer exception page, but for startup failures instead.

Off by default, but makes it way easier to diagnose startup failures than having to look at event logs and redirecting stdout logs.

**Comment by Tratcher** [comment]
So the equivalent of ASPNETCORE_CAPTURESTARTUPERRORS and ASPNETCORE_DETAILEDERRORS in Hosting? Better use the same settings.
