### ISSUE TITLE
ANCM: APPLICATION::DereferenceApplication is used without using APPLICATION::ReferenceApplication

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#557]
1. Attach debugger to w3wp to put following break points

bp aspnetcore!APPLICATION::ReferenceApplication ".echo ReferenceApplication; g" 
bp aspnetcore!APPLICATION::DereferenceApplication ".echo DereferenceApplication; g" 

2. Recycle aspnetcore applications

EXPECTED:

The break points hit for both APPLICATION::DereferenceApplication() and APPLICATION::ReferenceApplication().

ACTUAL:

The break point of APPLICATION::DereferenceApplication() is hit but the break point of APPLICATION::ReferenceApplication() is not hit.

**Comment by muratg** [comment]
@pan-wang could you check if this is done and close it accordingly? Thanks.

**Comment by muratg** [comment]
@jhkimnew will verify the behavior is as expected.

**Comment by jhkimnew** [comment]
The repro scenario of this issue is not valid anymore. I did that temporary to find any leak issue. We have better test coverage. So, closing this issue.
