### ISSUE TITLE
Improve configuration error messages when there is an invalid config.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#568]
- Log windows event log message when parsing a portion of configuration fails.  Make sure to put a fwlink in the event log message.

**Comment by natemcmaster** [comment]
FYI - current error message looks like this: https://rawgit.com/natemcmaster/75850119721330b49e466154edc285b4/raw/43b58b1b89939649c1761108fb4d25c22e98ae86/error.html

**Comment by muratg** [comment]
The main issue we're seeing often is the missing/corrupt/old/invalid Schema file.  We're not trying to identify other issues in this case.

**Comment by Eilon** [comment]
@pan-wang / @muratg / @jkotalik - Is this a must-have for Preview2? If not, let's move to RC1.

**Comment by pan-wang** [comment]
this error happens during test due to mismatched schema file. This will not happen for real setup scenario

**Comment by muratg** [comment]
No more action needed on this one.
