### ISSUE TITLE
Platform Handler cannot log to streaming logs location

### ISSUE THREAD

**Issue by glennc** [aspnet/IISIntegration#57]
There appears to be some bug in the platform handler that stops it from redirecting console output to the right location for streaming logs to work. The team have agreed that it is a bug they should just fix, but I don't know when that will actually happen.

**Comment by Eilon** [comment]
@Tratcher should this be assigned to you? Right now a ghost is working on this :smile:

**Comment by muratg** [comment]
@Eilon I believe the fix is in HttpPlatformHandler, and Ranjith is working on it.  This is a tracking bug to ensure we'll verify it once it's done.  

We can probably remove "Working" tag though :)

**Comment by Tratcher** [comment]
The fix is available and we're working on the validation.

**Comment by Tratcher** [comment]
This should be fixed in AspNetCoreModule v0.8.
@pan-wang Assigning this to you for verification in Azure.

**Comment by pan-wang** [comment]
I tested in a private stamp and did see the log file was created and information was logged correctly.

**Comment by moozzyk** [comment]
Related https://github.com/aspnet/Tooling-Internal/issues/548 ?

**Comment by muratg** [comment]
@moozzyk Seems related. @pan-wang could you take a look?

**Comment by moozzyk** [comment]
I linked because I remember a discussion about what log streaming is really supposed to be. I think this is fixed - in the other bug @maumar said that streaming works once the path is set correctly.

**Comment by maumar** [comment]
It works from VS if you set the log location to LogFiles//application, but using CLI it works for more cases, e.g. "default" LogFiles.
