### ISSUE TITLE
Cannot use routes that contain %2B

### ISSUE THREAD

**Issue by praeclarum** [aspnet/IISIntegration#575]
I have the following routes:

```csharp
options.Conventions.AddPageRoute("/packages/details", "packages/{id}/{version}/{targetFramework}");
```

This works great for urls like `/packages/foo/1/net`

However, if the `targetFramework` contains an escaped `+` as in: `/packages/foo/1/net%2Bother` then IIS (hosted as an Azure web app) says:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

And it never runs my code. You can see it in action here: http://fuget.org/packages/sqlite-net-pcl Just click the yellow button.

The same URL works fine on Kestrel. 

I expect IIS to behave as Kestrel since the URL is well-formed and matches my route definition.

**Comment by Tratcher** [comment]
What do you see in the application logs for that request?

**Comment by jkotalik** [comment]
I think IIS Request Filtering will filter out '%2b': https://blogs.iis.net/nazim/use-of-special-characters-like-in-an-iis-url.

**Comment by praeclarum** [comment]
Applog says:

```
```

**Comment by praeclarum** [comment]
@jkotalik my god that's terrible. How do you turn all that off?

**Comment by praeclarum** [comment]
I ended up creating a web.config file and put this in it:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <security>
            <requestFiltering allowDoubleEscaping="true" />
        </security>
    </system.webServer>
</configuration>
```

It would be nice if Kestrel and IIS had the same defaults. I can't test on IIS and getting these deployment surprises isn't nice.
