### ISSUE TITLE
Web API returns 404

### ISSUE THREAD

**Issue by mduey** [aspnet/IISIntegration#579]
I am using Visual Studio 17 (v 15.3.5) to create a .NET Core **Web API** and a **Web Application**.  For both projects, I used the defaults without changes and they both run fine on my workstation.

I then publish them (using Folder option) to my Windows 2008 SP2 server with IIS.  I have installed the .NET Core Windows Server Hosting bundle on the server following instructions from [https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?tabs=aspnetcore2x](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?tabs=aspnetcore2x).

I have multiple IP's on my server and each site is assigned a different IP through IIS.

The Web Application works fine, but the **Web API returns 404**.  

I have enabled logging and they both start the same (WebApi log shown here):
`Hosting environment: Production`
`Content root path: D:\webapi`
`Now listening on: http://localhost:14284`
`Application started. Press Ctrl+C to shut down.`

I noticed that when running local on my workstation, the Web API returns a 404 if the url does not contain the **/api/values**, so I made sure to try all variations of the url on the server.  They all return 404.

Am I missing something?

**Comment by Tratcher** [comment]
Why do you think it would work without `/api/values`? What outer values were you expecting to work?

**Comment by mduey** [comment]
I don't expect other URL values to work, I was just noting that it returns a 404 when I do and that my original problem does not stem from the fact that I was using the wrong URL.

One more  new item to note is that if I add the following app.Run() statement after the app.UseMvc():

`app.UseMvc();`
` app.Run(async (context) =>`
      ` {`
          ` await context.Response.WriteAsync("MVC did not find anything!");`
    `   });`
It will return the string.  So if I go to http://myserverip/api/values, it will return "MVC did not find anything" (instead of the 404).
Still, however, if I do this on my workstation, it returns the values in my [HttpGet].  So it looks like MVC is failing.

**Comment by Tratcher** [comment]
@mkArtakMSFT can you redirect this?

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
