### ISSUE TITLE
Not able to get it running in IIS

### ISSUE THREAD

**Issue by Fosol** [aspnet/IISIntegration#58]
I've got a Development environment setup and running with IIS, however I've recently attempted to publish to a QA environment and it won't work within IIS.

After I publish I can run the web application with the command line "web.cmd".  I just can't get IIS to give me anything at all.  I've set IIS up the same way as the Development environment (as far as I can tell).

Is there a list of steps to get things running in IIS?  Please don't point me to this page - http://docs.asp.net/en/latest/publishing/iis.html  as I've already tried that one.

I don't even get a log file created in the 'stdoutLogFile="..\logs\stdout.log"' location.

**Comment by Fosol** [comment]
Looks like I need to uninstall IISPlatformHandler and then delete all web sites and web applications in IIS.

Then reinstall and reconfigure...

**Comment by GuardRex** [comment]
@Fosol It's not fully updated for RC2, but if you want additional info, check my comment at https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294. If you get stuck, ping me back, and I'll see if I can help.
