### ISSUE TITLE
Uber issue for Diagnostics 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#581]
- [ ] #568 
- [ ] #556 
- [ ] #553 
- [ ] #552 
- [ ] #542 
- [ ] #516 
- [ ] #593 
@shirhatti if you find any others please edit the issue.

**Comment by shirhatti** [comment]
I've been adding a diagnostics label. I'll cross-check against that later

**Comment by muratg** [comment]
All work is tracked in seperate issues now. Closing.
