### ISSUE TITLE
Disable HTTP Upgrade feature when WebSockets are not available

### ISSUE THREAD

**Issue by anurse** [aspnet/IISIntegration#584]
## Out-of-proc

* ANCM sets `ASPNETCORE_WEBSOCKETS_SUPPORTED` environment variable to `true` if WebSockets module is installed **and** OS Version > Windows 7. Or `false` otherwise
* IIS Integration middleware reads this environment variable (defaults to `true` if not present)
* If `ASPNETCORE_WEBSOCKETS_SUPPORTED` = `false`: Remove the `IHttpUpgradeFeature` from the request features
* Else: do nothing

## In-proc

* `IISHttpServer` checks if WebSockets if WebSockets module is installed **and** OS Version > Windows 7 (either in the managed code, or by reading data populated by the native code, whichever is easier/possible)
* If `true`: Install the `IHttpUpgradeFeature` as before
* Else: **Do not** install the `IHttpUpgradeFeature`

**Comment by jkotalik** [comment]
@anurse for the inproc and out of proc scenarios, they are both on a per request basis? Therefore,the IISHttpContext should be the one to remove the IHttpUgradeFeature?

**Comment by anurse** [comment]
IIS should be modifying the request features yes. However, it's certainly the case that the decision to allow the upgrade feature can be made once per process, since it's not possible to enable the WebSockets module or upgrade the OS while the process is running ;). So yeah, it would be in the `IISHttpContext` that you would remove the feature, but you could use a global static variable to determine it.
