### ISSUE TITLE
[ERROR?] VaryByHeader rewrite by IIS (tested on 8.5 and 10) but ok for Kestrel and Azure

### ISSUE THREAD

**Issue by JTOne123** [aspnet/IISIntegration#590]
I have next code in my app

```
            services.AddMvc((options) =>
            {
                options.CacheProfiles.Add("DefaultAPI", new CacheProfile()
                {
                    Duration = 1 * 60 * 60,
                    Location = ResponseCacheLocation.Any,
                    VaryByQueryKeys = new[] { "test" },
                    VaryByHeader = "locale"
                });
            })
```

When I run it locally on Kestrel or Azure everything is fine.
Response header is "Vary:locale,Accept-Encoding"

But when it runs in IIS, I'm getting only "Vary:Accept-Encoding"

I did a workaround via web.config, but it's not an ideal solution
```
<configuration>
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <clear />
        <add name="Vary" value="locale" />
```

Ideas?

**Comment by shirhatti** [comment]
Moving to discussion milestone since this is an IIS issue and not an ANCM issue.

**Comment by shirhatti** [comment]
@bariscaglar Thoughts?

**Comment by bariscaglar** [comment]
> VaryByHeader = "locale"

Is this the line that adds the header? Is the claim then IIS somehow removes this header? I don't see any reason why. Are we certain this is an IIS issue?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
