### ISSUE TITLE
MOF file needed for ANCM

### ISSUE THREAD

**Issue by jimmyca15** [aspnet/IISIntegration#592]
Going forward ANCM will have a Trace Provider registered with IIS. The trace provider will be accompanied by a mof file to be consumed by WMI. 

We should make sure to check in the mof file so that the installer and any other interested parties can place it as needed.

**Comment by pan-wang** [comment]
pull request #603 https://github.com/aspnet/IISIntegration/pull/603

**Comment by muratg** [comment]
Just fixed in dev.
