### ISSUE TITLE
[In-proc] An absolute path for dotnet.exe is detected as .NET Framework

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#593]
`processPath="C:\Program Files\dotnet\dotnet"` works but `processPath="C:\Program Files\dotnet\dotnet.exe"` fails with an event log `Application 'C:\inetpub\wwwroot\' was compiled for .NET Framework. Please compile for .NET core to run the inprocess application or change the process mode to out of process. ErrorCode = '0x8027025b'.`

Justin says the issue is here:
https://github.com/aspnet/IISIntegration/blob/release/2.1/src/CommonLib/hostfxr_utility.cpp#L101-L112

**Comment by jkotalik** [comment]
This is only an issue on dev.

**Comment by jkotalik** [comment]
I also should check the bitness of the hostfxr.dll loaded (for dev).

**Comment by Tratcher** [comment]
Confirmed, preview1 works fine, my issues were on dev. Preview1 can do either `C:\Program Files\dotnet\dotnet` or `C:\Program Files\dotnet\dotnet.exe`.
