### ISSUE TITLE
[in-proc] x86 app pools on x64 machines don't work

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#594]
Version: dev
OS: 2016 x64

Setting the application pool to 32bit prevents my application from running. The site hangs for a while and I may get a 500.0 error. No event logs are produced.

It works if I revert to the RTM aspnetcore.dll (out-of-proc), or if I remove `hostingModel="inprocess"` and go back to out-of-proc. Running the app from the command line with the x86 dotnet.exe also works.

**Comment by Tratcher** [comment]
Justing thinks this is related to how the path is search for the right bitness. Workaround: Re-ordering the system path environment so that x86 dotnet is higher than x64 dotnet. However, this prevents x64 form working.

**Comment by muratg** [comment]
Fixed in dev.
