### ISSUE TITLE
[in-proc] Standalone doesn't work

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#596]
For preview1-28285 standalone published apps are not loading in ANCM/IIS, you get a 500.0 error and the following logs:
- Application '/LM/W3SVC/1/ROOT' with physical root 'C:\inetpub\wwwroot\' failed to load clr and managed application, ErrorCode = '0x8027025b.
- Application '/LM/W3SVC/1/ROOT' with physical root 'C:\inetpub\wwwroot\' hit unexpected managed background thread exit, ErrorCode = '0x0.

Adding a direct dependency on M.A.Server.IIS gets aspnetcoreh.dll published with the app but that doesn't change the errors.

There are no stdoutlogs.

**Comment by jkotalik** [comment]
Fixed on dev already. Investigated in preview1 branch and all arguments to hostfxr look correct. Will investigate in the coming days.

**Comment by jkotalik** [comment]
@muratg As this only applies to preview 1 and was fixed in dev, can we close?

**Comment by muratg** [comment]
@jkotalik 👍
