### ISSUE TITLE
Configure AspNetCoreModule to Only Capture Requests Behind a Specified Relative Url

### ISSUE THREAD

**Issue by Xacron** [aspnet/IISIntegration#598]
I have an ASP.NET Core site (API only, no content) targeting .NET Framework 4.7.1 with IIS Integration enabled in Visual Studio 2017.

I am trying to restrict the AspNetCoreModule handler to only handle requests below a specified path, "api/*". Here is the web.config excerpt:

```
<system.webServer>
    <handlers>
      <add name="aspNetCore" path="api/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
```
Unfortunately, the dotnet.exe process fails to start with a 405 error, which is actually coming from IIS Static File module. 

![image](https://user-images.githubusercontent.com/14314527/36397087-1af8735e-158f-11e8-8c64-dcf34bd87bfd.png)

![image](https://user-images.githubusercontent.com/14314527/36396937-6a0358e8-158e-11e8-88af-520310e1ddcd.png)

I need to keep the IIS Static File module because I am trying to use IIS to serve all requests that do not match the path "api/*" and use the ASP.NET Core Module only for ASP.NET API requests.

_I cannot use the ASP.NET Static File middleware because it is painfully slow and does not even come close to meeting typical SLAs for serving static files._

Is this configuration possible with ASP.NET Core?

**Comment by Tornhoof** [comment]
@RickStrahl hast a Blog Post in how to configure it. https://weblog.west-wind.com/posts/2017/Apr/27/IIS-and-ASPNET-Core-Rewrite-Rules-for-AspNetCoreModule

**Comment by Xacron** [comment]
@Tornhoof thanks for link, I have actually read Rick's post the key difference is that he is trying to maintain handling all requests by ASP.NET Core and redirecting only specific static files so that IIS serves those. However, I am trying to setup ASP.NET Core to only handle requests directed to api/* paths and for some reason this does not seem to be possible. I do not need ASP.NET Core involved in handling any requests that are not to api/* paths. Do you know if this is possible?

It seams like I should be able the configure the ANCM to handle only requests for api/* but this causes the system to choke.

**Comment by Tornhoof** [comment]
I honestly don't know. I set my static file handling up like Rick describes it. In another post https://weblog.west-wind.com/posts/2017/Mar/16/More-on-ASPNET-Core-Running-under-IIS he basically says the API/* approach does not work, because the content root is now in wwwroot and not in Root anymore.

**Comment by Xacron** [comment]
My content is actually not under wwwroot, one more reason why I do not want the ANCM handling all requests. I only need it to handle api/* requests, but the tooling doesn't seem to like changing the path for the ANCM handler to api/*

I can actually change the path to "*." and that works fine except then I'd have to still do a url rewrite to map "/" to "/index.html"

It seems like if I only want to use ASP.NET Core for API requests the tooling should work with the path set to api/*

**Comment by Tratcher** [comment]
Are you starting it under the debugger (F5) or not (CTL+F5)? The debug tooling sends a DEBUG requests to warm up the application.

**Comment by Xacron** [comment]
I'm starting it under debugger (F5) and this is exactly what I'm running into, some initial request that isn't correctly handled when ANCM is restricted to handling only api/* requests. 

Does this mean I cannot use F5 debugging unless the ANCM handles all requests?

**Comment by Tratcher** [comment]
No, it means you need to configure one of your handlers to accept the DEBUG verb. This worked for me:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore0" path="*" verb="DEBUG" modules="AspNetCoreModule" resourceType="Unspecified"/>
      <add name="aspNetCore" path="api/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Comment by Xacron** [comment]
Awesome, this works great! My resulting web.config is below. 

Can you explain what's happening with the DEBUG verb request, is it being ignored now or is it actually being handled by the same instance of the ANCM?

```
<system.webServer>
 <handlers>
   <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
   <remove name="OPTIONSVerbHandler" />
   <remove name="TRACEVerbHandler" />
   <remove name="aspNetCore" />
   <add name="aspNetCoreDebug" path="*" verb="DEBUG" modules="AspNetCoreModule" resourceType="Unspecified" />
   <add name="aspNetCore" path="api/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
 </handlers>
 <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" forwardWindowsAuthToken="false" stdoutLogEnabled="false" arguments="-argFile IISExeLauncherArgs.txt" />
</system.webServer>
```

**Comment by Tratcher** [comment]
It's being handled here:
https://github.com/aspnet/IISIntegration/blob/71b90a31a9dc72054d3ab1ba5123945e629fb74d/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L88-L93

**Comment by Xacron** [comment]
With this web.config definition is there still just a single instance of ANCM or does multiple handler entries create multiple ANCM instances to handle requests?

I expect of course that this should be cleaned up when publishing for production.

**Comment by Tratcher** [comment]
@pan-wang would this get you a single instance or multiple?

**Comment by pan-wang** [comment]
The module will be singleton. IIS jus put the module reference into the pipeline. IIS should chose the right handler based on the configuration and only one handler should be picked up at MapHandler. FREB log should be able to confirm it. If it is not the case, please let me know. It would be a bug in IIS.

**Comment by Xacron** [comment]
Thanks for resolution and the extra info.
