### ISSUE TITLE
ANCM: warning message which happens when failing to create log directory is ambigous

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#599]
1.	Enable logging
2.	Create a file named logs on the root directory to make ANCM fails to create logs directory
3.	Send a request and check the message of event warning #1004

EXPECTED:

The warning message include the information that ANCM fails to create the "logs" directory path.

ACTUAL:

The below warning message is shown. The actual reason of the failure is to fail to create log directory but the message is saying that it fails to create file, which is too general to figure out the reason of the problem.

Warning: Could not create stdoutLogFile , ErrorCode = '0x80070003'.

**Comment by shirhatti** [comment]
I believe this fixed by #602 
@jhkimnew Can you confirm and close?
