### ISSUE TITLE
Unable to run the sample with iis express

### ISSUE THREAD

**Issue by Kagamine** [aspnet/IISIntegration#6]
![image](https://cloud.githubusercontent.com/assets/2216750/10182990/5b2e053e-675d-11e5-8d8f-90d55b1de16d.png)

```
{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.0.0-beta8-15654"
  }
}
```

**Comment by Eilon** [comment]
Helios (the previous IIS integration stuff) no longer works with IIS. Which packages are you using in the project.json?

**Comment by Tratcher** [comment]
The beta7 tooling does not work with HttpPlatformHandler. We should have updated tooling out in a week or so.
