### ISSUE TITLE
ANCM: Setup: Msi files are not signed

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#607]
Files in MSI installer program are signed. But the MSI installer program itself is not signed.

**Comment by jkotalik** [comment]
@jimmyca15

**Comment by jimmyca15** [comment]
I'll sync up with @natemcmaster on how we can get this done.

**Comment by natemcmaster** [comment]
Dup of https://github.com/aspnet/Coherence-Signed/issues/778. @muratg is currently assigned to take a look at this.

**Comment by muratg** [comment]
Pinging @jimmyca15

**Comment by jkotalik** [comment]
Closing as dup.
