### ISSUE TITLE
Inproc: Arguments must not include "exec" if exec was already in the launcher arguments

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#609]
@BillHiebert and I ran into two issues when we parse arguments from the "arguments" section of web.config. 
- Bill was supplying the "exec" parameter in the arguments section, which we added too, and it was causing hostfxr to not start. For now, I think we can just not add "exec" as it isn't necessary. 
- There is no guarantee on which arguments is the path to the application dll, which we need to modify to be an absolute path if it isn't. I will check if the string ends with .dll.
@muratg this is higher priority as it is a blocking issue for Bill and is a change to the shim.

**Comment by muratg** [comment]
👍 but what's the risk? 

cc @shirhatti

**Comment by jkotalik** [comment]
Risk is Bill would need to custom provide arguments for inprocess to not have exec there. Also people who supply their own arguments in web.config could run into issues. I need to talk with the core-setup team about diagnosiblity of this issue because we don't get logs for invalid arguments.

**Comment by muratg** [comment]
🎉
