### ISSUE TITLE
Request hangs intermittently for no logged reason

### ISSUE THREAD

**Issue by joshmouch** [aspnet/IISIntegration#611]
Several times a day, there are requests in our Azure Web App that hang for 10 minutes before logging an error from AspNetCoreModule to our FREB logs.   This is a "relatively" quick request, and usually takes between 150ms to 1.5s.  So 10 minutes is definitely a problem.

10 minutes is what we have the "requestTimeout" property set to on the AspNetCoreModule, so put another way, the request hangs for as long as we have the "requestTimeout" set to.

The error in the FREB log looks like this:

> ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="400", HttpReason="Bad Request", HttpSubStatus="0", ErrorCode="An existing connection was forcibly closed by the remote host. (0x80072746)", ConfigExceptionInfo=""

The web.config contains:

```
<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" 
		            stdoutLogEnabled="true" 
		            stdoutLogFile="\\?\%home%\LogFiles\aspnetcore-stdout" 
		            forwardWindowsAuthToken="false" 
		            requestTimeout="00:10:00" />
```

Looking at the stdout log, there is nothing logged for that process during this time.
There is nothing logged in the Windows Event "Application Events".

Last thing of note (which I don't know if it's related or not) is that we do have both the Application Insights Profiler enabled on the App Service and the Application Insights Snapshot Collector enabled.  These both seem to be less than perfect, as they both occasionally throw unrelated errors here and there.  So I thought them worth mentioning.

**Comment by shirhatti** [comment]
@joshmouch From the information you've provided there's nothing to indicate erroneous behavior. It sounds like a request is actually taking 10 minutes and hitting the request time out.

Can you provide some more information? Could you perhaps capture a dump of dotnet.exe process during this "hung" request.

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.
