### ISSUE TITLE
failed to start process with commandline ErrorCode = '0x80070002 IIS

### ISSUE THREAD

**Issue by Jamie-Vangeysel** [aspnet/IISIntegration#616]
failed to start process with commandline 'dotnet v2.dll', ErrorCode = '0x80070002 : 0.

Running the command in cmd gives no error
C:\Websites\Deploy\api.groupclaes.be\secure>dotnet .\v2.dll
Hosting environment: Production
Content root path: C:\Websites\Deploy\api.groupclaes.be\secure
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

In order to have a better idea of what could be wrong i turned on logging but these 0kB log files don't help either ...

![image](https://user-images.githubusercontent.com/32323785/36736542-31af8d6c-1bd9-11e8-8865-584d2d02675e.png)

**Comment by jkotalik** [comment]
Do you have any logs in your windows event viewer? The error you are getting is a FILE_NOT_FOUND from ANCM. Confirm your web.config has the correct paths to dotnet.exe?

**Comment by Jamie-Vangeysel** [comment]
Yes, The first line is from The event viewer,
This is my web.config:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\v2.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>`
and the file directory:
![image](https://user-images.githubusercontent.com/32323785/36773429-e2613a54-1c59-11e8-8887-ac5897fd51b1.png)

how do you mean  the correct paths to dotnet.exe? there is a path variable, if u just open a cmd window in the folder in that directory it works fine

**Comment by Jamie-Vangeysel** [comment]
@jkotalik `processPath="C:\Program Files\dotnet\dotnet.exe"` seems to do the trick, thanks ;)

**Comment by ckrandhir** [comment]
![image](https://user-images.githubusercontent.com/27824830/42832173-04869cc2-89b6-11e8-9c99-2ef8b01dfb62.png)

I am getting this event log

**Comment by srinudhulipalla** [comment]
changing to processPath="C:\Program Files\dotnet\dotnet.exe" in web.config work to me. Not sure why IIS didn't pick the path.

**Comment by rzavolly** [comment]
As long as you have full x86 and 64-bit paths to dotnet in your OS environment just add .exe to your config line like so --> processPath="dotnet.exe" - you don't have to specify a full path to the executable in the web.config.  That worked for me.

**Comment by ewolution94** [comment]
> changing to processPath="C:\Program Files\dotnet\dotnet.exe" in web.config works to me as well. Not sure why IIS didn't pick the path.

Thank you so much! This worked for me too. Also, the [comment](https://github.com/aspnet/IISIntegration/issues/623#issuecomment-369805097) from user "Tarhesabz" for an issue with permissions on the IIS helped a lot.

**Comment by Thomasrnunez** [comment]
I've tried all the possible solutions that helped others from this form post but nothing worked for me.
If you do all of the above and still see the same issue then open a command prompt window and navigate to your project and run "dotnet <dll from webconfig>".  If you see an error like the one shown in this link: https://helpx.adobe.com/download-install/kb/error_on_launch.html

Then go to this link and download the right file for your OS and you application should startup.
