### ISSUE TITLE
failed to start process with commandline 'dotnet .\CVC.dll', ErrorCode = '0x80070002 : 0.

### ISSUE THREAD

**Issue by Tarhesabz** [aspnet/IISIntegration#623]
This is my first attempt at deploying ASP.NET Core on our server that's running a ASP.NET Web App on .NET Frameword 4.6.1. I created a new project in Visual Studio 2017 and published it using webdeploy. After browsing to the page I get the following error:

**HTTP Error 502.5 - Process Failure**

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

There's not much information in event viewer logs:
Application 'MACHINE/WEBROOT/APPHOST/mysite' with physical root 'C:\Inetpub\vhosts\cvclegal.com\mysite\' failed to start process with commandline 'dotnet .\CVC.dll', ErrorCode = '0x80070002 : 0.

I have the new runtime installed for ASP.NET Core 2.0.5 and followed the instructions for hosting on IIS.
Here is my web.config that's generated after deployment:

`<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\CVC.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>`

and my program.cs:
`public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }`

I enabled the stdoutLogFile, for each request it does create a .log file but it's 0k and empty.

**Comment by rezord** [comment]
Try to install on your local IIS computer and your local servers to test what is wrong with that server!

**Comment by Tarhesabz** [comment]
I did and it works fine on our local server. I have this problem on a VPS server. Win Server 2012 R2 with IIS 8.5

**Comment by Tarhesabz** [comment]
In my case, it was the permission issue. I went to application pools, advanced settings and changed the identity to LocalStstem, and that fixed the problem.

**Comment by jkotalik** [comment]
@Tarhesabz we are actively working on improving diagnostics for why your application didn't start. We know it is frustrating to run into 502.5 errors like this. Did you look at the Windows Event Log on your computer? Did you see any messages from the IIS AspNetCore Module?

**Comment by Tarhesabz** [comment]
Yes, I did. I pasted the results in my original post. basically saying "failed to start process with commandline 'dotnet .\CVC.dll', ErrorCode = '0x80070002 : 0" 
and my app would run if I went to command prompt and entered "dotnet .\CVC.dll", it's just IIS didn't have the right permissions to do it itself. and I wasn't getting proper error message to be aware of that issue. 
But since I used Plesk to create a subdomain and a website, I suspected that it might have been insufficient user permission and exactly that was the problem.

**Comment by iyanitra** [comment]
Same issue happen to me, i just start learning asp.net core 2.1. i try using self hosted no issue, but when try host the app to iis got same error.

**Comment by jkotalik** [comment]
@iyanitra If you haven't already, I would check our docs on[ diagnosing startup errors with ANCM](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#troubleshoot-app-startup-errors). Specifically, I would check the windows event log and see if there are any logs there.

We are working on making diagnostics better in the 2.2 timeframe.

**Comment by iyanitra** [comment]
@jkotalik i found the issue after installation aspnetcore i never restart my computer, after restart no issue accessing via IIS. Thanks

**Comment by gardavis** [comment]
Thanks @iyanitra - reboot after Core install was the solution to the HTTP 502.5.

**Comment by C-BERBER** [comment]
I HAVE rebooted.. and still the same error. any other thoughts? thanks CB

**Comment by C-BERBER** [comment]
So... Ensure that your .CORE versions match from dev machine to the one on the server...

Then it is about permissions at the server for IIS to your webconfig in the pool...

https://success.trendmicro.com/solution/1098768-cannot-read-configuration-file-appears-on-http-error-500-19-when-accessing-the-worry-free-busin

Of Course replace Trend with your site...

**Comment by Thomasrnunez** [comment]
I've tried all the possible solutions that helped others from this form post but nothing worked for me.
If you do all of the above and still see the same issue then open a command prompt window and navigate to your project and run "dotnet ". If you see an error like the one shown in this link: https://helpx.adobe.com/download-install/kb/error_on_launch.html

Then go to this link : https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows and download the right file for your OS and you application should startup.
