### ISSUE TITLE
404 error for static files in inprocess mode. 

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#625]
UseResponseCaching() does not work with inprocess mode. 404 error happens with static files on wwwroot directory. 

Here is the example code of UseResponseCompression() and I attached the error message in log file when it fails. 

<><><> 
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
            app.UseResponseCompression();
            app.UseResponseCaching();
            app.UseDefaultFiles();
            app.UseStaticFiles();
...
<><><>

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost/aspnetcoreapp/default.htm
info: Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware[24]
      No cached response available for this request.
info: Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware[27]
      The response could not be cached for this request.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 25.1349ms 404

**Comment by Tratcher** [comment]
It says the response finished with a 404, it couldn't find the default file. This does not look like an issue with response compression.

**Comment by jhkimnew** [comment]
The reason of the problem seems to be on others.
Even without using the UseResponseCaching(), I got 404 error.
The 404 error happens only with inprocess mode. 
The static file is placed on wwwroot folder. There is no problem if I use outofprocess mode.

**Comment by Tratcher** [comment]
I wonder if the content root / current directory is wrong.

**Comment by jhkimnew** [comment]
Ah, probably that is the reason of the problem. I put test app binary files on a different directory path. I will  check that part again and make the repro step more clear.

**Comment by jhkimnew** [comment]
With testing again in inprocess mode, I confirmed this issue only happens with UseResponseCaching() and app.UseResponseCompression().

FYI,
I tested this again after putting the test app binary files on the same path of the IIS root path and the issue still happens. I also tested after copying the static files of wwwroot on the test app binary directory but the problem still happens.

**Comment by jkotalik** [comment]
@jhkimnew we can investigate if the site root path is being set correctly in managed. I currently set it to be the physical path to the application.

**Comment by jhkimnew** [comment]
@jkotalik He was able to reproduce this issue. This issue happens because we use ".UseContentRoot(Directory.GetCurrentDirectory())" as the following.
For some reasons, it works with outofprocess mode but it does not work with inprocess mode.

                    host = WebHost.CreateDefaultBuilder(args)
                        .UseConfiguration(config)
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseStartup<StartupCompressionCaching>()
                        .Build();

**Comment by jkotalik** [comment]
The issue is UseContentRoot(Directory.GetCurrentDirectory()) will point to the w3wp folder. We would need to set the current directory to be the application path before starting dotnet. We may be able to set the current working directory before calling hostfxr_main, however who knows what that could mess with with IIS.

**Comment by jkotalik** [comment]
The issue is UseContentRoot(Directory.GetCurrentDirectory()) will point to the w3wp folder. We would need to set the current directory to be the application path before starting dotnet. We may be able to set the current working directory before calling hostfxr_main, however who knows what that could mess with with IIS.

**Comment by Tratcher** [comment]
The good news is that you don't need to call UseContentRoot. CreateDefaultBuilder and UseIISIntegration both set it for you.

**Comment by shirhatti** [comment]
I'll create a doc bug to track this. Looks like there's no product change

**Comment by Tratcher** [comment]
Unless @jkotalik can change the way coreclr is launched to make GetCurrentDirectory point to the application directory.
