### ISSUE TITLE
ANCM: Inprocess: 502.5 error is not shown when app fails to start because of wrong process/argument path

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#627]
Under inprocess mode, 502.5 is not shown when app fails to start because of wrong process/argument path.

**Comment by jkotalik** [comment]
Are you suggesting this should be a 500?

**Comment by jhkimnew** [comment]
I am suggesting the same behavior when we use outofprocess.

**Comment by shirhatti** [comment]
Can you share repro `web.config` and what you observed in the event log?

**Comment by jhkimnew** [comment]
This issue turns out to be a known issue. Closing this issue as duplicated issue.
