### ISSUE TITLE
ANCM Isnt producing any logs for IIS Site serving 503 Error

### ISSUE THREAD

**Issue by phxvyper** [aspnet/IISIntegration#628]
my ANCM-enabled site is serving a 503 Error and isn't producing any logs, at all.

**I have:** 

- an EC2 instance running Windows Server 2016,
- the .NET Web Host Bundle installed (including the .NET Core 2 SDK),
- the AspNetCoreModule installed,
- a site in IIS10 and an app pool with no managed code,
- the following `BuildWebHost`:

```
  public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
      .UseKestrel()
      .UseIISIntegration()
      .UseStartup<Startup>()
      .Build();
```
- this web.config for ASP.NET Core 2 MVC in the sites root folder:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\ProjectOutput.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

**What works:**

- placing an `index.html` with any content in the root folder of the site.
  - the content of the file is served properly when I goto the site from an external network or computer.

**What doesn't work:**

- placing my published ASP.NET Core MVC site in the root folder of the site, serves a 500 Internal Server Error
- additionally, nothing is getting logged either.
- **EDIT**: It's actually a 503 Service Unavailable error with no information in the response from the server. It was a 500 Internal Server Error last week because i had a malformed web.config. That issue is fixed and it matches what you see above.

**What could I be missing that would cause my project to not start, without any logging?**

**Comment by Tratcher** [comment]
Anything in the event viewer?

This is a new machine setup, correct? Was the hosting bundle installed before or after IIS? If the bundle was installed first then you need to repair it after installing IIS.

**Comment by phxvyper** [comment]
Hey!

No errors in the event viewer, some warnings about not being able to delete a CFG file.

The bundle was installed post-IIS setup, yes. I've reinstalled the bundled multiple times just to make sure, no luck :/

I've followed microsoft's documentation on setting up this server pretty much to the tee, but I feel like I'm probably missing something ridiculously simple lol.

**Comment by phxvyper** [comment]
Heads-up, this error was a 500 Error because I had a malformed web.config.

Its actually a 503 Service Unavailable error now. The response from the server has minimal headers and no body - no information about the error and no logs other than a W3SVC log that the 503 occurred.

**Comment by phxvyper** [comment]
I moved over to an apache proxy instead of using IIS, but I still want to know what the solution to this problem is for future reference. Any ideas so far?

**Comment by pan-wang** [comment]
could you please check whether you had app_offline.htm file inside the application folder? if you browser the application from the server using localhost, the error page will give more details about the root cause.

**Comment by phxvyper** [comment]
@pan-wang unfourtunately I can't really check on this issue for a while. When some stuff slows down I'll be able to revisit this but for now I'm going to close my issue <3
