### ISSUE TITLE
HttpContext.Connection.IsLocal returns true when hosted in an Azure webapp

### ISSUE THREAD

**Issue by fermaem** [aspnet/IISIntegration#63]
Discovered on version 1.0.0-rc2-16357.

Following #17 and its fix, `HttpContext.Connection.IsLocal` returns `true` when ran a local computer. 

Unexpectedly, it also returns `true` when hosted in an Azure web app.

**Note:** In order to test this, I've patched the kudu generated `deploy.cmd` script to target a different dnx runtime and changed the `dnu restore` sources

**Comment by Tratcher** [comment]
https://github.com/aspnet/IISIntegration/pull/43

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/536
