### ISSUE TITLE
ANCM: Inprocess: Application recycling under IISExpress does not happen when there is configuration change or app_offline is put

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#632]
Application recycling under IISExpress does not happen when there is configuration change or app_offline is put. 

@pan-wang or @jkotalik Please take a look at this issue.

Repro:

1. Start aspnetcore app in inprocess mode with IISExpress
2. Start a websocket connection and keep the connection active
3. Put app_offline.htm on the root path of the app

EXPECTED:

The websocket connection is gracefully shutdown

ACTUAL:

The websocket connection is still active.

**Comment by jkotalik** [comment]
Fixed by #637

**Comment by jkotalik** [comment]
Can you verify?

**Comment by jhkimnew** [comment]
Yes, this is fixed. Verified with test automation.
