### ISSUE TITLE
Port collision issue

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#643]
This is an uber issue to track multiple port collisions issue that we've been seeing with ANCM out-of-process.
Often times, Kestrel is unable to bind to the port specified by ANCM as LibUV throws a `Error -4091 EADDRINUSE address already in use` error.

For e.g., see aspnet/KestrelHttpServer#2125

**Comment by shirhatti** [comment]
As **NOT** recommended workaround is to force a static port assignment by setting the ASPNETCORE_PORT environment variable. Feel free to use this if you're can guarantee that the ephemeral port you chose will always be available.

**Comment by halter73** [comment]
More context:

https://github.com/aspnet/AspNetCoreModule/issues/64
https://github.com/aspnet/AspNetCoreModule/issues/226
https://github.com/aspnet/AspNetCoreModule/issues/260

**Comment by shirhatti** [comment]
@pan-wang Can you verify that we log the port when we fail to bind?

**Comment by pan-wang** [comment]
In some cases,  we did not.  Will update the logging code.

**Comment by jkotalik** [comment]
@mikeharder assigning to you for visibility of similar issues.

**Comment by shirhatti** [comment]
Closing since we have separate issues tracking retry.
