### ISSUE TITLE
Under stress, calling into hostfxr_get_native_search_directories can AV.

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#645]
For stress testing purpose, I did connect/close websocket repeatedly and noticed connecting websocket fails. After the problem happens, if we recycle IIS worker process, I got CLR exception error. 

@jkotalik Please take a look at this issue.

**Comment by jkotalik** [comment]
I did the same repo scenario on my machine and I didn't see any issues. Can you try and debug attach and get a dump of why the connection is not being processed? I would set a break point in the OnExecuteReqeustHandler in proxymodule.cxx and see if once the server is in an invalid state (requests are rejected), if we enter the OnExecuteRequestHandler at all.

**Comment by shirhatti** [comment]
Only thing left to do here is verify that it's already been fixed.

**Comment by muratg** [comment]
@shhsu  We're closing this one -- if we see this again, please reopen!
