### ISSUE TITLE
Question: how can I ensure the app is running in process?

### ISSUE THREAD

**Issue by ilmax** [aspnet/IISIntegration#667]
Hi, I've read the blog post about [preview1](https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-0-preview1-improvements-to-iis-hosting/) and I decided to give it a try, so I installed everything and created a web api project, configured in IIS and fired up `wrk` (installed in the same machine via WSL) to have a look at the perf.
The blog post says your findings are that in process delivers up to **4.4x** request throughput, but my numbers are a bit different i.e. the numbers are almost identical to the out of process ones so I would like to be sure I'm not missing something.

The api I used for the test is the `ValuesController` GET method generated by the template which returns a fixed `"value"` string.

What I find strange is that while performing the in process tests, I still saw a `dotnet.exe` process.
 
If you are interested in the numbers, you can find them [here](https://gist.github.com/ilmax/f5dfe6835d9215109b3fb7ba3702fef8)

**Comment by Tratcher** [comment]
You can check for server variables, those are only supported in-proc.
https://github.com/aspnet/IISIntegration/blob/810c4bcb0a29fb5f273a0c2b26b37e4ee431d05c/samples/NativeIISSample/Startup.cs#L67-L72

**Comment by jkotalik** [comment]
From those perf numbers and the fact that dotnet.exe is starting, my guess is you are still running of of process. Can you confirm inside of your published application that the hostingModel="inprocess" is set?

**Comment by ilmax** [comment]
What's in the gist under "IIS ANCM 2.1 preview1 hosting in process" have **hostingModel="inprocess"** and "IIS ANCM 2.1 preview1 hosting out of process" doesn't have the hostingModel attribute at all

**Comment by jkotalik** [comment]
You can also specify the hostingModel="outofprocess" to work with out of process. If no hostingModel is specified, we default to outofprocess. This is for backwards compatibility with older web.config files.

@BillHiebert I think we should default to having the hostingModel="outofprocess" for generated web.config files rather than it being empty. Thoughts?

**Comment by Tratcher** [comment]
That would fail on hosts with outdated schemas.

**Comment by ilmax** [comment]
I will look into this tomorrow morning.
Do you think it's reasonable to expect a noticeable improvements when running in-process?

**Comment by jkotalik** [comment]
Yes. If you don't see noticeable gains, we need to investigate why.

**Comment by ilmax** [comment]
Great, because I'm experimenting perf to replace an old WCF service with a brand new shiny asp.net core web api :)
So I started measuring perf of the old WCF vs the new asp.net core web api and turned out that asp.net core hosted in Kestrel outperforms WCF hosted in IIS Express (+1139%) but when hosted in IIS, asp.net core is actually slower (don't remember now how much slower, but if you are interested I can get back on this) than WCF and the latency is higher

**Comment by Tratcher** [comment]
That's odd, you shouldn't get that much variation between IIS and IIS Express.

**Comment by ilmax** [comment]
I'll get back with more numbers tomorrow, btw @Tratcher what do you think about a ~5 times drop from Kestrel to IIS out of process?

**Comment by ilmax** [comment]
Looks like `context.GetIISServerVariable` is not available in my version of `Microsoft.AspNetCore.Server.IISIntegration`. it's a bit strange because I can see the extension method on the repo but definitely not in my dll (checked with ILSpy).

The project file looks like this:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.1.0-preview1-final" />
  </ItemGroup>
```

Any idea of what am I missing?

**Comment by pan-wang** [comment]
@ilmax Do you test with IIS or IISExpress/VS? For IIS, could you please check whether aspnetcorerh.dll exists under %windir%/system32/inetsrv folder?

**Comment by ilmax** [comment]
@pan-wang I'm not able to make the code compile because the method `context.GetIISServerVariable` is not available

**Comment by Tratcher** [comment]
@ilmax sorry, I just realized GetIISServerVariable wasn't added until preview2 https://github.com/aspnet/IISIntegration/pull/562

**Comment by jkotalik** [comment]
Try checking the current name of the running process: https://stackoverflow.com/questions/616584/how-do-i-get-the-name-of-the-current-executable-in-c
If it is w3wp or iisexpress, you are running inprocess.

**Comment by ilmax** [comment]
ok, will re-try to run the benchmark tomorrow. One last question: do the dotnet.exe process should be up & running when hostingModel is in-process?

**Comment by jkotalik** [comment]
>  dotnet.exe process should be up & running when hostingModel is in-process?
No, it shouldn't be present.

**Comment by ilmax** [comment]
Thanks, so the numbers make sense because when I was measuring perf with hostingmodel in-process, dotnet.exe was running, this means it wasn't running in-process and explains why I got almost same results.

**Comment by ilmax** [comment]
> @ilmax Do you test with IIS or IISExpress/VS? For IIS, could you please check whether aspnetcorerh.dll exists under %windir%/system32/inetsrv folder?

@pan-wang  No, looks like it's not here! I've just have aspnetcore.dll

**Comment by ilmax** [comment]
Ok, sorted it out, it was an install issue. I've updated the gist with real numbers and looks like the inprocess version on my machine is **342%** faster on my machine

**Comment by jkotalik** [comment]
That's much more expected. I think our tests were running on beefier hardware. IIRC we saw ~30k req/sec for out of process, and 135k req/sec for in proc.

**Comment by ilmax** [comment]
Great! Thank you guys for your help!

**Comment by ilmax** [comment]
Great! Thank you guys for your help!
