### ISSUE TITLE
Remove X-IIS-WindowsAuthToken

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#67]
This changed between HttpPlatformHandler v1.2 and 1.3 form X-IIS-WindowsAuthToken to MS-PLATFORM-HANDLER-WINAUTHTOKEN. Remove the old one after RC2.
https://github.com/aspnet/IISIntegration/pull/66

**Comment by muratg** [comment]
Why RTW?

**Comment by Tratcher** [comment]
Compat bridge. Otherwise you have to update HttpPlatformHandler and AspNet in lockstep.

**Comment by muratg** [comment]
Moving back to RC2 because of the recent schedule changes. If needed, we'll move it out again.

**Comment by Tratcher** [comment]
Merged with #96
