### ISSUE TITLE
Investigate app_offline AV when shutting down application.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#671]
I remember running into an AV when we set the m_pApplication to null in the ApplicationInfo. I'm going to do a quick investigation to verify that either the AV is gone or there is still an issue.

**Comment by jkotalik** [comment]
@pan-wang @jhkimnew I couldn't reproduce any issues with app_offline. Do you two remember what situation caused app_offline to AV?

**Comment by pan-wang** [comment]
Jeong hit this issue with your private repro which had old code. I don't think it repro with the new code. Jeong can confirm it

**Comment by jhkimnew** [comment]
This issue is already fixed.
