### ISSUE TITLE
Make it easier to detect if the application deployed is running inprocess.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#674]
There have been some issues (#667) regarding detection of running inprocess or out of process. Current means are fairly arbitrary (detecting the IServerVariableFeature, checking current process name). I would like there to be a clear way of discovering which mode you are running as in managed code.

**Comment by Tratcher** [comment]
Careful, we don't want to add something like a IFeature that specifically says InProc. What's the simplest, most definitive way to detect in proc? The process name approach sounds reliable.
