### ISSUE TITLE
ru-by is an invalid culture identifier exceptions on iis

### ISSUE THREAD

**Issue by NGancevich** [aspnet/IISIntegration#680]
It's working on my local machine but doesn't on IIS server 2012 r2. I have asp.net core 2.0.6 . It's also valid culture according to microsoft https://msdn.microsoft.com/en-us/library/cc233982.aspx

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
