### ISSUE TITLE
Will URL rewriting still work?

### ISSUE THREAD

**Issue by villanus** [aspnet/IISIntegration#69]
Just curious if going through IIS can we still use URL rewrite rules?

**Comment by davidfowl** [comment]
Yes you can, here's an example https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/wwwroot/web.config#L8

**Comment by wpostma** [comment]
This is not working in rtm. Opening new issue.

**Comment by Tratcher** [comment]
"IsFile" conditions are the only part that we know have issues, depending on your project layout. They assume the files are in the same folder as the web.config.

**Comment by wpostma** [comment]
I'm having issues trying to use the IIS extension "URL rewrite" to rewrite URLs.  The results when trying to have more than one dotnet core application within a single app pool,  and using URL rewrite rules, is  HTTP 500.19 error, either Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'aspNetCore', or that it can't find web.config).   I assumed it might be incompatibility of URL Rewrite with the IIS-kestrel-reverse-proxy deal.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/BasicMiddleware/issues/43#issuecomment-233044629
