### ISSUE TITLE
Clarify response wire protocol details, buffering, chunked, content-length, etc.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#7]
When proxying behind IIS/Express there are a few un-expected side-effects. We need to at least document these, but also consider how to work around them if needed. See the affected tests in Universe\ServerTests\test\ServerComparison.FunctionalTests\ResponseTests.cs
1. Buffering vs streaming - what buffering is done by the platform handler or by default IIS scenarios? How can be enable full streaming?
2. Chunked vs Content-length - as a result of the default buffering, chunked responses are converted to content-length.
3. Connection: close - This only appears to close the connection between the proxy and the back-end server, it does not close the connection with the client.

**Comment by Tratcher** [comment]
@davidfowl

**Comment by muratg** [comment]
@Tratcher we can move out if needed.

**Comment by davidfowl** [comment]
@Tratcher Let's get a meeting with the http platform handler guys to go over this after we verify all of the behaviors.

**Comment by avanderhoorn** [comment]
Any chance anyone knows what the current buffer size is?

**Comment by Tratcher** [comment]
@avanderhoorn My testing shows the buffer is 8kb.

**Comment by avanderhoorn** [comment]
Huge thanks!

**Comment by Tragetaschen** [comment]
Just a quick summary from aspnet/Tooling#359:

This largely affects SignalR (in this case 2.2) hosted within ASP.NET 5 for example on Azure, since the only viable transport option is Long Polling. Without further tweaks, this fallback is only chosen by a client after a five second timeout.

**Comment by Tratcher** [comment]
The next version of HttpPlatformHandler (v1.3?) has disabled its internal buffering.

**Comment by avanderhoorn** [comment]
Great to hear. When is the rough eta for it to drop?

**Comment by Tratcher** [comment]
This as been fixed in AspNetCoreModule v0.8: https://github.com/aspnet/IISIntegration/issues/105.

The only un-expected behavior remaining is that specifying `Connection: close` from Kestrel closes the connection between Kestrel and IIS but not the connection between IIS and the client. That's appropriate per the protocol, so we'll leave it.
