### ISSUE TITLE
Get IIS Version

### ISSUE THREAD

**Issue by lillo42** [aspnet/IISIntegration#704]
Hi,

Is possible get IIS version? How can I get this information?

**Comment by Tratcher** [comment]
Not with the out-of-process model ANCM uses today. What do you need it for?

Note the IIS version is coupled to the OS version, so you could infer it.

**Comment by lillo42** [comment]
In my company we are create a web applications monitor and one of these information is IIS Version, but I think is better get Kestral Version.

How could I infer it?

**Comment by Tratcher** [comment]
The IIS version is linked to the OS version: https://en.wikipedia.org/wiki/Internet_Information_Services

Getting the kestrel version is more interesting. You could get it from the assembly attribute AssemblyInformationalVersion.

**Comment by lillo42** [comment]
Thanks,

**Comment by shirhatti** [comment]
Just wanted to add that if you're running in-proc, you have access to IIS Server Variables.
The `SERVER_SOFTWARE` server variables will have what you want
