### ISSUE TITLE
Question: IIS Reverse Proxy(AAR) vs ANCM

### ISSUE THREAD

**Issue by samcov** [aspnet/IISIntegration#706]
Do both work equally as well, with the main ANCM advantage being the ability to restart your process?

**Comment by Tratcher** [comment]
ANCM also has tighter integration for things like WindowsAuth, forwarders, etc.. With ARR you would need to do more manual configuration of the back-end app.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
