### ISSUE TITLE
"HTTP Error 502.5 - Process Failure" asp.net core error in Azure From VSTS

### ISSUE THREAD

**Issue by mihaj** [aspnet/IISIntegration#707]
I have a problem with deploying from VSTS to Azure Web App for NET CORE 2.0 app (my app use 2.0.6.). I get the well known HTTP Error 502.5 - Process Failure. **Funny thing is that it works if I deploy from Visual Studio.** And it's installed in West Europe region.

The Kudu shows this:

> D:\home\site\wwwroot>dotnet --info
> .NET Command Line Tools (2.1.101)
> 
> Product Information:
>  Version:            2.1.101
>  Commit SHA-1 hash:  6c22303bf0
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x86
>  Base Path:   D:\Program Files (x86)\dotnet\sdk\2.1.101\
> 
> Microsoft .NET Core Shared Framework Host
>   Version  : 2.0.6
>   Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

If I try to run:

> D:\home\site\wwwroot>dotnet My.API.dll
> 
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at My.API.Program.BuildWebHost(String[] args) in D:\vsts-agent-win-x64-2.129.1\_work\1\s\My.API\Program.cs:line 15
>    at My.API.Program.Main(String[] args) in D:\vsts-agent-win-x64-2.129.1\_work\1\s\My.API\Program.cs:line 1

I tried re-deployment, compared web.config, deps.json file, appSettings.json and all looks ok. Any ideas?

**Comment by shirhatti** [comment]
![vsts-enable-appoffline](https://user-images.githubusercontent.com/4734691/37736765-00010c72-2d0f-11e8-9b9a-2902f1f9e1f2.png)

Have you enabled the app_offline rule?

**Comment by mihaj** [comment]
I have this in my deploy:

![image](https://user-images.githubusercontent.com/557954/37737711-f15fd130-2d54-11e8-8cc4-ae6368464e90.png)

**Comment by shirhatti** [comment]
The fact you don't have the Publish using Web Deploy chosen is throwing me off. Are you using WebDeploy?

**Comment by mihaj** [comment]
I turned it ON, but still no luck. I compared the two zipps, and the one build with VSTS has more DLLs in than the one from VS2017.

Here is my publish step:
![image](https://user-images.githubusercontent.com/557954/37758200-a14ed334-2daf-11e8-8050-601e63bed157.png)

**Comment by mihaj** [comment]
Just fixed this issue. I have to add "Path to projects(s)" csproj file of the exact project. Then it worked, because all test projects were not included in the publish!
