### ISSUE TITLE
ANCM: Inprocess: Usability issue: No helpful error message when inprocess mode is used to old apps which does not support inprocess mode

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#717]
@jkotalik Please take a look at this issue.

@pan-wang found a usability issue yesterday. As far as I remember, the issue Pan found is like this.

1.	Deploy an app which used .NetCore v2.0 in out-of-process
2.	Verify it works
3.	Switch to inprocess mode
4.	Send a request

EXPECTED:

Users should be able to get a meaningful error to troubleshoot the issue. 
Maybe we should add a new event that the app fails to start because it uses old version SDK, which does not support inprocess-mode. 

ACTUAL:

No proper error message or information in the log file.

**Comment by shirhatti** [comment]
I'm closing this issue, since the expectation is that all 2.2 apps support in-process, so there shouldn't really be a usability concern any longer.
