### ISSUE TITLE
Ordering issues with calling UseIISIntegration and UseKestrel (or other server implementations)

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#729]
Today, UseIISIntegration() can only be called once and will be overwritten by other calls that add an IServer implementation. So for example, the following code will break and use Kestrel instead of IISHttpServer:

```C#
 public class Program
{
    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
               .UseKestrel(a =>
               {
                   a.Limits.MaxRequestBodySize = null;
                   a.AddServerHeader = false;
               })
               .UseStartup<Startup>()
               .UseIISIntegration()
               .Build();

    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }
```

CreateDefaultBuilder will call UseKestrel() and then UseIISIntegration(). Then, by calling UseKestrel again, we will override UseIISIntegration. The next call to UseIISIntegration will be blocked by: https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L38.

I see two ways we can go about this:

1. Let UseIISIntegration be called multiple times for inprocess. This matches other server behavior and follows the "Last call wins" design we follow. However, this would mean code for inprocess vs out-of-process would be different.
2. Modify Kestrel's behavior to do a TryAdd instead of overriding whatever server is there.

**Comment by muratg** [comment]
Triage: we decided to go with (1) -- we'll identify the mode we're in, probably by detecting the request handler's existence.

**Comment by Tratcher** [comment]
That's a weak fix, it assumes IISIntegration is called twice.

**Comment by shirhatti** [comment]
Justin and I spoke about how UseIISIntegration() gets added regardless of whether you call it because of HostingStartup. Adding this comment here, so it doesn't get forgotten during our design meeting.

**Comment by muratg** [comment]
Do we need a design meeting for this? @shirhatti  could you add a label / scheule the meeting if so?

**Comment by jkotalik** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/2440

**Comment by Tratcher** [comment]
@jkotalik file the matching HttpSys bug and close this issue.

**Comment by Tratcher** [comment]
This will be addressed by https://github.com/aspnet/IISIntegration/issues/741.
