### ISSUE TITLE
Investigate test flakiness on AppVeyor

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#734]
Tests return 500 occasionally, like https://ci.appveyor.com/project/aspnetci/iisintegration/build/1.0.577#L749. We need to see if tests fail like this on CI or locally and find why it is happening.

**Comment by Eilon** [comment]
Also consider switching to dotnet-ci and avoid AppVeyor (though the test might be just as flaky there).

**Comment by shirhatti** [comment]
Given that we're moving off Appveyor, I'm closing this
