### ISSUE TITLE
Make UseIISIntegration override IServer on every call

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#741]
Same behavior as other servers.

**Comment by Tratcher** [comment]
Also ContentRoot. See https://github.com/aspnet/IISIntegration/issues/727

**Comment by pakrym** [comment]
I would argue that we should let it fail and allow customers to discover that CurrentDirectory is not what they expected when running inproc.  Also, document this in migration guide.

**Comment by Tratcher** [comment]
Assigning @pakrym all future in proc bug reports for ContentRoot....

**Comment by pakrym** [comment]
@Tratcher what if we add a warning log to our startup filter that would check if the content root is set to current directory?

**Comment by Tratcher** [comment]
Feel free to log it, so long as you fix it as well.

**Comment by Eilon** [comment]
@muratg / @pakrym / @Tratcher - is this a must-have for Preview2? If not, let's move to RC1.

**Comment by pakrym** [comment]
Done, https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IIS/WebHostBuilderIISExtensions.cs#L38
