### ISSUE TITLE
Finalize installer story for 2.1

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#754]
2. How are we delivering these binaries to WindowsHostingBundle universe build step??
3. Where are installers produced by WindowsHostingBundle universe step delivered and who consumes them?
4. Are we going to produce preview installer? As part of universe? Naming?

**Comment by shirhatti** [comment]
Related https://github.com/aspnet/WindowsHostingBundle/issues/18

**Comment by shirhatti** [comment]
and https://github.com/aspnet/WindowsHostingBundle/issues/1
