### ISSUE TITLE
Could not redirect to correct path using RequireHttpsAttribute and IIS with IISIntegration.

### ISSUE THREAD

**Issue by Anduin2017** [aspnet/IISIntegration#757]
dotnet core version:
```
2.1.103
```

Visual Studio Version
```
15.6.4
```

1, Create a new asp.net core project using Visual Studio.
2, Click the property of the project and enable https in IIS debug settings.
3, Create a RequireHttpsAttribute on Home controller.
4. Start the web application.

You will be redirected to `https://localhost` and get a 404 error.

**Comment by Anduin2017** [comment]
I guess this was a problem in the IISIntegration for our web application could not realize that it was not running in the 443 port.

**Comment by Tratcher** [comment]
RequireHttpsAttribute isn't aware of the ports your system is running on, it defaults to 443. There is a buried option where you can set the port. 
https://github.com/aspnet/Mvc/blob/8e323a8e1e78b520e9a1c2a5a5f64139d5c210d0/src/Microsoft.AspNetCore.Mvc.Core/MvcOptions.cs#L355

We're working to replace this in 2.1 with a middleware that is more aware of your environment and redirects to the correct port. Give the preview a try and let us know what you think.

**Comment by Tratcher** [comment]
@BillHiebert our 2.1 Https everywhere story doesn't include full IIS debugging does it?

**Comment by BillHiebert** [comment]
You need to configure the certificate manually using inetmgr
