### ISSUE TITLE
SxS story for ANCM

### ISSUE THREAD

**Issue by pan-wang** [aspnet/IISIntegration#758]
ANCM current is global singleton. Theoretically we can ship multiple versions of ANCM and configure IIS with different module name or condition (as webengine for different .net version). If we choose this direction, the requesthandler assembly then can be part of application no matter of in-process or out of process.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/specs/issues/154

**Comment by shirhatti** [comment]
Tracked elsewhere
