### ISSUE TITLE
502 Bad Gateway - can we get a stack trace / exception?

### ISSUE THREAD

**Issue by Eilon** [aspnet/IISIntegration#76]
Copied from https://github.com/aspnet/Mvc/issues/3967

------------------

From @joshmouch:

Sometimes when I write bad code, DNX/MVC/ASP.NET 5 will stop responding correctly (either with the expected page or else with the DeveloperException page), and instead, give me a 502 Bad Gateway.  Up until now, I think this has always been when there is a StackOverflowException (i.e. an infinite loop somewhere).

However, I just added some code that I'm pretty sure isn't causing an infinite loop, but it's still causing ASP.NET 5 to return this 502 Bad Gateway.

So, my question is: is there a way to get a stack trace or an exception page instead of a non-helpful 502 Bad Gateway response?

**Comment by muratg** [comment]
@joshmouch could you provide a basic repro app?

**Comment by moozzyk** [comment]
If this is about http platform handler - turn on logging in the web.config and you should get log files in the `stdoutLogFile` folder.

e.g. `<httpPlatform processPath="..\HelloMvc.exe" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600" />`

**Comment by muratg** [comment]
No repro. @joshmouch if you still have issues, please either re-open or file a new bug here with a minimal repro.
