### ISSUE TITLE
Any reason why IISIntegration module does't forward all available headers to Kestrel?

### ISSUE THREAD

**Issue by dmumladze** [aspnet/IISIntegration#769]
Is it meant to work this way, or why does IISIntegration module not forward all available headers to Kestrel? 

There're few headers that IIS receives from the external reverse proxy, but it does not forward them over to Kestrel.

Setup is as follows:

**[Browser]** `<-->` **[External Reverse Proxy]** `<-->` **[IIS Integration (AspNetCoreModule)]** `<-->` **[Kestrel]**

First request goes to the **[External Reverse Proxy]**, which sets custom headers, which then reverse proxies **[IIS Integration (AspNetCoreModule)]**, which in turn reverse proxies **[Kestrel]**.  

I need **[IIS Integration (AspNetCoreModule)]** to forward all available headers to **[Kestrel]**.

**Comment by Tratcher** [comment]
Any examples?

**Comment by blowdart** [comment]
(As an aside there are always going to be headers that will never be forwarded, as they're set by the module themselves, and their presence would indicate an attempt to hijack some internal workings)

**Comment by dmumladze** [comment]
I have few headers one of which is ‘x-portal-loginid’ but Kestrel isn’t receiving it. 

Any chance that it can allow certain headers per configuration settings?

**Comment by Tratcher** [comment]
It shouldn't be filtering a header like that... @jkotalik can you repro?

**Comment by dmumladze** [comment]
No issues, apparently there's another custom module installed on IIS that's removing the headers.
