### ISSUE TITLE
Web.config appsettings visible in ASP.NET Core?

### ISSUE THREAD

**Issue by codyskidmore** [aspnet/IISIntegration#770]
I am researching the question in this StackOverflow article.

https://stackoverflow.com/questions/49069722/nested-appsettings-jsons-with-asp-net-core

Is is possible to access app settings in the parent web.config under IIS through AspNetCoreModule?

The goal is to allow ASP.NET Core applications to access the tenant's connection string (in a multi-tenant environment) from the parent web.config file.

**Comment by Tratcher** [comment]
No, there's no first class mechanism for this.

**Comment by codyskidmore** [comment]
What about setting the connection string in an environment variable in the parent web.config? 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module#setting-environment-variables

**Comment by Tratcher** [comment]
No. The ANCM environment variable web.config settings don't inherit well.

**Comment by codyskidmore** [comment]
Thanks.
