### ISSUE TITLE
ANCM event viewer logs render strings incorrectly on win7.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#772]
String from STRUs when logged to the windows event viewer seem malformed. 

Ex:
```Application '臰ĺ' with physical root 'Application '%s' with physical root '%s' failed to load clr and managed application, ErrorCode = '0x%x.' failed to load clr and managed application, ErrorCode = '0x60c.```

**Comment by jhkimnew** [comment]
This is fixed.
