### ISSUE TITLE
w3wp.exe crashed when rename app_offline.htm on Win10 X86 machine.

### ISSUE THREAD

**Issue by Mgoul** [aspnet/IISIntegration#780]
There are many w3wp.exe unhanding exception when running test on X86 machine. I check the event logs, there are many Application error about W3WP.

Machine build: 10.0.17133.1.x86fre.rs4_release.180323-1312 X86 
Error messages:
     Faulting application name: w3wp.exe, version: 10.0.17109.1000, time stamp: 0xd6e38087
Faulting module name: ntdll.dll, version: 10.0.17109.1000, time stamp: 0x9cc51555
Exception code: 0xc0000005

Repro steps:
1. Build AspNetCore application with cmd “dotnet publish D:\gitroot\AspNetCoreModule\test\AspNetCoreModule.TestSites.Standard --framework netcoreapp2.0”
2. Convert the test AspNetCore application to web application under Default Web Site
3. Create an 1App_offline.htm under AspNetCoreApp folder.
4. Send a request to AspNetCoreApp
5. Rename 1App_offline.htm to App_offline.htm, the crash issue repro.

This crash was caused below AV: 
(bc4.3c4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000000 ebx=0082a310 ecx=77ade062 edx=00000000 esi=d4022ba9 edi=00000000
eip=77b39863 esp=031bf6e0 ebp=031bf6f4 iopl=0         nv up ei pl nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010202
ntdll!RtlCaptureStackContext+0x13e23:
77b39863 ff773c          push    dword ptr [edi+3Ch]  ds:0023:0000003c=????????
0:010> kn
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
00 031bf6f4 77adfb72 ntdll!RtlCaptureStackContext+0x13e23
01 031bf710 77acaf7a ntdll!TpSetWaitEx+0x382
02 031bf8d8 75b2a1a4 ntdll!TpCallbackIndependent+0x6ca
03 031bf8ec 77aa343e KERNEL32!BaseThreadInitThunk+0x24
04 031bf934 77aa3412 ntdll!PssNtCaptureSnapshot+0x79e
05 031bf944 00000000 ntdll!PssNtCaptureSnapshot+0x77

**Comment by muratg** [comment]
cc @pan-wang

**Comment by pan-wang** [comment]
this is an build issue due to the change of compiler as part of moving code from source depot to git. Working on the fix

**Comment by jhkimnew** [comment]
@Mgoul Pan fixed to Dev branch with https://github.com/aspnet/IISIntegration/pull/783. 
Please verify this issue is fixed. Please rebuild aspnetcore.dll after pulling Dev branch.
