### ISSUE TITLE
Publish new asp.net core module on nuget for preview2

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/IISIntegration#782]
The current module on nuget is still 2.1.0-preview1-final https://www.nuget.org/packages/Microsoft.AspNetCore.AspNetCoreModule/2.1.0-preview1-final.
You should publish a new one, the old one is not compatible (some exception about missing method for get server variable if I remember correctly).
The one from myget works instead.

**Comment by shirhatti** [comment]
@Tornhoof We've made the decision that in-proc support is not yet ready for public consumption. There are still many issues we're working through. As a consequence, we will ship support for in-process after the 2.1 release. Given this change in plans, we haven't shipped a 2.1-preview2 or 2.1-rc package for the AspNetCoreModule
I'll create an announcement in the announcements repo with all the details soon.
