### ISSUE TITLE
How to generate IISExeLauncherArgs.txt?

### ISSUE THREAD

**Issue by senpost** [aspnet/IISIntegration#797]
I hope this the right place to ask, if not please point me in the right direction. 

We have bunch of Asp.Net Core webapps hosted in local IIS. We have a script that builds all these projects so developers don't have to open these solutions one by one in Visual Studio and build them.

After successful build, we can't navigate to these apps because `bin\IISSupport` folder in not created by msbuild. We couldn't check in these files because `IISExeLauncherArgs.txt` file contains absolute file paths [ex: C:\Projects\TestCoreApp\TestCoreApp\bin\IISSupport\pidfile.txt]. 

Is there a way I can generate `bin\IISSupport` without opening Visual Studio and starting debug?

Our Debug config web.config file looks like this, 
```xml
<aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" 
arguments="-argFile IISExeLauncherArgs.txt" 
forwardWindowsAuthToken="false" 
startupTimeLimit="3600" requestTimeout="23:00:00" stdoutLogEnabled="false" />
```

**Comment by Tratcher** [comment]
@BillHiebert

**Comment by shirhatti** [comment]
@senpost What are you trying to achieve? VSIISExeLauncher is just an artifact of how VS attaches the debugger to your ASP.NET Core application.

I'm going out on limb and guessing the `web.config` file that you're referencing was accidentally checked into source control. It looks like you've made no changes to the web.config generated via the websdk. Your best bet is to not include the web.config, it'll get auto-generated while building

**Comment by senpost** [comment]
@shirhatti Sorry for the delayed response, didn't get notified about your comment. 
We don't check in web.config files. Read on. 
We host several microservices, most of them are .Net Framework 4.7.1 and few of them are .Net Core. In developer machines, we use command line to build these services and host them in IIS. As soon as we build .Net Framework microservices using our command line utility, they  are ready and iis serves the responses.

For Asp.Net core this doesn't work because we have to generate web.config files and point to correct dll. Whenever we debug a microservice, Visual Studio overwrites our web.config file with VSIISExeLauncher.exe.

I am trying to come up with a consistent build process on our dev machines that works reliably. If you have better suggestions to build and host asp.net core web apps in IIS, please let me know.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
