### ISSUE TITLE
Websocket connection fails on in-process mode with SDK 2.1.300-preview3-008646 build 

### ISSUE THREAD

**Issue by MogulHuang** [aspnet/IISIntegration#798]
Repro Steps:
1.	Connect the test machine, create the ANCM test aspnetcoreapp named aspnetcoreapprc
2.	Open IE and browse http://localhost/aspnetcoreapprc/chatplus.html
3.	Type ws://localhost/aspnetcorerc/websocket  onto “WebSocket Server URL:” text box
4.	Click “Connect” button

EXPECTED: Websocket connection succeeded.
ACTAUL:You will see it fails. 

NOTE:
This issue happens only with in-process mode. 
You will see there is no problem if you try the repro steps again after switching hostingModel from in-process to out-process with updating D:\inetpub\wwwroot\aspnetcoreapprc\web.config file and recycling w3wp.exe process.

**Comment by Tratcher** [comment]
Can you share the app code?

**Comment by jhkimnew** [comment]
Here you are . https://github.com/aspnet/AspNetCoreModule/tree/dev/test/AspNetCoreModule.TestSites.Standard

**Comment by jhkimnew** [comment]
@shhsu Would you verify this? After that, our test should be updated with newer SDK version which contains this bug fix.

**Comment by Tratcher** [comment]
The scheme is supposed to be http/s. ws/s is only used on the client side, it's not transmitted as part of the request. IsWebSocketRequest must be failing for another reason, such as incorrect headers.

**Comment by Tratcher** [comment]
Can you capture a fiddler or wireshark trace of the request?

**Comment by shhsu** [comment]
Turns out it's IIS configuration issue. sorry for the false alarm
