### ISSUE TITLE
AspNetCoreModule doesn't work with WebListener/Http.Sys

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#8]
Right now all the tests run with Kestrel. When I briefly tried WebListener some of the test cases failed. The logs showed WebListener starting fine, but it never served any requests and HttpPlatformHandler kept re-starting the back-end process until it gave up.

I've seen it work when published to full IIS, so it might be a test setup issue.

**Comment by Schlurcher** [comment]
Can confirm this is happening with 1.2 on full IIS 8 on Server 2012. Backend keeps restarting until IIS gives up and serves a 502 Bad Gateway.

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.

**Comment by Tratcher** [comment]
Ok, now we understand why it doesn't work, and it won't any time soon.

HttpPlatformHandler starts the back-end process (dnx.exe). Then it opens a socket and tries to connect to the specified port. When that succeeds it cross checks the process that opened the port with it's list of child processes. If it finds a mismatch then it assumes it has a port conflict and it ends all of it's child processes and starts over.  In the case of WebListener the port is actually opened by Http.Sys in the System process, so it never matches and always gets ended by platform handler.

HttpPlatformHandler will eventually need to support Http.Sys based back-end servers, but it's a non-trivial change for them so this isn't happening any time soon.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#23
