### ISSUE TITLE
UnauthorizedAccessException 

### ISSUE THREAD

**Issue by prenaut41** [aspnet/IISIntegration#800]
I'm using asp.net core 2.0 MVC for a web application and am trying to set up windows authentication.  

I keep getting a System.UnauthorizedAccessException thrown by calls to get_AuthenticationType() when trying to request my web application's home page, which is a Razor page that includes a Razor template.  The application involves mostly SPA front-end javascript stuff, but the entry point is a Razor page.  

The application was working great with Anonymous Authentication, but breaks when I use Windows Authentication enabled in IIS:   
Breaks when I have Anonymous disabled and Windows Authentication enabled in IIS.  
Breaks when I have both Anonymous and Windows Authentication enabled in IIS when a controller action is called that has an "Authorize" attribute on it.  

The exception is being thrown in System.Security.Principal.WindowsIdentity.get_AuthenticationType(), based on the first two lines of the stack trace:
   at System.Security.Principal.WindowsIdentity.get_AuthenticationType()
   at AspNetCore._Views_Shared_spaRctTemplate_cshtml.<<ExecuteAsync>b__15_0>d.MoveNext()

I guess this is getting called somewhere when my Razor page is being processed.  

Calls to get_AuthenticationType() where identified as problems in at least the following two referenced issues:  
#231 #650.   

I was having trouble following those threads and what actually ended up happening, but it sounded like there had been fixes in the past to parts of the framework to avoid making the call to get_AuthenticationType().

Is there something in the framework that still needs to be fixed around processing the Razor pages in the case of Windows Authentication, or might I be doing something wrong?  If it is a framework issue, is there a relatively easy work around?

**Comment by prenaut41** [comment]
Ah!  I just realized that a while back that I had actually slipped @User.Identity.AuthenticationType into  my Razor template while debugging and had forgotten about that.  
That's what the problem was.

**Comment by springy76** [comment]
Why on earth should I not be allowed to query a `WindowsIdentity` instance which has `IsAuthenticated == true` and a valid `Name` property for its `AuthenticationType` property?
Is there a document saying "you aren't allowed to"?

**Comment by gtc-aurizon** [comment]
Reading through the other comments/issues raised on this, has this defect been addressed or a work-around provided?

**Comment by springy76** [comment]
@gtc-aurizon "work-around" seems to not use this property at all: https://github.com/aspnet/KestrelHttpServer/issues/1288#issuecomment-419141955
