### ISSUE TITLE
Usability: If app fails to start in process, users should restart worker process manually

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#801]
Once app fails with inprocess mode with a small mistake and in that case users will try again with fixing the problem. However, users will still see the app still show 5XX error. This is currently because we have a global flag which indicates the initial failure and once the failure happens, ANCM does not try again even the app is changed. 

Work-around is to recycle IIS worker process (w3wp.exe) which can be done ith putting app_offline.htm and remove the file. Obviously this will make users confused and we need to work to reduce the confusion. One simple is to stop the worker process automatically when the app fails from the beginning so that user's don't need to recycle the worker process manually.

**Comment by jkotalik** [comment]
This is by design. If there is a small mistake with the application, it usually means we have called hostfxr_main already. You cannot call hostfxr_main multiple times in the same process, so at that point we require the worker process to be recycled. If the application failed on Startup (before the request hits the server), we do not recycle the worker process, as that can be an attack vector and will cause IIS rapid failure protection to trigger.

**Comment by jhkimnew** [comment]
@jkotalik If so, please add the information to the event error message that users should restart worker process with inetmgr.exe after fixing the problem. Otherwise users will be very confused why the app does not work if they did not know about this.

**Comment by shirhatti** [comment]
Just so I understand correctly, a configuration change will trigger a process recycle right which should alleviate this concern. So when exactly does this become a concern?

**Comment by jhkimnew** [comment]
A configuration change won't trigger a worker process (w3wp.exe) recycle.
For example, the w3wp.exe process won't be recycled when you update the processPath of aspNetCore section of the web.config in the application root path with a different value, supposing the old value was wrong in inprocess mode and the new value was set to fix the problem. In that case, the problem won't be fixed until users recycle the w3wp.exe manually.

**Comment by muratg** [comment]
@jhkimnew @pan-wang fixed the issue of configuration change not triggering the recycle. Could you please verify that and close the bug? Thanks.

**Comment by jhkimnew** [comment]
@shhsu Would you verify this instead of me?

Here is the steps to verify this. 

1. Send a request aspnetcore app which is running in inprocess mode
2. Check the current process id of the corresponding w3wp.exe
3. Open web.config of the aspnetcore app and save without change
4. Verify the w3wp.exe is recycled or terminated
5. Send a new request to create the w3wp.exe if it was terminated
6. Change the value of processPath in the web.config
7. Verify the w3wp.exe is recycled or terminated

**Comment by shhsu** [comment]
verified

**Comment by jhkimnew** [comment]
@shhsu please add a new test case (or update existing test case) for this feature. We need to make sure the worker process is recycled with configuration change. I'd like to inform that the configuration change can be done in parent level as well. For example, you can make the processPath inherited from site level web.config and make multiple web applications with different worker process. When the configuration is changed in the site level, the change should recycle all the worker process of the multiple web applications. If you did not test that yet, please make sure that is covered by test automation.
