### ISSUE TITLE
Support app_offline.htm

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#81]
- Deployer uploads app_offline.htm (case insensitive)
 - HPH serves app_offline.htm for any new incoming requests
- HPH signals process shutdown (SignalR, WebSockets) (opt-in web.config: signalShutdown=true ?)
 - Ctl+C https://msdn.microsoft.com/en-us/library/ms683155(v=vs.85).aspx
 - Ctl+Break? Can Hosting receive both of these? Break might be more correct.
 - General feature for graceful shutdown
- HPH waits for process to end with timeout if shutdown signal was requested&sent
- Deployer needs to find out when the process is down / the files are unlocked
 - Retry loop on deletefile?
- Deployer uploads new files
- Deployer deletes app_offline.htm
- HPH restarts the back-end process
 
Initial HPH work completed by end of Feb.
Deployer developed in parallel
Update publish-iis to add signalShutdown to the web.config

RE: https://github.com/aspnet/Hosting/issues/141
@sayedihashimi

**Comment by Tratcher** [comment]
Hosting already supports Ctl+C and Ctl+Break.

**Comment by muratg** [comment]
Cool, thanks for checking!

**Comment by muratg** [comment]
Note for HPH side:  CreateProcess will need to be called the right way with the flag `CREATE_NEW_PROCESS_GROUP ` as specified in the [msdn article](https://msdn.microsoft.com/en-us/library/ms683155%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by GuardRex** [comment]
> HPH serves app_offline.htm for any new incoming requests

HPH will be checking periodically for the presence of this file? I wish checking for the file file could be disabled in options for `app.UseIISPlatformHandler()`.

**Comment by moozzyk** [comment]
@GuardRex - why?

**Comment by GuardRex** [comment]
Perf concern ... How often does HPH have to check for the file? Is it inconsequential (i.e., milliseconds spent every several seconds ... i.e., that's no "concern" to be concerned about)?

**Comment by PureKrome** [comment]
@moozzyk 

- Some people might _never_ want to push up an `app_offline.hml` so why waste the cpu check(s) (yes, micro opt).
- Security. disable the option for a rogue person to throw the site offline by just uploading a single file with some hacker message, etc.

**Comment by moozzyk** [comment]
@GuardRex - Perf concern - I would assume that platform handler will not poll but be notified about changes. Not sure how much overhead it would add but IIS already monitors changes to the web.config file and I don't think this is causing perf issues. 

@PureKrome - > Security. disable the option for a rogue person to throw the site offline by just uploading a single file with some hacker message, etc.

I guess this is always true - overwriting the .exe containing the app will have the same effect and you can take the site down just by overriding the web.config file.

**Comment by GuardRex** [comment]
> Perf concern - I would assume that platform handler will not poll but be notified about changes.

Perfect! ...... concern withdrawn.

**Comment by Tratcher** [comment]
@GuardRex On a related note, HPH is configured exclusively via the web.config. There's nothing you/we can do once the app has launched. UseIISPlatformHandler and similar just consume things provided by HPH.

**Comment by GuardRex** [comment]
@Tratcher I see. Just asking. I'm good.

**Comment by sayedihashimi** [comment]
>Deployer needs to find out when the process is down / the files are unlocked
    Retry loop on deletefile?

When VS is used we will pass the `appoffline` flag to MSDeploy. We will also pass a flag to retry 5 times by default. So the flow is that msdeploy will drop the app_offline.htm file, start uploading files from the client, and then delete the app_offline.htm. If there is a problem during the publish it will retry automatically. In some cases if the web server is taking too long to respond the publish operation may be blocked. I've never heard a report of this though. I think in most cases the app does go offline in time for one of the retries to continue.

cc @vijayrkn @bruceyclee

**Comment by haydenmc** [comment]
:+1:

**Comment by Tratcher** [comment]
This as been fixed in AspNetCoreModule v0.8: https://github.com/aspnet/IISIntegration/issues/105.

**Comment by derekgreer** [comment]
For anyone who happens upon this thread in the future, it should be noted that there are versions of the .Net Core Module that only respect all lower case "app_offline.htm".  (see comments here: https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module).  There is mention of this being fixed in the latest version, but it isn't clear which version.

**Comment by shirhatti** [comment]
It was fixed in [Version 1.0.1971](https://github.com/aspnet/AspNetCoreModule/releases/tag/1.0.1971).
