### ISSUE TITLE
Make IIS tests only use the netcoreapp2.1 as the client.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#810]
Currently tests run with netcoreapp2.0, 2.1 and net461. However, theses tests are only for the client, while the deployed result is always the same. We should just make all tests use netcoreapp2.1 and remove duplication of test coverage. The same thing was done by @Tratcher in server tests: https://github.com/aspnet/ServerTests/commit/53564567662a09adb3c8d4c5ecbd5b4cfada1351

**Comment by pakrym** [comment]
Done
