### ISSUE TITLE
Move Inprocess managed code into the M.A.S.IIS namespace.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#817]
To be able to OOB the server, we need it to be entirely separated from the M.A.S.IISIntegration namespace, so we can easily iterate on it. We would also need to change the way the server is instantiated via a new method on the webhostbuilder, like ```UseIISServer()```.

**Comment by shirhatti** [comment]
I'm assuming this issue also tracks re-targeting from latest to 2.1?

**Comment by pakrym** [comment]
Yes
