### ISSUE TITLE
Move ANCM setup strings from IIS-Setup to ANCM-Installer project

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#824]
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/IIS-Setup?path=%2Fiisca%2Fwix%2Fsetupstrings.wxl&version=GBmaster&_a=contents&line=247&lineStyle=plain&lineEnd=252

**Comment by rockerinthelocker** [comment]
While you guys are at it, please make sure the installer no longer removes custom settings from applicationHsot.config, such as

`<aspNetCore lockAllAttributesExcept="processPath,arguments,stdoutLogEnabled,stdoutLogFile,forwardWindowsAuthToken,disableStartUpErrorPage,hostingModel" />`

, during install. Thank you!
