### ISSUE TITLE
V2 ANCM for IISExpress build number should be the same to V2 ANCM for Full IIS

### ISSUE THREAD

**Issue by MogulHuang** [aspnet/IISIntegration#826]
The version of ANCM V2 Microsoft ASP.NET CoreModule for IIS Express is 2.1.18124 but the version of Microsoft ASP.NET CoreModule is 1.0.18124. V2 ANCM for IISExpress build number should be the same to V2 ANCM for Full IIS

**Comment by jkotalik** [comment]
@pan-wang has this been fixed?

**Comment by muratg** [comment]
@MogulHuang Could you please let us know if this is still an issue?

**Comment by shirhatti** [comment]
@jkotalik will verify and close
