### ISSUE TITLE
The ANCM V2 cannot work after uninstall V1 and the aspnetcore app got "HTTP Error 500.19" error

### ISSUE THREAD

**Issue by Jinjin2Ma** [aspnet/IISIntegration#828]
Description: The ANCM V2 cannot work after uninstall V1, The aspnetcore app got "HTTP Error 500.19" error. It's because the aspNetCore section also has been deleted when uninstall ANCM V1.

section name="**aspNetCore**" overrideModeDefault="Allow"  

Repro steps: 
1.Install ANCM V1 and V2 on machine.
2.Create an AspNetCoreApp used AspNetCoreModuleV2 module in web.config(D:\_ANCMTest\publishPathOutput)
3.Send a request to AspNetCoreApp and verify it works.
4.Uninstall ANCM V1 from ARP
5.Send a request to AspNetCoreApp again and verify it works.
 
Expected: AspNetCoreApp running
Actually: "HTTP Error 500.19"

**Comment by muratg** [comment]
This is fixed now.
