### ISSUE TITLE
ANCM doesn't do anything

### ISSUE THREAD

**Issue by JoeDurand3** [aspnet/IISIntegration#829]
Deployed an Asp.net core 2.0 project to IIS10 with the module and runtime installed, and I get no indication that the app has been started or otherwise.

Navigating to the url gives me a 'this page cannot be displayed' error.

Things I've attempted:
- checked application logs in Event Viewer. no mention of this particular app.
- enabling logs in web.config / created log folder. logs never get written.
- gave IUSR permissions on the folder. no change.
- reinstalled the hosting bundle installer with admin privileges.

What's frustrating is there is no log entry anywhere that even acknowledges the module .dll is even being loaded.

Only other thing I can thing of is other modules that might be interfering? There are 10+ .net framework apps running on same server.

**Comment by Tratcher** [comment]
What was the full error page?

**Comment by JoeDurand3** [comment]
Looked at the response in the browser more closely. Turns out there was an A record problem, so the request never made it to the site and app pool.
