### ISSUE TITLE
502.5 error - VS 2017 15.7.1; .net core 2.0.8 mvc

### ISSUE THREAD

**Issue by henrychang99** [aspnet/IISIntegration#830]
Hello - I am encountering the same issue posted earlier #681 with VS2017 15.7.1 Enterprise. I have created a .net core 2.0 (AspNetCore 2.0.8) mvc project. made some cosmetic changes to the default template and published to azure app service. the publish was successful but got 502.5 error when viewing it.

i have tried the wwwroot wipe, and it was not successful.

In the event log, i got the following:
8000808c.100010Keywords1129163281ApplicationRD00155DFE9F35Application 'MACHINE/WEBROOT/APPHOST/XYZCOM' with physical root 'D:\home\site\wwwroot' failed to start process with commandline 'dotnet .\xyz.com.dll', ErrorCode = '0x80004005 : 8000808c.100420Keywords1129293625ApplicationRD00155DFE9F35Warning: Could not create stdoutLogFile \?\D:\home\site\wwwroot\logs\stdout_8344_201851116448.log, ErrorCode = -2147024893.100010Keywords1129293921ApplicationRD00155DFE9F35Application 'MACHINE/WEBROOT/APPHOST/XYZCOM' with physical root 'D:\home\site\wwwroot' failed to start process with commandline 'dotnet .\xyz.com.dll', ErrorCode = '0x80004005 : 8000808c.

Is there any other information i can post here so that we can have better idea?

Thank you,
Henry

**Comment by Tratcher** [comment]
2.0.8 hasn't been made available on Azure yet. Expect an announcement next week.

**Comment by henrychang99** [comment]
@Tratcher, thank you for the information.  I will try to downgrade it and redeploy.

**Comment by henrychang99** [comment]
Downgraded to 2.0.3;
closed my VS 2017;
cleaned the solution;
redeployed and it was successful.

**Comment by terzano** [comment]
I ran into this problem multiple times in the past. Where can we find out the current versions supported on Azure? I am yet to find documentations on the versions supported.

**Comment by NikolaosWakem** [comment]
https://github.com/aspnet/IISIntegration/issues/476
