### ISSUE TITLE
Remove IHttpContext and ExePath from CreateApplication Api

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#842]
Once we split the inprocess and out of process request handlers (#839), we can remove the IHttpContext and ExePath from the CreateApplication, moving the creation of the config after newing up an application.

**Comment by pakrym** [comment]
How do we pass `ExePath` then?

**Comment by jkotalik** [comment]
we can pass via a better designed key/value mapping from shim to request handler.
