### ISSUE TITLE
Split samples, test apps and benchmarks

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#848]
Currently this repo uses the samples projects as samples, test apps AND benchmarks. This, in addition to being gross, has put us in an awkward situation. We don't want to change the TFM's of benchmark projects so that our data remains applicable, but we also need to more our tests (and thus their testapps) to `netcoreapp2.2`. For right now we've just gone ahead and moved to 2.2 to unblock everything, but we should clean this all up so our historical benchmarks data is useful.

CC @Tratcher who did most of the legwork here.

**Comment by pakrym** [comment]
Changing TFM of benchmark project is fine.

**Comment by muratg** [comment]
@ryanbrandenburg benchmarks project targets 2.2 now. Do you think we should multi-target, or is this good?

**Comment by ryanbrandenburg** [comment]
I would still prefer that we separate samples test apps and benchmarks, but now that it's not a technical issue I won't be too broken up if we kill this issue.

**Comment by pakrym** [comment]
Tests and benchmarks are using test web sites, and samples are independent now
