### ISSUE TITLE
Web.Config works on IIS 10 but gives error on IIS  8

### ISSUE THREAD

**Issue by DanJ210** [aspnet/IISIntegration#857]
I can host an asp.net core 2 site on my Windows 10 machine no problem. Works straight from publish. But when I try to host the same thing on a VM within the company I get an error stating my web.config has invalid entries. I can't open certain configurations in IIS as I'm told the web.config is invalid.

I did come across this link, https://github.com/aspnet/IISIntegration/issues/105, and I installed a new version .08 of the aspnet module but it didn't seem to do anything. The aspnetcore module is already installed and visible. With the config below I'm given a 500.19 stating that the request page cannot be accessed because the related configuration data for the page is invalid. The first line of `<?xml version="1.0" encoding="utf-8"?>` is red as if that's the problem. Any ideas on how I could understand what's going on? Why it works on IIS11 but not 8 with the same modules?

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\GIK_WebForm.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration> 
`

**Comment by muratg** [comment]
Did you install ANCM on the VM?  (You need to do it after IIS installation.)

You can check and see if `c:\windows\system32\inetsrv\aspentcore.dll` exists.

**Comment by DanJ210** [comment]
I did so much that it's hard to know what exactly got things working. But I believe it was the URL Rewrite Module needed to be manually updated. It was like version 1 something and I needed to update to the latest, version 2 something I believe, by using the Web Platform Installer.

**Comment by jkotalik** [comment]
Sorry that UrlRewrite caused that issue.
