### ISSUE TITLE
ANCM Request Handler versioning spec

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#859]
ANCM v2 will be installed to `%ProgramFiles%\IIS\AspNetCoreModule`

```
> tree %ProgramFiles%\IIS\AspNetCoreModule
├── aspnetcorev2.dll
└── requestHandler
    ├── 1.0
    │   └── outofprocessrh.dll
    ├── 2.0
    │   └── outofprocessrh.dll
    ├── 2.1-preview1
    │   └── outofprocessrh.dll
    ├── 2.1
    │   └── outofprocessrh.dll
    └── 2.2-preview1
        └── outofprocessrh.dll
```

In the happy path, the user doesn't have to specify a version of the out-of-process requestHandler. By default the latest stable version wins. As an aside, if the `handlerVersion` is ignored when `hostingModel="inprocess"`

```xml
<configuration>
    <system.webServer>
        <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified"/>
        </handlers>
        <aspNetCore processPath="dotnet"
                    arguments="myapp.dll"
                    hostingModel="outofprocess"/>
     </system.webServer>
</configuration>
```

If you don't want to be transparently upgraded you can either pin to a specific version or specify a version range or wildcard. For e.g.,

```xml
<configuration>
    <system.webServer>
        <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified"/>
        </handlers>
        <aspNetCore processPath="dotnet"
                    arguments="myapp.dll"
                    handlerVersion=">=2.1"
                    hostingModel="outofprocess"/>
     </system.webServer>
</configuration>
```

This table denotes all the permissible values for specifying a **stable** version range. Previews don't work with range specifiers and only work with exact version. (I tried to borrow logic from NuGet/hostfxr but they are all predicated on using SemVer. Given that our requestHandler has to maintain back-compat we're effectively always performing a *patch* release and the additional complexity wasn't worth it.)

> NOTE: Applying version range rules  or exact version matches can prevent you from receiving security updates.

| Notation | Applied rule | Description |
|----------|--------------|-------------|
| 1.0 | x == 1.0 | Exact version match |
| >1.0 | x > 1.0 | Minimum version, exclusive |
| >=1.0 | x ≥ 1.0 | Minimum version, inclusive |
| <=1.0 | x ≤ 1.0 | Maximum version, inclusive |
| <1.0 | x < 1.0 | Maximum version, exclusive |
| 2.1-preview1 | x == 2.1-preview1 | Exact version match |
| >=2.1-preview1 | Invalid |  |

## Examples

| Arguments | Applied rule|
|------------|-------------|
| `<aspNetCore processPath="dotnet" arguments="myapp.dll" handlerVersion=">=2.1" hostingModel="inprocess"/>` | Version ignored due to hostingModel |
| `<aspNetCore processPath="dotnet" arguments="myapp.dll" handlerVersion="2.1" hostingModel="outofprocess"/>` | 2.1 requestHandler due to exact version match |
| `<aspNetCore processPath="dotnet" arguments="myapp.dll" handlerVersion=">=2.1-preview" hostingModel="outofprocess"/>` | Range modifiers are not legal for pre-release versions |
| `<aspNetCore processPath="dotnet" arguments="myapp.dll" handlerVersion=">=1.1" hostingModel="outofprocess"/>` | 2.1 is latest stable version |

**Comment by shirhatti** [comment]
@pakrym Thoughts?

**Comment by Tratcher** [comment]
I was expecting something more like:
```
> tree %ProgramFiles%\IIS\AspNetCoreModule\v2
├── aspnetcore.dll
└── requestHandler
    ├── 1.0
    │   └── outofprocessrh.dll
    ├── 2.0
    │   └── outofprocessrh.dll
    ├── 2.1-preview1
    │   └── outofprocessrh.dll
    ├── 2.1
    │   └── outofprocessrh.dll
    └── 2.2-preview1
        └── outofprocessrh.dll
```
Leaving more room for the eventual v3.

**Comment by Tratcher** [comment]
How does handlerVersion apply to our testing environment? Requiring an exact version for nightlies would be painful.

**Comment by pakrym** [comment]
having 1.0 request handler under v2 ANCM doesn't make sense, let's keep major the same.

I think it's fine except that `1.0` means `>=1.0` everywhere else

**Comment by pakrym** [comment]
Additionally I would prefer not to produce 2 dlls with the same name and different contents `aspnetcore.dll`

**Comment by jkotalik** [comment]
I don't like that we match version numbers with dotnet. If we need to ship a rapid update to azure, things will be misaligned if we don't have patch versions.

**Comment by pakrym** [comment]
> I don't like that we match version numbers with dotnet

I don't think we are matching to dotnet for outofproc, but we are matching to the shim version.

**Comment by pakrym** [comment]
We should use `handlerSettings` for this and avoid updating schema again.

**Comment by rockerinthelocker** [comment]
@coolcsh , Shared hosting providers (and control panel vendors) will be amused and simply may not offer ASP.NET Core hosting beyond ASP.NET Core 2.0. In fact, nobody in the shared hosting industry is going to update control panel software and servers every few months because Microsoft released just another ASP.NET Core handler version for IIS. This update frenzy adds more complexity and maintenance burden hardly anyone in the shared hosting industry is willing to pay for.

**Comment by jkotalik** [comment]
Few questions that need to be resolved:
- By allowing people to specify the version of the request handler, it puts strain on both the customer and the hoster for knowing which version of the request handler will be on the machine. 
- Installing a specific version of the out of process request handler isn't possible unless the msi contains all previous versions of the request handler.

**Comment by pan-wang** [comment]
why should we add a subfolder "requestHandler" instead of using .net core version directly. Can we ask hostfxr to return the version of .net core for an given app? if possible, we then can put inprocess and outof process under the same folder.  This version folders will make setup a little bit complicated as we have to pass in the version string to the build 

the configuration should looks like

<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\EchoApp.dll" startupTimeLimit="60" stdoutLogEnabled="true" stdoutLogFile=".\logs\">
            <handlerSettings>
                <handlerSetting name="handlerVersion" value=">=2.1" />
            </handlerSettings>
        </aspNetCore>
  </system.webServer>
</configuration>

**Comment by shirhatti** [comment]
Takeaways from today's meeting
- No more version ranges. Only exact version matches
- Based on engineering risk, we might eliminate previews based additional cost since we're trying to avoid feature creep
- No schema change to add handlerVersion, instead we'll use the handlerSettings section

**Comment by jkotalik** [comment]
I propose we add patch version to the handlerVersion for a few reasons:
1. Makes parsing significantly easier (fx_ver_t would match up exactly)
2. Follows the versioning style of dotnet.

**Comment by shirhatti** [comment]
If we're doing x.y.z, I'm assuming we'd version as x.0.z (since technically ever release is a patch release). Is it that what you had in mind?

**Comment by shirhatti** [comment]
Notes from today:
- MSIs will never install preview versions

**Comment by jkotalik** [comment]
This portion is done. Will start validation.
