### ISSUE TITLE
Cannot get remote IP Address when using IIS 7.5

### ISSUE THREAD

**Issue by sharabiania** [aspnet/IISIntegration#86]
Using the code below, `RemoteIpAddress` is always `null` when deploying the _ASP.Net 5_ application on _IIS 7.5_.

`var test1 = HttpContext.Features.Get<IHttpConnectionFeature>();`

`var test2 = HttpContext.Connection.RemoteIpAddress;`

**Note** My IIS is running on a VM.

**Comment by Tratcher** [comment]
https://github.com/aspnet/IISIntegration/issues/17

**Comment by muratg** [comment]
Dup https://github.com/aspnet/IISIntegration/issues/17
