### ISSUE TITLE
hostingModel="InProcess" does not seem to work with ASP.NET Core 2.1 targeting .NET Framework 4.7.1

### ISSUE THREAD

**Issue by wdspider** [aspnet/IISIntegration#860]
I followed the steps listed here:
https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-0-preview1-improvements-to-iis-hosting/
using this hosting module: dotnet-hosting-2.1.0-rc1-final-win.exe
so that I could run my .NET Core WebAPI in the w3wp.exe IIS process rather than its own.

My web.config file looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
    <system.webServer>
        <handlers>
            <remove name="aspNetCore" />
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
        </handlers>
        <aspNetCore processPath=".\OpenApi.WebApi.exe" stdoutLogFile=".\logs\stdout" stdoutLogEnabled="false" forwardWindowsAuthToken="false" startupTimeLimit="3600" requestTimeout="23:00:00" hostingModel="InProcess" />
    </system.webServer>
</configuration>
```
However, this does not seem to achieve the desired results as I still see OpenApi.WebApi.exe as a separate process in Task Manager. Am I correct in understanding that this process should not be listed in Task Manager when the InProcess hostingModel is successful? Is there a better way to verify that the InProcess hostingModel is actually working?

Has the inprocess feature been removed from .NET Core 2.1 RC1?
Does the inprocess feature not actually work for .NET Core apps targeting .NET Framework 4.7.1?
Is there something else that I possible haven't configured correctly?

**Comment by Tornhoof** [comment]
In process was removed from 2.1 for now. It's not yet ready.

**Comment by Tratcher** [comment]
And no, .NET is not supported for InProc, only .NET Core.

**Comment by wdspider** [comment]
Just to confirm my understanding of the above 2 responses:

InProcess in not currently in .NET Core 2.1 RC1 as it's not ready yet.

Once it gets added back, InProcess will only support .NET Core apps that target .NET Core 2.1 and higher. InProcess will not support .NET Core apps that target .NET Framework.

Is this understanding correct?

**Comment by Tratcher** [comment]
That's correct. Expect additional details after 2.1.

**Comment by wdspider** [comment]
It probably would have helped to have a blurb about this in the RC1 Release Notes, but thank you for clearing up my confusion. As such, I'm going to go ahead and close this.

**Comment by jkotalik** [comment]
@shirhatti did you post an announcement for punting inproc to a later release? Sorry for the confusion @wdspider
