### ISSUE TITLE
publish-iis fails when there are no files in wwwroot folder 

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/IISIntegration#87]
dotnet publish does not create the wwwroot folder if there are no files in the wwwroot folder. When publish-iis runs, it needs to add the web.config to the wwwroot folder and it fails when the folder is not present.

e.g:
Configuring the following project for use with IIS: 'd:\dotnet\web\KWebDemo\KWebDemo\src\KTestingDemo\bin\Debug\dnxcore50\win7-x64\'
No web.config found. Creating 'd:\dotnet\web\KWebDemo\KWebDemo\src\KTestingDemo\bin\Debug\dnxcore50\win7-x64\wwwroot\web.config'
Could not find a part of the path 'd:\dotnet\web\KWebDemo\KWebDemo\src\KTestingDemo\bin\Debug\dnxcore50\win7-x64\wwwroot\web.config'.

**Comment by moozzyk** [comment]
Fixed with https://github.com/aspnet/IISIntegration/commit/90763b60a5806ab3a91bd8baa63fa5cd4b3c7300
