### ISSUE TITLE
Fix ANCM-Setup msi creation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#876]
Current failing on CI to sign the msis. @pan-wang I think your change caused it to start failing.

**Comment by pan-wang** [comment]
Let me take a look at the build log first

**Comment by jkotalik** [comment]
```C:\b\w\a5d1ced7d2322198\sign.msbuild(15,5): error MSB4044: The "SubmitCodeSignJob" task was not given a value for the required parameter "DisplayName". [C:\b\w\a5d1ced7d2322198\sign.msbuild.teamcity]```

**Comment by pan-wang** [comment]
the MSIs were generated correctly. I don't think I touched sign.msbuild. SubmitCodeSignJob is a passed in parameter and is defined in build/sign.props.

**Comment by jkotalik** [comment]
This was fixed due to a bad assumption on the location of other files.
