### ISSUE TITLE
Move aspnetcorev2_schema.xml to VS and Azure

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#891]
Now that the schemas have diverged, we need to get the v2 schema everywhere possible. This includes getting it on azure and in Visual studio. VS uses another schema besides the one installed by the MSI for xml tag verification.

edit (@muratg): VS => VS editor intellisense

**Comment by pakrym** [comment]
Are we going to revert changes from V1 schema?

**Comment by muratg** [comment]
@pakrym are you talking about https://github.com/aspnet/IISIntegration/blob/dev/src/AspNetCoreModuleV1/AspNetCore/aspnetcore_schema.xml#L26?  This would be breaking, no?

Unless you have a good reason, we're unlikely to change V1 schema from now on.

**Comment by muratg** [comment]
@shirhatti will figure out how to do this.

**Comment by pakrym** [comment]
@shirhatti  Does VS take intellisense schema from our install location?

**Comment by shirhatti** [comment]
Nope. We have to manually update schema.

**Comment by pakrym** [comment]
Another thing I noticed when looking at VS schema is that hostingmodel values are `CamelCased` there while the ones I added to templates are all lowercase, we need to decide which one we prefer because schema validation is case sensitive.

**Comment by pakrym** [comment]
I think we should close this bug and track intellisense update in https://github.com/aspnet/IISIntegration/issues/1224
