### ISSUE TITLE
Virtual Sub-Application running Framework 4.5 and log4Net 2.0.8 will not write log files

### ISSUE THREAD

**Issue by gthelp** [aspnet/IISIntegration#896]
On IIS 8 - have asp.net core application with following web.config and running under unmanaged application pool - works great

I created a virtual sub-application under it with web.config setup to remove aspnetcore and use net4log.
The sub application works fine, and trace tells me log4net is loading up, but never writes even with all write permissions enabled. I think their might be some other core component from parent site stepping on it.
Any ideas?

web.config for asp.net core app (parent)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout" />
  </system.webServer>
</configuration>
```

web.config for sub-application:
```
<?xml version="1.0"?>
<configuration>
<configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,Log4net"/>
  </configSections>
  <appSettings>
		<add key="log4net.Internal.Debug" value="true" />
	</appSettings>
<log4net>
		<!-- Define some output appenders -->
		<appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
			<lockingModel type="log4net.Appender.FileAppender+MinimalLock" />
			<file value="C:\inetpub\wwwroot\testsite\LogEvents\logging.txt" />
			<appendToFile value="true" />
			<maxSizeRollBackups value="50" />
			<maximumFileSize value="10MB" />
			<rollingStyle value="Size" />
			<staticLogFileName value="true" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%date [%thread] %-5level %logger [%ndc] - %message%newline" />
			</layout>
		</appender>
		<!-- Specify the level for some specific categories -->
		<logger name="MyAppLog">
			<level value="ALL" />
			<appender-ref ref="RollingLogFileAppender" />
		</logger>
	</log4net>
  <system.web>
    <compilation debug="true" targetFramework="4.5.2">
      <assemblies>
        <add assembly="System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
      </assemblies>
    </compilation>
    <customErrors mode="Off"/>
  </system.web>
<system.webServer>
    <handlers>
      <remove name="aspNetCore" />
    </handlers>
  </system.webServer>
</configuration>
```

**Comment by Tratcher** [comment]
What happens if you remove aspnetcore from the parent site?

**Comment by gthelp** [comment]
I removed the handler and aspnetcore tag from web.config in parent core app and it worked fine. I recycled app pools to make sure. Core app worked fine. fired with sub application and it worked fine, but log4net did not write again. I turned to trace write to log folder and .net app wrote to log folder fine, but not log4net component.
<?xml version="1.0" encoding="utf-8"?><configuration>    <system.web>    <trust originUrl="(https://translate.googleapis.com/translate_a/single)|(https://www.googleapis.com/language/translate/v2)|(http://api.microsofttranslator.com/V2/Http.svc/Translate)|(https://datamarket.accesscontrol.windows.net/v2/OAuth2-13)" />  </system.web>  <system.webServer>    <httpProtocol>      <customHeaders>        <add name="X-UA-Compatible" value="IE=edge,chrome=1" />         <remove name="X-Powered-By" />      </customHeaders>    </httpProtocol>  </system.webServer></configuration>





 

    On Thursday, June 7, 2018, 12:09:54 PM EDT, Chris Ross <notifications@github.com> wrote:  
 
 
What happens if you remove aspnetcore from the parent site?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
