### ISSUE TITLE
Invoke solution build on all native components rather than running msbuild .vcxproj

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#899]
Right now, we build each invoke msbuild to build each c++ project, like:

```xml
    <Exec Command="&quot;$(VisualStudioMSBuildx86Path)&quot; &quot;$(RepositoryRoot)test\CommonLibTests\CommonLibTests.vcxproj&quot; /t:Test $(BuildArgs) -p:Platform=%(Platforms.VCPlatform)"
      Condition="'$(VisualStudioMSBuildx86Path)' != ''" />
```

Ideally, this shouldn't be necessary. We should just be able to build the solution, which will build the vcxproj files. I tried this locally, and it continued saying the $(VCTargetsPath) was empty on command line, while in VS it was defined. VCTargetsPath is defined via a reg key. Seems like a bug. 

cc/ @Tratcher 

@pan-wang @shirhatti when porting ANCM to github, was there any reason we invoke msbuilds this way rather than via sln?

**Comment by shirhatti** [comment]
Unless I'm mistaken, it's because invoking sln build via the dotnet cli couldn't build native projects since it didn't have the required targets.

**Comment by shirhatti** [comment]
Let me check, but I think we copied it off the SignalR cpp client.

**Comment by shirhatti** [comment]
IIRC @pranavkm suggested it

**Comment by muratg** [comment]
@shirhatti Could you take a look?
