### ISSUE TITLE
Validate the new installer

### ISSUE THREAD

**Issue by muratg** [aspnet/IISIntegration#901]
## Scenarios to cover:
Needs to be verified on both x64 and x86 operating systems.
### Standalone scenarios (ANCM not installed on machine)
-  ANCM msi 
   - [x] apphost.config file to be updated with aspnetcore section and ANCM module
   - [x] aspnetcore.dll dropped in inetsrv
-  ANCMV2 msi 
   - [x] apphost.config file to be updated pointing ANCMV2 to ProgramFiles/IIS
   - [x] aspnetcorev2.dll in v2 directory
   - [x] aspnetcorev2_outofprocess.dll in v2/RH_VERSION directory
-  ANCM iis express
   - [ ] apphost.config file to be updated
   - [ ] aspnetcore.dll dropped in PF\IIS Express
-  ANCMV2 iis express msi 
   - [ ] apphost.config file to be updated pointing ANCMV2 to ProgramFiles/IIS
   - [ ] aspnetcorev2.dll in v2 directory
   - [ ] aspnetcorev2_outofprocess.dll in v2/RH_VERSION directory

### Upgrade scenarios:
-  ANCMV2 msi with RH version higher than currently installed
   - [ ] aspnetcorev2_outofprocess.dll in v2/higher RH VERSION in directory. Only one RH in directory.
-  ANCMV2 iis express msi 
   - [ ] aspnetcorev2_outofprocess.dll in v2/higher RH VERSION in directory. Only one RH in directory.

### Uninstall scenarios:
-  ANCM msi 
   - [ ] apphost.config removes ANCM module, but keeps aspnetcore section
   - [ ] Removes the dlls from inetsrv
-  ANCMV2 msi 
   - [ ] apphost.config removes ANCMV2 module, but keeps aspnetcore section
   - [ ] Removes the dlls from PF
-  ANCM iis express
   - [ ] apphost.config removes ANCM module, but keeps aspnetcore section
   - [ ] Removes the dlls from PF
-  ANCMV2 iis express msi 
   - [ ] apphost.config removes ANCMV2 module, but keeps aspnetcore section
   - [ ] Removes the dlls from PF

**Comment by muratg** [comment]
@jhkimnew Please wait for #859 and #883 to be done before getting the CTI folks started. Thanks!

**Comment by jhkimnew** [comment]
@muratg @shhsu will own ANCM test instead of me.
Assigning this to Peter

**Comment by jkotalik** [comment]
I want to do a bit of manual verification too. Will wait for the entire E2E to be done before validating.

**Comment by jkotalik** [comment]
First fixing the msis and windows hosting bundle.

**Comment by jkotalik** [comment]
@muratg updated with the scenarios to cover.

**Comment by muratg** [comment]
Thanks @jkotalik!

**Comment by jkotalik** [comment]
@pan-wang the aspnetcore section will be removed on uninstalling ANCMV1. 
Repro steps:
1. Install the ANCMv1 and v2 msis.
2. Uninstall ANCMV1
3. Check the ApplicationHost.config file, see that  ```<section name="aspNetCore" overrideModeDefault="Allow" />``` is removed.

**Comment by jkotalik** [comment]
IISExpress installer uses AspNetCoreModule section rather than AspNetCoreModuleV2 section

**Comment by shhsu** [comment]
Vendor has successfully verified results

**Comment by muratg** [comment]
Thanks @shhsu & @jkotalik!
