### ISSUE TITLE
Bad Gateway on AspNetCoreModule with ErrorCode 2147954552 on Azure

### ISSUE THREAD

**Issue by kanadaj** [aspnet/IISIntegration#903]
Hi,

I'm trying to install an ASP.NET Core 2.1 application on an Azure App Service which uses .NET Framework 4.7.2 and EntityFramework 6.

The application starts up as expected, with the following stdout:
```
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:20535
Application started. Press Ctrl+C to shut down.
```

At which point the application seems to receive no new requests, and the page returns
> 502 - Web server received an invalid response while acting as a gateway or proxy server.

Looking into the FREB logs, the process stops at

```
MODULE_SET_RESPONSE_ERROR_STATUS
ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="2147954552", ConfigExceptionInfo=""
```

This happens on both controller actions and static files.

Web.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\RoyalRoadL.Net.Core.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Comment by kanadaj** [comment]
BindingRedirect doesn't seem to work

**Comment by kanadaj** [comment]
After some fiddling around, it seems like the Azure App Service doesn't do the automatic binding redirect to 4.2.0.0?

**Comment by kanadaj** [comment]
At this point, I'm at a loss. I have no idea how to dance around the fact that the System.Net.Http NuGet package doesn't seem to work at all, while tha GAC package only works on my development machine.

**Comment by kanadaj** [comment]
Found a potential answer at https://github.com/dotnet/corefx/issues/28833#issuecomment-386718038

**Comment by jkotalik** [comment]
@kanadaj regarding startup errors, we are working on improving diagnosing startup errors for future releases of ANCM. Did you see any events in the windows event log with an exception from dotnet?

**Comment by kanadaj** [comment]
No, no errors in the Windows Event Log that I can find. Also, the startup error itself didn't appear in stdout either until the environment was set to Development.

**Comment by jkotalik** [comment]
ANCM should redirect both stdout and stderr to the logfile when stdoutLogEnabled=true. Regarding verbosity, I am not sure why nothing is logged in release compilation. As this exception occurs before Application main, it should be the responsibility of dotnet framework to log it. 

Also, dotnet core will emit a windows event log when there is a critical startup error. Are you able to compiler your app on core? That may help diagnostics here.

**Comment by kanadaj** [comment]
Yes, I can compile the app and it does work on localhost. The issue happens when it tries to start up on an Azure App Service. I don't think I can view Windows Event Logs in there.

It's completely beyond me why the error isn't emitted into stdout.log without setting the environmental variable to Development, maybe a bug?

**Comment by jkotalik** [comment]
You should be able to check the windows event log by going to the App Service and clicking Advanced Tools. This will open Kudu, and open the Debug Console. Inside the log folder, there should be an eventlog.xml file that contains all windows event logs.

**Comment by kanadaj** [comment]
I will check it tomorrow if I can reproduce it. My eventlog.xml got damaged somehow (it is fairly big, and it just cuts off at some point even if I download the whole file), so I need to roll back my changes to repro the error then see what's in that xml.
