### ISSUE TITLE
reuse object requesthandler

### ISSUE THREAD

**Issue by pan-wang** [aspnet/IISIntegration#905]
IIS has pattern of reusing request level objects via overwriting new and delete operators (instead creating new object per request) to avoid heap fragments. We should stay with this pattern for inprocess and outofprocess handlers.

**Comment by pakrym** [comment]
Do we create any native object per request in inprocess handler?

**Comment by pan-wang** [comment]
Inprocess handle itself

**Comment by pakrym** [comment]
Right, I didn't see it pop up in the profile but will look again.
