### ISSUE TITLE
509 after deployment on  first request

### ISSUE THREAD

**Issue by s093294** [aspnet/IISIntegration#91]
It seems to me that after a deployment to azure website with RC1, the first request always get a 500 error. Has anyone been able to confirm the same?

The error information logged was:
```

HTTP Error 500.19 - Internal Server Error

The requested page cannot be accessed because the related configuration data for the page is invalid.



Detailed Error Information:



Module
   IIS Web Core 

Notification
   Unknown 

Handler
   Not yet determined 

Error Code
   0x80070002 

Config Error
   Cannot read configuration file  

Config File
   \\?\D:\home\site\app0\web.config 



Requested URL
   http://localhost:80/ 

Physical Path
    

Logon Method
   Not yet determined 

Logon User
   Not yet determined 

```

**Comment by Tratcher** [comment]
Can you share the final web.config file that ended up on the server?

**Comment by s093294** [comment]
So, the error page is very much correct. There is no web.config at app0. so there might not be any direct issue with the hosting bits. 

I need to figure out how a /demos/demo1 request ends up at the app for / .

The apps deployed is simple app.useFileServer() apps. 

Next time the server have been idling for a bit i will try to monitor the request abit better to see if I get anything from there.

**Comment by muratg** [comment]
Closing per the last comment
