### ISSUE TITLE
Numerous crashes in IIS/ANCM with .NET Core 2.0.6

### ISSUE THREAD

**Issue by aymericb** [aspnet/IISIntegration#913]
We've been seeing a lot of crashes of the `w3wp.exe` powering the AspNetCore IIS module, on Windows Server 2016 Standard with IIS 10. We have both `Microsoft .NET Core 2.0.3 - Windows Server Hosting` and `Microsoft ASP.NET Core 2.0.6 - Runtime Package Store` installed. The version of `aspnetcore.dll` is `7.1.1982.0`.

These crashes are caused by Access Violations in ANCM. They seem to increase with load on the server. We typically get a dozen of main crashes a day. But each main crash is followed by a handful of crashes that rapidly follows. It looks like _Rapid Failure Protection_ is having troubles restarting ANCM, but eventually it recovers and runs for a couple of hours, until the next spike of crashes occur.

We have other web sites behind IIS but they all run the "classic" .NET framework; none of these are crashing in any way. This is occurring for our only .NET Core site.

I have uploaded an `mht` report from Debug Diag Analysis. The stack traces from the crashes are varied, but they all dereference a null pointer.

[https://dl.barthe.ph/c5f442e.mht](https://dl.barthe.ph/c5f442e.mht)

Here's the three most common ones:

- the assembly instruction at `iiscore!W3_CONTEXT_BASE::OnPostedCompletion+53` in `C:\Windows\System32\inetsrv\iiscore.dll` from Microsoft Corporation has caused an access violation exception (`0xC0000005`) when trying to read from memory location `0x00000000` on thread 12

- the assembly instruction at `iiscore!NOTIFICATION_CONTEXT::RequestDoWork+9e` in `C:\Windows\System32\inetsrv\iiscore.dll` from Microsoft Corporation has caused an access violation exception (`0xC0000005`) when trying to read from memory location `0x00000000` on thread 9

- the assembly instruction at `aspnetcore!RegisterModule+a01e` in `C:\Windows\System32\inetsrv\aspnetcore.dll` from Microsoft Corporation has caused an access violation exception (`0xC0000005`) when trying to read from memory location `0x00000000` on thread 12

The issue on `aspnetcore!RegisterModule+a01e` seems unrelated to [merge #151](https://github.com/aspnet/AspNetCoreModule/pull/151) since we do not use Web Sockets at all.

I can communicate the minidumps via a private channel if necessary. If there is any other things that would help, please let me know.

Kind Regards,
Aymeric

**Comment by jkotalik** [comment]
We believe this issue is resolved with the the latest [Windows Hosting Bundle](https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.8) . See 
https://github.com/aspnet/Announcements/issues/294 for more information. 

If you continue to see issues, please directly email me at the email listed on my github profile.

**Comment by aymericb** [comment]
We have update to the 2.0.8 runtime and the crashes are gone. Thank you.
