### ISSUE TITLE
[Investigate] Use entire loopback address space for proxying

### ISSUE THREAD

**Issue by benaadams** [aspnet/IISIntegration#92]
Rather than using a single loopback address (e.g. 127.0.0.1) can the entire loopback address space be used? (e.g. 127.0.0.1 -> 127.255.255.255) which may bump the available ephemeral ports from 16k to 16M * 16k = 256Bn ports and prevent port exhaustion.

Note: I don't know if this will be a simple change to get working; or if it would work?

Also don't know if the entire address space works with fast loopback, though hopefully it does https://github.com/aspnet/IISIntegration/issues/29

https://github.com/aspnet/KestrelHttpServer/issues/652#issuecomment-190833513
> Note that we also need to increase the value for "MaxUserPort" registry, otherwise TCP ports needed for the communication between IIS and DNX will be exhausted, which will cause internal errors.

/cc @SajayAntony @mgravell @taoliseki

**Comment by SajayAntony** [comment]
This makes sense. These are internal connections and I'm not sure the limits of this integration yet.
/cc @davidso Platform handler should support large number of connections, over the ephemeral port limits.

**Comment by Tratcher** [comment]
Note it's not really up to HttpPlatformHandler, it's a question for WinHttp.

**Comment by SajayAntony** [comment]
@Tratcher good point. I think we just need to know if we set ourselves up to a hard limit based on MaxUserPorts or not when behind a proxy like IIS.

**Comment by SajayAntony** [comment]
@benaadams @taoliseki I don't know if this possible. Even after binding the local socket to different IP's and with different outbound IPs. looks like the loopback address resources fall into the same bucket. 
Connect fails at around the 65k limit. 

```
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
```

This is the pattern 
```
  TCP    127.0.0.15:18256       127.0.0.15:5000        ESTABLISHED     31976
  TCP    127.0.0.16:18257       127.0.0.16:5000        ESTABLISHED     31976
  TCP    127.0.0.17:18258       127.0.0.17:5000        ESTABLISHED     31976
  TCP    127.0.0.18:18259       127.0.0.18:5000        ESTABLISHED     31976
  TCP    127.0.0.19:18260       127.0.0.19:5000        ESTABLISHED     31976
  TCP    127.0.0.20:18261       127.0.0.20:5000        ESTABLISHED     31976
  TCP    127.0.0.21:18262       127.0.0.21:5000        ESTABLISHED     31976
  TCP    127.0.0.22:18263       127.0.0.22:5000        ESTABLISHED     31976
  TCP    127.0.0.23:18264       127.0.0.23:5000        ESTABLISHED     31976
  TCP    127.0.0.24:18265       127.0.0.24:5000        ESTABLISHED     31976
```

**Comment by benaadams** [comment]
@SajayAntony interesting... and a bit weird. Might be something to take up with the Windows networking team? In theory it should work; but I've never seen it suggested as a solution yet (was mostly hoping)

**Comment by benaadams** [comment]
Ipv4 loopback is essentially an is high bit set test; Ipv6 decided this was a mistake as it reserved so much space (16M ip addresses) and only has a single address for loopback. However in this situation if it worked with the full address space it could be an advantage 

As ports reservation is the quad pair SRC_IP:PORT<->DST_IP:PORT

**Comment by muratg** [comment]
AspNetCoreModule folks will be doing some investigation on this (and other possible perf improvements)

**Comment by benaadams** [comment]
Listening on multiple ports is another option; isn't as good of one though; as its eating up the ports, so would be bad in a dense cluster of services/sites

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#27
