### ISSUE TITLE
build.cmd korebuild issues

### ISSUE THREAD

**Issue by HaoK** [aspnet/IISIntegration#927]
So build.cmd is blocked from running even after I installed the various listed components:

          "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
          "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81",
          "Microsoft.VisualStudio.Component.VC.ATL",
          "Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop"

I went ahead and just removed these entries and was able to build the repo

**Comment by jkotalik** [comment]
Run ```run.ps1 install vs```. It will bring up the vs installer. There may be some differences in the components vswhere returns versus what is actually installed.

**Comment by HaoK** [comment]
Is that the correct command?

```
C:\github\IISIntegration [dev ≡ +0 ~1 -0 !]> .\run.ps1 install vs
Using KoreBuild 2.2.0-preview1-17081
Specify --help for a list of available options and commands.
Exception thrown: 'Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument 'install'
```

**Comment by jkotalik** [comment]
build.cmd -u first. That will download a newer version of korebuild.

**Comment by HaoK** [comment]
I was able to run install vs, and it succeeded but I still get the same error:

```
C:\github\IISIntegration [dev ≡ +0 ~2 -0 !]> .\run.ps1 install vs
Using KoreBuild 2.2.0-preview1-17090
Starting msbuild with arguments: msbuild C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj -t:InstallToolsets -v:n
Executing 'C:\Users\haok\.dotnet\x64\dotnet.exe msbuild C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj -t:InstallToolsets -v:n'
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/15/2018 2:41:06 PM.
     1>Project "C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj" on node 1 (InstallToolsets target(s)).
     1>InstallToolsets:
         C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\modules\KoreBuild.Tasks\vswhere.exe -latest -prerelease -products Microsoft.VisualStudio.Product.Enterprise -format json
         Found vs installation located at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise
         Downloading 'https://aka.ms/vs/15/release/vs_Enterprise.exe' to 'C:\Users\haok\AppData\Local\Temp\vs_Enterprise.exe'
         Downloaded visual studio exe to C:\Users\haok\AppData\Local\Temp\vs_Enterprise.exe.
         Calling: C:\Users\haok\AppData\Local\Temp\vs_Enterprise.exe modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" --in C:\Users\haok\AppData\Local\Temp\vs_Enterprise.json --wait --norestart
     1>Done Building Project "C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj" (InstallToolsets target(s)).

Build succeeded.
```

```
C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\modules\KoreBuild.Tasks\module.targets(154,5): error : Could not find an installation of Visual Studio that satisifies the specified requirements in C:\Github\IISIntegration/korebuild.jsonExecute run.ps1 install vs to update or install the current vs installation. [C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj]

```

**Comment by jkotalik** [comment]
Weird, that shouldn't be happening. Vswhere.exe is the one responsible to for checking which components are installed. Can you check which component vswhere.exe thinks you don't have installed? Ex: emove the  "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81" dependency and build again.

**Comment by HaoK** [comment]
"Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop"

**Comment by HaoK** [comment]
Let me double check that installed is checked, I manually did these earlier today as well

**Comment by jkotalik** [comment]
Alright thanks. This could be a bug with vswhere.exe.

**Comment by Tratcher** [comment]
@mikeharder was having fun with this recently. I think VS Where didn't like preview builds?

**Comment by HaoK** [comment]
So I need to install an older non preview build with these components?

**Comment by jkotalik** [comment]
no. you shouldn't need to at all. Delete the line in korebuild. I'll ping @mikeharder about the issue with vswhere.exe and how we can fix it in build tools.

**Comment by HaoK** [comment]
Ok cool, next problem I'm seeing is the functional tests are failing locally off a clean dev, is there some other setup I need to do for the functional tests to pass?  IIS is installed and I'm able to create new projects and run them against IIS thru VS...

**Comment by jkotalik** [comment]
Run in an administrator console or run this script: https://github.com/aspnet/IISIntegration/blob/dev/tools/update_schema.ps1

**Comment by pakrym** [comment]
Closing, please reopen if there is anything else to do here.
