### ISSUE TITLE
ASP.NET Core 2.1.1 fails with HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by Shadowman4205** [aspnet/IISIntegration#945]
Hello,
After upgarding my project from .NET CORE 2.0 to .NET CORE 2.1, and upgraded all microsoft packages to 2.1.1. With updated visual studio to 15.7.4, .NET CORE 2.1 sdk(V2.1.3) and .NET CORE 2.1 runtime(V2.1.1) installed i am getting this error when i try run my app.
![scr](https://user-images.githubusercontent.com/23194476/41651412-31b281f8-7489-11e8-9801-f3a39a45e22b.png)

**Comment by Tratcher** [comment]
Please follow the troubleshooting steps and let us know if you still have an issue:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#app-startup-errors

**Comment by ColorTwist** [comment]
I had the same exact issue.
Version v2.1.301 should fix that (Previously had v2.1.300) .

**Comment by coder8keyboard** [comment]
-Open Command Prompt
-Navigate to bin directory of your project. Let's assume your project name is 'test'
-Run 'dotnet .\test.dll' and you will see something like Microsoft.Aspnetcore.all version 2.1.2 was not found.
-Then run 'dotnet -info' and you will see your .netcore runtime. Mine was 2.1.1. 
So I downgraded my Microsoft.Aspnetcore.all nuget package to 2.1.1 and it worked after.
Alternatively, you could upgrade .netcore runtime but that's more work :)

**Comment by jaredfholgate** [comment]
I had the same issue after installing the hosting package. The fix was much simpler for me. Just running IISRESET resolved it.

**Comment by mynkow** [comment]
I added the following line in the csproj and it started working. All troubleshoots suggested by @Tratcher did not help me at all because of misleading information

`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />`

**Comment by jawaidakhter** [comment]
I just update my dotnet sdk core version in global.json file with installed dot net version, and my project start working

C:\>dotnet --version
2.1.402

global.json
========
{
  "sdk": {
    "version": "2.1.402"
  }
}

**Comment by JashanChittesh** [comment]
> -Open Command Prompt
> -Navigate to bin directory of your project. Let's assume your project name is 'test'
> -Run 'dotnet .\test.dll' and you will see something like Microsoft.Aspnetcore.all version 2.1.2 was not found.
> -Then run 'dotnet -info' and you will see your .netcore runtime. Mine was 2.1.1.
> So I downgraded my Microsoft.Aspnetcore.all nuget package to 2.1.1 and it worked after.
> Alternatively, you could upgrade .netcore runtime but that's more work :)
> The error on web browser and events log is useless. Can't wait for .netcore 3 :P

This answer is really helpful - only "Run 'dotnet .\test.dll'" should be "Run 'dotnet .\NameOfYourMainApplication.dll'" (obviously "NameOfYourMainApplication" is a placeholder for the name of your application DLL ;-)

Also, I personally found it easier to upgrade the .netcore runtime than doing another build and uploading it to my server. I guess after each Visual Studio update, you should probably check this URL and upgrade your server, if a new version is available: [.NET Core 2.1 downloads](https://www.microsoft.com/net/download/dotnet-core/2.1)

Eventually, you'll move to .NET Core 2.2 and that's simply "2.2" at the end of the URL: [https://www.microsoft.com/net/download/dotnet-core/2.2](https://www.microsoft.com/net/download/dotnet-core/2.2)

I'm leaving this here for others and my future self when I run into a broken Web app update process during the next crunch mode when the last thing I have time for is following useless "troubleshooting" guides.

**Comment by rpawlaszek** [comment]
@estomagordo have you tried the [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/)? This worked for me.

**Comment by estomagordo** [comment]
@rpawlaszek yes, eventually I noticed someone mentioned this. And it worked. Thanks.

**Comment by amilathennakoon** [comment]
Downgrade nuget Microsoft.AspNetCore.All to 2.1


![image](https://user-images.githubusercontent.com/14935969/46525862-59b79880-c8aa-11e8-9161-91c05ffbb9e2.png)

**Comment by adamcweitzman** [comment]
In the release folder:

          "Microsoft.AspNetCore": "2.1.1",
          "Microsoft.AspNetCore.All": "2.1.1",
          "Microsoft.AspNetCore.App": "2.1.1",
          "Microsoft.EntityFrameworkCore": "2.1.4",
          "Microsoft.EntityFrameworkCore.Tools": "2.1.4",
          "Microsoft.NETCore.App": "2.1.0",

Could the last line be throwing it off? If so, how to update? the package is blocked by nuget

**Comment by rpawlaszek** [comment]
@adamcweitzman, could you check your nuget version?

**Comment by adamcweitzman** [comment]
yes, copy and paste of the nugget:

![sdfdsf](https://user-images.githubusercontent.com/13594324/46564064-b88d0a00-c8ca-11e8-8b95-bd64d88e97ef.PNG)

**Comment by adamcweitzman** [comment]
maybe i need to manually set the path? in my runtime.config in \bin I still have the correct version

**Comment by rpawlaszek** [comment]
I meant the version of nuget you use. I had no problem with installing the 2.1.5 version of Microsoft.AspNetCore.App. Go to powershell and simply type in 'nuget'

**Comment by rpawlaszek** [comment]
The version I have installed is 4.8.1 Could you try with this one? And another thing: what is the environment you have set for the self-contained deployment? (mine: win-x86)

**Comment by kbdavis07** [comment]
Got same error on a VM hosted on Azure with IIS,  the self-contained deployment seems to fix this issue for me for now.

**Comment by Pete1138** [comment]
I deployed an app to IIS in an Azure VM, came back to it after a few hours and it started showing this error.
-Run 'dotnet .\test.dll'  spins up the app fine (no errors).
self-contained deployment has not fixed this for me
