### ISSUE TITLE
Make the extension method for WebHostBuilder do everything required to correctly set up default app to work in IIS

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/IISIntegration#95]
Right now, an app needs to configure itself in 3 places for IIS integration:
- Dependency and post-publish script in `project.json`
- Call to add IIS integration during `WebHostBuilder` phase in `Program.cs`
- Call to add HTTP forwarders & IIS integration middleware in `Startup.cs`

This is too many places. I'd like us to remove the need for any code in `Startup.cs` for IIS integration by default. Instead, a single extension-method call in the `WebHostBuilder` phase should configure the IIS URL, and add both the required middleware via an `IStartupFilter`.

- [x] Add the IIS auth middleware via the startup filter
- [x] Add the header overrides middleware via the startup filter

I'd also like the package names to be:
- [x] Microsoft.AspNetCore.Server.IISIntegration
- [x] Microsoft.AspNetCore.Server.IISIntegration.Tools

Example resultant `project.json`:
``` json
{
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "runtimeOptions": {
    "gcServer": true
  },
  "dependencies": {
    "Microsoft.NET.DotNetCore": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0"
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0"
  },
  "frameworks": {
    "dotnetcore1.0": {}
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
  }
}
```

**Comment by DamianEdwards** [comment]
ping @muratg @moozzyk @Tratcher

**Comment by moozzyk** [comment]
@DamianEdwards  - `dotnet-publish-iis can't be renamed` to `Microsoft.AspNetCore.Server.IISIntegration.Tools`. Dotnet tools (and therefore the packages) have to start with `dotnet-` prefix

**Comment by DamianEdwards** [comment]
I don't believe that is true, or at least will continue to be. The dispatching logic looks for assemblies in referenced packages without regard to the package name itself.

**Comment by DamianEdwards** [comment]
By that I mean, we'd need the package name to be different to the tool assembly name.

**Comment by moozzyk** [comment]
I will try it but I think I tried it originally and I could not make it work.

**Comment by muratg** [comment]
@DamianEdwards do you want to rename all the other tool packages as well?  I'll start a thread about the rename of the other package + the extension method.

cc @Eilon

**Comment by DamianEdwards** [comment]
@muratg if we prove this works, then yes. I think we should standardize on a ".Tools" suffix for our tools packages, e.g. Microsoft.AspNetCore.Razor & Microsoft.AspNetCore.Razor.Tools

**Comment by JunTaoLuo** [comment]
@moozzyk did you make an announcement for the renaming of the tools package?

**Comment by moozzyk** [comment]
Not yet - so far only publish-iis was renamed and started working end-to-end today. I talked to @NTaylorMullen and they would like to rename to happen after they finish all feature work. He suggested to talk to other teams who have tools to check if they are fine with that. I think the rename will happen late next week.

**Comment by NTaylorMullen** [comment]
Just to add some clarification: The desktop support for ef, scaffolding and dotnet-razor-tooling is in progress. I'm not 100% familiar with what it'll take to do the rename but if it'll potentially cause massive merge conflicts among the tools I'd like to push it off until the desktop support is in. If not, then go for it :smile:
