### ISSUE TITLE
ASPNETCORE_IIS_HTTPAUTH value ends in semi-colon

### ISSUE THREAD

**Issue by sandrakim90** [aspnet/IISIntegration#960]
Values in environment variable ASPNETCORE_IIS_HTTPAUTH end in a semi-colon. For example: "anonymous;" or "windows;". To be consistent with other environment variables, the semi-colon should be removed.

Using .NET CORE 2.1 on Windows with IIS and IIS Express.

**Comment by Tratcher** [comment]
What are you using it for? That key is intended for internal use.

**Comment by sandrakim90** [comment]
This is the question that I posted on StackOverflow:
https://stackoverflow.com/questions/50747280/asp-net-disable-authorization-depending-on-host

**Comment by sandrakim90** [comment]
@Tratcher wrote "That key is intended for internal use"
I think any variable not labelled as "internal" will get used by developers and unintentionally will become public.

Suggest calling the variable like ASPNETCORE_IIS_HTTPAUTH_(INTERNAL) or ASPNETCORE_IIS_HTTPAUTH_(EXPERIMENTAL)

**Comment by Tratcher** [comment]
We won't prevent you from using it, but it was designed for communicating between two specific components (AspNetCoreModule and IISIntegration). We won't make changes to it without an additional compelling scenario.

Note the value is a semicolon separated list. The presence or absence of a trailing semicolon is not significant.

**Comment by sandrakim90** [comment]
Thank you for clarification. This incident can be closed.
