### ISSUE TITLE
Batch logs in local buffer to be written to the windows event logs on failure.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#974]
Currently our logs are printed to console/stdout if debugging is enabled, however most people won't be publishing their apps in debug. One way we can get around this is to capture all ANCM startup logs into a local buffer and pumping it to the event log on first failure.

**Comment by pakrym** [comment]
There is one problem with this: after we get first error log we would usually get more when error propagates up the stack and it's nice to have them too.
